mozilla-services/socorro

socorro/external/es/connection_context.py, socorro/external/es/query.py, socorro/unittest/external/es/test_query.py
=> Fixes bug 1114552 - Added Query service to es module.

alembic/versions/52dbc7357409_bug_1056025_and_bug_1037855_rename_.py
=> Nobug - fix busted import for alembic

alembic/versions/5387d590bc45_fixes_bug_1117907_remove_sigsum_fks_.py
The SQL in this migration was incorrect!  Now corrected with testing via IRC from a user that was affected.
=> Fixes nobug issue with SQL for FK drops

socorro/external/es/supersearch.py, socorro/unittest/external/es/test_supersearch.py
=> Fixes bug 1120953 - Fixed errors with Super Search in new es module.

socorro/unittest/external/es/test_supersearch.py
@phrawzty I have been a bad colleague and I forgot to fix this before merging. Will you please forgive me? :angel:
=> Bug 1120953 - Fixed ambiguous test name.

socorro/external/crashstorage_base.py, socorro/external/fs/fs_new_crash_source.py, socorro/unittest/external/fs/test_fs_new_crash_source.py, socorro/unittest/external/rabbitmq/test_rmq_new_crash_source.py
as per request by @rhelmer, a restoration of the ability for the processor to use the FS classes as a new crash source
=> No Bug - added new crash source for fs

webapp-django/crashstats/crashstats/models.py
=> fixes bug 1121749 - Unable to nose test specific files due to models.py loading

requirements.txt, socorro/external/postgresql/service_base.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/tokens/middleware.py
=> fixes bug 1119378 - Upgrade to Django 1.6

Makefile, docs/development/build-from-source.rst, scripts/bootstrap.sh
@rhelmer not exactly what we talked about, but one way of handling this. r?
=> Fixes bug 1120984 create 'make dev' instead of bootstrap

alembic/versions/2cdb9abe6291_fixes_bug_1122145_add_release_repos_for_.py
Should clear this up! @rhelmer r?
=> Fixes bug 1122145 - add fennec repos to table

requirements.txt, scripts/cmp_hbase_s3.py, scripts/sync_fs.py, scripts/sync_hbase_s3.py, socorro/unittest/external/filesystem/create_json_dump_store.py, socorro/unittest/external/hbase/test_hbase_client.py, socorro/unittest/testlib/createJsonDumpStore.py
Editor removed some whitespace issues as well. I didn't do a full PEP8 on these.. it would be a pretty major on the scripts and I don't have a test environment for the hbase/s3 scripts.
=> Fixes bug 1122311 remove simplejson from requirements

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/manage/forms.py, webapp-django/crashstats/manage/static/manage/css/api_tokens.css, webapp-django/crashstats/manage/static/manage/js/api_tokens.js, webapp-django/crashstats/manage/static/manage/js/events.js, webapp-django/crashstats/manage/static/manage/js/pagination_utils.js, webapp-django/crashstats/manage/static/manage/js/users.js, webapp-django/crashstats/manage/templates/manage/api_tokens.html, webapp-django/crashstats/manage/templates/manage/base.html, webapp-django/crashstats/manage/templates/manage/home.html, webapp-django/crashstats/manage/templates/manage/users.html, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/urls.py, webapp-django/crashstats/manage/views.py, webapp-django/crashstats/settings/base.py
r? @rhelmer 
@AdrianGaudebert wanna take a quick look too?
=> fixes bug 1119347 - Admin creation of API tokens

alembic/versions/445fefe2e08f_fixes_bug_794549_add_partitioning_to_.py
=> Fixes bug 794549 Add partitioning to reports_duplicates table

puppet/modules/socorro/manifests/init.pp
Minor style fixes; highly non-critical. :hamster: 
@rhelmer `r?`
=> style tidying

puppet/modules/socorro/manifests/init.pp
Should speed the provisioning up, too.
@rhelmer `r?` :last_quarter_moon_with_face:
=> fix bug 1123691; remove maven et al.

alembic/versions/e4ea2ae3413_fixes_bug_1122145_update_special_.py, docs/development/databaseadminfunctions.rst, socorro/external/postgresql/raw_sql/procs/update_product_versions.sql
Added documentation to the function and our shipped documentation. Also opening another bug to just rip this junk out and replace with something considerably simpler.
@rhelmer r?
=> Fixes bug 1122145 add fennec release repos to special_product_platforms

alembic/versions/5e14d46c725_bug_855423_change_ra.py, requirements.txt
This should get us a version of alembic that is ok with multiple branches.
=> Nobug upgrading alembic and sqlalchemy

docs/development/build-from-source.rst, docs/development/unittesting.rst, scripts/bootstrap.sh
Longer term fix might be to change bootstrap.sh
=> Fixes bug 1123363 add setup.py develop to make dev

scripts/hive_adi_test.py
Stashing this in case someone needs to verify ADI directly from hive again.
=> Used for bug 1124872 - script for querying hive ADI

alembic/versions/42c267d6ed35_reload_update_reports_duplicates.py, socorro/external/postgresql/raw_sql/procs/update_reports_duplicates.sql
Refactoring so this is a bit easier to read for future dbas.
=> Nobug refactor duplicates sql

alembic/versions/42c267d6ed35_reload_update_reports_duplicates.py, requirements.txt, socorro/external/postgresql/setupdb_app.py
=> Stopgap for bug 1126980 alembic stamp doesn't work with v0.7.4

puppet/modules/socorro/manifests/init.pp
* EPEL is now managed as a packaged install. :smile: 
* Elasticsearch and PGDG have keys associated with them. :relaxed: 
* devtools has no GPG key available. :disappointed: 
I also set up a dep chain where `ca-certificates` -> `yum-plugin-fastestmirror` -> `everything_else`.  This should keep things fairly future-proofed (famous last words).
@rhelmer `r?`
=> fix bug 1126917; verify gpg keys of repos where possible

socorro/external/postgresql/crashes.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_crashes.py, socorro/unittest/middleware/test_middleware_app.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/templates/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
=> Fixes bug 1125862 - Removed paireduuid service and associated webapp bits.

docs/configuring-socorro.rst
=> No bug - Added instructions for Elasticsearch to the configure page.

docs/troubleshoot.rst
=> No bug - Added documentation about crontabber state.

webapp-django/crashstats/crashstats/templates/crashstats/report_index.html
=> Fixes bug 1126288 - Made links in /report/index point to the new cool stuff.

socorro/collector/wsgi_breakpad_collector.py, socorro/unittest/collector/test_wsgi_breakpad_collector.py
I've benchmarked for two days and can detect no impact on the collectors whats so ever.  Perhaps we're being overly cautious in not wanting to put the md5sum code into the collector.  This is clearly the most logica place to put it.
=> Fixes Bug 907499 - added checksum to collector

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report_list_graph.js
=> fixes bug 1102244 - Hover details on reports/list graphs off screen

webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
=> fixes bug 1131089 - api requests without Auth-Token 302

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report.js, webapp-django/crashstats/crashstats/templates/crashstats/report_index.html
=> fixes bug 1131319 - "Show/hide other threads" setting remembered

socorro/processor/symbol_cache_manager.py
=> fix bug 1131228 - catch unexpected OSError and return early

.travis.yml
=> fix bug 1134687 - run travis jobs with sudo:no

webapp-django/bin/bootstrap.sh
=> bug 1134755 offline asset compression in travis tests of webapp

webapp-django/crashstats/supersearch/forms.py, webapp-django/crashstats/supersearch/tests/test_forms.py
=> Fixes bug 1137480 - Removed duplicates from versions in Super Search.

config/reprocess_crashlist.ini-dist, scripts/reprocess_crashlist.py, socorro/app/for_application_defaults.py, socorro/external/rabbitmq/reprocess_crashlist.py
Creates a script for handling bulk reprocessing loads from a production machine.
=> Fixes bug 1137752 adds reprocessing submission script

scripts/bootstrap.sh, scripts/defaults
=> fix bug 1142149 - make it possible to override python2.6 for virtualenv

socorro/unittest/external/elasticsearch/test_settings.py, socorro/unittest/external/elasticsearch/test_supersearch.py, socorro/unittest/external/elasticsearch/unittestbase.py
=> fix bug 1142475; add maximum_es_version decorator for ES tests

docs/configuring-socorro.rst, webapp-django/crashstats/manage/templates/manage/symbols_uploads.html, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/symbols/forms.py, webapp-django/crashstats/symbols/migrations/0002_auto__del_field_symbolsupload_file.py, webapp-django/crashstats/symbols/models.py, webapp-django/crashstats/symbols/templates/symbols/api_upload.html, webapp-django/crashstats/symbols/templates/symbols/home.html, webapp-django/crashstats/symbols/tests/test_models.py, webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/urls.py, webapp-django/crashstats/symbols/utils.py, webapp-django/crashstats/symbols/views.py, webapp-django/settings_test.py
This reverts commit 7d096f6fffd18713e605ba768f9b4bbca0023947.
=> Reland "fixes bug 1085530 - store uploaded symbols to S3, r=@rhelmer"

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py
=> fixes bug 1124267 - waffle on /api by default

socorro/processor/signature_utilities.py
added the symbol "__aeabi_fcmpgt" to the irrelevant skiplist
=> fixes bug 1142767 added __aeabi_fcmpgt to irrelevant

webapp-django/crashstats/supersearch/form_fields.py, webapp-django/crashstats/supersearch/tests/test_views.py
=> Fixes bug 1144094 - Prevented empty parameters to break Super Search.

webapp-django/crashstats/supersearch/static/supersearch/js/socorro/search.js
=> Fixes bug 1144262 - Use current mode when searching in Super Search.

requirements.txt, webapp-django/bin/ci.sh, webapp-django/bin/linting.py
=> fixes bug 1022097 - switch from check.py to flake8

webapp-django/crashstats/crashstats/tests/test_models.py
=> fixes bug 1143167 - measure_fetches() decorator is never tested

webapp-django/crashstats/base/templates/crashstats_base.html, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/analytics.js, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report.js, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report_list.js, webapp-django/crashstats/supersearch/static/supersearch/js/socorro/search.js
cc @rhelmer @lonnen 
I combined two bugs in one git commit message. Let's see if that works. 
To read more about event tracking see https://developers.google.com/analytics/devguides/collection/analyticsjs/events
=> fixes bug 1119200, 1119203 - GA analytics to tabs

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/urls.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/urls.py
=> fixes bug 1144791 - Don't expect favicon.ico to be collected

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/urls.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/urls.py
=> Revert "fixes bug 1144791 - Don't expect favicon.ico to be collected"

requirements.txt
=> fixes bug 1145131 - django 1.6.11

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/urls.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/urls.py
=> fixes bug 1144791 - favicon.ico straight from django

scripts/rabbitmq-integration-test.sh, socorro/processor/processor_app.py, socorro/processor/socorrolite_processor_2015.py
r? @twobraids - this makes processor work with collector without any additional configuration, and use a default ruleset that does not use any external resources (like postgres) or anything Mozilla-specific.
=> bug 1130598 - simpler processor default

alembic/versions/63d05b930c3_fixes_bug_1136854_fix_permissions_.py, alembic/versions/732abe64c5a_fixes_bug_1136711_deprecate_bixie.py
Fixes something that broke the stage refresh. Sorry! Production database has some things in it that our repo does not. :/
=> Fixes nobug issue with migration drop ordering

requirements.txt, webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/templates/crashstats/ratelimit_blocked.html, webapp-django/crashstats/crashstats/utils.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/supersearch/tests/test_views.py, webapp-django/crashstats/supersearch/views.py
=> fixes bug 1145374 - Ratelimit the search interface

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/settings/base.py
=> fixes bug 1143048 - Up the default ratelimit for the API

socorro/unittest/external/elasticsearch/unittestbase.py, socorro/unittest/external/es/base.py
=> No bug - Raised timeout for Elasticsearch tests.

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/supersearch/tests/test_views.py
=> fixes bug 1148470 - Intermittent ratelimit failures

config/systemd/socorro-collector.service, config/systemd/socorro-crashmover.service, config/systemd/socorro-middleware.service, config/systemd/socorro-processor.service, config/systemd/socorro-webapp.service
r? @phrawzty - in the process of bootstrapping a consul cluster and connecting clients to it, I found that envconsul will generally retry until consul is working but will quit in some circumstances, which means the service will go into the failed state.
=> bug 1148310 - always try to restart socorro apps

scripts/database/create_heroku_stage_database.sh, socorro/external/postgresql/setupdb_app.py
This includes a script to pull a minimal set of data from a stage database and put it into Heroku.
=> Fixes bug 1144169 add script for a stage refresh into a heroku database

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
@rhelmer r?
(cc @AdrianGaudebert but I think you're on PTO)
=> fixes bug 1149196 - report_list  ValueError on install_time sometimes

scripts/crons/crontabber.sh
r? @phrawzty - same as PR #2695 but on a sensible branch name this time.
=> Bug1148628 run crontabber under envconsul

webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
=> fixes bug 1149578 - install_time not always present in correlation signatures

socorro/external/postgresql/signature_summary.py
@rhelmer r?
I'm confident this fixes it. See https://gist.github.com/peterbe/d09cd6fd7765642453ea
=> fixes bug 1151455 - signature summary constraints on report_date

webapp-django/crashstats/supersearch/templates/supersearch/search_results.html
Also add titles to links and italicise the link in the "Signature facet" tab
=> Bug 1056984 Remove external link icons from "Signature report" links

scripts/defaults, scripts/rabbitmq-integration-test.sh, scripts/test.sh, socorro/database/database.py, socorro/external/postgresql/base.py, socorro/external/postgresql/connection_context.py, socorro/external/postgresql/postgresqlalchemymanager.py, socorro/external/postgresql/setupdb_app.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_base.py, socorro/unittest/external/postgresql/test_crashes.py, socorro/unittest/external/postgresql/test_gccrashes.py, socorro/unittest/external/postgresql/test_setupdb_app.py, socorro/unittest/external/postgresql/unittestbase.py, socorro/unittest/middleware/test_middleware_app.py
This reverts commit 632d251ba61f9f538ebb9acf11313a8118812829.
=> Revert "added PG URL support as defaults in ConnectionContext"

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report_list_correlations.js
=> fix bug 1152922 - use correct order for columns

webapp-django/crashstats/settings/base.py
=> settings base fixes

docs/configuring-socorro.rst
=> (no bug) - more explicit instructions on how to get consul going

.gitignore, webapp-django/crashstats/settings/base.py
=> fixes bug 1157386 - Compression should be on by default

requirements.txt, webapp-django/crashstats/settings/base.py
=> fixes bug 1156394 - Use dj-database-url to unpackage settings.DATABASES

socorro/processor/symbol_cache_manager.py, socorro/unittest/__init__.py, socorro/unittest/processor/test_symbol_cache_manager.py, socorro/unittest/skip_if.py, socorro/unittest/test_skip_if.py
=> fixes bug 1158929 - Avoid pyinotify like the plague on OSX

requirements.txt
=> fixes bug 1160231 - Upgrade to crontabber 0.16.1

webapp-django/crashstats/settings/base.py
=> no bug - fix config key, should be username not password here

docs/development/build-from-source.rst, docs/development/databasesetup.rst, scripts/deploy.sh, scripts/rabbitmq-integration-test.sh, scripts/setup-socorro.sh, scripts/test.sh, socorro/external/postgresql/postgresqlalchemymanager.py, socorro/external/postgresql/setupdb_app.py, socorro/unittest/external/postgresql/test_base.py, socorro/unittest/external/postgresql/test_setupdb_app.py
this is my take on the previous PR 2643 from @selenamarie.  It is a refactoring of the ```setupdb_app.py``` as well as its associated ```PostgreSQLAlchemyManager``` class.  
@selenamarie gets credit for most of the work, I get credit for beautification and integration.
=> Fixes bug 1132937 - add Heroku PG support with its strange superuser requirements

socorro/cron/jobs/fetch_adi_from_hive.py, socorro/unittest/cron/jobs/test_fetch_adi_from_hive.py
=> Fennec adi correction

socorro/lib/search_common.py, socorro/unittest/lib/test_search_common.py
@peterbe r?
This needs to be merged before we can take https://github.com/mozilla/socorro/pull/2758 in.
=> Fixes bug 1161030 - Added support for generic beta versions to Super Search.

scripts/package/rpm-after-install.sh
=> bug 1162085, persist subdir correctly, and create now too

webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/views.py
=> fixes bug 1164512 - Creating API tokens manually not recorded as admin events

docs/configuring-crash-stats.rst, docs/configuring-socorro.rst, docs/production-install.rst, docs/troubleshoot.rst, scripts/setup-socorro.sh
r? @peterbe @twobraids - more readable config, that happens to be be more amenable to loading directly into the environment. This contains the fixes from and replaces PR #2763
=> Bug1160603 load config files into consul

webapp-django/crashstats/crashstats/helpers.py, webapp-django/crashstats/crashstats/templates/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_helpers.py
=> fixes bug 1165012 - strip "report this bug" summary

webapp-django/crashstats/manage/forms.py, webapp-django/crashstats/manage/templates/manage/graphics_devices.html, webapp-django/crashstats/manage/tests/sample-pci.ids, webapp-django/crashstats/manage/tests/test_utils.py, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/utils.py, webapp-django/crashstats/manage/views.py
@rhelmer r?
Like I said in IRC, I played with this and all the unknown on [this page](https://crash-stats.mozilla.com/report/list?product=Firefox&signature=nsIPresShell%3A%3AAddRefreshObserverInternal%28nsARefreshObserver*%2C+mozFlushType%29) would be resolved. 
It's hard to gauge the **quality** of the database other than the merits of quantity which is partly the reason I've decided to NOT wipe away the old stuff for dealing with CSV files from PCIDatabase.com
=> fixes bug 1166063 - Support uploads from https://pci-ids.ucw.cz/

webapp-django/crashstats/crashstats/templates/crashstats/partials/reports.html
=> fixes bug 1166526 - Date column empty on reports

scripts/bootstrap.sh, scripts/install.sh, setup.py, socorro/external/postgresql/server_status.py, socorro/unittest/external/postgresql/test_server_status.py, socorro/unittest/middleware/test_middleware_app.py, webapp-django/bin/ci.sh
r? @peterbe - this is pretty much the simplest way I could figure out.
=> fix bug 1161812 - put revision files in root of package

scripts/defaults
=> fix bug 1166782 - use consistent versioning scheme for RPM

requirements.txt
@rhelmer r?
PS. I deleted all [cache repositories](https://travis-ci.org/mozilla/socorro/caches) on Travis just prior to starting this PR.
=> fixes bug 1166838 - new peep hashes for github.com .zip files

scripts/install.sh
=> bug 1161812 - manipulate revision files before copying into build

scripts/install.sh
=> bug 1161812 - build_dir must be modified last

webapp-django/crashstats/supersearch/views.py
=> Fixes bug 1166919 - Hide uuid field from Super Search results.

docs/configuring-socorro.rst
=> (no bug) - remove useless PG storage class from docs

scripts/crons/cron_libraries.sh
=> bug 1167256 - ensure that betas get correlation reports

webapp-django/crashstats/crashstats/views.py
=> Fixes bug 1166529 - Removed unused variable from report/list view.

.travis.yml
=> fixes bug 1166866 - No pip install in travis

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
=> Fixes bug 1164531 - Sanitized build id before using it in BetaVersionRule.

socorro/external/statsd/crashstorage.py, socorro/unittest/external/statsd/test_crashstorage.py
this is a stab at a crashstorage class that will log any call to its method to statsd.
=> Fixes Bug 1167767 - add statsd storage class to count calls to crashstore

requirements.txt
=> bug 1167767 - add datadog to requirements.txt

requirements.txt
Going to r someone as soon as I see this working once in travis.
=> fixes bug 1164465 - psycopg2 2.6

socorro/external/statsd/crashstorage.py, socorro/external/statsd/dogstatsd.py, socorro/unittest/external/statsd/test_crashstorage.py
pave over the differences between datadog statsd and regular statsd
=> Fixes Bug 1170168 even more - adjustments to datadog statsd

requirements.txt
This reverts commit a3de52469fb18c4ed86100dd3b3874bcc69f735c.
r? @peterbe
=> Revert "bug 1164465 - psycopg2 2.6.1 by github sha"

socorro/external/statsd/crashstorage.py, socorro/unittest/external/statsd/test_crashstorage.py
tried to get the name from the wrong object...
=> No Bug  - corrected getting name of statsd wrapped crashstore

socorro/external/postgresql/dbapi2_util.py, socorro/external/postgresql/postgresqlalchemymanager.py, socorro/external/postgresql/releases.py, socorro/external/postgresql/skiplist.py, socorro/external/postgresql/tcbs.py, socorro/unittest/collector/test_submitter_app.py, socorro/unittest/external/postgresql/test_crashstorage.py, socorro/unittest/external/postgresql/test_dbapi2_util.py
close all PG cursors after their use to prevent leaking memory
=> fixes Bug 1170604 - updated use of cursors to ensure closure

.gitignore, minidump-stackwalk/Makefile, minidump-stackwalk/jit-crash-categorize.cc
r? @rhelmer
I don't think the jit-crash-categorize code itself needs a review, dmajor and I have both been in it and we can probably trade reviews on it in the future.
=> bug 1171937 - import jit-crash-categorize code

webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
Sorry Adrian if this feels out of context for you. It's just Python. I didn't want to steal Rob's attention.
=> fixes bug 1131987 - symbol upload and wildcard emails for private

webapp-django/crashstats/crashstats/views.py
@KaiRo-at, 
I don't know what you mean by [*"for the first entry in"*](https://bugzilla.mozilla.org/show_bug.cgi?id=1166068#c6) but do you like what you see in the screenshot?
=> fixes bug 1166068 - Graphics hexes in tooltips

minidump-stackwalk/http_symbol_supplier.cc, minidump-stackwalk/http_symbol_supplier.h, minidump-stackwalk/stackwalker.cc
This includes disk cache hits/misses as well as elapsed HTTP fetch time for misses. It looks like this:
```json
{
"modules" : [
{
"base_addr" : "0xd50000",
"code_id" : "54224E6B6000",
"debug_file" : "plugin-container.pdb",
"debug_id" : "42331CE9D3A74178A1753DD1D9115F8C2",
"end_addr" : "0xd56000",
"filename" : "plugin-container.exe",
"loaded_symbols" : true,
"symbol_disk_cache_hit" : false,
"symbol_fetch_time" : 2344.384033203125,
"version" : "32.0.3.5379"
},
{
"base_addr" : "0x5e070000",
"code_id" : "54224D93192e000",
"debug_file" : "xul.pdb",
"debug_id" : "553EB6DB78C34A58BE608DB8784798642",
"end_addr" : "0x5f99e000",
"filename" : "xul.dll",
"loaded_symbols" : true,
"symbol_disk_cache_hit" : true,
"version" : "32.0.3.5379"
}
]
}
```
We should be able to use this with …
=> Output symbol cache stats in stackwalker output

socorro/lib/search_common.py, socorro/unittest/lib/test_search_common.py
=> Fixes bug 1171955 - Fixed all betas filter for Super Search.

socorro/processor/signature_utilities.py
added "(NS_)?(Lossy)?(Copy|Append|Convert).*UTF.*" to the prefix skip list
=> Fixes Bug 1130960 - added new RE to prefix list for UTF signatures

socorro/processor/breakpad_transform_rules.py
add another predicate to the JIT rule.
=> Fixes Bug 1124241 - added  "no module" predicate

socorro/processor/breakpad_transform_rules.py
stupidly used "platform" instead of "os_name" to detect windows.
=> No Bug - corrected platform to os_name

socorro/collector/crashmover_app.py, socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
correct error in selection of a base class for an ad hoc app.
=> No Bug - corrected wrong base class for copy raw & processed app

socorro/external/crashstorage_base.py
=> No Bug - ensured NullCrashStorage returns socorro DotDicts

socorro/external/es/crashstorage.py
=> ES 'no stackwalker' class missing string converter for redactor_class

socorro/external/postgresql/tcbs.py, socorro/lib/sqlutils.py, socorro/unittest/external/postgresql/test_crashes_signatures.py, socorro/unittest/external/postgresql/test_tcbs.py, socorro/unittest/lib/test_sqlutils.py
=> fixes bug 1173911 - tcbs reports order by checking

requirements.txt
=> fixes bug 1164465 - psycopg2 2.6.1 from pypi

socorro/external/postgresql/base.py, socorro/unittest/external/postgresql/test_base.py
=> Fixes bug 1174169 - Fixed magic beta filter for report/list/.

scripts/bootstrap.sh
=> bug 1171937 - copy other stackwalker binaries

socorro/collector/wsgi_breakpad_collector.py, socorro/unittest/collector/test_wsgi_breakpad_collector.py
r? @twobraids / @peterbe 
I am not sure that nginx will be able to handle gzipped HTTP POST as Apache did for us in the past, and we have at least Fennec clients out there sending these.
Unfortunately I wasn't able to reuse the multipart form parser `web.py` uses since they don't expose it in a useful way AFAICT, it's basically just a wrapper around `cgi.FieldStorage` using the `web.utils.storage` class though.
Besides the unit test, I have tried this on an EC2 instance with nginx+uwsgi, and it seems to work as expected with the client in https://gist.github.com/rhelmer/c9e3c861e3844d9cb142 (which you'll notice is very similar to the unit test)
=> fix bug 1176543 - collector should handle gzipped form posts

socorro/cron/crontabber_app.py
anyone r? (one liner, config change)
=> Fixes bug 1165869 - Run the elasticsearch cleanup cron job weekly.

socorro/processor/breakpad_transform_rules.py
adjustments to how the JIT category rule selects its targets
=> NO BUG - fixed predicate for JIT rule

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/supersearch/models.py
=> Fixes bug 1177307 - Verify the content of _facets field in public API.

webapp-django/crashstats/symbols/tests/test_utils.py, webapp-django/crashstats/symbols/utils.py, webapp-django/crashstats/symbols/views.py
=> fixes bug 1177217 - Problem extracting .zip content due to unsupported content-type

webapp-django/crashstats/manage/forms.py, webapp-django/crashstats/manage/templates/manage/base.html, webapp-django/crashstats/manage/templates/manage/crash_me_now.html, webapp-django/crashstats/manage/templates/manage/home.html, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/urls.py, webapp-django/crashstats/manage/views.py
=> fixes bug 1180850 - Crash Me Now for the webapp

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
=> Revert "fixes bug 1179456 - a ES bulk load within crashstorage context"

webapp-django/crashstats/manage/forms.py, webapp-django/crashstats/manage/templates/manage/base.html, webapp-django/crashstats/manage/templates/manage/crash_me_now.html, webapp-django/crashstats/manage/templates/manage/home.html, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/urls.py, webapp-django/crashstats/manage/views.py
This was reverted to help investigate a production issue that crept in shortly after AWS before we had our monitoring in order. The patch is r+, but we will be relanding and shipping each of these PRs one at a time on July 9 to attempt to find the problematic patch.
=> 2. Rebort! "Revert "fixes bug 1180850 - Crash Me Now for the webapp""

socorro/processor/signature_utilities.py
=> fixes Bug 1180882 - added  '_invalid_parameter_noinfo' to prefix list

socorro/external/rabbitmq/crashstorage.py, socorro/unittest/external/rabbitmq/test_crashstorage.py
while not including remediation, this PR formalizes the logging of the acks so we can match them.
=> Fixes Bug1183608 - added logging to assist in confirming acks

socorro/external/rabbitmq/crashstorage.py, socorro/unittest/external/rabbitmq/test_crashstorage.py
when there duplicate crash_ids in the queues and the duplicates are picked up by the same processor, both the job acknowledgement cache and the dumps on disk experience a collision.  This results in failed queue ack'ng (and therefore stuck jobs) as well as failures in running the stackwalker.  The QueingThread should detect this situation and decline to accept the duplicate crash jobs.
=> FIxes Bug 1185031 - make Rabbit refuse to offer crashes already in progress

webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
=> fixes bug 1187497 - Cannot read compressed symbols

webapp-django/crashstats/symbols/views.py
=> fixes bug 1187986 - Change boto S3 calling format when connecting

socorro/cron/jobs/fetch_adi_from_hive.py, socorro/unittest/cron/jobs/test_fetch_adi_from_hive.py
@twobraids r?
I did some indentation fixes here and there too. That's why it looks like a bigger diff. 
Those changes makes the code read better I think. 
I'm now going to try to set up a crontabber instance locally that just runs this job.
=> bug 1185751 - Get ADI pulled in on stage

socorro/external/rabbitmq/crashstorage.py, socorro/unittest/external/rabbitmq/test_crashstorage.py
the queuing thread of the processors (and stage-submitter) do not recover from connection errors on that thread.  The iterator is not protected by a transaction object because for other queue types, that can result a long running transaction and excessive locking.  This historical decision is not necessary as rabbit's ```...basic_get``` method can easily be wrapped in a transaction object.  
This PR does the wrapping and new tests ensure that a broken connection is re-established rather than just allowing the thread to hang.
=> Fixes Bug 1187642 - wrapped rabbitmq basic_get in transaction object

alembic/versions/b99155654de_sunset_all_future_metrofirefox.py, socorro/external/postgresql/raw_sql/procs/update_product_versions.sql
=> bug 1189432 - remove metro firefox

socorro/cron/jobs/truncate_partitions.py
=> fixes bug 1191006 - truncate partitions more aggressively

webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
=> fixes bug 1191458 - Don't create if you can't get an S3 if it doesn't exist

webapp-django/crashstats/symbols/views.py
=> fixes bug 1187986 - revert S3 calling format

webapp-django/crashstats/symbols/views.py
@rhelmer r? 
We're getting desperate. It's past 4pm.
=> better errors on bucket creation errors

.travis.yml, scripts/start-travis-elasticsearch.sh
Testing to find out what version of ES travis installs
=> fixes bug 1189394 - Update travis to use Elasticsearch 1.4

webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
=> fixes bug 1191549 - s3connection.lookup() is better

socorro/external/es/base.py, socorro/external/es/query.py, socorro/external/es/super_search_fields.py, socorro/external/es/supersearch.py, socorro/middleware/middleware_app.py, socorro/unittest/external/es/base.py, socorro/unittest/external/es/test_query.py, socorro/unittest/external/es/test_super_search_fields.py, socorro/unittest/external/es/test_supersearch.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/base/tests/testbase.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/views.py, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/supersearch/models.py, webapp-django/crashstats/supersearch/tests/test_forms.py, webapp-django/crashstats/supersearch/tests/test_views.py
@AdrianGaudebert This works locally when clicking around and stuff. The tests also pass locally. 
I had to do a lot of deep debugging to get this to work and I probably have a lot of ugly code lying around. I just wanted you to get involved early and I wanted to see how tests work out on travis.
=> Bug 1188087 supersearchfields directly via ssocorro

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/daily.js, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/dashboard_graph.js
disable secondary x-axis, the year, on the dashboard graph
=> (nobug) disable secondary x-axis

socorro/external/postgresql/adi.py, socorro/unittest/external/postgresql/test_adi.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py
=> fixes bug 1194329 - Expose raw ADI counts in public web API

docs/index.rst, docs/symbols.rst
@luser if you can make a PR towards my fork, we should have enough to at least have it written down somewhere.
=> fixes bug 1186454 - Document structure of symbol files to be uploaded

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py
So when I started I thought I'd apply this to that little `SocorroMiddleware.fetch` method that actually makes the method call to a thing like `socorro.external.es.supersearch.SuperSearch.get` and at that point immediately convert the call to a 400 Bad Request. 
But then I changed my mind. If someone uses the public web API and supply some nasty value (e.g. `date=2015-02-32`) that our first line of defense can't catch and it goes into the implementation classes then it was the user's fault for supplying bad data. 
However, if it happens in a django view (e.g. `report_list()`) or the super search django view, the the user didn't type things in. Most likely they just click things. Granted, on the super search UX you *do* type in values. However, **that** we should catch …
=> fixes bug 1195406 - BadArgumentErrors need to become 400 Bad Requests

requirements.txt
@AdrianGaudebert @lonnen r?
I installed it on my local laptop, was able to sign out and sign in again.
=> fixes bug 1195920 - django 1.7.10

socorro/external/es/supersearch.py, socorro/lib/search_common.py, socorro/unittest/external/es/test_supersearch.py, socorro/unittest/lib/test_search_common.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/supersearch/models.py
=> Fixes bug 1194769 - Added date and number histograms to Super Search.

socorro/lib/search_common.py, socorro/unittest/external/es/test_supersearch.py, socorro/unittest/lib/test_search_common.py
=> fixes bug 1195345 - bad error on supersearch when the date range is too large

socorro/collector/submitter_app.py, socorro/external/fetch_app.py, socorro/middleware/middleware_app.py, socorro/processor/timemachine.py
remove all the places where HBase is the default crashstore - we're just not doing that anymore.
=> NO BUG - HBase shouldn't be the default for anything

webapp-django/crashstats/base/templates/crashstats_base.html
=> fixes bug 1196483 - {ally} Document has invalid language code.

webapp-django/crashstats/manage/tests/test_views.py
=> fixes bug 1196832 - Refactor tests that mock patch SuperSearchFields

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
=> fixes bug 1197915 - crontabber status ALLGOOD

webapp-django/crashstats/crashstats/templates/crashstats/daily.html, webapp-django/crashstats/crashstats/templates/crashstats/status.html, webapp-django/crashstats/crashstats/views.py
It's not a security thing because you can't have access to what gets printed there.
=> fixes bug 1198528 - status page tries to display python data as json

alembic/versions/4afd4e13281d_correct_windows_unknown_to_windows_10.py
@twobraids r?
cc @selenamarie 
Because I had closed https://github.com/mozilla/socorro/pull/2949 and then rebased this branch, it couldn't re-open the pull request.
=> fixes bug 1132652 - Windows 10, not Windows Unknown

socorro/processor/signature_utilities.py
added new Regular Expression to the signature generation prefix skip list
=> fixes Bug 1200416 - added "nsTArray_Impl<.*" to prefix list

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/manage/views.py
Note the left-over comment in the code with the print statement :)
I'll rebase that away when I get the r+.
=> fixes bug 1196751 - Implementation instantiation gets overly cached

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report_list_signature_summary.js, webapp-django/crashstats/crashstats/templates/crashstats/signature_summary.html, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
=> Fixes bug 1194048 - Added a rank to product/versions signature summary.

alembic/versions/16b2bee7db72_backfill_signature_summary_os_28_days.py
=> fixes bug 1201270 - Migration to backfill last 28 days of signature_summary_os

webapp-django/crashstats/symbols/management/commands/reencode-bad-sym-files.py
@rhelmer r?
So this was thorny to say the least. 
My local python can't connect to S3 buckets with setting calling_format. And centos can't connect to S3 buckets if you do. 
See extended comment. 
Secondly, you can't, on my Python 2.7 OSX do something like `requests.get('https://s3.amazonaws.com/peterbe.org.allizom.crash-stats.staging.crashes/v1/symbolPush/C356CD0633314E568FDCFF475732FE741/NPSWF64.sym')` 
So I changed how the URL is made.
=> Reencode to work without setting calling format

docs/configuring-crash-stats.rst, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
@rhelmer r?
Note: I make the bug of this PR depend on [1131987](https://bugzilla.mozilla.org/show_bug.cgi?id=1131987) which isn't [resolved yet](https://github.com/mozilla/socorro/pull/2840) but I know once it lands you're going to be able to do the wildcards stuff.
=> fixes bug 1172693 - Document how to configure S3 symbol uploads

webapp-django/crashstats/manage/forms.py
=> fixes bug 1189032 - GroupForm needs updating

webapp-django/crashstats/crashstats/static/crashstats/css/report_list.less, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report_list_sigurls.js, webapp-django/crashstats/crashstats/templates/crashstats/partials/sigurls.html, webapp-django/crashstats/crashstats/tests/test_views.py
=> fixes bug 1204108 - Don't truncate signature URLs

webapp-django/crashstats/symbols/management/commands/reencode-bad-sym-files.py, webapp-django/crashstats/symbols/models.py
=> bug 1193536 - only reencode S3 uploads of matching bucket name

webapp-django/crashstats/monitoring/tests/test_views.py, webapp-django/crashstats/monitoring/views.py
=> fixes bug 1204960 - crash-analysis health warnings

socorro/external/es/supersearch.py, webapp-django/crashstats/supersearch/models.py, webapp-django/crashstats/topcrashers/templates/topcrashers/topcrashers.html, webapp-django/crashstats/topcrashers/tests/test_views.py, webapp-django/crashstats/topcrashers/views.py
=> Fixes bug 1195310 - Showed startup crash icon in new topcrashers.

webapp-django/crashstats/base/templates/crashstats_base.html
=> bug 1186474 - remove crash_trends link

webapp-django/crashstats/supersearch/static/supersearch/css/search.less, webapp-django/crashstats/supersearch/static/supersearch/js/socorro/search.js
=> Fixes bug 1205407 - Display error messages from the server correctly.

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/topcrashers/templates/topcrashers/topcrashers.html, webapp-django/crashstats/topcrashers/tests/test_views.py, webapp-django/crashstats/topcrashers/views.py
=> Fixes bug 1195307 - Added first appearance date to new topcrashers.

webapp-django/crashstats/manage/templates/manage/analyze-model-fetches.html, webapp-django/crashstats/manage/templates/manage/api_tokens.html, webapp-django/crashstats/manage/templates/manage/base.html, webapp-django/crashstats/manage/templates/manage/crash_me_now.html, webapp-django/crashstats/manage/templates/manage/events.html, webapp-django/crashstats/manage/templates/manage/featured_versions.html, webapp-django/crashstats/manage/templates/manage/fields.html, webapp-django/crashstats/manage/templates/manage/graphics_devices.html, webapp-django/crashstats/manage/templates/manage/group.html, webapp-django/crashstats/manage/templates/manage/groups.html, webapp-django/crashstats/manage/templates/manage/home.html, webapp-django/crashstats/manage/templates/manage/products.html, webapp-django/crashstats/manage/templates/manage/releases.html, webapp-django/crashstats/manage/templates/manage/skiplist.html, webapp-django/crashstats/manage/templates/manage/symbols_uploads.html, webapp-django/crashstats/manage/templates/manage/user.html, webapp-django/crashstats/manage/templates/manage/users.html, webapp-django/crashstats/monitoring/templates/monitoring/index.html, webapp-django/crashstats/symbols/templates/symbols/api_upload.html, webapp-django/crashstats/symbols/templates/symbols/base.html, webapp-django/crashstats/symbols/templates/symbols/home.html, webapp-django/crashstats/symbols/templates/symbols/symbols_base.html, webapp-django/crashstats/symbols/templates/symbols/web_upload.html, webapp-django/crashstats/tokens/templates/tokens/home.html
The only ones left now are...:
```
$ git ls-files | grep '\.html' | xargs python indentations.py  | grep -v 4
2 	crashstats/crashstats/templates/crashstats/daily.html
2 	crashstats/crashstats/templates/crashstats/report_index_not_found.html
2 	crashstats/crashstats/templates/crashstats/report_index_pending.html
2 	crashstats/crashstats/templates/crashstats/report_index_too_old.html
2 	crashstats/crashstats/templates/crashstats/report_list.html
2 	crashstats/crashstats/templates/crashstats/reports_columns_form.html
2 	crashstats/crashstats/templates/crashstats/reports_columns_form_hint.html
1 	crashstats/crashstats/templates/crashstats/signature_summary.html
2 	crashstats/crashstats/templates/crashstats/topchangers.html
```
=> bug 1207638 - 4-spaces .html files

docs/development/elasticsearch.rst, webapp-django/crashstats/supersearch/templates/supersearch/search.html, webapp-django/crashstats/supersearch/tests/test_views.py, webapp-django/crashstats/supersearch/views.py
=> fixes bug 1208172 - swap supersearch-custom-query waffle flag to negative

webapp-django/crashstats/topcrashers/views.py
=> Fixes bug 1206078 - Corrected ranking diff in new topcrashers.

webapp-django/crashstats/crashstats/static/crashstats/css/screen.less, webapp-django/crashstats/crashstats/templates/crashstats/report_list_base.html, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/signature/templates/signature/signature_report.html, webapp-django/crashstats/supersearch/form_fields.py
=> Revert 1200596

socorro/external/es/supersearch.py, socorro/lib/search_common.py, socorro/unittest/external/es/test_supersearch.py
Replaced the wilcard and match_phrase queries with filter queries, allowing them to be combined with other filters in boolean filters. 
Values of a filter now combine with "OR" instead of "AND", except for ranges.
@peterbe r?
=> Fixes bug 1197251 - Rewrote SuperSearch filters combination. 

alembic/versions/30adec758cc9_drop_lag_log_table.py, socorro/external/postgresql/models.py
=> fixes bug 1198531 - drop laglog table

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
retry this months later to see if it works.
=> fixes Bug 1179456 - ES bulk load within crashstorage context

webapp-django/crashstats/crashstats/static/crashstats/css/screen.less, webapp-django/crashstats/crashstats/templates/crashstats/report_list_base.html, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/signature/templates/signature/signature_report.html, webapp-django/crashstats/signature/views.py, webapp-django/crashstats/supersearch/form_fields.py, webapp-django/crashstats/supersearch/tests/test_form_fields.py
@peterbe Same 2 commits that you reviewed, plus a new one that fixes that ``DateTimeField`` class that caused problems on prod.
=> Fixes bug 1200596 - Added a link to signature report from report/list/

.eslintrc
@peterbe So this is mostly enforcing the default rules. Many failures I see are caused by undefined global variables like ``$``, but there are other interesting things, like missing semicolons, wrong indentation, etc. Once we agree on a ruleset I'll try to fix at least a few files, and maybe add that to our build process (though I doubt I'll do it on the ``crashstats`` app's JS files, because they are quite a mess).
=> No bug - Added a config file for eslint.

socorro/external/postgresql/adi.py, socorro/external/postgresql/bugs.py, socorro/external/postgresql/bugs_service.py, socorro/external/postgresql/crashes.py, socorro/external/postgresql/crontabber_state.py, socorro/external/postgresql/dbapi2_util.py, socorro/external/postgresql/field.py, socorro/external/postgresql/gccrashes.py, socorro/external/postgresql/graphics_devices.py, socorro/external/postgresql/platforms.py, socorro/external/postgresql/product_build_types.py, socorro/external/postgresql/products.py, socorro/external/postgresql/releases.py, socorro/external/postgresql/report.py, socorro/external/postgresql/server_status.py, socorro/external/postgresql/signature_first_date.py, socorro/external/postgresql/signature_urls.py, socorro/external/postgresql/skiplist.py, socorro/unittest/external/postgresql/test_dbapi2_util.py
@twobraids r?
Thanks for the FetchAllSequence class. I really like the much shorter new code we can get out of this.
=> fixes bug 1213334 - sequence for cursor.fetchall()

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/crashes_per_user.js
=> fixes bug 1213069 - product selection bug

webapp-django/crashstats/topcrashers/templates/topcrashers/topcrashers.html
=> Fixes bug 1196779 - Added dates in links to signature report in new TCBS.

webapp-django/crashstats/crashstats/static/crashstats/css/crashes_per_user.less, webapp-django/crashstats/crashstats/static/crashstats/css/daily.less, webapp-django/crashstats/crashstats/static/crashstats/css/screen.less, webapp-django/crashstats/crashstats/templates/crashstats/crashes_per_user.html, webapp-django/crashstats/crashstats/templates/crashstats/daily.html, webapp-django/crashstats/crashstats/templates/crashstats/report_list_base.html, webapp-django/crashstats/crashstats/templates/crashstats/topcrasher.html, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/signature/templates/signature/signature_report.html, webapp-django/crashstats/topcrashers/templates/topcrashers/topcrashers.html
=> fixes bug 1213058 - Link old Crashes per user reports to new one

webapp-django/crashstats/tokens/static/tokens/css/home.css, webapp-django/crashstats/tokens/static/tokens/js/home.js, webapp-django/crashstats/tokens/templates/tokens/home.html, webapp-django/crashstats/tokens/tests/test_views.py
This feels much better. No longer dependent on some hack in HTML or any hack in CSS.
=> fixes bug 1212969 - show API tokens with javascript

webapp-django/crashstats/monitoring/tests/test_views.py, webapp-django/crashstats/monitoring/views.py, webapp-django/crashstats/settings/base.py
=> fixes bug 1214023 - Monitor if crontabber is failing to start at all

webapp-django/crashstats/monitoring/tests/test_views.py, webapp-django/crashstats/monitoring/views.py
@lonnen or @AdrianGaudebert r?
I'd like this push this out sooner rather than later. Hence calling for your attention @lonnen. Once this is in I can push to prod.
=> fixes bug 1214023 - crontabber monitoring on date comparison

webapp-django/crashstats/topcrashers/templates/topcrashers/topcrashers.html, webapp-django/crashstats/topcrashers/tests/test_views.py
=> Fixes bug 1214743 - Fixed error when no first date for a signature.

webapp-django/crashstats/crashstats/templates/crashstats/about_throttling.html, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/urls.py, webapp-django/crashstats/crashstats/views.py
=> fixes bug 1214510 - /about/throttling page

webapp-django/crashstats/crashstats/models.py
=> fixes bug 1215581 - Reduce CrontabberState caching to an almost minimal

docs/development/webapp.rst, requirements.txt, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/settings/__init__.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/settings/test.py
=> fixes bug 1123905 - Stop depending on test-utils

alembic/versions/3860644579f4_drop_crontabber_state_table.py, docs/development/databasetabledesc.rst, socorro/external/postgresql/models.py, socorro/external/postgresql/staticdata.py, socorro/unittest/external/postgresql/test_setupdb_app.py
=> fixes bug 1215577 - Delete old crontabber_state table

socorro/app/fetch_transform_save_app.py, socorro/lib/task_manager.py, socorro/lib/threaded_task_manager.py, socorro/processor/processor_app.py
enhancements to the previous PR under the same name.
=> fixes Bug 1212917: cleanup of the iterator refactoring

socorro/cron/jobs/bugzilla.py, socorro/unittest/cron/jobs/test_bugzilla.py
=> fixes bug 1215511 - bugzilla crontabber app and days_into_past

webapp-django/crashstats/base/templates/crashstats_base.html, webapp-django/crashstats/crashstats/templates/crashstats/home.html, webapp-django/crashstats/crashstats/templates/crashstats/topchangers.html
=> Fixes bug 1216984 - Unlinked topchangers and added a deprecation notice.

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/supersearch/models.py
=> Fixes bug 1216928 - Exposed SuperSearchFields in public API.

socorro/cron/jobs/ftpscraper.py, socorro/unittest/cron/jobs/test_ftpscraper.py
=> fixes bug 1217917 - Change default FTP scraping URL

socorro/dataservice/dataservice_app.py, socorro/external/boto/crashstorage.py, socorro/external/rabbitmq/crashstorage.py, socorro/processor/mozilla_processor_2015.py, socorro/processor/socorrolite_processor_2015.py
some derived classes change the underlying configuration defaults in a manner that changes the value for all super classes too.  Make the scope of the change local to the defining class only.
=> fixes Bug 959724 - the set_default problem that overrode underlying config defaults

webapp-django/crashstats/signature/static/signature/css/signature_report.less, webapp-django/crashstats/signature/static/signature/js/signature_report.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_summary.js, webapp-django/crashstats/signature/templates/signature/signature_report.html, webapp-django/crashstats/signature/templates/signature/signature_summary.html, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/signature/urls.py, webapp-django/crashstats/signature/views.py, webapp-django/crashstats/supersearch/tests/common.py, webapp-django/crashstats/supersearch/views.py
@peterbe r?
This is the first step, I'm adding no new features to Super Search, no new data, just using existing features. I could reproduce 4 features perfectly (architecture, process type, flash version and exploitability), and an imperfect operating system summary (it's missing more precise OS names). 
I'm now going to work on adding what's needed to make the remaining 5 features.
=> Fixes bug 1214558 - Added a first prototype of a Summary tab.

setup.cfg, socorro/cron/jobs/ftpscraper.py, socorro/unittest/cron/jobs/test_ftpscraper.py
Note! This PR does NOT yet have new tests. The reason I'm prematurely making it a PR is to optimize our day. Perhaps you can get started with what we have so far whilst I re-write the unit tests. 
Again, sorry for baking in a bunch of pep8 fixes into the mix. I did that to get momentum on this work last week as a warm-up.
=> fixes bug 1217828 - make ftpscraper work on https://archive.mozilla.org

socorro/external/es/supersearch.py, socorro/unittest/external/es/test_supersearch.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/supersearch/models.py
=> Fixes bug 1219206 - Added cardinality feature to Super Search.

webapp-django/crashstats/signature/templates/signature/signature_summary.html, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/signature/views.py
=> Fixes bug 1221948 - Used platform_pretty_version instead of platform.

socorro/external/postgresql/graphics_report.py, socorro/unittest/external/postgresql/test_graphics_report.py, webapp-django/crashstats/crashstats/views.py
Adrian, it would be cool if you can review this soon. I'm hoping to have it in production by the end of Monday.
=> fixes bug 1222635 - Graphics report doesn't respect date parameter

socorro/external/es/supersearch.py, socorro/lib/search_common.py, socorro/unittest/external/es/test_supersearch.py, webapp-django/crashstats/supersearch/models.py
=> Fixes bug 1221952 - Added _aggs parameter for all fields.

webapp-django/crashstats/profile/static/profile/css/profile.css, webapp-django/crashstats/profile/templates/profile/profile.html, webapp-django/crashstats/profile/views.py
=> Fixes bug 1215153 - Added links to Profile page, removed tokens.

webapp-django/crashstats/base/context_processors.py, webapp-django/crashstats/base/templates/crashstats_base.html, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/settings/base.py
=> fixes bug 1223062 - Remove Pingdom RUM monitoring

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
=> Fixes bug 1218751 - Use Windows NT instead of just Windows.

webapp-django/crashstats/base/templates/crashstats_base.html, webapp-django/crashstats/crashstats/decorators.py, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/nav.js, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/topcrashers/views.py
=> Fixes bug 1221172 - Top navigation made more flexible and robust.

webapp-django/crashstats/crashstats/static/crashstats/css/screen.less, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
What do you think @AdrianGaudebert ?
=> fixes bug 1224011 - KeyError on histogram_date in Crashes per User

scripts/data/supersearch_fields.json, webapp-django/crashstats/signature/templates/signature/signature_summary.html, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/signature/views.py
=> Fixes bug 1221957 - Added a Product summary.

socorro/external/postgresql/graphics_devices.py, socorro/lib/external_common.py, socorro/unittest/external/postgresql/test_graphics_devices.py
=> Fixes bug 1224151 - Allowed multiple values in graphics_devices service.

webapp-django/crashstats/signature/templates/signature/signature_summary.html, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/signature/views.py
=> Fixes bug 1225447 - Added a Graphics Adapter summary.

socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
this patch adds the signature ```<name omitted>``` to the list of exceptions for the template collapsing signature generation rule.
=> fixes Bug 1222080 - added "name omitted" special case to sig gen rule

webapp-django/crashstats/signature/views.py
=> Fixes bug 1227514 - Sorted graphics adapters by count.

socorro/external/es/supersearch.py, socorro/lib/search_common.py, socorro/unittest/external/es/test_supersearch.py, webapp-django/crashstats/supersearch/models.py
=> Fixes bug 1225445 - Added _aggs.product.version parameter to Super Search.

socorro/external/http/correlations.py, socorro/unittest/external/http/test_correlations.py
So this has apparently been a bug for a very long time. 
Any file that ends with a .gz [for example](https://crash-analysis.mozilla.com/crash_analysis/20151116/20151116_Firefox_43.0b2-interesting-modules-with-versions.txt.gz) gets downloaded in raw gzip format and saved in the temp directory as `something.txt` and then when it parses it it always fails because the content is not a regular string.
=> fixes bug 1225600 - Correlation http downloads gets gzip wrong

socorro/external/es/supersearch.py, socorro/lib/search_common.py, socorro/unittest/external/es/test_supersearch.py, webapp-django/crashstats/signature/templates/signature/signature_summary.html, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/signature/views.py, webapp-django/crashstats/supersearch/models.py
Added infinite level aggregations to Super Search.
@peterbe r?
=> Fixes bug 1227621 - Added a Mobile summary to signature report.

webapp-django/crashstats/signature/templates/signature/signature_summary.html, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/signature/views.py
=> Fixes bug 1221950 - Added installations count to Product summary.

webapp-django/crashstats/topcrashers/views.py
=> Fixes bug 1228124 - Added product to context in new TCBS.

webapp-django/crashstats/topcrashers/tests/test_views.py, webapp-django/crashstats/topcrashers/views.py
=> Fixes bug 1228302 - Always set a version in context.

webapp-django/crashstats/base/templates/crashstats_base.html, webapp-django/crashstats/crashstats/templates/crashstats/home.html
=> Bug 1221048 - Link to new implementations by default

socorro/cron/jobs/fetch_adi_from_hive.py, socorro/unittest/cron/jobs/test_fetch_adi_from_hive.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1226345 is a beast. 
Let me share what I know...
First of all, what's happen thrice in the last couple of days (or weeks?) is that Hive has returned 0 rows and thus the whole ADI stored procedure mess has failed. The `fetch-adi-from-hive` job says all is well because nothing broke. 
The concern is that we might be READING **whilst** Hive is being filled up and thus we might accidentally read too few ADI numbers. That's what that bug has spun into a discussion about comparing the results today with yesterday's. Or, we might be able to scrape some VPN protected complicated page and make a judgement call based on that. That's all SUPER scary and doable but means a lot of code. 
This PR takes care of the most basic situation where we get exactly 0 …
=> bug 1226345 - fail fetch-adi-from-hive if 0 rows

webapp-django/crashstats/crashstats/templates/crashstats/home.html
=> Fixes bug 1232426 - Fixed version in home page links to TCBS.

webapp-django/crashstats/topcrashers/tests/test_views.py, webapp-django/crashstats/topcrashers/views.py
=> Fixes bug 1228969 - Removed the version check from new topcrashers.

socorro/processor/signature_utilities.py
=> Fixes bug 1229238 - Added PLDHashTable::Remove to the prefix list.

socorro/processor/signature_utilities.py
=> Fixes bug 1231317 - Added std::_Atomic_fetch_add_4 to the skip list.

scripts/crons/cron_libraries.sh
This puts the version of cron_libraries.sh into the github repo that we have been running on the crash-analysis box for some time now.
=> merge correlations changes from crash-analysis box into Socorro source

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/utils.py, webapp-django/crashstats/settings/base.py
=> fixes bug 1241286 - Rate-limit for authenticated users too

socorro/cron/jobs/matviews.py, socorro/unittest/cron/jobs/test_matviews.py
@adngdb I'd love to get this in on prod before tomorrow.
=> fixes bug 1243405 - Make build-adu-matview depend on fetch-adi-from-hive

socorro/external/es/correlations.py, socorro/external/es/mappings/correlations_index_settings.json, socorro/unittest/external/es/test_correlations.py
This mapping will probably need to be tuned a bit, but at least now you have a foundation on which you can start building your correlations app.
=> Fixes bug 1242983 - Added a mapping for correlations.

socorro/cron/jobs/fetch_adi_from_hive.py, socorro/unittest/cron/jobs/test_fetch_adi_from_hive.py
@adngdb As soon as you've merged this, I'll enable this job on stage's crontabber consulate thing.
=> bug 1246673 - ADU matviews on stage crontabber never run

webapp-django/crashstats/crashstats/jinja2/crashstats/home.html, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/dashboard_graph.js, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
This PR has a lot of code moving around, sorry about that. Also note that the JS file has no actual logic changes, it's only a code cleanup based on what eslint was saying.
=> Fixes bug 1238972 - Use Super Search to generate home page graph.

webapp-django/crashstats/base/templatetags/jinja_helpers.py, webapp-django/crashstats/base/tests/test_jinja_helpers.py
@adngdb I asked @rhelmer to review this because I wanted to land it today.
=> fixes bug 1249623 - clean query args before calling reverse()

webapp-django/crashstats/tokens/models.py, webapp-django/crashstats/tokens/tests/test_models.py
The loop in there is maybe not ultra-performant (for example, fixing the users' permissions for each token) but this operation is extremely rare.
=> fixes bug 1250645 - revoke some permissions when groups change

socorro/processor/signature_utilities.py
=> Fixes bug 1249794 - Added nsDebugImpl::Abort to the prefix list.

tools/webqapassing.py
cc @lonnen @jdotpz @m8ttyB
I wrote this. Primarily for myself, as a tool to be more careful when I push out a release tag, that WebQA tests are healthy. In particular, stage. I.e. stage shouldn't have become broke from recent changes if you're pushing to prod. 
This PR is basically to put that script into the repo or not.
=> webqapassing tool

alembic/versions/335c2bfd99a6_bug_1255444_fix_fennecandroid_for_new_.py
=> bug 1255444 fix fennecandroid for new release repository

socorro/external/postgresql/crashstorage.py, socorro/unittest/external/postgresql/test_crashstorage.py
add a config parameter to the Socorro PG crashstorage class to optionally save the processed crash.  'save_processed_crash' is a boolean, with this behavior:
True: the processed crash json is saved to a table PG
False: the processed crash json is not saved directly [DEFAULT]
this has no effects on the regular 'reports' table.  It only toggles the save behavior on the the json table for processed crashes
This change does not prevent the creation of the processed crash table in PG nor stop socorro from trying to fetch a processed crash from that table.
=> fixes Bug 1252461 allow for optionally saving processed json in PG

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/topcrash.js, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html, webapp-django/crashstats/topcrashers/tests/test_views.py, webapp-django/crashstats/topcrashers/views.py
OK, this is ready now. Incidentally, I used the opportunity to make that Topcrashes page support several versions (which it should already have). 
@willkg how do you feel about reviewing this?
=> Fixes bug 1258420 - Added a by build date option to Topcrashers.

socorro/cron/jobs/ftpscraper.py, socorro/unittest/cron/jobs/test_ftpscraper.py
To actually run:
```
time python socorro/cron/jobs/ftpscraper.py --product=thunderbird,firefox,mobile
```
(Takes about 5 minutes and instead of writing into PG, it just prints what it would insert)
I'm not convinced about the way the test classes are set up with the mocking. Not sure it's particularly important either.
=> fixes bug 1260216 - Use requests in ftpscraper.py

webapp-django/crashstats/settings/base.py
So now I get the best of both worlds:
* MUCH fewer things
* On local dev, I can set up, in my `.env` a `IMPLEMENTATIONS_DATABASE_URL` to make it different.
=> bug 1261145 - Only use DATABASE_URL everywhere in webapp

Vagrantfile, puppet/vagrant/modules/socorro/manifests/init.pp
* make memory default to 1024 but configurable via environment
variable
* make puppet debug output configurable via environment variable
* add breakpad_rw postgres role
r?
=> Fixes bug 1261879 - Vagrant fixes

socorro/processor/mozilla_processor_2015.py, socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
This reverts commit 702ca6be292370575a993abedc26792fcc37b91d.
=> Revert "Fixes bug 803779 - Added a rule for Abort signatures."

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/models.py
=> filtering on signaturesummary api results

docs/development/glossary/index.rst
@twobraids It's rough and short but did I get the gist right?
=> document about priorityjob vs reprocessing

webapp-django/crashstats/crashstats/forms.py, webapp-django/crashstats/crashstats/tests/test_forms.py
This just prevents people from using the date parameter wrong and triggering a internal server error.
=> fixes bug 1264940 - validate date range on crashes per day

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
@peterbe this should take priority over everything else, we'd like to have this turned on in prod by Monday. Let's work together to have it in stage asap so we can test it on real data.
=> Bug 1265015 - Added a new crashstore to put subset of the json_dump in ES.

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
=> Revert "Bug 1265015 - Added a new crashstore to put subset of the json_dump in ES."

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
Reverts the reverts. 
No code review needed. I just need to re-land this onto stage.
=> Revert "Revert "Bug 1265015 - Added a new crashstore to put subset of the json_dump in ES.""

socorro/external/postgresql/base.py, socorro/external/rabbitmq/crashstorage.py, socorro/middleware/search_common.py, socorro/unittest/external/rabbitmq/test_reprocessing.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/manage/forms.py, webapp-django/crashstats/manage/jinja2/manage/base.html, webapp-django/crashstats/manage/jinja2/manage/home.html, webapp-django/crashstats/manage/jinja2/manage/reprocessing.html, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/urls.py, webapp-django/crashstats/manage/views.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/supersearch/models.py
=> fixes bug 598608 - Add a way to reprocess reports

socorro/processor/mozilla_processor_2015.py, socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
=> Fixes bug 1268029 - Added a Rule to replace a signature if there is a JIT classification.

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py
=> Fixes bug 1271281 - Hide API base classes from public eyes.

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report.js, webapp-django/crashstats/crashstats/views.py
=> fixes bug 1005224 - log failed correlations reports

socorro/processor/mozilla_processor_2015.py, socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
@peterbe the first commit is the one you reviewed a few weeks ago, the second one is the new feature that KaiRo asked for in the bug.
=> Fixes bug 803779 - Added a rule for Abort signatures.

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py
=> fixes bug 1278244 - Bugs api to take a list

webapp-django/crashstats/base/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/static/crashstats/css/screen.less, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/signature/jinja2/signature/signature_reports.html, webapp-django/crashstats/signature/static/signature/css/signature_report.less, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/signature/views.py
=> Fixes bug 1269894 - Add an annotation to AMD CPU bug related crashes.

socorro/cron/jobs/missingsymbols.py
=> make it not a tuple

socorro/external/es/supersearch.py, socorro/middleware/search_common.py, socorro/unittest/external/es/test_supersearch.py, webapp-django/crashstats/supersearch/form_fields.py
@peterbe This is rather important for our users, and blocking a few things, see the bug. Sorry for dropping this on you just before my vacations, but would you mind seeing that it makes it to prod as soon as possible when you're back?
=> Fixes bug 1282529 - Include null values in results with falsy boolean filter.

socorro/siglists/prefix_signature_re.txt, socorro/siglists/trim_dll_signature_re.txt
Reverts mozilla/socorro#3383
temp revert to unblock a push
=> Revert "Bug 1274345. Add some 64bit dlls to the siglists"

socorro/external/es/supersearch.py, socorro/middleware/search_common.py, socorro/unittest/external/es/test_supersearch.py, webapp-django/crashstats/supersearch/form_fields.py
=> Revert "Fixes bug 1282529 - Include null values in results with falsy boolean filter."

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
Just a couple of tweaks for crash-stats' "Details" tab. I haven't tested them.
@peterbe, can you please review?
=> Some crash-stats webapp tweaks

.travis.yml
Trying to see if that fixes the issue.
=> Fixes bug 1289704 - Use ruby 2 in travis build process.

schemas/validate_and_test.py
now I can run this from anywhere
=> validate_and_test relativity

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
The chaotic ordering of fields in crash-stats has been bugging me for a while. This improves things.
=> Reorder crash report fields.

socorro/external/postgresql/server_status.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_server_status.py, socorro/unittest/middleware/test_middleware_app.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
=> fixes bug 1242974 - Remove processor status from status json

socorro/external/es/supersearch.py, socorro/unittest/external/es/test_supersearch.py
=> fixes bug 1290926 - no facets at all if _facets_size=0

webapp-django/crashstats/status/context_processors.py
We forgot to change it to `.exists()`.
=> bug 1290687 - .exists to check for status messages

socorro/external/boto/crashstorage.py, socorro/unittest/external/boto/test_connection_context.py, socorro/unittest/external/boto/test_crashstorage.py
Stylistic cleanup and change from `self.assertEqual` to `eq_`.
=> cleanup code around boto

tools/trigger
=> Trigger a deploy

webapp-django/crashstats/manage/jinja2/manage/status_message.html, webapp-django/crashstats/manage/static/manage/css/status_message.css, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/urls.py, webapp-django/crashstats/manage/views.py, webapp-django/crashstats/settings/bundles.py
Sorry Adrian, I should have made a bigger stink of this when you first wrote it. 
I just couldn't sleep at night knowing there's a URL you can simply visit that does DB writes.
=> fixes bug 1298159 - Disabling status messages should require POST

webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
Ted, if you don't have time to review, please throw this over to @adngdb
=> fixes bug 1295154 - Bad regex on symbol upload expressions

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/utils.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_aggregations.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_graphs.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_reports.js, webapp-django/crashstats/supersearch/jinja2/supersearch/search.html, webapp-django/crashstats/supersearch/static/supersearch/css/search.less, webapp-django/crashstats/supersearch/static/supersearch/js/lib/dynamic_form.js, webapp-django/crashstats/supersearch/static/supersearch/js/socorro/search.js, webapp-django/crashstats/supersearch/views.py
Oww man, I'm sorry @peterbe, I have done a lot of refactoring in the ``search.js`` file. Pretty much all of the file has changed or moved around. Maybe you want to review it as if it were a brand new file?
=> Fixes bug 1293694 - Merged simple and advanced Super Search forms.

minidump-stackwalk/Makefile
=> Fix stackwalker build on OS X

socorro/processor/mozilla_processor_2015.py, socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
add a transform rule to mutate the default theme's extension id into a more easily identifiable string
=> fixes bug 1301222 with a transform rule

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
=> Fixes bug 1303657 by fixing the "Build Architecture" tooltip.

webapp-django/crashstats/signature/jinja2/signature/signature_report.html, webapp-django/crashstats/signature/static/signature/js/signature_report.js
Please merge this before doing any prod release!
=> Fixes bug 1281540 - Show form in Signature Report after loading is done.

socorro/processor/mozilla_processor_2015.py, socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
I haven't tested it manually yet and I don't know how to run the automated tests yet. Hopefully Travis will take care of the second part.
=> Fixes bug 1306449 - Augment signatures that have the IPC Message Name annotation

tools/webqapassing.py
=> fixes bug 1308974 - Change domain where WebQA tests are summarized

socorro/external/fs/crashstorage.py, socorro/unittest/external/fs/test_fslegacydatedradixtreestorage.py
We have a problem with the -stage collector where we can get two
crashes with the same crash id. The first one will come in and get
saved--no problem.  The second one comes in and then trouble
starts. First, save_raw_crash() saves the crash by calling into
_save_files(). _save_files() happily stomps on any existing file, so
if there was a file already, it's no big deal.
Then save_raw_crash() goes to create two symlinks. Before this patch,
it would raise an OSError creating the name symlink because it created
one already with the first crash. That wouldn't get handled, so it'd
percolate up all the way and cause the collector to return an HTTP 500
to the client. Blech.
This patch changes the code to ignore the OSError. The better thing to
do would be for FSTemporaryStorage to realize the …
=> Fixes bug 1297760: handle OSError when symlinking

socorro/external/fs/crashstorage.py
Peter pointed out it'd be better to have *any* logging, so I added
a logging.info line.
@peterbe: Quick r?
=> fixes bug 1297760: Adjust logging for OSError

socorro/external/postgresql/crashes.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_crashes.py, socorro/unittest/middleware/test_middleware_app.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/signature/tests/test_views.py
=> fixes bug 1309024 - AduBySignature pure implementation

.gitignore
=> ignore e2e test's py.test cache

socorro/cron/jobs/fetch_adi_from_hive.py
=> bug 1307980 - new Hive URL schema

docs/development/dev-services.rst, puppet/vagrant/modules/socorro/files/build_python.sh, puppet/vagrant/modules/socorro/files/home/bashrc, puppet/vagrant/modules/socorro/manifests/init.pp
- fixes Vagrant environment to build Python 2.7.11 and use it
- updates and tweaks documentation for setting up Vagrant environment
- tweaks setup to install vim and emacs to make life easier in
the vm for Will
=> Update and fix Vagrant environment

socorro/processor/processor_app.py
E.g. https://sentry.prod.mozaws.net/operations/socorro-stage/issues/363454/
=> fixes bug 1313329 - set raven context in processor app

minidump-stackwalk/stackwalker.cc, socorro/schemas/crash_report.json
=> Fixes bug 1318481 - Put the PID in json_dump.

e2e-tests/requirements.txt
@m8ttyB et al. r?
Pretty straightforward, here:
* removed redundant bidpom include
* bumped all other dependencies with the exception of selenium
Ad-hoc job which passed, here: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/socorro.adhoc/84/console
=> Update pinned dependencies

e2e-tests/requirements.txt
=> Update requests to 2.12.3

webapp-django/crashstats/base/tests/testbase.py, webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/profile/tests/test_views.py, webapp-django/crashstats/symbols/tests/test_api.py, webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/tokens/tests/test_views.py
Note that it does NOT grant you access to download Unredacted JSON or minidumps. 
See https://bugzilla.mozilla.org/show_bug.cgi?id=1013976#c3 *"a desired feature in terms of data transparency (not so much an engineering ask)"*
=> fixes bug 1013976 - logged in users to see their own PII

socorro/external/es/base.py, socorro/external/es/crashstorage.py, socorro/external/es/index_creator.py, socorro/external/es/super_search_fields.py, socorro/unittest/external/es/test_super_search_fields.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/settings/base.py
This is a "better" version of #3620, see my commit for more explanations. 
I suggest that, if this PR is fine and gets an r+, we merge it and proceed with it, and close #3620. If this needs more work, then we should merge #3620 instead and land this later on as an improvement. 
cc @lonnen @milescrabill
=> Fixes bug 1319896 - Increased the number of shards per index to 10.

requirements.txt, socorro/processor/symbol_cache_manager.py
=> fixes bug 1252220 - Remove dependency of ordereddict

socorro/processor/mozilla_processor_2015.py, socorro/processor/rules/memory_report_extraction.py, socorro/unittest/processor/rules/memory_reports/bad_kind.json, socorro/unittest/processor/rules/memory_reports/bad_missing_key.json, socorro/unittest/processor/rules/memory_reports/bad_units.json, socorro/unittest/processor/rules/memory_reports/bad_unrecognizable.json, socorro/unittest/processor/rules/memory_reports/good.json, socorro/unittest/processor/rules/test_memory_report_extraction.py, socorro/unittest/processor/test_signature_utilities.py
This is based on work by @nnethercote, see [bug 1291173](https://bugzilla.mozilla.org/show_bug.cgi?id=1291173) for more context. 
Assigning to Will because you seem to be willing to review processor stuff. Feel free to bounce it to Peter if you think that's incorrect. :)
=> Bug 1291173 - Added a rule to extract key measurements from memory_report.

e2e-tests/tests/test_api.py
=> fixes bug 1316407 - Create a suite of e2e tests for the API

e2e-tests/requirements.txt
This release fixes a JSON-encoding bug, per https://pypi.python.org/pypi/requests/2.12.5
=> Bump requests to latest

e2e-tests/tests/test_api.py
This fixes the assertion that we should have at least one signature first date
for each signature--that turns out to not necessarily be the case. I changed it
to make sure it's > 0. Hopefully we don't eventually find ourselves in a
situation where it's 0, though I suspect that's possible.
While doing that, I changed some variable names to make the code easier to read
and I added comments to summarize what's about to happen so it's easier to
verify the test is doing what it should be doing.
r?
=> Fixes bug 1331726 - fix assertion in test_public_api_navigation

config/package/usr/lib/systemd/system/socorro-webapp.service
@adngdb r?
This is a little bit of a funky way of doing this, but we aren't already using a config file for uwsgi, so there's nowhere else to add it without creating and using one.
=> Bug 1338565 - webapp: increase uwsgi buffer-size 4096 (default) => 16384

socorro/schemas/README.md
This README should be the place to start to make any changes to the schema. How to test it is part of it. 
CC @marco-c
=> (no bug) documentation about using validate_and_test.py

webapp-django/crashstats/manage/forms.py, webapp-django/crashstats/manage/jinja2/manage/symbols_uploads.html, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/views.py
=> fixes bug 1333169 - ability to search in uploaded content in admin

socorro/external/postgresql/raw_sql/procs/sunset_date.sql
It's just a comment. Anybody can merge.
=> bug 1312961 - correct comment about sunset date

webapp-django/crashstats/crashstats/jinja2/crashstats/crontabber_state.html, webapp-django/crashstats/crashstats/static/crashstats/css/crontabber_state.css, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/crontabber_state.js
I didn't want to spend too much time on this. But here's something that works.
=> fixes bug 1357833 - Reflect jobs that don't run in /crontabber-state

e2e-tests/tox.ini
Passes locally for me and our dev CI:
https://gist.github.com/stephendonner/0aca99afb14bffeb821e24f8be025d8b
@willkg I know it's only been four days since the last update, but if you want this, r?
If not, let me/us know the frequency for these; thanks!
=> Updating e2e test requirements/dependencies

e2e-tests/tox.ini
=> Update to pytest-selenium 1.10.0

.editorconfig
=> Fix Makefile and yml file editing

minidump-stackwalk/stackwalker.cc
This adds a string property "thread_name" to thread stacks output by
stackwalker. The thread names are parsed from the crash annotation
"ThreadIdNameMapping", which is the concatination of:
thread_id:"thread name",
Example: 6106:"Timer",6108:"Link Monitor",6109:"Socket Thread",
=> Fixes bug 1358457 - Added thread_name to thread stacks in stackwalker.

minidump-stackwalk/http_symbol_supplier.cc
This will allow the symbol server to store the info necessary for missing
symbols so we can fetch them from the Microsoft symbol server.
I tested this by generating a minidump from my local browser with the crashme extension, and then running the stackwalker binary with `--symbols-url http://s3-us-west-2.amazonaws.com/org.mozilla.crash-stats.symbols-public/v1/`, which is where we currently point the production stackwalker. The stackwalker log showed:
```
2017-05-12 12:11:44: simple_symbol_supplier.cc:196: INFO: No symbol file at /tmp/symbols/firefox/8EF4BE7ED885345C9942AA5C8DC0C6C90/firefox.sym
2017-05-12 12:11:44: http_symbol_supplier.cc:338: INFO: HTTPSymbolSupplier: fetching http://s3-us-west-2.amazonaws.com/org.mozilla.crash-stats.symbols-public/v1/firefox/8EF4BE7ED885345C9942AA5C8DC0C …
```
=> bug 1363177 - send code_id and code_file in query string when fetching symbols via HTTP

socorro/processor/general_transform_rules.py, socorro/processor/mozilla_transform_rules.py
This fixes some exceptions that were very frequently occurring in the processor, and that we now see since we have added error reporting. I am fixing those 3 errors at once because they are very similar.
=> Fixes bug 1364933 - Made some Rules more conservative.

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_views.py
@rhelmer Feel free to review if you want to.
=> fixes bug 1365368 - use RemoteType in displaying "Process Type"

docker/config/alembic.ini, docker/config/processor.env, docker/config/test.env, docker/run_test.sh
This fixes alembic issues in "make dockertest" which came about from a lack of
alembic.ini file.
=> Fixes bug 1366051 - fix alembic issues in "make dockertest"

.dockerignore
This will ignore .cache directory for COPY steps.
=> Add .cache to dockerignore

bin/ci/deploy-dockerhub.sh
=> deploy-dockerhub.sh: separate processor/webapp

.circleci/config.yml
=> circleci conf: re-enable push to dockerhub

bin/ci/deploy-dockerhub.sh, docker-compose.yml
=> circleci conf: use local prefix images

.dockerignore, docker/run_tests_in_docker.sh, setup.cfg
This fixes creation of the data container so that the files and directories have
the correct permissions so that the tests can run (and possibly fail) and
everything works right.
=> Fixes bug 1368726 - Fix perms for data container

.circleci/config.yml, bin/ci/deploy-dockerhub.sh
=> circleci conf: require DOCKER_DEPLOY=true to do any dockerhubby things

webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/middleware.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/supersearch/views.py
No middleware no `BadStatusCodeError` ever.
=> fixes bug 1217459 - SuperSearch can't raise a BadStatusCodeError

e2e-tests/tox.ini
@willkg / @chartjes ?
Test output here: https://gist.github.com/stephendonner/64bb0840003305a3d32c8f52f45fe641 (from https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/socorro.adhoc/57/console)
=> Update all test dependencies

config/package/usr/lib/systemd/system/socorro-middleware.service
=> Bug 1353371 - change middleware service to be a no-op

socorro/siglists/README.md
@willkg How is this? I feel like I am forgetting a lot of things, but it's difficult to figure out everything I need to say. Maybe it will work better if you ask questions about what you find unclear?
=> No bug - Added documentation about the siglist review process.

socorro/external/postgresql/setupdb_app.py
This rearranges some of the code in setupdb_app and changes some of the code so
that it only runs when --createdb is specified.
=> bug 1387096 - cleans up setupdb_app

socorro/unittest/processor/test_signature_utilities.py
This nixes ok_, eq_, and friends for pytest equivalents.
=> bug 1361764 - convert signature tests to pytest format

socorro/unittest/processor/test_signature_utilities.py
Reverts mozilla-services/socorro#3891
=> Revert "bug 1361764 - convert signature tests to pytest format"

socorro/cron/jobs/bugzilla.py
I appreciate this feels like a scary mess but the change is quite simple. 
Look at the two uploaded log files about ALL SQL that happens before and after this PR. 
Basically, when we remove this `NothingUsefulHappened` stuff, instead of ROLLBACK after each `SELECT signature FROM bug_associations WHERE bug_id = ...` now it does a  COMMIT instead. That's all. 
The good outcome of this is that we don't trigger [this logging](https://github.com/mozilla-services/socorro/blob/7681a91c1211e294c0d37de2011c4ba8a11a3e0c/socorro/database/transaction_executor.py#L52-L56) anymore.
=> fixes bug 1387597 - Fix transaction_executor to not log benign errors

scripts/add_crashid_to_queue.py, socorro/lib/ooid.py, socorro/scripts/add_crashid_to_queue.py, socorro/unittest/lib/test_ooid.py, socorro/unittest/scripts/test_add_crashid_to_queue.py, socorro/unittest/testbase.py
* adds a is_crash_id_valid lib function for verifying crash ids
* adds a scripts/add_crashid_to_queue.py script which is a stub that executes
functionality in socorro/scripts/add_crashid_to_queue.py
* adds unit tests for new module
=> bug 1388449 - add add_crashid_to_queue and scaffolding

docs/components/webapp.rst
=> docs: Update google auth directions

alembic/versions/f8b13d90e22a_remove_data_dictionary_table.py, socorro/external/postgresql/models.py
One less table never tastes bad.
=> fixes bug 1319956 - Remove `data_dictionary` table

docs/gettingstarted.rst
Meant to include this in pull #3926.
=> Clarify my.env doc

docker-compose.yml, docker/Dockerfile.processor, docker/config/docker_common.env, docker/config/processor.env, docker/create_weekly_tables.py, docker/fetch_normalization_data.py, docker/run_update_data.sh
* fix configuration so processor uses S3 container
* add two more things to run_update_data.sh that maintain the appropriate
weekly tables
* update localstack to 0.7.4
=> fixes bug 1391771 - fixes processor in local dev environment

docker/Dockerfile.processor, docker/config/docker_common.env, docker/config/processor.env, scripts/process_and_quit.sh
This fixes things so that stackwalker runs successfully
=> Fix stackwalker execution

socorro/unittest/external/es/test_index_cleaner.py
If indices existed already, then these tests will fail. That's problematic
because it also means that it's stomping on non-test data. This adds a test_
prefix so that it's only looking at test_ things and not stomping on things it
shouldn't be.
To test:
1. process a crash
2. run `curl localhost:9200/_aliases` from the host--that shows you the indices and aliases that exist in Elasticsearch
3. run `make dockertest` which will run all the tests -- the `test_index_cleaner` tests should pass
4. run `curl localhost:9200/_aliases` and it should be the same indices and aliases as in step 2
=> fixes bug 1393286 - fix IntegrationTestIndexCleaner tests

docs/architecture/signaturegeneration.rst, socorro/lib/treelib.py, socorro/processor/mozilla_processor_2015.py, socorro/processor/mozilla_transform_rules.py, socorro/processor/processor_app.py, socorro/processor/skunk_classifiers.py, socorro/siglists/README.md, socorro/signature/README.rst, socorro/signature/__init__.py, socorro/signature/__main__.py, socorro/signature/signature_utilities.py, socorro/unittest/lib/test_treelib.py, socorro/unittest/processor/__init__.py, socorro/unittest/processor/test_mozilla_transform_rules.py, socorro/unittest/processor/test_processor_app.py, socorro/unittest/signature/__init__.py, socorro/unittest/signature/test_signature_generator.py, socorro/unittest/signature/test_signature_utilities.py
This massive thing is an overhaul of how Socorro does signature generation. It also includes a command line interface and some documentation on how to use it.
=> fixes 1385970 signature cli

e2e-tests/Jenkinsfile
As in the title; full, passing build output here: https://gist.github.com/stephendonner/3653a22891695ed3fc91a5b4f9e8f97e
=> Update to Firefox 55

e2e-tests/tox.ini
Tested and passes; keeps this at parity with the rest of our web-automation suites w/same stack:
https://gist.github.com/stephendonner/ffed5b6f3793bf2fd4e897bbade090bd
r? @chartjes
=> Update e2e-tests dependencies

e2e-tests/README.md
@chartjes / @willkg r?
This host hasn't existed for a while, and we're in the middle of transition to a new Ops-provisioned host.  If desired, I can do another PR when that's up and running.
(But it'll still be behind VPN, so the badges won't reflect status, they'll just function as links to the builds.)
=> Remove broken badges

webapp-django/crashstats/settings/base.py
With the local dev environment, these comments aren't relevant anymore.
=> Remove comments

socorro/signature/__main__.py
This adds a --different-only flag to the signature generation cli that restricts
output to just signatures that changed.
This also removes caching of the "normalized" form of stack frames because that
prevents them from getting normalized which is annoying when you're changing how
normalization works.
=> fixes bug 1402190 - add --different-only flag to signature generation cli

docker/fetch_normalization_data.py, docker/run_update_data.sh
It's important that we test with FennecAndroid, too, so this adds that to the
list of things to pull down in a local development environment.
=> Add FennecAndroid to local development environment

Makefile, docker-compose.yml, docker/Dockerfile.docs, docker/as_me.sh, docker/run_build_docs.sh, docs/conf.py, docs/gettingstarted.rst
This redoes the architecture diagram using graphviz and dot notation. It's not
the bestest thing in the world, but it's editable without additional tools and
it seems good for now.
=> fixes bug 1389463 - create architecture diagram using dot

docs/components/processor.rst
I didn't actually test this, but pretty sure this is correct.
Can you test this out? Is it clear what's going on and how the pieces work with each other?
=> Add example of using shell scripts for processing crashes

docs/components/processor.rst, socorro/scripts/fetch_crash_data.py
=> fixes bug 1409475 - improve docs around API token requirement

socorro/scripts/__init__.py, socorro/scripts/fetch_crash_data.py, socorro/unittest/scripts/test_init.py
I was doing some analysis this morning and decided that implementing this would *radically* speed up analysis times. Plus it hits -prod a lot less.
=> fixes bug 1409038 - Add --dumps/--no-dumps flag to scripts/fetch_crash_data.py

CONTRIBUTING.rst, requirements.txt, setup.py, socorro/unittest/cron/crontabber_tests_base.py, socorro/unittest/cron/jobs/base.py, socorro/unittest/cron/jobs/test_ftpscraper.py
* remove nose from requirements and `setup.py`
* remove mentions of nose in documentation
* pull in crontabber's `TestCaseBase` and `IntegrationTestCaseBase` and de-nosify
them
=> fixes bug 1405675 - remove last vestiges of nose [no rush]

e2e-tests/Jenkinsfile
=> Switch to email-ext plugin for Jenkins build-email notifications

e2e-tests/tox.ini
@chartjes r?
Passing ad-hoc build here: https://gist.github.com/stephendonner/4fdaa5a9dc301b377753ae8fbf614c3f
=> Update all pytest requirements to latest

e2e-tests/tox.ini
@chartjes / r?
Wanted to keep this separate from the earlier pytest changes, just in case.
Passing build here: https://gist.github.com/stephendonner/357c87443d5bc494cda0204444b3e8ca
=> Upgrade Selenium version

.pyup.yml
=> Fix invalid YAML in PyUp config.

e2e-tests/tox.ini
@chartjes r?
Passing-suite output here: https://gist.github.com/stephendonner/06f3702fd58e3f9ceddcc96cbd70022a
=> Update pytest to 3.2.5

alembic/versions/f35c26426066_bug_1418488_drop_emailcampaign.py, socorro/external/postgresql/models.py
Socorro no longer uses these tables, so time to drop them.
=> fixes bug 1418488 - drop EmailCampaign, EmailContact, and EmailCampaignsContact

socorro/unittest/external/statsd/test_stastsd_rule_benchmark.py
This fixes bug 1419866 by removing the transform-rule-wrapping test from the statsd benchmark tests. It is testing unused behavior and adds a dependency on the Transform Rule System behavior that I'm overhauling in another branch (bug 1409648)
=> Fixes Bug 1419866 - removes statsd benchmark test of unused behavior

e2e-tests/tox.ini
@chartjes @willkg r?
Passing build here: https://pastebin.com/AGWw8PqX
=> Update pytest and pytest-metadata to latest

socorro/scripts/reprocess.py
* make "sleep" an argument you can pass on the command line
* improve the output so that it's easier to see where you are in the list
and let you more easily kill reprocessing and restart roughly where you
left off
I made these changes yesterday while trying to reprocess 131k crashes without triggering the "socorro.normal queue is too large!" alarms.
We talked about the sleep thing before. This lets us set the sleep between pushing a group which makes it easier to match adding items to the reprocess queue (queue production) with how fast the processor is taking them off (queue consumption). This also prints out the crash id at the end of the group, so if you have a big list of 131k crash ids, you can kill the script and know roughly where you need to start so as not to re-re-reprocess …
=> Improve sleep and output for reprocess script

webapp-django/crashstats/base/templatetags/jinja_helpers.py, webapp-django/crashstats/base/tests/test_jinja_helpers.py, webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/signature/jinja2/signature/signature_reports.html
This adds two new cases for is_dangerous_cpu to catch and also adds a
unit test.
=> fixes bug 1413925 - extend is_dangerous_cpu

e2e-tests/tox.ini
@chartjes r?
Passing ad-hoc build here: https://gist.github.com/stephendonner/75cd7d0a2185efebb1d881cc166d9970
=> Update pytest-selenium to latest

e2e-tests/tox.ini
@chartjes r?
Passing build here: https://pastebin.com/ri1KUEd8
=> Upgrade to latest pytest

scripts/deploy_bug.py
This script generates the text we can use to build a deploy bug.
=> Add scripts/deploy_bug.py script

scripts/deploy_bug.py
This is a minor tweak to the post-deploy steps. I was updating the docs and it occurred to me we were missing a few that we sometimes do.
=> Tweak post-deploy steps in deploy_bug script

e2e-tests/README.md
Updates and cleanup of the e2e tests README.
@chartjes r? /cc @stephendonner @m8ttyB
=> Update the e2e tests README

socorro/siglists/prefix_signature_re.txt
This adds pages_commit, chunk_recycle, and chunk_alloc.
=> fixes bug 1191055 - add pages_commit and friends to prefix list

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/crontabber_state.js
- Fix some inconsistent indenting that was failing eslint.
- The `d.x`, `d.y`, and `d.dy` attributes on sankey datums appears to have been
replaced with `d.x0`, `d.x1`, `d.y0`, and `d.y1`. So we replace all old
attributes with the new ones (dy is computed from y0 and y1).
- Pass nodes and links via the sankey constructor.
- Replace `sankey.nodeWidth` call with a property computed from the datum's `x0`
and `x1` values.
- Replace `sankey.update` with `sankey.relayout`.
- Replace `sankey.link` with `d3.sankeyLinkHorizontal`.
Most of these changes were found in the release notes on the sankey Github:
https://github.com/d3/d3-sankey/releases.
=> Fix bug 1431162: Fix errors in crontabber_status.js due to D3/sankey updates.

e2e-tests/Jenkinsfile
@chartjes @davehunt r?
Until we've got these running in Docker/using geckodriver.
Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/socorro.adhoc/106/console
=> Update to Firefox 58

e2e-tests/README.md
=> Fix path to renamed /requirements/requirements.txt file

alembic/versions/3c5d40ea7c5a_bug_1435068_remove_tcbs_table.py, socorro/external/postgresql/models.py
These tables have been sitting around unused since May 2017. Time for them to go.
=> fixes bug 1435068 - remove tcbs and tcbs_build tables

webapp-django/package-lock.json, webapp-django/package.json
I ain't playing games, Travis.
=> Update frontend dependencies

socorro/scripts/fetch_crash_data.py
If `fetch_crash_data` is using a bad api token (expired, non-existent, etc)
it should raise that as an error and not continue rather than save the
error it's getting back from Socorro as the raw crash. This makes that so.
=> fix bug 1431546 - raise errors on bad API token

docker/config/local_dev.env, socorro/processor/breakpad_transform_rules.py, socorro/processor/mozilla_transform_rules.py, socorro/processor/processor_2015.py, socorro/processor/processor_app.py, socorro/unittest/processor/test_mozilla_transform_rules.py
This fixes a bunch of issues related to PRs that landed recently and bad review on my part.
When this lands, we'll need to make some config changes in -stage and -prod as well as the new infrastructure. I'll detail those changes in a followup comment and in the bug.
=> bug 1439928 - fix processor

docker/config/local_dev.env, requirements/default.txt, webapp-django/wsgi/socorro-crashstats.py
We don't use new relic much anymore, so this nixes it.
=> fix bug 1442022 - nix new relic

webapp-django/crashstats/settings/bundles.py
From 1500 or so files being collected, copied, and post-processed, down to 248. I left some projects with wildcards since they had so few files as to not be an issue.
=> Reduce amount of staticfiles being collected.

alembic/versions/7d33170669e2_bug_1435074_remove_home_page_graph.py, socorro/external/postgresql/models.py
This removes two tables that are just sitting around and not used by anything anymore.
To test:
1. switch to master branch and do `make dockersetup`
2. switch to this branch and do
```
$ ./docker/as_me.sh bash
you@processor:/app$ alembic -c docker/config/alembic.ini upgrade heads
```
=> fixes bug 1435074 - remove home_page_graph and home_page_graph_build

docker/config/local_dev.env, webapp-django/crashstats/manage/jinja2/manage/base.html, webapp-django/crashstats/manage/jinja2/manage/home.html, webapp-django/crashstats/manage/jinja2/manage/site_overview.html, webapp-django/crashstats/manage/jinja2/manage/site_status.html, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/urls.py, webapp-django/crashstats/manage/views.py, webapp-django/crashstats/settings/base.py
This implements a basic status page that shows version, migration, and
crontabber state. It'll make it easier to surveil the status of the site.
=> fix bug 1455295 - implement basic status page

e2e-tests/Jenkinsfile
@Osmose @willkg r?  Also, should I file a bug for this?
=> Switch IRC channel for bot spam to...#breakpad-bots

e2e-tests/README.md
@Osmose r?  Sorry I missed this in the earlier PR :-(
=> [e2e-tests] Update doc to reference the Pipfile

alembic/versions/fd76c8bb0d78_bug_1459276_reports.py
This fixes the migration to account for `reports_clean` being a partitioned
table.
stage can't get past this migration, so I think the only way to move forward is to fix the migration in place.
=> bug 1459276: fix migration

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/correlation.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_correlations.js
1. This PR improves the message.
2. Added message.
3. Run webapp and access to http://localhost:8000/signature/?signature=test#correlations
=> bug 1403124: When correlations are missing for a channel, suggest looking at a different one

socorro/signature/siglists/README.rst
We created a Bugzilla component for signature generation changes. This
updates the documentation to recommend using that.
=> Update bug component for signature generation changes

docs/howto.rst
This updates the command line to use for those commands. This also removes
the note which isn't relevant anymore now that we have the new infra
which autoscales.
=> Update reprocessing docs

socorro/signature/siglists/irrelevant_signature_re.txt
Fix [bug 1477280](https://bugzilla.mozilla.org/show_bug.cgi?id=1477280)
=> Fix bug 1477280 - Skip exp2

webapp-django/crashstats/authentication/management/commands/auditgroups.py, webapp-django/crashstats/authentication/tests/test_auditgroups.py
This makes the output clearer in regards to inactivity amounts and also
adds a total at the end.
=> bug 1477782: adjust output of auditgroups

webapp-django/crashstats/tokens/admin.py, webapp-django/crashstats/tokens/models.py
* makes tokens searchable via email address and notes
* fixes how tokens are represented--no longer do they show up as "Token"
which is unhelpful
* makes them filterable by permissions (this could use work, but it's
better than before)
=> Fix Token admin

webapp-django/crashstats/documentation/jinja2/documentation/docs_base.html, webapp-django/crashstats/documentation/jinja2/documentation/products.html, webapp-django/crashstats/documentation/urls.py, webapp-django/crashstats/documentation/views.py
This is based on my research for Socorro.
It's possible parts of this are wrong. It's very likely we'll want to change some of this as we add new products. It's a living document that we can adjust as we go along.
=> fix bug 1478055: Add product documentation

socorro/signature/rules.py, socorro/signature/tests/test_rules.py
This adjusts signature generation such that it normalizes frames
from Rust sources differently than frames from other sources (usually
C/C++).
This adds a bunch of additional tests from real data to make sure
things don't regress including a few comments about things that should
get fixed in the future.
For the most part, this doesn't change anything--it's just a refactoring
to enable future changes.
=> fix bug 1481282: handle c/cpp and rust frames separately

webapp-django/crashstats/crashstats/tests/test_utils.py, webapp-django/crashstats/crashstats/utils.py
This fixes version sorting in the product home page so the right "featured" versions show up.
=> fix bug 1483097: fix version sorting in product home page

socorro/external/es/super_search_fields.py, socorro/unittest/external/es/test_super_search_fields.py
This fixes `doc_values` in Elasticsearch mappings for the `boolean` and nested
cases. `boolean` fields can't have `doc_values=True`. This isn't documented
anywhere, but appears to be the case as near as we can determine.
This also fixes nested cases where a field may have sub fields or be
of an `object` type with properties. The code now traverses the structures
adding `doc_values=True` where appropriate.
=> fix bug 1323033: fix doc_values for nested and boolean cases

socorro/external/es/super_search_fields.py
This adds some fields to super search that have been requested.
=> fix bug 1490662, 1420797, 1467856: add fields to super search

README.rst
I just need to trigger a stage deploy. Figured this was an easy way to do it.
=> Cosmetic README tweaks

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
ftpscraper would generate a product_versions record for X.0b99 which is a
"final beta". This fixes the `BetaVersionRule` to do a lookup for
`(product, build id, beta)` channel and if that returns nothing and the
version is possibly a final beta version, it will do a second lookup for
`(product, build id, release)` and if that returns something, it adds a b99
to the end of the version string.
Buildhub only stores build information for Firefox and Fennec, so we shouldn't
bother hitting it for other products. This fixes that.
This also splits up the monolithic "test_everything" into separate tests.
=> fix bug 1501780: fix b99 and reduce buildhub hits

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
Previously beta/aurora version lookups could get an rc version, but we
don't want that to ever happen, so this restricts those lookups to
non-rc versions.
=> fix bug 1503250: fix BetaVersionRule lookups for beta/aurora

webapp-django/crashstats/manage/admin.py, webapp-django/crashstats/manage/templates/admin/buildhub_check.html
This adds Fennec to the `buildhub_check` page so we can see what's going
on there, too.
=> bug 1504281: add fennec to buildhub_check page

docker/run_tests_python3.sh
This adds commented out lines for what remains to get working in Python 3.
This will make it easier to make sure we've got everything.
=> bug 1406703: add comments for what's remaining

socorro/lib/requestslib.py
This fixes `session_with_retries` so it's actually retrying now.
=> fix bug 1507016: fix session_with_retries

socorro/processor/breakpad_transform_rules.py, socorro/unittest/processor/test_breakpad_transform_rules.py
This adds metrics and logging for mdsw results because that's a good thing to have.
=> fix bug 1507190: mdsw metrics

socorro-cmd, socorro/cron/crontabber_app.py, socorro/external/boto/connection_context.py, socorro/external/es/crashstorage.py, socorro/external/es/supersearch.py, socorro/lib/converters.py, socorro/lib/datetimeutil.py, socorro/lib/external_common.py, socorro/lib/search_common.py, socorro/processor/mozilla_transform_rules.py, socorro/processor/symbol_cache_manager.py, socorro/unittest/external/es/test_crashstorage.py, webapp-django/crashstats/api/templatetags/jinja_helpers.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/base/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/form_fields.py, webapp-django/crashstats/crashstats/forms.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/utils.py, webapp-django/crashstats/manage/utils.py, webapp-django/crashstats/supersearch/models.py, webapp-django/crashstats/supersearch/tests/common.py
This fixes usage of basestring across the application and converts uses of
it to `six.text_type` or `six.string_type` depending on what's going on.
=> bug 1507186: fix usage of basestring

socorro/processor/processor_app.py, socorro/unittest/processor/test_processor_app.py
This is mostly cosmetic cleanup. The method was already doing most of
what we need it to do in regards to structure and exception handling.
=> fix bug 1426257: clean up _transform

minidump-stackwalk/README.rst
Minor update to breakpad docs that I meant to go in the previous PR.
=> Update breakpad docs

scripts/build-breakpad.sh
This should be the last change for this bug. I built it locally and it seemed to compile without an issue.
@willkg Any suggestions on what to land after the build to get this on stage?
=> Fix bug 1515805: Update Breakpad version.

requirements/default.txt, webapp-django/crashstats/base/jinja2/crashstats_base.html, webapp-django/crashstats/base/jinja2/footer_nav.html, webapp-django/crashstats/base/jinja2/header_title.html, webapp-django/crashstats/base/static/img/menu.svg, webapp-django/crashstats/base/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/static/crashstats/css/base/layout.less, webapp-django/crashstats/crashstats/static/crashstats/css/components/nav.less, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/nav.js, webapp-django/crashstats/settings/base.py
The header was starting to get a little crowded, so I decided to put the user menu options within a dropdown:
=> Fix bug 1511032: Move user info and documentation link to header.

webapp-django/crashstats/crashstats/utils.py
The versions in the nav bar are pulled from Super Search, so they're based
on the crash reports we've seen for that product in the last 60 days.
This fixes the query so that it's not cached in the `SuperSearchUnredacted` model
because it's cached in the `get_versions_for_product`. This also increases the
`_facets_size` so that it picks up versions which have recently been released
for which we don't have many crash reports, yet.
=> bug 1527728: fix versions in nav bar

socorro/cron/crontabber_app.py
This gets rid of some configuration options and reduces the complexity of
crontabber a bit to make it easier to convert to Everett later.
* removes commands I never used
* nixes more of the `depends_on` code because we don't have dependencies
anymore
* folds in arg defaults for `classes_in_namespaces_converter_with_compression`
=> bug 1529342: reduce crontabber some more

docker-compose.yml, docker/config/local_dev.env
This reworks the collector service so it pulls in the latest collector
and runs it with the appropriate bits so that you have a complete
fully functional crash reporting pipeline.
=> bug 1400076: rework collector service to work right

socorro/external/pubsub/crashqueue.py
The collector will sometimes toss a "test" crash id in the queue to make
sure that it can publish to the queue. The processor needs to consume
those by acking them and then throwing them away. This fixes that.
=> bug 1527345: fix handling of "test" crash ids

socorro/external/pubsub/crashqueue.py
Previously, the iterator would do one pass and then stop. The caller would toss
those crash ids in the work queue and then sleep for 7 seconds. That makes for
really lousy processed crashes throughput.
This fixes that by mimicking the `RabbitMQCrashQueue` and continuing to iterate
between queues until it hits a pass that yields no waiting crash ids. Then it
returns.
=> bug 1527345: fix PubSubCrashQueue iterator

webapp-django/crashstats/crashstats/admin.py
This was dumb. I thought I tested it, but I must have goofed the testing. Boo.
=> bug 1536903: fix queryset for processing in admin

webapp-django/crashstats/cron/tests/test_cronmarksuccess.py, webapp-django/crashstats/cron/tests/test_cronreset.py, webapp-django/crashstats/cron/tests/test_cronrun.py, webapp-django/crashstats/cron/tests/test_utils.py
=> bug 1493687: add the tests

webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
the change is depending on https://bugzilla.mozilla.org/show_bug.cgi?id=1543456 in order to have the full intended effect...
=> bug 1543465: add bug_type=defect parameter to report bug url

socorro/external/pubsub/crashqueue.py, socorro/processor/processor_app.py
This adds some handling for "504 Deadline Exceeded" in the pubsub queue code and also fixes the processor app to send unhandled exceptions from queue code to Sentry.
=> bug 1545784: deal with "504 Deadline Exceeded"

docker/run_update_data.sh, webapp-django/crashstats/crashstats/management/commands/archivescraper.py
This fixes a few issues with archivescraper. One is a bug and the others are to make it produce better logging so we can see what's going on later.
=> bug 1542388: archivescraper fixes

webapp-django/crashstats/cron/admin.py, webapp-django/crashstats/cron/management/commands/cronlist.py, webapp-django/crashstats/cron/management/commands/cronrun.py
Series of minor fixes to cronrun and friends to make them a little easier to debug going forward.
=> bug 1547807: cronrun fixes

webapp-django/crashstats/cron/models.py
This makes it easier to know what's what in contexts like the Django admin.
=> bug 1547807: add __str__ to Job and Log

docs/howto.rst
Tried to document PII access request processing and deploying in a way that isn't going to be wrong in a month, but has enough details that it's doable by someone from reading the docs.
=> Document deploys and PII request processing

README.rst
[BugSplat](https://www.bugsplat.com/) provides a hosted Breakpad/Crashpad solution with a [free plan](https://www.bugsplat.com/docs/payments/free-plan) for open source, individual and academic usage.
=> Add BugSplat to list of hosted solutions

socorro/scripts/fetch_crash_data.py
This makes `fetch_crash_data` more useful by allowing it to pull from any host and also adding support for pulling down processed crash data.
=> bug 1555744: support --host and --processed in fetch_crash_data

socorro/external/es/super_search_fields.py, webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_views.py
=> bug 1560998: make RemoteType private

product_details/FennecAndroid.json
Nightly and Beta are now tracking the 68.1 release
=> Update current Fennec Nightly & Beta version numbers

socorro/scripts/fetch_crash_data.py
This fixes `fecth_crash_data` to also have a `--raw`/`--no-raw` argument which
makes it easier to use it to *just* download processed crash data.
=> Fix fetch_crash_data to optionally not download raw crash data

docker/config/local_dev.env, docker/config/never_on_a_server.env, docker/config/test.env, requirements/default.txt, webapp-django/crashstats/crashstats/configman_utils.py, webapp-django/crashstats/monitoring/views.py, webapp-django/crashstats/settings/base.py
This cleans up a bunch of configuration issues. Figured I'd break this out into a separate PR rather than do it along with the boto -> boto3 changes.
None of these configuration changes require changes to the server configuration.
=> Clean up configuration

.circleci/config.yml, README.rst
This enables docker-layer-caching to reduce build times in Circle CI.
=> bug 1597334: enable docker-layer-caching

product_details/FennecAndroid.json
=> Update current Fennec versions

product_details/FennecAndroid.json
Should be 68.3.0 instead of 68.3.
=> Fix the Fennec release version

webapp-django/crashstats/crashstats/management/commands/verifyprocessed.py, webapp-django/crashstats/crashstats/tests/test_verifyprocessed.py
The verifyprocessed command failed because the `check_past_missing()` method hadn't been updated to boto3 things. There were no tests, so it wasn't caught.
This adds tests and fixes the code.
=> bug 1603231: fix verifyprocessed

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
Let's say we have two crash reports that have a field that isn't in super search fields. The first crash report has a field value that's a big string. The second one has a nested value. When the first is
indexed, Elasticsearch will infer that field to be a string. When the second gets indexed, it'll raise an "unknown property" error and not index the crash report.
This fixes that situation by adding code that recognizes what just happened, drops the field from the document, and retries indexing. This adds a test, too. This also adds metrics so we can see how often
these indexing errors happen.
=> bug 1603236: fix unknown property indexing failure

webapp-django/crashstats/cron/management/commands/cronrun.py
If cronrun is working on a backfill job that has a bunch of run_times to get through, then it'll go through all those run_times and if everything is successful, it'll update the "last_success" field for that job.
However, since the run_times for a backfilled job start with the "last_success" datetime, if a job fails half-way through, it'll start all over again at the beginning. Ugh.
This fixes it so that cronrun saves its place after every successful run_time. If it fails (ran out of time, some random problem, whatever), it'll start the run_times at the last successful run_time. This will
drastically improve the situation where a backfill job has to catch up from many failures.
=> bug 1603308: fix cronrun to save place after every run_time

webapp-django/crashstats/crashstats/management/commands/updatemissing.py, webapp-django/crashstats/crashstats/management/commands/verifyprocessed.py
We can search for a bunch of items in Elasticsearch at the same time rather than one at a time. This adjusts the code to batch Elasticsearch lookups.
=> bug 1603308: adjust Elasticsearch check to do it in batches

webapp-django/shell.py
The shell includes readline completion, all the models, and some other
things in the space. Makes some debugging easier.
=> Add a convenient shell for the webapp

webapp-django/crashstats/authentication/management/commands/auditgroups.py, webapp-django/crashstats/authentication/tests/test_auditgroups.py, webapp-django/crashstats/cron/__init__.py
This makes auditgroups consistent with other commands.
=> bug 1544427: change --persist to --dry-run in auditgroups

webapp-django/crashstats/topcrashers/views.py
The topcrashers summary line was confusing because the math was being done against a "total_number_of_crashes" that was not the total number of crashes but instead the user-provided number of signatures to look at. This fixes everything by pulling the total number from the search
results which is the total number of crash reports that match the given filters.
To test:
1. process like 1000 crashes--enough to get a Firefox version to look at that has more than 50 crash reports
2. look at the top crashers page and make sure it's something like this:
```
The report covers 259 (58.07%) of all 446 crashes during this period. 
```
and not something like this:
```
The report covers 4277 (8554.0%) of all 50 crashes during this period. 
```
=> bug 1543767: fix topcrashers summary line

product_details/FennecAndroid.json
Bump Nightly & Beta to 68.5 and Release to 68.4.
=> Update Fennec versions

product_details/FennecAndroid.json
Nightly is purposely not being modified due to Fenix migration
=> Update Fennec versions for new releases

socorro/processor/rules/mozilla.py, socorro/unittest/processor/rules/test_mozilla.py
For crash reports from Linux, the platform pretty version has been "Linux" which is pretty unhelpful.
This changes it so that it uses the value in `json_dump.lsb_release.description` which comes from `/etc/lsb_release` file in Linux. When this is available, it's a far more useful string like "Ubuntu 18.04 LTS".
To test:
1. process a Linux crash that has a `json_dump.lsb_release.description` value; for example bp-53090204-c74f-4041-9caf-84ee30200218
2. the platform pretty version (shows up as "OS" on the details tab of the crash report) will be "Ubuntu 18.04 LTS"
=> bug 1616194: use json_dump.lsb_release.description for platform pretty version

socorro/schemas/validate_and_test.py
This fixes the `validate_and_test` script so it runs. It's still erroring out on `SubmittedFromInfobar`, but that's a different problem.
To test:
```
$ make shell
app@socorro:/app$ python socorro/schemas/validate_and_test.py 
```
=> bug 1626032: fix validate_and_test script

webapp-django/package-lock.json
This updates minimist to a version that isn't known vulnerable.
=> Update minimist to 1.2.3 or later

requirements/default.txt, socorro/unittest/conftest.py, socorro/unittest/external/es/test_crashstorage.py, socorro/unittest/external/test_crashstorage_base.py, socorro/unittest/processor/rules/test_breakpad.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/tests/test_sentrylib.py
This updates markus and switches to using it's new assertion helpers.
=> Update markus to 2.2.0

socorro-cmd, socorro/scripts/db.py, socorro/scripts/es.py, socorro/unittest/scripts/test_db.py, socorro/unittest/scripts/test_es.py
This rewrites `db` and `es` to use click. It adds a basic "does this run" test, too.
I didn't do the other scripts in that directory because I think I'm going to remove them when I work on bug 1631108.
=> bug 1409547: add basic tests to scripts

socorro/unittest/processor/rules/test_general.py
I had switched most of the general rules code already. This updates the tests.
To test:
1. run tests
=> bug 1383113: switch to getitem notation for general rules

scripts/find_crashes_with_field.py, scripts/permadelete_crash_data.py, scripts/remove_field.py, socorro/unittest/test_find_crashes_with_field.py, socorro/unittest/test_permadelete_crash_data.py, socorro/unittest/test_remove_field.py
This reworks the deletion scripts to use click for argument parsing. It also adds basic tests.
=> bug 1619962: rework deletion scripts to use click and add basic test

socorro/external/crashstorage_base.py, socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py, socorro/unittest/external/test_crashstorage_base.py
Previously, we would put everything in the raw and processed crash in the document and index that in Elasticsearch--even things that were not specified in super_search_fields. This caused multiple problems with strings that were invalid keys. We worked through those. This also caused the problem where we have a bunch of unknown user-provided data in Elasticsearch.
The one thing where this helps is we can sometimes retroactively make a field searchable and have some data in Elasticsearch already. This doesn't happen often enough to be compelling.
This changes the Elasticsearch crash storage such that it removes anything in the raw and processed crash that isn't specified in super_search_fields. This moves us another step towards a world where we have a well defined schema of what we're …
=> bug 1624345: stop saving random data to elasticsearch crashstorage

requirements/default.txt, webapp-django/crashstats/crashstats/jinja2/crashstats_base.html, webapp-django/crashstats/crashstats/static/crashstats/css/base/layout.less, webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py, webapp-django/crashstats/settings/base.py
We don't need this--it's just fluff. Given that, best to remove it.
=> bug 1657705: remove gravatar

socorro/external/es/connection_context.py, socorro/external/es/supersearch.py, socorro/unittest/external/es/test_supersearch.py
This fixes supersearch so that regardless of the specified date range,
it'll drop the indices that are older than the retention policy.
These indices shouldn't exist, so supersearch would have searched them,
failed, then spent an inordinate amount of time trying to fix the query
by dropping bad indices one at a time.
=> bug 1643339: don't search indices older than retention policy

docker/config/gunicorn_config.py
This (should) fix gunicorn double-logging and reduce some of the non-mozlog fluff in the logs.
=> bug 1643344: fix gunicorn logging

docker-compose.yml, docker/config/local_dev.env, docker/run_tests.sh
Hopefully this fixes the flaky CI issues.
=> bug 1674778: update localstack to 0.12.2

webapp-django/crashstats/authentication/management/commands/hackeremails.py, webapp-django/crashstats/authentication/tests/test_hackeremails.py
This adds a django management command to list all the users with access to protected data. This is the "Hackers" group.
=> bug 1681390: add command for listing protected data users

webapp-django/crashstats/manage/admin.py
This fixes the protected data users admin page to show users in the
Hackers group and the Hackers Plus group.
=> bug 1681390: add Hackers Plus users

socorro/external/es/connection_context.py, socorro/external/es/crashstorage.py, socorro/scripts/es.py, socorro/unittest/external/es/test_crashstorage.py
A while back, I changed `save_processed_crash` to drop any keys that weren't in super_search_fields. That works fine if the index mapping matches super_search_fields. However, it fails whenever we add a new field and deploy--all the indexes will not have the new field. With the current code, the new field will get indexed, ES will guess at the storage_mapping, and make it a string. That breaks aggregations going forward if the storage_mapping for that field is different than what it is in super_search_fields.
This changes the `save_processed_crash` code to drop any keys that aren't in super_search_fields OR aren't in the mapping for the index the crash will be indexed in. This fixes the issues we're having.
One consequence of this is that when adding a new field, it will have no effect …
=> bug 1686103: don't index fields that aren't in the mapping

.gitignore, WHATSNEW.rst, docs/index.rst, docs/whatsnew.rst, webapp-django/crashstats/crashstats/static/crashstats/css/base/typography.less, webapp-django/crashstats/crashstats/static/crashstats/css/components/panel.less, webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py, webapp-django/crashstats/documentation/jinja2/documentation/docs_base.html, webapp-django/crashstats/documentation/jinja2/documentation/whatsnew.html, webapp-django/crashstats/documentation/static/documentation/css/documentation.less, webapp-django/crashstats/documentation/static/documentation/js/documentation.js, webapp-django/crashstats/documentation/tests/test_views.py, webapp-django/crashstats/documentation/urls.py, webapp-django/crashstats/documentation/views.py
This adds a What's New docs section that's built from a `WHATSNEW.rst`
file in the repo root.
=> bug 1692504: add What's New docs section

webapp-django/crashstats/api/views.py, webapp-django/crashstats/tokens/middleware.py
This fixes a bug where if you were using API endpoints from your browser
(like from the API docs), it would whack your loging.
This fixes another bug wehre it was still creating session cookies and
not properly removing them.
=> bug 1262424: fix another session issue and a bug

docker/Dockerfile, docker/Dockerfile.docs, requirements.in, requirements.txt
This updates Django to 2.2.19 and Python to 3.9.2.
=> Update Django and Python

webapp-django/crashstats/manage/templates/admin/graphics_devices.html, webapp-django/crashstats/supersearch/jinja2/supersearch/search_custom.html
`action=""` isn't a valid HTML5 thing. Pretty sure this is preventing me from uploading PCI data.
=> bug 1695576: fix form action values

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_views.py
This also removes some code that was labeled as good to remove in April
2019.
=> bug 1692312: add last error value to details tab in report index view

socorro/external/es/crashstorage.py, socorro/external/es/super_search_fields.py, socorro/unittest/external/es/test_crashstorage.py, socorro/unittest/external/es/test_super_search_fields.py
This fixes the case where `async_shutdown_timeout` values weren't getting truncated.
Before indexing data into Elasticsearch, the crashstorage code truncates the values for "string" and "keyword" fields. The way it figured out which fields were which was messy, missed a bunch of fields, and didn't cache intermediary work which would always produce the same results.
This refactors that code up so it's a little better and fixes the immediate issue in bug #1704529. The `get_fields_by_item()` function isn't great, but it's ok for now.
=> bug 1704529: clean up field value truncation code

socorro/processor/rules/general.py, socorro/unittest/processor/rules/test_general.py
Previously, the `cpu_arch` field in the processed crash was based solely on the output from minidump-stackwalk. Further, if there was no output, then `cpu_arch` was set to `""`. The empty string is a problematic value since it's difficult to search with.
This changes that code in two ways:
1. it changes the default value for `cpu_arch` and `cpu_info` to "unknown" which is an easier value to work with
2. if there's no minidump-stackwalk output (no minidumps or a minidump that can't be parsed), then it looks at `Android_CPU_ABI` which is an annotation that exists for Android crash reports and covers the case where it's a Java crash
We can add additional ways to determine the `cpu_arch` going forward.
This also rewrites the relevant tests.
=> bug 1710854: rework cpu_arch calculation

.log4brains.yml, docs/adr/20210819-run-stackwalk-as-subprocess.md
* change timezone to Etc/UTC
* capitalize a title
=> bug 1726032: fix nits in ADRs

socorro/processor/processor_pipeline.py, socorro/unittest/processor/test_processor_pipeline.py
This improves processor notes in a few ways:
1. it's easier to distinguish between lines--they don't all glom
together
2. you can use ; in a line now since it's not used as a line ending
indicator
3. it adds an explicit "start processing" with a timestamp so you can
more easily distinguish runs
4. it's shown as individual lines rather than a big blob in the report
view
This has one minor problem where if there are lots of notes, it can take
up a lot of space. I'll think about that at some other point. We might
want a tab for "how did this crash report fare in ingestion" and move
collector notes, processor notes, minidump-stackwalk status, and
whatever else there.
=> bug 1626811: improve processor notes

docs/stackwalk.rst
We should probably flesh out that section more, but this is good enough
for now.
=> Update stackwalk docs

product_details/FirefoxReality.json, product_details/MozillaVPN.json
This doesn't include any bug links. I figure we can add those later.
=> bug 1743436: add MozillaVPN to products

docker/Dockerfile
```
cf2031c Use reqwest's Bytes type instead of copying into a Vec
```
=> Update rust-minidump to cf2031c8

docs/spec_crashreport.rst
This cleans up the crash reporting spec and reorganizes it so
(theoretically) it's easier to follow for someone who's writing a crash
reporting client.
This adds some additional HTTP response codes and what the client should
do.
This moves the notes about differences with the Breakpad upload tool to
a section at the end.
=> bug 1746872: overhaul crash reporting spec

webapp-django/crashstats/sentrylib.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/tests/test_sentrylib.py
This fixes the sanitizer bug in the sentrylib code that was preventing
errors from being posted to Sentry.
=> bug 1748268: fix sanitizer bug

Makefile, docker-compose.yml, docker/Dockerfile.fakesentry, docker/config/local_dev.env, docker/config/test.env, webapp-django/crashstats/tests/test_sentrylib.py
This adds a fake sentry service (kent) and configures the local dev
environment to use it.
=> bug 1748484: add fake sentry service

socorro/scripts/reprocess.py
I keep hitting ReadTimeout and ConnectionError errors during the .send()
phase. This captures those and retries the whole request rather than
dying.
=> Fix reprocess to be more resilient

webapp-django/crashstats/crashstats/models.py
Apparently we have some data we want to cache that's larger than the
memcached max size and that's causing cache.set() to error out.
This wraps that in a try/except block and emits a cache_set_error metric
so the code "recovers", but also lets us monitor the situation in case
we want to do something different when we learn more.
=> bug 1753550: recover after cache.set error

webapp-django/crashstats/supersearch/models.py
Socorro only supports specific products so it makes sense to return an HTTP 400 for SuperSearch queries for unsupported products.
To test:
1. Search for crash reports with product `FennecAndroid` with the SuperSearch web interface. It should raise an error in the interface.
2. Search for crash reports with product `FennecAndroid` using the SuperSearch API:
```
curl "http://localhost:8000/api/SuperSearch/?product=FennecAndroid"
```
It should return an HTTP 400 Bad Request.
=> bug 1755322: validate product values for supersearch

docs/spec_crashreport.rst
I added support for multipart/mixed to the specification. Further, I
fixed some typos and clarified some text.
=> bug 1747398: add support for multipart/mixed

socorro/external/es/super_search_fields.py
The TestIntegrationSuperSearchFields.test_test_mapping test fails
intermittently in CI. It feels like a race condition between creating
the new index, ES figuring its stuff out, and then running a search on
the cluster.
This adds some code to make sure the cluster is happy before moving on
to the search. It also wraps the search code in a loop to re-attempt a
few times before ultimately failing.
Maybe that'll help.
=> bug 1759080: attempt to reduce intermittent ci fail

socorro/external/boto/crashstorage.py
This redoes TelemetryBotoS3CrashStorage to build the crash document it
sends to telemetry ingestion solely from the processed crash.
This no longer uses super search fields and reduces some of the tangling
between crash storage systems which is creating a lot of problems.
The processed crash contains data that has been normalized and
validated, so it's a better source to use than the raw crash. This
handles a few historical naming issues, but otherwise it's pretty
straight-forward and driven entirely by the telemetry_socorro_crash.json
schema.
=> bug 1755095: fix TelemetryBotoS3CrashStorage to not use super search fields

socorro/schemas/telemetry_socorro_crash.json
This fixes ipc_system_error by converting the value to a string.
=> bug 1755095: fix ipc_system_error

socorro/lib/libjson.py, socorro/unittest/lib/test_libjson.py
This adds support for "patternProperties" in json schemas.
This also adds tests for the "required" property validator which I
had implemented but didn't write tests for.
=> bug 1783027: support patternProperties in json schema reducer

socorro/external/es/crashstorage.py, socorro/processor/processor_app.py, socorro/unittest/external/es/test_crashstorage.py
We no longer need the elasticsearch redactor code, so it's time to
remove it and simplify things.
=> bug 1784927: remove elasticsearch redactor code

socorro-cmd, socorro/scripts/fetch_missing.py
The fetch_missing script fetches information from the MissingProcessedCrash API. This makes it much easier to reprocess missing crashes after a bug fix.
=> bug 1790049: add fetch_missing script

socorro/signature/rules.py, socorro/signature/tests/test_rules.py
This iterates through the inlines if there are any when looking at frames to build the signature.
```
$ socorro-cmd signature 829c31ce-e2d8-4102-9188-d35fa0220908
Crash id: 829c31ce-e2d8-4102-9188-d35fa0220908
Original: js::TenuringTracer::collectToObjectFixedPoint
New:      js::NativeObject::getDenseInitializedLength
```
=> bug 1788269: add inline functions to signature

socorro/signature/siglists/signature_sentinels.txt
Should help https://crash-stats.mozilla.org/report/index/484959f0-3d09-41da-943f-78ced0220915
=> Add alloc::alloc::handle_alloc_error to sentinals

socorro/signature/siglists/prefix_signature_re.txt
This should make https://crash-stats.mozilla.org/report/index/4635bba7-7e13-4d2f-a28c-0a1550220914 better
=> Add mozilla::OffTheBooksMutex::Lock to prefix list

webapp-django/crashstats/sources/views.py
This changes the source highlight to use the TextLexer which doesn't do any lexing for large files. This significantly speeds up its ability to return the source file.
=> bug 1786827: use null lexer for large files

socorro/processor/rules/mozilla.py, socorro/unittest/processor/rules/test_mozilla.py
This fixes topmost_filenames to account for inline function data. It also redoes the docstring and slightly adjusts the behavior to omit the field altogether if the data isn't there to determine the top-most filename.
=> bug 1800141: fix topmost_filenames

socorro/signature/siglists/prefix_signature_re.txt
See bug 1801884 for the request.
=> Bug 1802315 - add mozilla::dom::Promise::* as signature prefix

socorro/signature/rules.py, socorro/signature/tests/test_rules.py
The OOM is when the value is Reporting and not Reported. This fixes that.
=> bug 1796094: fix JSLargeAllocationFailure OOM detection

socorro/external/es/super_search_fields.py, socorro/external/es/supersearch.py, socorro/external/fs/crashstorage.py, socorro/lib/__init__.py, socorro/lib/libversion.py, socorro/lib/search_common.py, socorro/processor/processor_app.py, socorro/processor/rules/mozilla.py, socorro/signature/rules.py
This is mostly cosmetic, but it reads better.
=> Switch to using contextlib.suppress

socorro/scripts/fetch_crashids.py
While doing this, I converted the script to use f-strings.
=> Add --date=thisweek to fetch_crashids script

socorro/processor/cache_manager.py
This switches event checking to use & (it's a bitmask) instead of "in" which iterates over the list. & should be a little faster even if the lists are short.
This improves other cases where the file might not exist when we check the size and handles those cases appropriately.
=> bug 1822648: improve filenotfound resiliency and switch to &

webapp/crashstats/documentation/views.py
This caches the computed data for the data dictionary thus reducing the work involved in handling data dictionary requests.
The way I did this, the cache is shared across all the gunicorn workers. It only caches real fields--so the cache is bounded by the number of fields we have (it's like 100 or something). It doesn't cache 404 responses because those are quick to compute and if we cached those, then the cache would be unbounded.
I figured I'd cache for an hour. The search results used for examples will change over time, but an hour is probably fine.
=> bug 1838302: cache computed data for datadictionary

webapp/crashstats/documentation/views.py
The protected crash contains several nested structures and the path through those structures is reflected in the "field" value. Because of that, the cache_key could be arbitrarily long which memcached doesn't like.
This adjusts the code to validate the dataset is one of two values and also hashes the field so it meets memcache key constraints.
=> bug 1838302: fix cache keys for nested protected data

webapp/crashstats/documentation/views.py
This re-adds all the _histogram.* and _histogram_interval.* fields.
=> bug 1845341: fix supersearch api docs

Makefile, docker-compose.yml, docker/config/local_dev.env, docker/config/test.env, docs/dev.rst, webapp/crashstats/cron/__init__.py, webapp/crashstats/manage/admin.py, webapp/crashstats/manage/templates/admin/site_status.html
- bug 1855494: add psql make target and site status admin page
- bug 1855494: run clearsessions weekly
=> bug 1855494: add clearsessions to cron

bin/circleci_push.sh
This is the same change as https://github.com/mozilla-services/antenna/pull/947
=> bug 1860580: Make Docker Hub upload script more robust.

webapp/.gitignore, webapp/package-lock.json, webapp/package.json
This package is several major versions out of date, and after reviewing the code, it does not appear to be used anywhere. Removing it will prevent us from receiving N/A warnings from GitHub/npm.
=> webapp: remove unused pkg.json package

docs/crashpings.rst, docs/overview.rst
Turns out I've had the "opt-out by default" language wrong all these years. This fixes cases of that to clearer "default on/off" language.
=> Fix opt-out language

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .gitignore, Makefile, docker-compose.yml, docs/dev.rst
mostly copied from https://github.com/mozilla-services/antenna/pull/964/files
=> bug-1884002: Add devcontainer configuration

docker/Dockerfile
See #mozilla-services/socorro-stackwalk/pull/15
=> specify platform in base image

.circleci/config.yml, pyproject.toml
Note: This also requires a change in Jenkins which I'll do after this lands.
=> bug-1857938: change tag pattern to vYYYY.MM.DD[-N]

.github/workflows/build-and-push.yml
copied from antenna with `Build Docker images` through `Run tests` commands changed to match circleci and `local_image` in the last step set to `local/socorro_app:latest`.
This will push socorro images to GAR for deployment in GCP.
=> OBS-158: Add github actions CI

docs/signaturegeneration.rst, socorro/signature/README.rst
This PR includes up some of the suggested changes in bug-1898268 as well as some comments @willkg made on Slack.
=> bug-1898268: Some updates to the docs for signature generation changes.

bin/remove_field.py
by modifying it to only use the existing crash storage api
blocks #6669
=> bug-1908543: fix remove_field.py for gcs

bin/permadelete_crash_data.py, socorro/external/crashstorage_base.py, socorro/external/es/crashstorage.py, socorro/external/fs/crashstorage.py, socorro/external/gcs/crashstorage.py, socorro/tests/external/es/test_crashstorage.py, socorro/tests/external/fs/test_fspermanentstorage.py, socorro/tests/external/gcs/test_crashstorage.py, socorro/tests/external/test_crashstorage_base.py
This makes it a little clearer that it did something and how long it took from the output.
=> Add additional output to permadelete

.devcontainer/Dockerfile, docker-compose.yml, docker/Dockerfile
because I noticed some deprecations while working on es8 support
=> Fix deprecations during docker compose build

.github/workflows/manual-deployment.yml
The workflow was copied without any changes from Tecken and Eliot.
https://mozilla-hub.atlassian.net/browse/OBS-467
=> OBS-467: Add workflow to manually trigger a deployment.

socorro/external/pubsub/crashqueue.py, socorro/tests/external/pubsub/test_crashqueue.py
This changes the way the processor pulls from queues. Previously, it pulled pull_max_messages from each queue in order and then processed that. If we had a backlog of standard and reprocessing queue work, then they'd be handled equally. That's bad for standard queue processing and caused alerts and stuff.
This changes it to prefer processing the standard queue 5 over the reprocessing queue 5 to 1 and makes it much less likely the standard queue backs up when someone reprocesses a bunch of crash reports.
When this hits stage, I can test it more thoroughly by reprocessing a bunch of crash reports. It may be we want something bigger than 5 to 1. We can tune that going forward.
=> bug-1945653: adjust processing queue balance

.github/dependabot.yml, .gitignore
Grouping dependabot pull requests to make it a little less noisy.
=> Group dependabot pull requests

.github/workflows/build-and-push.yml
This is the same change as in https://github.com/mozilla-services/antenna/pull/1273.
https://mozilla-hub.atlassian.net/browse/CRINGE-65
=> CRINGE-65: Upgrade to version 4 of the docker-push action.
