socorro/processor/processor_app.py
the code that moved the delete of the temporary dump files somehow acquired a module qualifier.  and that prevents the processor from logging file deletion problems.
this is the fix.
=> fixes Bug 1117590 - removed bogus module on exception

socorro/app/fetch_transform_save_app.py, socorro/processor/processor_app.py
the old HBase modules logged the "saved" message.  I've instead moved that to the transform functions rather than than crashstorage classes.
=> added logging of saved to transform functions

socorro/cron/jobs/automatic_emails.py, socorro/cron/jobs/fetch_adi_from_hive.py, socorro/external/postgresql/connection_context.py, socorro/external/postgresql/setupdb_app.py, socorro/external/rabbitmq/connection_context.py
configman can offer sensitive status to options that should not be echoed to stdout, stderr or logs.  Make sure that all Socorro apps use that tagging for sensitive options
=> fixes Bug 1117961 - ensure that all passwords are tagged as secret

socorro/database/transaction_executor.py, socorro/external/boto/crashstorage.py, socorro/unittest/external/boto/test_crashstorage.py
this PR add dual transaction executors to the BotoS3 class.  This allows ```gets``` and ```saves``` to have different transactional behaviors.  On re-tryable Exceptions, ```saves``` should retry forever until they succeed.  However, on reads, the  retry behavior should be less forgiving and give up after a while.  
In the processors, the default ```transaction_executor_class``` should be ```TransactionExecutorWithInfiniteBackoff``` while ```transaction_executor_class_for_get``` should be ```TransactionExecutorWithLimitedBackoff```.    In other places, like the middleware, ```transaction_executor_class_for_get``` likely should be ```TransactionExecutor``` so that it only tries once.
=> fixes Bug 1118269 - added separate transaction executor for gets to BotoS3CrashStore

socorro/cron/jobs/ftpscraper.py
=> fix bug 1118224 - check for existing buildID before trying to insert

socorro/lib/transform_rules.py, socorro/processor/processor_2015.py, socorro/unittest/lib/test_transform_rules.py, socorro/unittest/processor/test_processor_2015.py
Processor2015 is not as responsive to SIGTERM as the HybridProcessor was.  That's because the TransformRule system doesn't honor the quit_check callback function.  
This PR extends the quit_check call back function to the TransformRule system
=> fixes Bug 1117168 extended quit check to transform rules

alembic/versions/5387d590bc45_fixes_bug_1117907_remove_sigsum_fks_.py
This removes a bunch of things we tried out in prod but aren't being used. A search of index scans and index tuple fetches reveals that at most, one of the following indexes was used at most 4 times over its life going back to early 2014.
RIP unused indexes!
The foreign keys are also unused and unnecessary and cluttering up the database.
=> Fixes bug 1117907 remove unneeded indexes and fks

docs/requirements.txt, requirements.txt
r? @phrawzty or @rhelmer or @AdrianGaudebert 
So, by default readthedocs will automatically find our `./requirements.txt` and run it. This is problematic in two ways:
1) We don't have `sphinx` in there. We could add it but then we would also have to "peep-add" all of it's 5 other dependencies (there is some overlap with things we already have like `six` and `jinja2`). We could just add it and since readthedocs runs `pip install -r requirements.txt` they would automatically fetch the dependencies. However, it would make our requirements.txt file useless for developers who we encourage to use `peep install -r requirements.txt`. 
2) We have A LOT of stuff in our `requirements.txt` and poor readthedocs will have to install all of them. Some builds simply fail because of problems with `sasl.c` …
=> bug 1119223 - custom requirements for readthedocs

socorro/external/postgresql/models.py
No migration included as we never created a primary key in production.
=> Fixes bug 1119840 - remove PK from missing_symbols

scripts/crons/cron_libraries.sh
should go out today or tomorrow. @KaiRo-at can you double check the versions override when you get a chance?
=> bug 1120551 - bump forced versions correlation thingy for ff 36

minidump-stackwalk/Makefile, minidump-stackwalk/http_symbol_supplier.cc, minidump-stackwalk/http_symbol_supplier.h, minidump-stackwalk/stackwalker.cc
There's better documentation in https://github.com/luser/socorro/commit/cc2849ed2eb35c56df567748c6f9f095958eca69 for what I actually implemented here.
This allows using the stackwalker in the current mode unless we specify the new options, and we should be able to transition to the S3 storage incrementally.
=> bug 1118446 -  Implement HTTP symbol fetching in stackwalker

minidump-stackwalk/get-minidump-instructions.cc, puppet/modules/socorro/manifests/init.pp
Some simple workarounds to support GCC 4.4.
=> bug 1119525 - fix get-minidump-instructions build in vagrant

alembic/versions/1023855cf1ad_fixes_bug_1117911_load_truncate_.py, docs/configuring-socorro.rst, docs/development/databaseadminfunctions.rst, socorro/cron/crontabber_app.py, socorro/cron/jobs/drop_old_partitions.py, socorro/cron/jobs/truncate_partitions.py, socorro/cron/jobs/weekly_reports_partitions.py, socorro/external/postgresql/raw_sql/procs/truncate_partitions.sql, socorro/unittest/cron/jobs/test_truncate_partitions.py
We may not want to make this a default for our open source users.
Maybe what I should do is add configuration that sets the default number of weeks to something much larger, and then our local config is 2 weeks.  Thoughts?
=> Fixes bug 1117911 crontabber to truncate raw/processed crash partitions >2 weeks

requirements.txt
We use requests for the fetching of the middleware and for django-browserid. 
We use lxml for pyquery which I think we only use for testing the django views.
=> fixes bug 1122301 - upgrade requests and lxml

socorro/processor/mozilla_processor_2015.py, socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
as outlined in Bug 1104317, a signature that includes "::RunWatchdog" is not useful.  Check for that signature and, if found, reprocess the signtaure for Thread-0 instead of the crashing thread, and prepend the string "shutdownhang" to the signature.  Make sure that the new signature doesn't ignore the "ProcessNextEvent" but adds it to the prefix regular expression.
=> Fixes Bug 1104317 - adds SignatureRunWatchDog rule to processor

socorro/lib/converters.py, socorro/processor/breakpad_transform_rules.py, socorro/unittest/lib/test_converters.py, socorro/unittest/processor/test_breakpad_transform_rules.py
this PR provides two processor rules (though does not actually set them up for use - separate bug for that).  The first rule is a generic base class for rules that need to invoke an external process.  The second rule is an implementation that uses the base class to invoke ted's dump-lookup tool.
=> fixes Bug 1121462 - add generic external process rule

docs/development/build-from-source.rst, docs/development/webapp.rst, requirements.txt, scripts/deploy.sh, scripts/package/after-install.sh, webapp-django/bin/ci.sh, webapp-django/bin/linting.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/symbols/migrations/0001_initial.py, webapp-django/crashstats/tokens/migrations/0001_initial.py
@rhelmer r?
So, one caveat is that when you go from not-using-south to start using it you basically need to run a one-off command for an installed app (namely waffle). See https://bugzilla.mozilla.org/show_bug.cgi?id=1122319#c1
Another caveat is that once this is deployed and in master, every developer will need to run: `./manage.py migrate tokens 0001 --fake` and `./manage.py migrate symbols 0001 --fake` on his/her computer. That's less scary compared to having to run the `./manage.py migrate waffle --fake` command once on the webheads.
=> bug 1122319 - Start using south migrations

webapp-django/bin/ci.sh
@rhelmer or @AdrianGaudebert r?
I tested this locally. I created a brand new database (e.g `socorro_webapp_new` with `createdb`) and put this in my `settings/local.py`. Then without running either `syncdb` or `migrate` I just went straight to `FORCE_DB=true ./manage.py test` and it works. 
Let's just check this is how it's expected to work in travis.
=> fixes bug 1122319 - south migration problem in jenkins

setup.py, socorro/external/postgresql/postgresqlalchemymanager.py, socorro/external/postgresql/setupdb_app.py
Adds `data_file` paths for our SQL files so that when the package is installed, `alembic` is able to find the raw SQL files in the `virtualenv`.
=> Fixes bug 1129476 add SQL files to setup.py install for alembic

socorro/unittest/external/postgresql/test_signature_urls.py, socorro/unittest/processor/test_mozilla_transform_rules.py
=> fixes bug 1130048 - Tests should pass in python 2.6 and 2.7

requirements.txt
@rhelmer r?
So, the strange thing is that we used to depend on version [0.6](https://pypi.python.org/pypi/django-appconf/0.6) and that only had 1 file to download. So I don't see why we had two shas for that when there was only the tarball available. 
We could investigate this deeper and try to understand why it used to have multiple files on pypi but doesn't any more. 
Instead, I thought I'd just put the latest version in and it works. The [latest version](https://pypi.python.org/pypi/django-appconf/1.0.1) does have a tarball and a wheel.
=> fixes bug 1133814 - django-appconf sometimes fails to install with peep

docs/configuring-socorro.rst, webapp-django/crashstats/manage/templates/manage/symbols_uploads.html, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/symbols/forms.py, webapp-django/crashstats/symbols/migrations/0002_auto__del_field_symbolsupload_file.py, webapp-django/crashstats/symbols/models.py, webapp-django/crashstats/symbols/templates/symbols/api_upload.html, webapp-django/crashstats/symbols/templates/symbols/home.html, webapp-django/crashstats/symbols/tests/test_models.py, webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/urls.py, webapp-django/crashstats/symbols/utils.py, webapp-django/crashstats/symbols/views.py, webapp-django/settings_test.py
@rhelmer r? cc @twobraids 
So basically, we stop storing the uploaded file. Instead, we immediately unpack it and send it straight into S3. All within one big request.
=> fixes bug 1085530 - store uploaded symbols to S3

socorro/unittest/external/postgresql/test_backfill.py, socorro/unittest/external/postgresql/test_base.py, socorro/unittest/external/postgresql/test_crashes.py, socorro/unittest/external/postgresql/test_crontabber_state.py, socorro/unittest/external/postgresql/test_products.py, socorro/unittest/external/postgresql/test_report.py, socorro/unittest/external/postgresql/test_signature_summary.py, socorro/unittest/external/postgresql/unittestbase.py
cc @rhelmer @AdrianGaudebert @selenamarie @twobraids 
These changes works locally for me. Instead of creating 93 connections it only creates 23 connections for running the tests in `socorro/unittest/external/postgresql/`.
There are probably many more places where we can reuse fixtures across a whole test case. If you can find more things to tune, please feel free to open a PR against this PR.
=> bug 1134686 - Use setUpClass for more efficient test cases

scripts/crons/cron_libraries.sh
The next version of our usual correlation version bump. Should go into production in the week of 2014-02-23.
=> Bug 1133765 - Update forced versions for correlations for Firefox cycle starting 2015-02-24

config/crontabber.ini-dist, socorro/unittest/config/commonconfig.py.dist, socorro/unittest/config/jenkins.py.dist, socorro/unittest/cron/setup_configman.py, socorro/unittest/external/postgresql/test_crash_data.py, socorro/unittest/external/postgresql/unittestbase.py
We're using breakpad_rw sometimes and that messes things up once we no longer assume that our core users have superuser privileges.
=> Fixes bug 1136917 - update default user to be 'test' for use in tests

docs/production-install.rst
ES is now a requirement so... maybe we should have this in our production install docs.
=> Nobug add starting elasticsearch to production install docs

socorro/processor/hybrid_processor.py, socorro/processor/legacy_processor.py, socorro/processor/processor_2015.py, socorro/processor/processor_app.py, socorro/unittest/processor/test_hybrid_processor.py, socorro/unittest/processor/test_legacy_processor.py, socorro/unittest/processor/test_processor_2015.py, socorro/unittest/processor/test_processor_app.py
originally slated to create a new processor type, instead this PR modifies the existing processor_app.  It adds the ability for the processor to fetch an existing processed crash along with the raw crash and dumps.  The existing processed crash is then passed on to the configured processor algorithm.  For processor2015, the rules may work with the processed crash at will or ignore it entirely.  
This method of expanding the abilities of the existing processor_app class cuts down significantly on the amount of redundant code in comparison with my original solution.
=> fixes Bug 1138488 - added supplemental processing to ProcessorApp

minidump-stackwalk/dumplookup.cc
Same thing we're doing in other sources.
=> Fix dumplookup build on old GCC

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/manage/views.py
=> fixes bug 1143126 - avoid MemcachedKeyLengthError on analyze_model_fetches

minidump-stackwalk/stackwalker.cc
We'll need this to fix bug 1140358. r? @twobraids
=> Output code_id in stackwalker's module list

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
this fixes the bug where the logger doesn't work properly when the PG password is incorrect: "Nonetype doesn't have..."
the ProductIdMap is set up by a configman aggregation just like logging is setup by an aggregation.  they are order dependent, but configman does not guarantee order.  the solution is to move the ProductIdMap to the constructor of the rule rather than as an aggregation.
=> fixes bug 1131398 - move setup of product id map to constructor

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/analytics.js, webapp-django/crashstats/signature/static/signature/js/signature_report.js
@peterbe While I was at it, I also fixed the Analytics class, which had an incorrect method name. :-) (I guess testing a patch should never be an option... Silly reviewer, no cookies for me! )
=> Fixes bug 1145173 - Added tabs analytics to the signature report page.

socorro/external/crashstorage_base.py, socorro/unittest/external/test_crashstorage_base.py
create a crashstore that wraps two crashstores and decides between them by comparing the date embedded in the crash_id with a threshold date given to the crash store.  If the embedded date is before the threshold, save/get from the fallback storage system.  Otherwise save/fetch from the primary crashstore
=> fixes bug 1144293 - added MigrationCrashStore

socorro/collector/collector_app.py, socorro/dataservice/dataservice_app.py, socorro/middleware/middleware_app.py, socorro/webapi/servers.py, wsgi/collector.py, wsgi/middleware.py
the Socorro code often links the words Apache and ModWSGI. Since modwsgi works under more than just Apache, the names that label modwsgi things ought not be saddled with the name Apache, too.
=> fixes Bug 1147519 - remove "Apache" from names

requirements.txt
upgrade to the latest configman enabling several features useful to Socorro:
1) support for "--admin.print_conf=env"  will output a series of shell compatible environment variables for all the configman options
2) support round tripping without editing when creating "ini" files.  The output "ini" file will have things left as defaults commented out, thing that changed will not be commented out.
3) several bug fixes
=> No Bug - upgrade to latest configman

webapp-django/crashstats/manage/tests/sample-graphics.csv, webapp-django/crashstats/manage/tests/test_utils.py, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/utils.py
@selenamarie r? or if you're too busy getting started in your new team, @rhelmer r?
So, if you look at [Adapter Graphics Report](https://crash-stats.mozilla.com/report/list?signature=mozilla%3A%3Alayers%3A%3ADataTextureSourceD3D9%3A%3AUpdateFromTexture%28IDirect3DTexture9*%2C+nsIntRegion+const*%29&range_value=28&range_unit=days) in the Signature Summary you'll see that all the hexes for the adapters we don't recognized are padded as 4 characters. E.g. `0x0221`. And `'0x0221' != '0x221'` even though `hex(int('0x0221', 16)) == hex(int('0x221', 16))` is true. 
So that's why we miss so many adapters in the signature summary that starts with a leading 0. This PR fixes that.
=> fixes bug 1148587 - 0x221 is the wrong adapter hex

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py
@rhelmer or @AdrianGaudebert r?
I've seen cases where the stored JSON file is corrupt. If it is we shouldn't block but just remove the file and not rely on that as a cache.
Also, I found that there was no test coverage for retrieving from the middleware file cache.
=> fixes bug 1149239 - Unreliable JSON disk IO for models fetch cache

scripts/crons/cron_libraries.sh
The next version of our usual correlation version bump. Should go into production in the week of 2014-03-30.
=> Bug 1148090 - Update forced versions for correlations for Firefox cycle starting 2015-03-31

socorro/lib/datetimeutil.py, socorro/unittest/lib/test_datetimeutil.py
the MissingSymbolsRule in the processor can fail if the date_processed is an actual datetime rather than a string.  Because the crashstorage classes may stringify datetimes and that change propagates to the processed crash given to other crashstorage modules, the crashstorage modules must be defensive and should not assume types.
This PR fixes the utility method that creates a table partition suffix to accept either datetime instances or strings.
@selenamarie   r?
=> fixes Bug 1150970 - added case where type is datetime rather than str

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
the MissingSymbolsRule despoiled its own SQL by save the result after it formatted it.  That meant thet the second time around, there were no formatting variables in the string and formatting failed.  
fixed that problem and added tests to make sure that the rule works more than once.
=> also fixes Bug 1150970 - stopped MissingSymbolRule from spoiling its own SQL

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
@lonnen r?
With this approach that part of the code will work if it's...
* a timestamp (e.g. coming from supersearch)
* a formatted date & time string (e.g. coming from the postgres middleware)
* a proper datetime (future proofing when we stop this to-string formatting nonsense and leave it as a `datetime.datetime` type)
=> fixes bug 1149196 - report_list and install_time carefulness

scripts/defaults, scripts/rabbitmq-integration-test.sh, scripts/test.sh, socorro/database/database.py, socorro/external/postgresql/base.py, socorro/external/postgresql/connection_context.py, socorro/external/postgresql/postgresqlalchemymanager.py, socorro/external/postgresql/setupdb_app.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_base.py, socorro/unittest/external/postgresql/test_crashes.py, socorro/unittest/external/postgresql/test_gccrashes.py, socorro/unittest/external/postgresql/test_setupdb_app.py, socorro/unittest/external/postgresql/unittestbase.py, socorro/unittest/middleware/test_middleware_app.py
This PR enables the PG ConnectionContext classes to use a PG URL existing as an environment variable ```database_url``` to prime the configuration defaults.  For example if the environment variable is: ```postgres://test:aPassword@localhost:5432/socorro_migration_test```, then the class ```socorro.external.postgresql.connection_context.ConnectionContext``` will have the following defaults automatically:
``` python
database_hostname=localhost
database_username=test
database_password=aPassword
database_port=5432
database_name=socorro_migration_test
```
It also facilitates removing the old ```socorro.database.Database``` class from the middleware.  The middleware integration tests are now also free of the dreaded ```.../unittest/confg/commonconfig.py```.
=> Fixes bug 1137879 add support for postgres URLs

scripts/defaults, scripts/rabbitmq-integration-test.sh, scripts/test.sh, socorro/external/postgresql/base.py, socorro/external/postgresql/connection_context.py, socorro/external/postgresql/postgresqlalchemymanager.py, socorro/external/postgresql/setupdb_app.py, socorro/middleware/middleware_app.py, socorro/unittest/cron/setup_configman.py, socorro/unittest/external/elasticsearch/unittestbase.py, socorro/unittest/external/es/base.py, socorro/unittest/external/postgresql/test_base.py, socorro/unittest/external/postgresql/test_crashes.py, socorro/unittest/external/postgresql/test_gccrashes.py, socorro/unittest/external/postgresql/test_setupdb_app.py, socorro/unittest/external/postgresql/unittestbase.py, socorro/unittest/middleware/test_middleware_app.py
This PR enables the PG ConnectionContext classes to use a PG URL existing as an environment variable ```database_url``` to prime the configuration defaults.  For example if the environment variable is: ```postgres://test:aPassword@localhost:5432/socorro_migration_test```, then the class ```socorro.external.postgresql.connection_context.ConnectionContext``` will have the following defaults automatically:
``` python
database_hostname=localhost
database_username=test
database_password=aPassword
database_port=5432
database_name=socorro_migration_test
```
It also facilitates removing the old ```socorro.database.Database``` class from the middleware.  The middleware integration tests are now also free of the dreaded ```.../unittest/confg/commonconfig.py```.  
finally, the scripts/defaults, …
=> (re)  Fixes bug 1137879 -  add PG URL support as defaults in ConnectionContext

socorro/processor/mozilla_processor_2015.py, socorro/processor/skunk_classifiers.py, socorro/unittest/processor/test_mozilla_processor_2015.py
Runs SigTrunc before SignatureRunWatchDog to truncate signatures with "shutdownhang" correctly. Also adds a simple test for mozilla_processor_2015.py.
=> Fix bug 1151436. Handle signatures over 255 chars correctly.

config/package/nginx/conf.d/socorro-collector.conf, config/package/nginx/conf.d/socorro-webapp.conf
r? @jdotpz just updated stage and discovered I got this wrong
=> (no bug) fix syntax error in example nginx config files

socorro/external/postgresql/base.py, socorro/unittest/external/postgresql/test_base.py
r? @twobraids 
I actually think we can refactor even more. I don't like that the big fat `try: ... except psycopg2.Error` block encompasses more than 1 thing. However, the DRY was a bigger violation for now. 
This is actually a fairly high priority fix because it without it we'll never have constructive error messages when the connection can't be made.
=> Bug 1156321 attributeerror on connectionrollback in postgres base

alembic/versions/56f5cdf9bcdb_bug_1000160_use_version_string_instead_.py, socorro/external/postgresql/base.py, socorro/external/postgresql/raw_sql/procs/001_update_reports_clean.sql, socorro/processor/mozilla_processor_2015.py, socorro/processor/mozilla_transform_rules.py, socorro/unittest/external/postgresql/test_base.py, socorro/unittest/external/postgresql/test_crashes.py, socorro/unittest/processor/test_mozilla_transform_rules.py
@twobraids Does this look good to you? 
Note that this is not ready to be merged yet. I need to figure out a transition plan, and to modify a bunch of code related to those version numbers.
=> Fixes bug 1000160 - Set the correct version number in processed crashes.

scripts/package/rpm-after-install.sh
r? @phrawzty - not sure how this is being installed successfully anywhere with this bug, but apparently it is!
=> typo in chown command, needs to specify username

config/package/nginx/conf.d/socorro-analysis.conf
@phrawzty I think this is what we really need for https://crash-analysis.mozilla.com
=> bug 1155504 - enable autoindex for crash-analysis

socorro/collector/wsgi_breakpad_collector.py, socorro/unittest/collector/test_wsgi_breakpad_collector.py
raw crashes that already have a "dump_checksums" when resubmitted will cause trouble in collection.  The value will overwrite the new checksums being created by collector, causing a TypeError.
=> fixes Bug 1159776 - stop existing 'dump_checksums' in raw crashes from causing trouble

docs/configuring-socorro.rst
r? @twobraids - I have a typo in the new docs so the ES config doesn't actually work as-is.
Note that `PolyCrashStorage` is introduced later in this document, I wanted to keep it simple here and just override the primary destination crash storage class.
=> Docs typo in es config

socorro/processor/mozilla_processor_2015.py, socorro/processor/mozilla_transform_rules.py
add new rule to rewrite the release channel for fennec to 'beta' when (product name == Fennec and build_id == 20150427090529 and channel == 'release')
=> fixes bug 1159993 - rewrite release channel for certain Fennec

socorro/external/postgresql/connection_context.py, socorro/unittest/database/test_transaction_executor.py
Moved the PG OperationalError to the Conditional list so that the OOM can be treated as fatal.  
For the record, I do not believe that this will resolve the larger issue of problems in the processor using too much memory.
=> fixes Bug 1163421 moved PG OperationalError to Conditional list

scripts/crons/cron_libraries.sh
The next version of our usual correlation version bump. Should go into production in the week of 2014-04-11.
Note that I'm adding the intermediary 38.0.5 version this time as we'll have that on beta for the next weeks and only then will have 39.0 betas, and we should make sure both are covered in correlations while they're on beta.
=> Bug 1162287 - Update forced versions for correlations for Firefox cycle starting 2015-04-12

scripts/rabbitmq-integration-test.sh
furthering the no json in PG test  to forestall the debilitating memory leak.
=> no  bug - fix rabbit integration test to not force use of PG for processed crashes

requirements.txt, socorro/external/postgresql/connection_context.py, socorro/external/postgresql/crashstorage.py, socorro/external/postgresql/crontabber_state.py, socorro/external/postgresql/field.py, socorro/external/postgresql/report.py, socorro/unittest/database/test_transaction_executor.py, socorro/unittest/external/postgresql/test_crash_data.py
@twobraids r?
cc @rhelmer 
So, the major difference between psycopg2 2.4 and 2.5 (as far as I can see it affecting us) is...
* When you query a table that has a `json` column, what you get is a dict (or whatever is appropriate). Not a string that is JSON text that you need to convert with `json.loads()`. crontabber supports both old and new versions of psycopg2 because it does [this trick](https://github.com/mozilla/crontabber/blob/11bcf6e2e73b1f660ad736142ef52c32affc2170/crontabber/app.py#L245-L246) which makes it more agnostic.
* The actual error from within postgres gets put into exceptions the normal way. No more of this `some_exception.pgcode` or `some_exception.pgerror` See
```python
>>> import psycopg2
>>> psycopg2.__version__
'2.5.5 (dt dec pq3 ext)'
>>> try:
... …
```
=> fixes bug 1164465 - psycopg2 2.5.5

config/package/usr/lib/tmpfiles.d/socorro.conf
@phrawzty `/var/lock/` is a symlink to `/run/lock/` now, so we need to make a `tmpfiles.d` entry to get it to persist on reboot.
I think we should ultimately switch away from custom lock/unlock function to `flock`, but we'll probably need this dir anyway.
=> fix bug 1167017 - persist /var/lock/socorro on reboot

socorro/cron/jobs/laglog.py, socorro/unittest/cron/jobs/test_laglog.py
@twobraids r?
Note: The old tests never actually tested anything. It never iterated anything back when looping over that `each_server` result. So none of the crucial stuff was ever tested. 
This bug was about protecting against sporadic and bad NULLs coming back from `pg_stats_replication` (most likely related and due to high load or something) but I sorta kill two birds with one stone with this PR.
=> fixes bug 1164922 - laglog sometimes chokes on null

webapp-django/crashstats/base/context_processors.py, webapp-django/crashstats/base/templates/crashstats_base.html, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/settings/base.py
@jdotpz or @rhelmer r?
So this is the just the code. It hinges on the environment variable `PINGDOM_RUM_ID=555f618cabe53d05797ee534` being set.
=> fixes bug 1167787 - Install browser header for Pingdom in socorroweb

socorro/app/for_application_defaults.py, socorro/collector/crashmover_app.py, socorro/external/es/crashstorage.py, socorro/processor/general_transform_rules.py, socorro/unittest/external/es/test_crashstorage.py
This PR introduces a new app that can copy the raw and processed json version of a crash from a source to a destination.  it takes this form:
```bash
$ socorro raw_and_processed_copier 
```
This PR also adds a special ES crashstorage class that employs a redactor to edit keys from the processed crash.  The idea is to use it to remove any key from the processed crash in the form '...json_dump'.
=> fixes Bug 1161648 - new raw & processed copier app for ES migration

config/package/etc/nginx/conf.d/socorro-collector.conf.sample, config/package/etc/nginx/conf.d/socorro-middleware.conf.sample, config/package/etc/nginx/conf.d/socorro-webapp.conf.sample
The path to the uwsgi sockets in the systemd configs was changed in 1f5a4f2f946a662470ef3be077c445e082b0b22e so the path in the nginx sample configs should be too.
=> bug 1162085 - sample config path is wrong

socorro/external/statsd/crashstorage.py, socorro/unittest/external/statsd/test_crashstorage.py
here's an additional class for statsd crashstorage - a benchmarking class  that calls the ```timing``` method.  Any call to a wrapped crashstorage class is timed and the information sent to statsd.
=> fixes Bug 1170168 - added statsd benchmarking wrapper

scripts/crons/crontabber.sh
r? @jdotpz / @peterbe - we don't want envconsul to run as a daemon, by default it listens for changes and will restart if there are config changes to the socorro/common or socorro/crontabber prefixes.
We don't want envconsul to kill crontabber while it is running just to push out config changes, crontabber should finish the current run and pick them up on the next.
=> (no bug) - crontabber should use envconsul -once

minidump-stackwalk/common.h, minidump-stackwalk/dumplookup.cc, minidump-stackwalk/get-minidump-instructions.cc, minidump-stackwalk/http_symbol_supplier.cc, minidump-stackwalk/http_symbol_supplier.h, minidump-stackwalk/stackwalker.cc
r? @rhelmer who ran into this issue when trying to move the symbol cache to local disk on EC2 instances, where /tmp is EBS. We use `rename` to move the temp file to its final location but that doesn't work across filesystems.
=> Add a --symbols-tmp argument to stackwalker to set temp directory for symbol download

socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
normalize all signature that contain templates to this form: 
```
Alpha<Bravo<Charlie>, Delta>::Echo<Foxtrot> --> Alpha<T>::Echo<T>
```
remove old normalization rule from Bug 481445 that normalized templates with integer agruments
```
f<3>(x, y, z) -->  f<T>(x, y, z)
```
=> fixes Bug 1163831 - collapse templates in signatures

socorro/processor/signature_utilities.py
add mozilla::ipc::MessageChannel::Send to the prefix list in processor signature generation
=> Fixes Bug 1162703 - added mozilla::ipc::MessageChannel::Send to prefix

socorro/processor/signature_utilities.py, socorro/processor/skunk_classifiers.py, socorro/unittest/processor/test_signature_utilities.py, socorro/unittest/processor/test_skunk_classifiers.py
this is an experimental change to signature generation. It removes the arguments from C++ signatures during signature normalization.  We want to try this to see how this affects top signature reports.  It has been made to be turned on/off (default off) via configuration so we can see if it is helpful or harmful.
=> fixes Bug 1171437 - added option to remove arguments from signatures

socorro/processor/breakpad_transform_rules.py, socorro/processor/mozilla_processor_2015.py, socorro/processor/signature_utilities.py
I've written this in the form of a classifier rule.  This is all it takes to put the stdio results of an external program into a single key in a processed crash.  This is a fine example of a classifier that anyone could write to include in Socorro.  
Placing the output of this external program into the "classifications.jit" namespace within the processed crash, makes it readily available for access by future rules, such as signature manipulation. At the same time this imposes a hierarchical structure on what will likely evolve into many different types of crash classification systems.  Signature itself is just another classifications system that happens to have gotten into Socorro first and so remains entrenched.  I encourage others to write classifiers. A new one could, perhaps, end up …
=> Fixes Bug 1124241 - added jit category external program

socorro/external/postgresql/base.py, socorro/unittest/external/postgresql/test_base.py
This reverts commit 498f453772e276be2ddc54a41f3b5060bd1136df.
This is causing /report/index to not show stack traces on prod, and the "raw dumps" tab on that same page to be blank. (/cc @AdrianGaudebert )
r? @peterbe
=> Revert "Fixes bug 1174169 - Fixed magic beta filter for report/list/."

socorro/processor/breakpad_transform_rules.py, socorro/processor/mozilla_processor_2015.py, socorro/unittest/processor/test_breakpad_transform_rules.py
the tests for the JIT classifier were written to a file that was never checked in to git, nor did its name start with the word "test".  The tests were never run, I didn't notice, and interpreted silence as success.  Once tests were put into the proper file, some obvious defects were found and then corrected.
=> fixes Bug 1177715 - added missing tests, and associated corrections

socorro/processor/breakpad_transform_rules.py, socorro/unittest/processor/test_breakpad_transform_rules.py
the jit categorizer was returning a LF at the end of the string.  We suspect that was unpalatable by ES.  It's been removed.
=> NO BUG - removed LF from output of jit categorizer

socorro/external/boto/crashstorage.py
change default of the boto 'prefix' to empty string
=> No Bug - change default of the boto 'prefix' to empty string

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
we'd like to try the ES bulk load to see how it would work in a crash storage class.
@AdrianGaudebert  - I suspect that you're more familiar with the elasticsearch python API than the rest of us.  could you take a look at this to see if the implementation makes any sense?  The form of the call to ```helpers.bulk``` was very confusing and I have no idea if I have done it correctly.
=> fixes bug 1179456 - a ES bulk load within crashstorage context

scripts/crons/cron_libraries.sh
This adds current aurora and nightly versions as well as all planned beta versions for this cycle.
=> Bug 1181634 - Update forced versions for correlations for Firefox cycle starting 2015-06-29

socorro/external/boto/crashstorage.py
=> Revert "No Bug - change default of the boto 'prefix' to empty string"

socorro/processor/breakpad_transform_rules.py, socorro/unittest/processor/test_breakpad_transform_rules.py
=> Revert "NO BUG - removed LF from output of jit categorizer"

socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
discovered a case where the simplistic approach of removing stuff between parens was the wrong thing.  There exists a signature fragment of this form:   .... (anonymous namespace)::
added code to prevent that example from being collapsed.
=> re-fixes Bug 1171437 - added exceptions to args collapsing

socorro/external/crashstorage_base.py
the NullCrashStorage class is used in ad hoc testing.  It serves no purpose in actual prod code.  In its use in testing, however, it ought to implement the full API. We don't it want raising errors.  We want it to silently ignore everything that it is told to do.
the method ```get_raw_dumps_as_files``` was missing, I added it...
=> NO BUG - added missing method to NullStorage

socorro/collector/submitter_app.py, socorro/external/rabbitmq/rmq_new_crash_source.py, socorro/unittest/collector/test_submitter_app.py
the API used by the submitter has a slight and annoying variation from the standard crashstorage API.  The changes here enable the rabbitmq crashstorage and new_crash_source classes to be compatible with the way that submitter wants things to work.
=> NO BUG - api adjustments for compatiblity rabbit / submitter

socorro/app/fetch_transform_save_app.py, socorro/collector/crashmover_app.py, socorro/collector/submitter_app.py, socorro/processor/processor_app.py, socorro/unittest/app/test_generic_fetch_transform_save_app.py
When we adopted RabbitMQ for use in the processor, we discovered that acknowledging a item taken from a Rabbit queue had to be done by the same thread that pulled the item from the queue.  We retro fitted the new_crashes iterator and the transform method of the processor to accomplish this.  Unfortunately, we only did that for the processor and its dependencies.
Now that we're wanting to use RabbitMQ in other places, like the submitter, we need to make the same retrofitting to that component.  Rather than doing it entirely piecemeal, refactor the acknowledgement callback so that _any_ component can successfully use RabbitMQ as a crash_id streaming source.  
Pull the "try...finally" block that runs the ack function out of the processor's transform method into the base class.  This allows …
=> Fixes Bug 1186505 - unified signature for transform method in FTS apps

socorro/collector/crashmover_app.py, socorro/collector/submitter_app.py, socorro/external/rabbitmq/crashstorage.py, socorro/processor/processor_app.py, socorro/unittest/app/test_generic_fetch_transform_save_app.py, socorro/unittest/collector/test_crash_mover_app.py, socorro/unittest/collector/test_submitter_app.py, socorro/unittest/processor/test_processor_app.py
nope nope nope 
the PR that closed this Bug 1186505 was half-assed and incomplete.  
every instance of the method 'source_iterator' must accept from its internal iterator crashes either in the form of 
1)  crash_id
2)  ((crash_id,), {'additional': 'kwargs'})
and should always return the second form.
ALSO:
the rabbitmq method 'new_crashes' must run the '_consume_acknowledgement_queue' BEFORE checking for the end of iteration.  If it does not, then the last crash will not be acknowledged in the queue.
=> Fixes Bug 1186505 - complete a half-assed unification of 'source_iterator'

socorro/external/es/supersearch.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/supersearch/models.py, webapp-django/crashstats/supersearch/tests/test_views.py, webapp-django/settings_test.py
@AdrianGaudebert r? cc @twobraids 
So this stops using the middleware for talking to ES for supersearch queries. 
Adrian, when I started this work I used to hack it so that the `fetch` method first did the usual `requests.get()` and then it did it the new way. So every page I hit, it would make 2 ES queries. 
I used that to make sure the results are the same. They were. Also, I used it to measure if the direct method was much faster. It was. But only by 5-15% depending on the size. So much of the time spent is on the network and when doing local development it uses CherryPy instead of the much better uWSGI we use in production. 
I know the size of the patch is scary. 99.99% of it is fixing how the mocking is done in tests. Instead of mocking `requests.get` it mocks …
=> fixes bug 1188085 - socorro.external.es.supersearch.SuperSearch directly

socorro/collector/wsgi_breakpad_collector.py, socorro/unittest/collector/test_wsgi_breakpad_collector.py
we seem to be getting crashes with null bytes embedded in strings.  Ensure that the collector sanitizes these strings so that the null bytes don't come through and upset the delicate sensibilities of PostgreSQL.
=> fixes Bug 1168511 - filter all strings in raw crash input to remove \x00

socorro/external/postgresql/adi.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_adi.py
@rhelmer r? (informal)
Rob, I just wanted to share what I've got so far. 
Again, here's an example of its use: https://gist.github.com/peterbe/843ec4764e39dc6a364d
The reason I'm not treading with confidence is because I'm not entirely sure how I'm going to need this to work. My objective is to pull in data from this into the webapp and use SuperSearch aggregates to combine crash counts with ADI. In particular for the sake of the /daily report. I haven't yet started looking at throttle values.
=> fixes bug 1186512 - Expose raw ADI counts

scripts/crons/cron_libraries.sh
This adds current aurora and nightly versions as well as all planned beta versions for this cycle, and should land on prod in the week of August 10.
Note the conversation from https://github.com/mozilla/socorro/pull/2877 - we need to update the crashanalysis node with that code to actually make it live.
=> Bug 1190046 - Update forced versions for correlations for Firefox cycle starting 2015-08-10

webapp-django/crashstats/symbols/management/commands/reencode-bad-sym-files.py
@rhelmer r?
I've successfully run this on my laptop using my personal S3 account. 
A bunch of URLs that that couldn't be opened in the browser before [can now be opened in the browser](https://s3.amazonaws.com/peterbe.org.allizom.crash-stats.staging.crashes/v1/AccessibleMarshal.pdb/83C8F71548914DEFB5A49C880BCDFD3B1/AccessibleMarshal.sym)
Once this lands we'll need to run this from somewhere on a stage node. You start the script with:
```
./manage.py reencode-bad-sym-files
```
By default it will attempt go through every file uploaded. So it'll that a freakishly long time. An alternative is to add `--max-uploads=3` (for example). That'll pick 3 random uploads and go through each file in those.
=> fixes bug 1193536 - re-encode old .sym files

socorro/collector/wsgi_breakpad_collector.py, socorro/unittest/collector/test_wsgi_breakpad_collector.py
it turns out that the null string can occurr in both the key and the value.  The previous fix for this problem only focused on the values for the keys, not the keys themselves.  
This fixes that oversight.
=> Fixes Bug 1168511 (again) - add ability to test keys for null bytes

requirements.txt
@jdotpz r? This should fix the build.
=> Bug 1184173 - Added missing hash for freezegun package.

socorro/collector/wsgi_breakpad_collector.py, socorro/unittest/collector/test_wsgi_breakpad_collector.py
the collector bad bytes cleanup is failing on unicode/str conversions.  separate the cases so that can be more controlled in the cleanup of bad bytes.
=> more Fixes Bug 1168511 - separate unicode & str cases in cleaning of null bytes.

socorro/external/fs/crashstorage.py, socorro/external/postgresql/crash_migration_app.py, socorro/unittest/external/fs/test_fsdatedradixtreestorage.py
removes out-dated prohibition on saving raw crash in the ```save_raw_and_processed``` method
=> Fixes Bug 1196722 - allow FS to save raw, dumps & processed in combined call

webapp-django/crashstats/crashstats/static/crashstats/css/crontabber_state.css, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/crontabber_state.js, webapp-django/crashstats/crashstats/templates/crashstats/crontabber_state.html
@lonnen r?
It looks like this:
Stage wasn't reporting any errors at the moment so I had to fake the json. That's why I added some `<` and `>` to make sure those got escaped properly.
=> fixes bug 1198533 - More info about failed crontabber jobs

socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
two problems:
1. the RunWatchDog rule will not trigger properly if arguments are collapsed. solution: remove the arguments from the predicate
2. the RunWatchDog rule on triggering, regenerates the signature forcing it to use thread-0. The collapse arguments boolean does not extend to this regeneration.  Solution: add a "reference_value_from" to make configman signature arguements act globally instead of only locally.  Then set "resource.signature.collapse_arguments=True" in consulate.
=> Fixes Bug 1200628 - altered RunWatchDog sig rule to account for arg collapsing

socorro/external/statsd/statsd_rule_benchmark.py, socorro/unittest/external/statsd/test_stastsd_rule_benchmark.py
this is a demo of what can be done with the statsd classes and processor rules...  
this change creates a base counter rule class and then uses it to define two processor rules that detect conditions during processing and then increment a statsd counter.  
CountStackWalkerTimeoutKills  will track how many times the stackwalker is killed for taking too long.
CountStackWalkerFailures will track how many times the stackwalker crashes or returns a bad error code.
=> Fixes Bug 1172511 - examples of CountAnythingRules for the processor

scripts/package/deb-after-remove.sh, scripts/package/deb-before-remove.sh
The socorro files (configs specifically) and user should only be removed on
purge.
https://wiki.debian.org/AccountHandlingInMaintainerScripts has some
good guidelines regarding account deletion.
=> The debian postrm cleanup should happen on purge

alembic/env.py
@twobraids r?
CC @selenamarie @rhelmer 
So, to run the migrations (or just see what the current head is) I have to edit `/etc/socorro/alembic.ini` and change the line `sqlalchemy.url = ...` every time the admin node is restarted. That cumbersome. 
I.e. the following:
```
vi /etc/socorro/alembic.ini
cd /data/socorro/application/
. /data/socorro/socorro-virtualenv/bin/activate
alembic -c /etc/socorro/alembic.ini current
```
The problem is that the admin node is ephemeral and my changes to `/etc/socorro/alembic.ini` are wiped. 
As of this patch, I can override `sqlalchemy.url` by running it like this:
```
env sqlalchemy.url=postgresql://USER:PASSW@HOSTNAME/breakpad alembic -c config/alembic.ini current
```
I get the values from:
```
envconsul -prefix socorro/common -sanitize -upcase env | …
```
=> alembic to be able to read from env

requirements.txt
It's hard to see if there are "left-over dependencies" that we can live without. 
Imagine a script you run over night that tests all sorts of combinations of removing items from `requirements.txt` and sees if the whole test suite passes.
=> fixes bug 1192014 - Purge pyelasticsearch

webapp-django/crashstats/supersearch/static/supersearch/js/socorro/search.js
This is now what it looks like when you get a 400 AJAX query:
And this is what it looks like when you get a 500 error:
=> fixes bug 1190443 - Error message on SuperSearch AJAX search inserts whole HTML

scripts/crons/cron_libraries.sh
This adds current aurora and nightly versions as well as all planned beta versions for this cycle, and should land on prod early in the week of September 21.
Note that need to update the crashanalysis node with that code to actually make it live.
=> Bug 1205014 - Update forced versions for correlations for Firefox cycle starting 2015-09-21

scripts/integration-test.sh, scripts/rabbitmq-integration-test-2015.sh, socorro/app/for_application_defaults.py, socorro/collector/collector_app.py, socorro/collector/wsgi_breakpad_collector.py, socorro/collector/wsgi_generic_collector.py, socorro/lib/converters.py, socorro/unittest/collector/test_collector_app.py, socorro/unittest/collector/test_wsgi_breakpad_collector.py, socorro/unittest/collector/test_wsgi_generic_collector.py, socorro/unittest/lib/test_converters.py, socorro/webapi/classPartial.py, socorro/webapi/servers.py, testcrash/not_breakpad/not_a_breakpad_crash.json
the collector may be called on to collect things other than breakpad type crashes.  Enable the collector to have multiple services at different URLs that can route data-payloads to any other crash storage systems.
features:
1. This change should remain backwards compatible with the existing collector.
2. Separate the URI from the implementation class, so that service implementation classes can be reused
3. Config for each service should be in its own namespace
4. each service should have its own crash storage class so that different types of data-payloads may be routed to different places
5. each service implementation should brand the raw_crash with a ```type_tag``` to further allow sorting or routing
6. the ```type_tag``` should be used as the return prefix when the collector …
=> Fixes Bug 1205350 - collector2015 - allow multiple collector types

requirements.txt, socorro/unittest/external/es/test_supersearch.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/supersearch/tests/test_views.py
@peterbe r?
I'm also upgrading ``elasticsearch-dsl`` to fix a bug: when you were querying for 0 results, it would instead return Elasticsearch's default number of results, which is 10. That's fixed with the latest version.
=> Fixes bug 1207085 - Do not consider `0` as a falsy value in API.

socorro/external/es/supersearch.py, socorro/external/postgresql/adi.py, socorro/external/postgresql/product_build_types.py, socorro/lib/search_common.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_adi.py, socorro/unittest/external/postgresql/test_crash_data.py, socorro/unittest/external/postgresql/test_product_build_types.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/static/crashstats/css/crashes_per_user.less, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/crashes_per_user.js, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/daily.js, webapp-django/crashstats/crashstats/templates/crashstats/crashes_per_user.html, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/urls.py, webapp-django/crashstats/crashstats/views.py
@AdrianGaudebert here's a sneak peek. It gives pretty nice results on the "By Crash Date" but we have some work to do on the "By Build Date" still since PG seems to yield such totally different numbers. 
Todo:
=> Bug 1196867 new crashes per user using supersearch

socorro/external/es/connection_context.py
This is what broke the custom search. Now it works.
=> fixes bug 1207705 - KeyError 'elasticsearch_timeout_extended'

socorro/processor/signature_utilities.py, socorro/unittest/external/es/test_supersearch.py, socorro/unittest/processor/test_signature_utilities.py
one of the eternal complaints about Socorro is the inability to search for crashes based on frames of the crashing thread's stack.  While the signature is based on the frames of the crashing thread, it is heavily edited.  The stack frames themselves are removed from the processed crash because of disk space issues.  
During the process of creating a signature, there is a point when all the normalized frame signature are assembled into a list.  This is just before the application of the skip list regular expressions.  Taking this list of normalized frame signatures and concatenating them into one long string introduces a way to search the stack for patterns in calls.  
Normally, after signature generation is complete, the list is thrown away.  Rather than that, we should explore its …
=> Fixes Bug1208129 - add proto_signature to processed crash

webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/management/__init__.py, webapp-django/crashstats/symbols/models.py, webapp-django/crashstats/symbols/tests/test_api.py, webapp-django/crashstats/symbols/views.py
Note! This is the first time we use our Public API to expose something stored "in Django". 
I chose to not bother with the caching. First of all, this endpoint requires auth so it's quite unlikely that one of the people with a permission will abuse it. And it's simple and fast anyway. The other reason is that I didn't want to spend time inventing that when there wasn't a real need. One thing at a time. 
This commit doesn't have a "fixes" in the commit message. 
That's because, once deployed on stage and prod we need to execute the `./manage.py syncdb` run so that it picks up the new permission that I defined in the `crashstats/management/__init__.py`
Also, even when that's done, I don't think the bug is ready until the likes of Ted and Benjamin gets his group(s) …
=> bug 1012759 - API to audit uploaded symbols

socorro/collector/breakpad_submitter_utilities.py, socorro/collector/submitter_app.py, socorro/external/crashstorage_base.py, socorro/unittest/collector/test_submitter_app.py, socorro/unittest/external/test_crashstorage_base.py
the variants of the crash storage classes that are defined along with the submitter, to not follow the crash storage API correctly. For example, the file system crash source for the submitter doesn't iterate over crash_ids, but crash paths instead.  
pave over these differences in the submitter so that the submitter is capable of using the standard crash storage API.  +tests
=> Fixes Bug 1204563 - make the submitter more friendly to other crashstores

socorro/external/fs/crashstorage.py, socorro/unittest/external/fs/test_tar_crashstore.py
the correlations scripts write to and then read crashes from tar files.  Make  writing and reading CrashStorage classes that produce the same kind of tar'd gziped files.
=> fixes Bug 1210260 - correlation script compatible crashstore

socorro/collector/submitter_app.py, socorro/collector/wsgi_generic_collector.py, socorro/external/boto/crashstorage.py, socorro/external/crashstorage_base.py, socorro/external/fs/crashstorage.py, socorro/external/happybase/crashstorage.py, socorro/external/hb/crashstorage.py, socorro/external/http/crashstorage.py, socorro/unittest/collector/test_submitter_app.py, socorro/unittest/external/boto/test_crashstorage.py, socorro/unittest/external/fs/test_crash_data.py, socorro/unittest/external/fs/test_fsdatedradixtreestorage.py, socorro/unittest/external/fs/test_fslegacydatedradixtreestorage.py, socorro/unittest/external/fs/test_fsradixtreestorage.py, socorro/unittest/external/happybase/test_crashstorage.py, socorro/unittest/external/hb/test_crashstorage.py, socorro/unittest/external/hbase/test_crashstorage.py, socorro/unittest/external/http/test_crashstorage.py, socorro/unittest/external/test_crashstorage_base.py
_**This PR may look daunting but it isn't that complicated.** It introduces two classes that take the place of what were simple ```dict``` mappings.  It touches a lot of files, but in a very rote manner._
There has been a bifurcation in the crash storage data throughout the history of the classes.  The crash dumps have two different representations:
1) a mapping of crash names to binary data blobs
2) a mapping of crash names to file pathnames.
It has been a manner of gentleman's agreement that two types do not mix. However, as the two methods have evolved in parallel the distinction has become more and more inconvenient.
This PR introduces two classes that encapsulate the two representations.  They each include a method to turn itself into the other. Any crash storage class on receiving a …
=> fixes Bug 1212334 - disambiguate crash dumps being in memory or files

socorro/external/postgresql/graphics_report.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_graphics_report.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/forms.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/urls.py, webapp-django/crashstats/crashstats/views.py
cc @twobraids 
I'd like to get some early eyes on this whilst I wait for the Graphics team to get back to me about which columns we can blanket out. E.g. `adu_count`. 
Once we have the most expensive columns blanket'ed out (e.g. `adu_count` and `duplicate_of`) that query will become many many times faster. 
How to test this? Run the branch and load http://socorro.dev/graphics_report/?date=2015-10-08 for example. Note that you need to be logged in. 
How to test it on the command line...
First you need to generate an API token that has the "Run long queries" permission. 
Then something like this:
```
curl -v -H "Auth-Token: 12312312312312312" http://socorro.dev/graphics_report/?date=2015-10-08
```
Or if you want to test that it gets gzipped properly, download it like …
=> fixes bug 1212088 - Expose graphics related CSV report via webapp

webapp-django/crashstats/tokens/static/tokens/css/home.css, webapp-django/crashstats/tokens/templates/tokens/home.html
Turns out, it's [not trivial](https://css-tricks.com/fighting-the-space-between-inline-block-elements/) to get rid of those spaces between the tags. But I think I got it working.
=> fixes bug 1212969 - display copyable token without whitespace

socorro/external/es/supersearch.py, socorro/unittest/external/es/test_supersearch.py
@AdrianGaudebert What should the number be? Should it be tied to the "Run long queries" permission?
=> fixes bug 1214718 - SuperSearch should guard against massive _results_number

webapp-django/crashstats/manage/static/manage/js/featured-versions.js, webapp-django/crashstats/manage/templates/manage/featured_versions.html
So this is the least hacky thing I can image we start with. I first tried to write it as a script that anybody could own and run with an API token. But then I needed a new permission (and possibly tie that to a group) and our FeaturedReleases model couldn't accept anything other than multipart form.
I say we make this available and it only shows on stage or localhost and it'll make stage look more sane and should solve the problem for QA.
=> fixes bug 1214436 - Ability to sync featured versions from prod

socorro/app/fetch_transform_save_app.py, socorro/app/socorro_app.py, socorro/collector/crashmover_app.py, socorro/collector/submitter_app.py, socorro/external/postgresql/crash_migration_app.py, socorro/lib/task_manager.py, socorro/lib/threaded_task_manager.py, socorro/processor/processor_app.py, socorro/unittest/app/test_generic_fetch_transform_save_app.py, socorro/unittest/app/test_socorro_app.py, socorro/unittest/collector/test_crash_mover_app.py, socorro/unittest/collector/test_submitter_app.py, socorro/unittest/processor/test_processor_app.py
unify the iterator models between the processor and submitter families of FTS apps.  Since the correlation reports will be encoded as TransformRules, this means using the processor as the base app class.  However, the processor is long running and its iteratation system doen't ever raise the StopIteration exception.  The submitter app class has the ability to allow an iterator to run to exhaustion and then quit, but doesn't have a good method of using a TransformRule system.
Push all the iteration down to the FetchTransformSaveApp class rather that repeating components through the class hierarchy.  Give the processor the ability to limit iteration to "forever", "all" or a specific number of iterations.
DO NOT BREAK BACKWARDS COMPATIBILITY WITH EXISTING CONFIGURATION.
=> fixes Bug 1212917 - refactor iteration - push to base classes

docs/configuring-socorro.rst
he docs on how to setup Socorro are outdated in the section about setting up the Collector.  The "application" parameter is now required to select which Collector app to use.  We have two of them now:
``` python
socorro.collector.collector_app.CollectorApp
```
```python
socorro.collector.collector_app.Collector2015App
```
=> fixes Bug 1216524: added CollectorApp to config instructions

webapp-django/crashstats/crashstats/templates/crashstats/daily.html, webapp-django/crashstats/crashstats/templates/crashstats/report_index_not_found.html, webapp-django/crashstats/crashstats/templates/crashstats/report_index_pending.html, webapp-django/crashstats/crashstats/templates/crashstats/report_index_too_old.html, webapp-django/crashstats/crashstats/templates/crashstats/report_list.html, webapp-django/crashstats/crashstats/templates/crashstats/reports_columns_form.html, webapp-django/crashstats/crashstats/templates/crashstats/reports_columns_form_hint.html, webapp-django/crashstats/crashstats/templates/crashstats/signature_summary.html, webapp-django/crashstats/crashstats/templates/crashstats/topchangers.html
Now, when I run
```
git ls-files | grep '\.html' | xargs python indentations.py | grep -v 4
```
it yields nothing. Meaning, we're done!
=> fixes bug 1207638 - All .html templates to use 4 spaces for indentation

docs/configuring-socorro.rst
The bash block didn't show up at all in the docs.
=> fix missing new line in PR#3047

docs/configuring-socorro.rst
Following the documentation I was missing this in the `processor.conf`. The processor did run but wasn't picking up the crash reports collected by the collector.
=> Add missing configuration line that prevents the processor from processing

socorro/app/socorro_app.py
there was a debug line in the socorro app hierarchy that was inadvertently left in.  in some edge cases it causes an exception during a shut down.  fix it.
=> fixes Bug 1218579  -removed logger reference at the end that might not exist

scripts/crons/cron_libraries.sh
This adds current aurora and nightly versions as well as all planned beta versions for this cycle, and should land on prod this week still.
Note that need to update the crashanalysis node with that code (and make sure this version of the script is actually being run) to actually make it live.
=> Bug 1219384 - Update forced versions for correlations for Firefox cycle starting 2015-10-29

requirements.txt, webapp-django/bin/linting.py, webapp-django/crashstats/base/helpers.py, webapp-django/crashstats/base/monkeypatches.py, webapp-django/crashstats/crashstats/helpers.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/settings/test.py, webapp-django/crashstats/urls.py, webapp-django/manage.py, webapp-django/wsgi/socorro-crashstats.py
This might need some care when reviewing. I'm quite confident about the code changes, but what I'm less confident about is the django-compressor stuff. 
I was able to set
```
COMPRESS_ENABLED=False
COMPRESS_OFFLINE=False
```
and run the site fine. The `.less` files were converted to `.css` just fine. 
Also, I was able to change to 
```
COMPRESS_ENABLED=True
COMPRESS_OFFLINE=True
```
and run
```
./manage.py collectstatic --noinput && ./manage.py compress --engine=jinja2 --force
```
like I always do and then runserver and that worked fine too.
=> fixes bug 1216807 - Get rid of funfactory

scripts/integration-test.sh, socorro/processor/socorrolite_processor_2015.py
We don't use the ScorroLiteProcessor at Mozilla, but our docs lead new users to start with it.  We ought to ensure that it works.  
Fix the missing symbol in the SocorroLiteProcessor and add it to the integration tests to make sure it works.
=> Fixes Bug 1218366  fixed missing import in the SocorroLiteProcessor class + a test

webapp-django/crashstats/crashstats/views.py
Took me some time to figure this one out even though the change is so small. But the point is that this multiplication is not done during querying in the old daily report.
=> fixes bug 1219863 - crashes per user throttling applied

socorro/cron/jobs/ftpscraper.py, socorro/unittest/cron/jobs/test_ftpscraper.py
@rhelmer Thank you for helping!
I tested this first by manually running `ftpscraper.py`. And now it inserts builds for `mozilla-aurora-android-api-11`. Before this change, the `repository` value became `mozilla-aurora-android-api` and that's not a valid repository value in `special_product_platforms`.
=> fixes bug 1221624 - FennecAndroid repository digit trimming

socorro/external/postgresql/adi.py, socorro/unittest/external/postgresql/test_adi.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
Wow! I can't believe we let the new `Crashes per User` be landed without tests. 
So there's two big changes here. 
1. Test coverage of the `crashes_per_user`. One when everything is normal. And one when one of the requested versions is one of those "beta" releases. I.e. it ends with a "b". 
2. "Explosion and compression". Basically, when the user requests to see the data for version "XX.b", before doing the ADI query *and* the SuperSearch query, I look into the known list of current releases for all other versions that start with "XX.b" but is not "XX.b". So basically, if the request is `?p=Firefox&version=19.0&version=18.0b` instead of doing the queries on `versions=['19.0', '18.0b']` I convert that to `versions=['19.0', '18.0b1', '18.0b2', '18.0bn', ...]`. And when the results come …
=> fixes bug 1219776 - Remove beta hack on crashes per user

webapp-django/crashstats/settings/base.py
This PR doesn't automatically close the bug because we also need to check that consulate have `CACHE_MIDDLEWARE` **on** (or not set) and `CACHE_MIDDLEWARE_FILES` **off** (or not set).
=> bug 1225602 - CACHE_MIDDLEWARE_FILES should be off by default

requirements.txt, webapp-django/wsgi/socorro-crashstats.py
Here's how I run the webapp locally WITH newrelic enabled 
```
NEWRELIC_PYTHON_INI_FILE=~/dev/MOZILLA/CORRO/newrelic.ini    \
DJANGO_SETTINGS_MODULE=crashstats.settings uwsgi --pythonpath   \
./webapp-django/ -w webapp-django.wsgi.socorro-crashstats   \
--http :9090 -H ~/virtualenvs/socorro
```
I don't know how to check that bits are actually sent to newrelic.com but I put some print statements in to test and it did seem to configure without any problems.
=> fixes bug 1223949 - New relic configuration to wsgi file

webapp-django/wsgi/socorro-crashstats.py
I checked that this worked by running:
```
NEWRELIC_PYTHON_INI_FILE=xxxxxxewrelic.ini \
DJANGO_SETTINGS_MODULE=crashstats.settings uwsgi --pythonpath   \
./webapp-django/ -w webapp-django.wsgi.socorro-crashstats     --http :8000\
-H ~/virtualenvs/socorro -M --need-app --workers 3
```
And it spat this out:
```
...
mapped 291040 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
added ./webapp-django/ to pythonpath.
NEWRELIC_PYTHON_INI_FILE set but file does not exist. Skipping to initialize newrelic agent.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f7f6a600830 pid: 67248 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 67248)
spawned uWSGI worker 1 (pid: 67249, cores: 1)
spawned uWSGI worker 2 (pid: …
```
=> fixes bug 1226359 - Fail more gracefully if the NEWRELIC_PYTHON_INI_FILE doesn't exist

socorro/app/fetch_transform_save_app.py, socorro/collector/submitter_app.py, socorro/external/crashstorage_base.py, socorro/external/fs/fs_new_crash_source.py, socorro/external/postgresql/new_crash_source.py, socorro/external/rabbitmq/rmq_new_crash_source.py, socorro/processor/timemachine.py, socorro/unittest/collector/test_submitter_app.py, socorro/unittest/external/fs/test_fs_new_crash_source.py, socorro/unittest/external/postgresql/test_new_crash_source.py, socorro/unittest/external/rabbitmq/test_rmq_new_crash_source.py, socorro/unittest/external/test_crashstorage_base.py, socorro/unittest/lib/test_converters.py
The correlation reports feed on data about specific Product/Versions.  In their original form, they read from a tar file of all the day's processed crashes.  Since in their new form they are in an FTS app, they can use a crash_iter that is more targeted.
Create a new_crash_source module for Postgres that accepts a list of Products/Versions in this form:  "Firefox, 41.0.1, 42.0, 43.0a3; Thunderbird, 38.1.0, 38.2.0; ...".  From that, create a query that will target just those crashes and then offer the stream of crash_ids as an iterator for an FTS app.  
There are at least two other new_crash_source iterators floating around in the Socorro source code.  Consolidate all of these into one module called socorro.external.postgresql.new_crash_source
=> Fixes Bug 1219265 - iterator for products & versions for correlation reports + consolidation

socorro/app/fetch_transform_save_app.py, socorro/lib/transform_rules.py, socorro/processor/processor_2015.py, socorro/processor/processor_app.py, socorro/unittest/app/test_generic_fetch_transform_save_app.py, socorro/unittest/collector/test_crash_mover_app.py, socorro/unittest/lib/test_transform_rules.py
three inheritance trees, FTS Apps, Crashstorge and Transform classes all have their own ways to shut themselves down.  Unify them all to use a simple 'close' method.  This makes them more compatible with each other, predictable and helps them move toward being contextmanager compatible.
=> unify close behavior for FTS source/destination & TransformRules

webapp-django/crashstats/crashstats/forms.py, webapp-django/crashstats/crashstats/tests/test_forms.py, webapp-django/crashstats/crashstats/views.py
It's still bad, but it's a LOT better now. 
Before:
**53 `memcache.get` calls**
After:
**30 `memcache.get` calls**
What this is, is the metric for rendering 1 Report list page of a randomly picked signature. 
So why does it still need 13 calls just render 1 page? It loads one AJAX call for every tab (which is a good thing) and each time it needs to verify that the product and version supplied in the AJAX URL's query string is sane. 
This is going to make for much less memcache IO and it's going to make the Report list page faster.
There's still more "deeper" work that can be done but considering that the Report list a slowly dying feature it's not worth going further at the moment.
=> fixes bug 1227685 - CurrentProducts.get is called too much

webapp-django/crashstats/crashstats/templates/crashstats/home.html
@peterbe somehow I missed that during my local tests and found only on stage just now. r?
=> Fixes bug 1221048 - Fixed link to Plugin Topcrashers in home page.

scripts/crons/cron_libraries.sh
This adds current aurora and nightly versions as well as all planned beta versions for this cycle, and should land on prod early next week (2015-12-14 or closely after).
Note that need to update the crashanalysis node with that code (and make sure this version of the script is actually being run) to actually make it live.
=> Bug 1231796 - Update forced versions for correlations for Firefox cycle starting 2015-12-14

requirements.txt, webapp-django/crashstats/settings/base.py
The reason I'm confident this'll work is because I managed to send [this in](https://sentry.prod.mozaws.net/operations/socorro-stage/group/155635/) 
That's from my laptop using the socorro stage project. Scroll down to the bottom and you can see that I clearly used raven 5.9.0. 
As of this version of raven we'd now be able to append a version for all crashes. Look at [the second code example here](https://docs.getsentry.com/hosted/clients/python/advanced/). [Here](https://docs.getsentry.com/hosted/clients/python/integrations/django/)'s how you do it in Django. The problem is that can only get that version out of the middleware at runtime. Not when the uwsgi workers are starting up. I'll ask @jdotpz if he has some good ideas.
=> fixes bug 1227237 - Upgrade raven and track releases

config/package/usr/lib/systemd/system/socorro-webapp.service
Perhaps now's not the time but I'm going to see about [uwsgitop](https://github.com/xrmx/uwsgitop)
You need to start uwsgi with `--stats`.
I noticed that our memory usage on all three webheads hovers steadily around 1Gb at the time of writing. Our m3.xlarge instances have [15Gb of ram](https://aws.amazon.com/ec2/instance-types/) and I noticed that at the time of writing free tells me we have 14Gb total and we use 1Gb. 
So let's see what those numbers are when we go to a higher number of processes (aka. workers).
=> fixes bug 1233194 - 6 uwsgi workers for webheads

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/signature/views.py
I think this is an important patch. Now that signature summary is the "default" (well, I mean the new TCBS is default and that new one prefers signature report) we need to prioritize this functionality. The whole page is currently always held up by a ~1 second server rendering delay as it pulls down the graphics devices. 
We could potentially make the whole experience even better by NOT rendering this in django at all. Perhaps instead we display the table with JUST the hexes and then a piece of jQuery sucks up all the hexes and makes an AJAX query and on-the-fly replaces the hexes with real names. However, I'm not convinced that'd make the page a whole lot faster. Response time would be faster but shuffling a ton of hexes back and forth in jQuery would add to extra load strain when you …
=> fixes bug 1228122 - Optimize and abstract graphics devices lookup

linux-requirements.txt, requirements.txt, scripts/bootstrap.sh
This solves two things. 
1. Now you can do `peep install -r requirements.txt` on non-Linux without having to rely on rhelmer's fork on github (which is not on pypi). 
2. rhelmer's fork made it installable on OSX but once installed it would cause problems with Django because Django tries to use it (based on it being import'able) but will of course fail. That's why we can do add [this hack](https://github.com/rhelmer/pyinotify/pull/2) to rhelmer's fork.
=> fixes bug 1237666 - Break out pyinotify install for non-linux

socorro/lib/search_common.py, socorro/unittest/lib/test_search_common.py
Is this right?
It's easy to reproduce. If you go to the /api page and just fill in a single date on the `date` key, you get a 500 error.
=> fixes bug 1237715 - API SuperSearch without a full date parameter

webapp-django/crashstats/settings/base.py, webapp-django/crashstats/settings/bundles.py, webapp-django/package.json
@adngdb So yuglify has [a bug that can't handle certain jquery files](https://github.com/yui/yuglify/issues/19).  And sadly yuglify uses the old UglifyJS and not UglifyJS2. Switched fixed the problem. 
What `yuglify` was was a wrapper over `cssmin` and (the old) `uglifyjs`. So instead of keeping it, I decided it's better we just use explicitly `cssmin` and (the new) `uglifyjs`. 
Yeah, it's confusing. Compare: [uglify-js](https://www.npmjs.com/package/uglify-js) and [uglify](https://www.npmjs.com/package/uglifyjs). 
Also, [this was confusing](https://twitter.com/peterbe/status/686607276254298113)
=> Bug 1238595 syntaxerror in compressed jquery ui

requirements.txt, webapp-django/crashstats/settings/base.py
Yes, I did upgrade uWSGI and gunicorn. That's because if I didn't they wouldn't compile any more on my machine. 
What `commonware` did for us is...:
* Made sure all cookies are httponly and secure by default. We manage that with `SESSION_SECURE_COOKIE = True` and there's now a new `SESSION_COOKIE_HTTPONLY` setting which Django respects.
* It sets a `X-Frame-Options: DENY` header. (see `curl -v https://crash-stats.mozilla.com >/dev/null`) We can do that with stock Django now.
=> fixes bug 1237671 - Refactor out funfactory python dependencies we longer needed

scripts/crons/cron_libraries.sh
This adds current aurora and nightly versions as well as all planned beta versions for this cycle, and should land on prod early next week (2016-01-25 or closely after).
Note that once again we need to update the crash-analysis node with that code (and make sure this version of the script is actually being run) to actually make it live.
=> Bug 1241343 - Update forced versions for correlations for Firefox cycle starting 2016-01-25

scripts/bootstrap.sh
switch breakpad to using a non-dot bucket name.
I made a hyphenated bucket with the same contents to satisfy the wildcard cert. This will prevent the build from failing on systems that actually validate the cert.
=> nobug -- fixup breakpad bucket name

socorro/external/boto/connection_context.py, socorro/external/boto/crashstorage.py, socorro/external/postgresql/new_crash_source.py, socorro/unittest/external/boto/test_connection_context.py
CC @twobraids 
Lars, you are the ideal reviewer for this PR but I don't want to assign you out of principle. 
However, the change is small but quite significant. 
The most important change is on line 270 in `socorro/external/boto/crashstorage.py`.
It changes the default to use this new regional connection context class. I don't know if we've specified an override in consul for this but even if we have it's not a huge concern since the old class is still there. 
Another important "trick" is that the default region is `us-west-2` which is what I know we Mozilla use. By setting it as a default we can pursue this new code into prod without having to config change anything. 
By the way, I was able to now get my report index page (using `org.allizom.crash-stats.rhelmer-test.crashes`) to work in …
=> Bug 1242024 - Use a regional S3 connection context

socorro/cron/jobs/matviews.py
I missed one. See https://bugzilla.mozilla.org/show_bug.cgi?id=1243405#c3
Sorry for the pep8 fix. My git hooks are harsh. With this change, it'll shut up on that file.
=> fixes bug 1243405 - make adu-matview depend on fetch-adi-from-hive

scripts/integration-test.sh
I don't think this will definitely remove all those weird integration test errors we see. I still don't know for sure if this is the explanation. 
But there have been cases where we're seen some strange diffs related to whitespace. Let's avoid that. 
I'm also adding a bit more verbosity to compare the directory contents when there is a diff.
=> fixes bug 1248730 - Don't compare correlation .json files with whitespace

socorro/external/postgresql/adi.py, socorro/external/postgresql/crashes.py, socorro/external/postgresql/dbapi2_util.py, socorro/external/postgresql/product_build_types.py, socorro/external/postgresql/products.py, socorro/external/postgresql/raw_sql/views/001_product_info_view.sql, socorro/external/postgresql/releases.py, socorro/external/postgresql/report.py, socorro/external/postgresql/signature_first_date.py, socorro/lib/external_common.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_dbapi2_util.py, socorro/unittest/external/postgresql/test_graphics_report.py, socorro/unittest/external/postgresql/test_products.py, socorro/unittest/lib/test_external_common.py, webapp-django/crashstats/api/static/api/css/documentation.css, webapp-django/crashstats/api/templatetags/jinja_helpers.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/base/tests/testbase.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/utils.py, webapp-django/crashstats/profile/tests/test_views.py, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/supersearch/models.py, webapp-django/crashstats/supersearch/tests/test_views.py, webapp-django/crashstats/topcrashers/tests/test_views.py
@adngdb I know. It's huge. Let me explain...
What you need to play with it start it and use the new `/api/ProductVersions`. It's basically just a tool to read directly from the new class `socorro.external.postgresql.products.ProductVersions`. It works, right?
Next, because this is now the second implementation class that is directly implemented in the webapp, I had to do some surrounding changes...
**1)** Usually the implementation classes return something like this:
```python
things = self.query(sql, sql_params).zipped()
return {
'hits': things,
'total': len(things)
}
```
The problem with that is that `.zipped()` return a list of `DotDict` instances. Because `DotDict` is a fancy instance and not just a plain `dict` two very important classes struggled to deal with them. …
=> Bug 1246253 one productversions api to rule them all

socorro/processor/signature_utilities.py
=> Fixes bug 1249805 - Added mozilla::CondVar::.* to the prefix list.

webapp-django/crashstats/signature/views.py, webapp-django/crashstats/supersearch/views.py
Whenever Django renders a response, the dict parameters you give is generally called a "context". 
Not so important but we sometimes call that thing "data" and sometimes we call it "context". However we call it "context" much more than "data" so let's stick to that for consistency.
=> consistently call it 'context'

scripts/crons/cron_libraries.sh
This adds current aurora and nightly versions as well as all planned beta versions for this cycle, and should land on prod early next week (2016-03-07 or closely after).
Note that once again we need to update the crash-analysis node with that code (and make sure this version of the script is actually being run) to actually make it live.
=> Bug 1252887 - Update forced versions for correlations for Firefox cycle starting 2016-03-07

socorro/external/postgresql/crontabber_state.py, socorro/middleware/middleware_app.py, socorro/unittest/external/postgresql/test_crontabber_state.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/monitoring/tests/test_views.py, webapp-django/crashstats/monitoring/views.py
Note how I took the liberty to delete the `test_carry_mware_error_codes` test. 
That one was about testing how the middleware response HTTP error codes. It had to use something so it used the `CrontabberState` (because it's simple). 
As of this PR, the middleware isn't gone. But it's dying. The `CrontabberState` no longer comes from the middleware and I **could** change the test to instead use some other implementation that's still in `middleware_app` but at this rate, that'd just have to be change and be changed as we continue to dismantle the middleware.
=> fixes bug 1254124 - Crontabber state pure implementation

socorro/processor/signature_utilities.py
This is since nsRefPtr has been renamed to RefPtr.  I'm leaving the equivalent nsRefPtr.* line for older versions.
=> Add 'RefPtr.*' to prefixSignatureRegEx.

socorro/processor/signature_utilities.py
From what I understand, js::AutoEnterOOMUnsafeRegion::crash is either a replacement or at least a similar thing to js::CrashAtUnhandlableOOM which we already handle, and from the name, I'm pretty sure that all of AutoEnterOOMUnsafeRegion is pretty surely OOM handling, so if we crash there, we should assign an "OOM" signature.
=> Bug 1257572 - Add js::AutoEnterOOMUnsafeRegion::crash to our markers for OOM signatures

socorro/analysis/correlations/correlations_app.py, socorro/external/es/correlations.py, socorro/external/es/crashstorage.py, socorro/external/es/index_creator.py, socorro/external/es/new_crash_source.py, socorro/unittest/external/es/base.py, socorro/unittest/external/es/test_correlations.py, socorro/unittest/external/es/test_new_crash_source.py
The way to run this is like this:
```
socorro correlations  \
--resource.postgresql.database_port=5433 \
--resource.postgresql.database_name=breakpad \
--secrets.postgresql.database_username=breakpad_rw \
--secrets.postgresql.database_password=*********** \
--resource.boto.access_key="**********************" \
--secrets.boto.secret_access_key="*********************" \
--resource.boto.resource_class=socorro.external.boto.connection_context.RegionalS3ConnectionContext \
--resource.boto.bucket_name="org.allizom.crash-stats.rhelmer-test.crashes" \
--resource.postgresql.transaction_executor_class=socorro.database.transaction_executor.TransactionExecutor \
--global.correlations.core.output_class=socorro.external.es.correlations.CoreCounts \ …
```
=> Bug 1249359 store correlations in es

socorro/cron/jobs/ftpscraper.py, socorro/unittest/cron/jobs/test_ftpscraper.py
I ran this a bunch of times before and after. The difference is small. I think it's because the real difference is in the latency between me and that S3 bucket. 
Before it was, on average 1.46 minutes. After it was 1.20 minutes. 
Either way, now you don't get a lot of those warning log messages at least.
=> fixes bug 1261164 - Skip bogus .json files in ftpscraper

socorro/processor/mozilla_processor_2015.py, socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
Added a new transform Rule to the processor to add the abort message to the signature of crashes that have an AbortMessage field. The format is "Abort | <AbortMessage[0:80]> | <C signature>".
cc @KaiRo-at @twobraids
=> Fixes bug 803779 - Added a rule for Abort signatures.

minidump-stackwalk/Makefile
This small change is necessary to build the stackwalker against the latest Breakpad code, which is https://bugzilla.mozilla.org/show_bug.cgi?id=1262135 .
=> Fix stackwalk build against newer Breakpad

scripts/breakpad-taskcluster.sh, scripts/build-breakpad.sh
This is bug 1230659. There are two parts to this:
1) Fix build-breakpad.sh to check Breakpad out of the git repo that is its canonical home nowadays using gclient, since that's how you do it.
2) Add a breakpad-taskcluster.sh script that can be run in Taskcluster that configures the environment properly (needs to download a newer GCC etc) and runs build-breakpad.sh.
I split breakpad-taskcluster out as a separate script because the Socorro build scripts will try to invoke build-breakpad.sh for a local build that's not on Linux, so I figured I'd keep the Taskcluster-specific bits separate.
This isn't going to be set up to run as CI anywhere right now, but at least having a one-click way to get a new build of Breakpad is useful.
r? @lonnen or @rhelmer
=> Modify Breakpad build scripts to build in TaskCluster

scripts/bootstrap.sh
This immediately gets us a newer Breakpad build, and will also
streamline the process for updating Breakpad in the future, since
new runs of the same Taskcluster task will update the index to
point at the most recent build.
@peterbe: this is the better solution I was talking about this morning.
=> Pull the Breakpad tarball from a Taskcluster index

socorro/middleware/search_common.py, socorro/unittest/middleware/test_search_common.py, webapp-django/crashstats/base/tests/test_utils.py, webapp-django/crashstats/base/utils.py, webapp-django/crashstats/signature/views.py, webapp-django/crashstats/supersearch/tests/test_views.py, webapp-django/crashstats/supersearch/views.py
This is quite an important fix. First of all, if you do a `/api/SuperSearch/` query with a future date, instead of getting an error from ElasticSearch about the index not existing, you now get this:
Secondly, when we talk to ES from the webapp, we used to do that via the middleware using `requests.get`. We don't any more. Instead we use the `get_implementation()` and a pure python solution. That means that any errors happening in the implementation will be pure raised exception in the django views where this is used. Note the lack of `try:except:` [here](https://github.com/peterbe/socorro/blob/8e513792f3474b55fcfb16908283f1c5dffc07ba/webapp-django/crashstats/crashstats/models.py#L350).
That means that all the places where we do things like `models.SuperSearch().get(**params)` if anything …
=> fixes bug 1264960 - Super searching for future dates

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
The diff is big. Sorry. But the only real change is how it gathers `install_time` in the view before rendering the template. 
Whilst I was in there I tidied up the tests.
=> fixes bug 1264153 - show install time in report index

scripts/crons/cron_libraries.sh
This adds current aurora and nightly versions as well as all planned beta versions for this cycle, and should land on prod early next week (2016-04-25 or closely after).
Note that once again we need to update the crash-analysis node with that code (and make sure this version of the script is actually being run) to actually make it live. I can actually do that, just need the latest rpm to contain this patch when I should deploy it.
=> Bug 1266400 - Update forced versions for correlations for Firefox cycle starting 2016-04-25

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
We could maybe add to the URL, the `&date=>...&date=<...` like it does on `topcrashers.html` but it feels slightly out of context. What do you think? We'd have to arbitrarily pick today and today minus 7 days.
=> fixes bug 1268043 - "More Reports" link on report index links to old report list

minidump-stackwalk/http_symbol_supplier.cc, minidump-stackwalk/http_symbol_supplier.h, minidump-stackwalk/stackwalker.cc
This will let us link to symbol files from the report page (bug 1184101), which would be useful.
This is mostly just refactoring things to reuse the "build a symbol URL" logic, and then storing the URL the existing SymbolStats struct.
=> bug 1187852 - make stackwalker expose symbol URLs for modules with loaded symbols

webapp-django/crashstats/api/views.py, webapp-django/crashstats/base/ga.py, webapp-django/crashstats/base/tests/test_ga.py, webapp-django/crashstats/crashstats/decorators.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/settings/test.py
CC @adngdb 
To test this manually, I ran this: https://gist.github.com/ccc7d2f3a4329febfd777f4441baa2f0
Then I edited my `.env` like this:
```
GOOGLE_ANALYTICS_API_URL=http://localhost:5000/?timeout=2
GOOGLE_ANALYTICS_DOMAIN=what.ever.org
GOOGLE_ANALYTICS_ID=ANY-THING
```
Things to note;
I'm still not 100% sure what to put for the `cid` value. In `fjord` the `cid` was usually made around a particular Django ORM object. That doesn't really exist in this context. The documentation on `cid` is both vague and clear at the same time. Generally, it's supposed to be like a session ID for the client. That doesn't exist when people do `curl https://crash-stats.m.c/api/SomeModel/` since "curlers" wouldn't re-use a cookie. We could do something like this:
```
cid = request.session.get('ga_cid')
if …
```
=> fixes bug 1126776 - Analytics for the public API

alembic/versions/373ef4569b93_correlations_table.py, socorro/external/postgresql/models.py
This was tricky to make. But I think I figured it out and I have no, in my local psql, a nice looking table. 
Here's how I created it:
```
$ dropdb 
$ createdb socorro_integration_test
$ PYTHONPATH=. python socorro/external/postgresql/setupdb_app.py --database_name=socorro_integration_test --database_username=peterbe --database_password=secret --database_superusername=peterbe --database_superuserpassword=secret
$ alembic -c config/alembic.ini revision --autogenerate -m 'correlations table'
$ jed alembic/versions/373ef4569b93_correlations_table.py
```
=> fixes bug 1267301 - Postgres table for storing correlations

webapp-django/crashstats/crashstats/tests/test_views.py
Oops!
```
:~/dev/MOZILLA/SOCORRO/socorro/webapp-django (eq-not-ok-on-status-code $)$ ggrep ok_ | grep status_code
crashstats/crashstats/tests/test_views.py:753:        ok_(response.status_code, 200)
crashstats/crashstats/tests/test_views.py:765:        ok_(response.status_code, 400)
crashstats/crashstats/tests/test_views.py:773:        ok_(response.status_code, 400)
crashstats/crashstats/tests/test_views.py:782:        ok_(response.status_code, 400)
crashstats/crashstats/tests/test_views.py:791:        ok_(response.status_code, 400)
crashstats/crashstats/tests/test_views.py:1156:        ok_(response.status_code, 302)
crashstats/crashstats/tests/test_views.py:1178:        ok_(response.status_code, 200)
crashstats/crashstats/tests/test_views.py:1313:        ok_(response.status_code, 302) …
```
=> eq not ok on status code

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/topcrashers/tests/test_views.py, webapp-django/crashstats/topcrashers/views.py
I put in a print statement [here](https://github.com/peterbe/socorro/blob/6e89e6ac4dab66c622e1c229780c5f4312d11a5b/socorro/external/postgresql/signature_first_date.py#L19) that said `print "Querying for", len(params['signatures']), "signatures"`. 
Then I opened the Top Crashers for each version of Firefox. Before this patch, it said:
```
Querying for 50 signatures
Querying for 50 signatures
Querying for 50 signatures
Querying for 50 signatures
```
Then, after writing this patch, same thing and this time it printed this out:
```
Querying for 50 signatures
Querying for 47 signatures
Querying for 29 signatures
Querying for 40 signatures
```
In other words, it stops querying PG for signatures' first date if it's already done that for some other version. 
So this patch makes it less SQL select …
=> fixes bug 1269453 - Improve cachability for the first signature dates

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/manage/tests/test_views.py
This is purely stylistic changes. No code or functionality change. 
I just replaced all places where it does things like:
```python
def mocked_get(...):
return Response("""
{"foo": null}
""")
```
...with...:
```python
def mocked_get(...):
return Response({
'foo': None,
})
```
Whilst I was in there I also replaced all (I hope) use of `"` in favor of `'`.
=> bug 1091732 - No Response as JSON strings in crashstats/test_views.py

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/utils.js
This certainly fixes the problem. 
Before this fix, loading [this url](http://socorro.dev/search/?product=Firefox&app_notes=~WGL%2B&_facets=signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature) would insert into the `app_notes` search this value: `WGL`. After this change that value becomes `WGL+`. 
But I suspect this line that I'm removing might be there for a good reason. Some other reason. Perhaps an old reason.
=> fixes bug 1270662 - Supersearch drops special characters from URL

scripts/crons/active-firefox-versions.py, scripts/crons/cron_libraries.sh
cc @KaiRo-at 
@jdotpz The reason I'm asking you for a review is because you're the best at bash and stuff. Also you might need to be aware of what we're trying to do since you're the expert at deploying this script on crash-analysis. 
[First read this](https://bugzilla.mozilla.org/show_bug.cgi?id=1270248#c0)
I've tested this script on the crash-analysis to make sure it works (I just ssh'ed in and pasted the code in vi):
```
[centos@prod-analysis-i-d66ada10 ~]$ vi active-firefox-versions.py
[centos@prod-analysis-i-d66ada10 ~]$ ./active-firefox-versions.py
43.0.4 44.0 44.0.1 44.0.2 45.0 45.0.1 45.0.2 46.0 46.0.1 46.0b 46.0b1 46.0b10 46.0b11 46.0b2 46.0b4 46.0b5 46.0b6 46.0b7 46.0b8 46.0b9 46.0b99 47.0a2 47.0b 47.0b1 47.0b2 48.0a1 48.0a2 49.0a1
```
What I'm not sure about is the execution of …
=> bug 1270248 - Read active versions from the API instead

webapp-django/crashstats/supersearch/static/supersearch/js/socorro/search.js
Seem's jQuery's `$.params({'foo': ['!']})` fails us. It manages to get other characters right. 
See http://codepen.io/peterbe/pen/reovmx?editors=1010
=> fixes bug 1270498 - ! should be URL encoded in the SuperSearch API URL

socorro/external/boto/connection_context.py, socorro/unittest/external/boto/test_connection_context.py, socorro/unittest/external/boto/test_crashstorage.py
This breaks out key building into a separate class allowing us to
specify which keybuilder class to use.
It also creates a new DatePrefixKeyBuilder which will pull the date
portion off the end of a raw_crash ooid and add that to the s3
pseudo-filename before the ooid. This new pseudo-filename form lets us
list all the crashes that came in on a specific date.
Further, it does this in a backwards compatible way by changing
build_key() to build_keys() which returns a list of keys to try in order
of "goodness". That way .fetch() can try the keys in order until it
finds the object in question.
r?
=> Fixes bug 1266827: Add keybuilder class to s3 crash storage [DO NOT MERGE]

webapp-django/crashstats/crashstats/forms.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/bugzilla.js, webapp-django/crashstats/crashstats/tests/test_forms.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
cc @adngdb 
The bug description is pretty extensive. 
The **tl;dr** is that we don't change anything on the outside. Instead, when calling the URL `/buginfo/bug?bugs_ids=123,124,125` that whole request does not get cached. Instead it individually caches `123`, `124` and `125`. 
Also, I refactored it so that with that view, you can't specify the `include_fields` any more. It's hardcoded. It's no longer trying to be a cached proxy to Bugzilla's API. It tries to be smarter than that. 
One cool benefit with this is that we can now write a Pulse consumer (I have a working prototype of this on my laptop) that connects to the same memcache as we use in production. Then it can immediately invalidate the cache so we'd be able to set the cache time to 24h or 7days AND never ever have stale …
=> fixes bug 1272053 - Refactor how we cache individual bug data cache

webapp-django/crashstats/crashstats/management/__init__.py
I'm not letting this git commit close the bug automatically. 
Once this lands we need to run `envconsulstuff ./manage.py migrate` and I'll run this `__init__.py` and make sure the permission exists there.
=> bug 1270487 - New permission to reprocess crashes

webapp-django/crashstats/api/static/api/js/testdrive.js, webapp-django/crashstats/base/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/static/crashstats/js/lib/qs.js, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report_list_graph.js, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/topcrash.js, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/home/static/home/js/home.js, webapp-django/crashstats/settings/bundles.py, webapp-django/crashstats/signature/static/signature/js/signature_report.js, webapp-django/crashstats/signature/static/signature/js/signature_tab.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_reports.js, webapp-django/crashstats/supersearch/static/supersearch/js/socorro/search.js, webapp-django/crashstats/topcrashers/static/topcrashers/js/topcrashers.js
``$.param`` uses the ``+`` sign to encode white spaces. So I added a new library to Socorro, called ``Qs``, to deal with query string creation.
=> Fixes bug 1273538 - Correctly encode white spaces in URLs.

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_views.py
cc @luser 
Adrian, to test this: Do a search [like this](http://socorro.dev/search/?product=Firefox&signature=nsGlobalWindow&_facets=signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#crash-reports) and click on any of the crash IDs. 
Then click on the Modules tab. Some filenames should be links. 
Careful what you click on! These files are HUGE and might make your browser tremble with stress.
=> fixes bug 1184101 - report index modules tab link to symbols

socorro/processor/mozilla_processor_2015.py, socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
Reverts mozilla/socorro#3354
Revert because the feature is not good enough yet, and I don't have time to work on making it perfect now.
=> Revert "Fixes bug 803779 - Added a rule for Abort signatures."

webapp-django/crashstats/supersearch/jinja2/supersearch/search.html
I got tired of having to look at it.
=> bug 1114591 - remove supersearch regex swapping warning

alembic/versions/89ef86a3d57a_extend_missing_symbols.py, socorro/external/postgresql/models.py
Note that this commit does not fix the bug. I just want to make sure the tables (in particular on prod) is updated so when I change the processor rule and the cron job, the columns are there. 
CC @luser
=> bug 1140937 - Change missing symbols cron to include filename and code_id

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
DO NOT MERGE UNTIL PROD ADMIN ALEMBIC MIGRATIONS HAVE BEEN RUN. 
It is my intention to do to prod [what I did to stage](https://bugzilla.mozilla.org/show_bug.cgi?id=1140937#c11) after the next pending prod deployment.
=> bug 1140937 - update missing symbols rule to for code_*

socorro/external/rabbitmq/crashstorage.py, socorro/unittest/external/rabbitmq/test_reprocessing.py, webapp-django/crashstats/api/jinja2/api/documentation.html, webapp-django/crashstats/api/static/api/js/testdrive.js, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/reprocessing.js, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/views.py, webapp-django/crashstats/settings/bundles.py
See:
This is quite a lot a bigger change than I had planned. It's because we don't have any exposed API endpoints that take only POST. So, apart from regular code reviews, here's what you ought to also test. 
First of all, make sure you have run `./manage.py migrate` so that you have the new reprocessing permission. 
Then, go to a report index page. Notice the new Reprocessing tab. It should just work. To trigger the AJAX error state you have to temporarily "mess" with the code or just switch off your django server (so you'd get a http error). 
You should now also be able to reprocess crashes from the command line. E.g.:
```
curl -v -X POST -H "Auth-token: 8b9bfcb0872d4b1881a61e5d7247d617" -d 'crash_ids=9a715a26-02d0-4fe8-856c-4cdcd2160524' -d …
```
=> fixes bug 1275359 - Reprocess from report index page

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1278498#c5 and https://bugzilla.mozilla.org/show_bug.cgi?id=1278498#c7
=> bug 1278498 - don't write to missing_symbols unless debug_id & debug_file

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/supersearch/tests/common.py
This adds a title to each ``<th>`` with the description of the field and the name of that field in Super Search. It also formats numbers a bit better. It removes ``distributor`` and ``distributor_version`` because I think they are deprecated (these fields haven't had a value in a while). 
cc @nnethercote, I hopefully took everything you did in #3360 and added some of the other things you wanted. Note that I moved the descriptions you wrote to our Super Search Fields list on production, you can see that here: http://crash-stats.mozilla.com/api/SuperSearchFields/ If you want to be able to edit those descriptions yourself, you will have to be made a superuser of crash-stats, but considering your involvement with us I think that would make sense. Let's discuss it in London if you're …
=> Fixes bug 1275799 - Added a title with a description of each field in report/index/.

webapp-django/crashstats/base/jinja2/400.html, webapp-django/crashstats/crashstats/middleware.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/home/tests/test_views.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/signature/views.py, webapp-django/crashstats/supersearch/tests/test_views.py, webapp-django/crashstats/topcrashers/tests/test_views.py, webapp-django/crashstats/topcrashers/views.py
Don't ask why I dedicated an hour of my Friday afternoon to this. The short answer was that I was just curious. I wanted to play with the [`handler400`](https://docs.djangoproject.com/en/1.8/ref/urls/#django.conf.urls.handler400) but that's not at all what that's for. :)
Before:
After:
=> fixes bug 889491 - Improve error messages for invalid queries

docs/development/build-from-source.rst, docs/development/webapp.rst
`./manage.py syncdb` doesn't do anything any more. If it does, it's just doing the same as `migrate`.
=> document to only use ./manage.py migrate

socorro/external/postgresql/products.py, socorro/unittest/external/postgresql/test_products.py
My goal is to remove all use of the product_info view. One thing at a time. 
What I did was I just copied the definition of the view into the current query and did some juggling of column names.
=> fixes bug 1280579 - Stop using product_info view in products implementation

webapp-django/package.json
CC @willkg Can you try this branch too in your local django-webapp. 
Pull my branch, then `rm -fr ./node_modules` then `npm install`. 
To test that it works, run `./manage.py collectstatic --noinput --clear` and  also start your `runserver` to make sure that works too. 
What version of node do you have installed? If `<6` does usage of `graceful-fs@>=4` break things?
=> fixes bug 1282582 - Upgrade node packages to support Node v6

socorro/siglists/prefix_signature_re.txt, socorro/siglists/trim_dll_signature_re.txt
relanding this in the order it originally landed.
had to back it out temporarily to rush an infra fix through.
Reverts mozilla/socorro#3386
=> Revert "Revert "Bug 1274345. Add some 64bit dlls to the siglists""

socorro/external/es/supersearch.py
@peterbe Don't ask me why this works, because I have no clue. The current code works for fields like ``accessibility`` but not for ``submitted_from_infobar``, and I do not have the slightest idea as to why. But, I have confirmed in my testing that removing this (unneeded and buggy) line fixed the problem. 
Of course, since I don't understand the problem, I have no idea how to reproduce it in unit tests. :(
=> Fixes bug 1282529 - Removed field name from truthy Elasticsearch operator.

webapp-django/crashstats/authentication/management/commands/migrate-users-csv.py, webapp-django/crashstats/authentication/migration.py, webapp-django/crashstats/authentication/tests/test_migration.py
cc @adngdb 
When we switch from Persona to Google Sign-in, people who used to sign in with `alias@example.com` will no longer be able to do so. They simply HAVE to use `flastname@example.com`. If they used to use `alias@...` their permissions etc would be lost. So we'll "merge" those and transfer all the goodies that `alias@...` had to `flastname@...`. 
The day we switch over from Persona to Google Sign-in we need to generate a CSV file that looks like this:
```
ALIAS,CORRECT
alias@example.com,flastname@example.com
alias2@example.com,flastname2@example.com
aliasN@example.com,flastnameN@example.com
```
Then we need to scp that file into any of the webheads and run this command:
```
$ envconsul -prefix socorro/common -prefix socorro/webapp-django \
./manage.py migrate-alias-users --dry-run …
```
=> Bug 1287548 migrate users by ldap alias email

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/models.py
First load of the home page (or refreshing the page):
Second load of the home page (by click, not reloading):
=> fixes bug 1289833 - Cache-Control on API responses

webapp-django/crashstats/authentication/context_processors.py, webapp-django/crashstats/base/jinja2/crashstats_base.html, webapp-django/crashstats/crashstats/tests/test_views.py
This just avoids the exception happening in the context processor if there's ever a `WSGIRequest` object that doesn't have a `user` attribute. 
I still don't know how that could happen but it's easy to write a test for at least.
=> bug 1283285 - careful with request.user in context processor

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/base/jinja2/crashstats_base.html, webapp-django/crashstats/crashstats/decorators.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/utils.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/views.py, webapp-django/crashstats/profile/tests/test_views.py, webapp-django/crashstats/profile/views.py, webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py, webapp-django/crashstats/tokens/tests/test_views.py, webapp-django/crashstats/tokens/views.py
I know this one is huge but it's actually really simple. Lemme explain:
* `request.user.is_active` is better than `request.user.is_authenticated` when you want to decide if the user should be given something. If an anonymous user makes a request, django automatically sets `request.user = AnonymousUser()`. That user is [always `is_active=False`](https://github.com/django/django/blob/master/django/contrib/auth/models.py#L386) so by using `request.user.is_active` you're asking two questions at the same time. "Is the user  authenticated?" (I.e. does the user have a session cookie) AND "Is the user active?". 
* Some places we were using `django.contrib.auth.decorators.login_required` and that one relies only on `request.user.is_authenticated()`. I made a new one, with the only difference that …
=> fixes bug 1289196 - observe user.is_active

socorro/cron/jobs/ftpscraper.py
Firefox 48.0 dropped android-api-9, and 46.0 changed api-11 to api-15, so look for those when scraping. 
We may have been mis-identifying crashes - eg https://crash-stats.mozilla.com/report/index/b8b4676f-64af-497f-84c2-73e0f2160804 is '48.0 fennec on release', but report a buildID of 20160727164219 instead of 20160726133114. Meanwhile other crashes are fine - eg https://crash-stats.mozilla.com/report/index/99f5e6ce-f435-4e09-8953-baa122160804
=> Update platforms for Android

socorro/external/postgresql/bugs.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py
Now you can type multiple bug IDs and if you type some non-integer junk it doesn't barf. 
On prod you can only pass in one bug ID. The other ones are ignored:
=> fixes bug 1292143 - Bad escape on bug_ids to SignaturesByBug

webapp-django/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html
@peterbe this doesn't break layout for me locally, using stage data. Does it for you? I think that's what we want to do anyway. It's simple and solves the problem. I don't think we care too much if sometimes the data overflows to the right.
=> Fixes bug 1290326 - Do not truncate signatures in Topcrashers.

requirements.txt
I reduced the requirements.txt file for socorrolib to just the
requirements that it needs. The requirements.txt file is sourced as
install dependencies by setup.py. Because of this, it'll be tricky to
update dependencies that socorrolib doesn't actually use in this
repository.
This updates to the latest version of socorrolib.
r?
=> Bug 1292235 update socorrolib to 0.2.3

socorro/external/boto/connection_context.py, socorro/unittest/external/boto/test_connection_context.py
Implements boto HostPortS3ConnectionContext so that we can connect to a local fake s3. This will make it easier to do development work without requiring that we have S3 buckets and a network connection.
r?
=> 1295206 boto fakes3

socorro/collector/collector_app.py, socorro/collector/wsgi_breakpad_collector.py, socorro/collector/wsgi_generic_collector.py, socorro/external/metrics_base.py, socorro/external/statsd/dogstatsd.py, socorro/external/statsd/metrics.py, socorro/unittest/collector/test_collector_app.py, socorro/unittest/collector/test_wsgi_breakpad_collector.py, socorro/unittest/external/statsd/test_metrics.py, socorro/unittest/external/test_metrics_base.py
This creates a new kind of external component called Metrics. It gets used in the breakpad collector after saving the crash to log data about the incoming crash at the point we've collected it.
r?
=> Bug 1293776 initial pass on StatsdMetrics

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/settings/test.py
@adngdb ,
what's neat about this is that you can now have memcache in your `.env` (or leave it out and let it be the default from `settings/base.py`) so that when you do a lot of runserver work it's able to cache things after runserver restarts.
=> fixes bug 1297684 - force LocMemCache in tests

webapp-django/crashstats/crashstats/static/crashstats/css/screen.less
google SSI injects a small iframe that is absolutely positioned and causes a 4 px high box to appear below the sticky footer. This removes it from display and prevents a vertical scroll from showing up.
=> nobug -- hide the injected google iFrame

webapp-django/crashstats/crashstats/static/crashstats/css/screen.less
removes the earlier attempt to use min-height and replaces it with a flexbox based approach that ensures the footer appears either below the content or at the bottom of the page
My local env is hosed so this needs a little extra testing. I've checked this change against the main page and search page using dev tools. If something is broken it will not be subtle -- after landing, load the main page, search, topcrasher, daily, report list, and report index to check. You may want to use devtools to remove a div panel or two in order to make room.
Before:
After:
=> fixes bug 1298969

socorro/processor/signature_utilities.py
Some linux crashes are crashing in RunWatchdog without calling it from or otherwise including the '::' operator in the frame, so these crashes are not triggering the appropriate processor rule.
This fixes it by removing the '::' requirement from the predicate. There are no Firefox crashes in super search at the time of this writing that will be adversely caught by this -- it should catch the same crashes as the previous rule plus the missing reports.
We may need to reprocess after this. Check the bug.
=> fixes bug 1290967

webapp-django/crashstats/supersearch/form_fields.py, webapp-django/crashstats/supersearch/tests/test_form_fields.py
I'm not super familiar with this code but I think I have a decent solution. It's decent because it's not hard coded specifically to "date" values.
Basically, if you have multiple prefixed values, each and every value is compared and checks that the operator function for each makes sense.
=> fixes bug 1296208 - super search error when dates are illogical

webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py, webapp-django/crashstats/crashstats/utils.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/signature/views.py, webapp-django/crashstats/supersearch/form_fields.py
I wrote the test before I wrote the `.encode()` fix.
=> fixes bug 1300921 - TypError on time_tag() with unicode

scripts/build-breakpad.sh
This enhances the breakpad script with some prechecks so that the breakpad make target will successfully run idempotently. Additionally it fixes some shellcheck warnings.
=> nobug - make breakpad build idempotent

webapp-django/crashstats/crashstats/decorators.py, webapp-django/crashstats/crashstats/jinja2/crashstats/login.html, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/oauth2.js, webapp-django/crashstats/manage/decorators.py, webapp-django/crashstats/manage/tests/test_views.py, webapp-django/crashstats/manage/views.py
The two major changes here are:
1) The oauth2.js code now seeks out a `?next=/some/url` if available and redirects to that instead of doing `document.location.reload()`.
2) The `superuser_required` decorator is rewritten. One of the reasons we wrote our our (a long time ago) was to do two things: A) check that you're signed in AND superuser and B) if you're not a superuser store a flash message. By instead using the well-tested one in django.contrib.auth.dectorators we get the `?next=/admin/` for example when you try to access a superuser protected view. However the flash message is lost but the login page already has a message for those who are signed in but not allowed all the way in.
=> fixes bug 1283296 - Redirect back after sign-in

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
The commit adds a new "How to read this crash report" link. It also
changes the existing link from "Search Mozilla Support for Help" to
"Search Mozilla Support for this signature".
=> Fixes bug 1290329 with a new link

socorro/schemas/crash_report.json
They're always strings. They're strings that contain numbers. 
See https://github.com/mozilla/socorro/blob/3877c90cfcbf3e12ca031321959a1964b0b9efe0/minidump-stackwalk/stackwalker.cc#L760-L761 and https://github.com/mozilla/socorro/blob/3877c90cfcbf3e12ca031321959a1964b0b9efe0/minidump-stackwalk/stackwalker.cc#L122
=> fixes bug 1294088 - JSON Schema ambiguous types on certain keys

webapp-django/crashstats/crashstats/static/crashstats/css/report_index.css
=> fixes bug 1290329 - add spacing between sumo links on report index

socorro/external/boto/crashstorage.py
The default value of `configman.dotdict.DotDict` broke processing, because configman DotDict cannot be JSON-serialized. The DotDict object from socorrolib is a very simple extension of the default dict type, so it is what we should use for our crash documents.
=> Fixes bug 1303250 - Use a JSON-serializable DotDict object.

webapp-django/crashstats/settings/base.py, webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
I know this is probably pretty hard to test but here's what I did...
1) I have this in my `.env`
```
AWS_ACCESS_KEY=...secret...
AWS_SECRET_ACCESS_KEY=...secret...
SYMBOLS_BUCKET_DEFAULT_LOCATION=us-west-2
#SYMBOLS_BUCKET_DEFAULT_NAME=peterbe-crash-stats-symbols
SYMBOLS_BUCKET_DEFAULT_NAME=peterbe.crash.stats.symbols
```
2) Tried to upload a .zip file and got this error:
```
CertificateError: hostname 'peterbe.crash.stats.symbols.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```
3) Applied the patch and uploaded again now now it worked!
Once this PR lands there shouldn't be anything we need to do in config.
=> fixes bug 1306048 - ability to connect to S3 by region for symbol upload

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_views.py
Here's an attempt. I'm pretty sure this line is not going to fly:
```
<p><a href="{{ '../../api/UnredactedCrash/?crash_id=' + report.uuid }}">{{ '/api/UnredactedCrash/?crash_id=' + report.uuid }}</a></p>
```
It works, but I figure this should probably be done in views.py. I tried to do it there but couldn't work out how to -- the raw dump URLs are done with calls like `reverse('crashstats:raw_data', args=(crash_id, 'dmp'))` which I don't understand.
=> Fixes bug 1304289 by add a link to the unredacted crash.

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/urls.py, webapp-django/crashstats/crashstats/views.py
Here's how to test it:
Make a search like this: https://crash-stats.allizom.org/search/?contains_memory_report=%21__null__&product=Firefox&_sort=-date&_facets=signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature
Click on one of the crash IDs and load the Raw Dumps tab. There should NOT be a third link at the bottom of that tab until after you've signed in. 
When you sign in and try again it should present you with a third link at looks something like this: `/rawdumps/7e99cdee-6148-4ae5-a5bc-81b9c2160915-memory_report.json.gz`
When you click it, it should make you save the file. Save it. Then then go to `about:memory` and click the "Load..." button. Should work.
=> fixes bug 1061371 - UI to download memory file from crash reports

socorro/external/boto/connection_context.py, socorro/unittest/external/boto/test_connection_context.py
Here's why I'm confident this works (and is necessary!):
```
>>> conn = boto.s3.connect_to_region('us-west-2', aws_access_key_id='AKI....)  # personal credentials
>>> bucket = conn.create_bucket('peterbe-test-bucket-delete-me')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/boto/s3/connection.py", line 590, in create_bucket
response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>IllegalLocationConstraintException</Code><Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.</Message><RequestId>18E674025CAD633F</RequestId><HostId>m9B9tQ1 …
```
=> fixes bug 1296008 - Create bucket with region

webapp-django/crashstats/supersearch/jinja2/supersearch/search.html
Here's a screenshot showing the new "A guide to searching crash reports" button.
=> Fixes bug 1306208 by adding a link to the MDN search docs.

webapp-django/crashstats/supersearch/static/supersearch/js/socorro/date_filters.js, webapp-django/crashstats/topcrashers/views.py
@peterbe Alright, I've got this! ``moment`` is actually a pretty good library to deal with these timezone problems, it just took me some time to find the right functions to use. 
So now, if a date has no timezone, UTC is used. If a date has a timezone, that timezone is used to convert the date to UTC. That is dealt with in the ``datetime_filters`` component directly, when dealing with dates from the URL. 
I also kept the topcrashers's timezone-aware date change, because it's better, but it is not needed to fix the problem.
=> Fixes bug 1281540 - Ensure dates are UTC in links to signature report.

socorro/external/crashstorage_base.py, socorro/unittest/external/test_crashstorage_base.py
The cool thing is that I now have a fully functional local processor. 
It is configured to run that S3TelemetryCrashStorage as its nth class and that means it runs AFTER the `ESCrashStorageRedactedJsonDump` class. 
Then I run the processor, and it does upload two json files. Both contain the full `json_dump` thing. Also, I load ES to see what was stored there:
As you can see, it's the redacted `json_dump` key.
=> Bug 1296621 let polycrashstorage process cloned objects each time

webapp-django/crashstats/base/jinja2/400.html, webapp-django/crashstats/base/jinja2/404.html, webapp-django/crashstats/base/jinja2/500.html, webapp-django/crashstats/base/jinja2/crashstats_base.html, webapp-django/crashstats/base/jinja2/error.html, webapp-django/crashstats/base/jinja2/footer_nav.html, webapp-django/crashstats/base/jinja2/header_title.html, webapp-django/crashstats/base/static/js/error.js, webapp-django/crashstats/base/views.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/settings/bundles.py, webapp-django/crashstats/urls.py
Check the [bug description](https://bugzilla.mozilla.org/show_bug.cgi?id=1303853#c0).
This patch totally simplifies how error template rendering happens. Now crashstats_base.html is left to healthy requests. No more subtle errors during rendering the `500.html`. 
To test this, make sure you have `DEBUG=False` and `DEBUG_PROPAGATE_EXCEPTIONS=False` and to trigger the `DisallowedHost` I use my nginx but under a domain that Django was not allowing. See:
I also checked that it continues to work for other errors:
Page Not Found:
Bad Request:
(note how I messed with the `date_end` parameter in the URL)
JSON errors still work as expected:
SuperSearch errors still work:
It also continues to work when I put in a temporary `raise NameError('test!')` in one of the view functions:
=> fixes bug 1303853 - Error templates depend on request

webapp-django/crashstats/symbols/jinja2/symbols/api_upload.html, webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
cc @luser 
Sorry that this is a bit messy Adrian. I even had to put in html comments. 
There are a bunch of difference states but ultimately this PR is about being able to visit `http://socorro.dev/symbols/upload/api/` without being signed in. That way the documentation can be available for people who have an auth token but just aren't signed in on the webapp. 
Beyond that, there are states that try to guide the user. 
1. You're signed in but haven't generated a API Token valid for symbol uploads
2. You have an API Token valid for symbol uploads
3. You're signed in but don't even have permission to generate an API Token for the necessary permission.
=> fixes bug 1137376 - symbols upload page public

webapp-django/crashstats/crashstats/jinja2/crashstats/crashes_per_day.html, webapp-django/crashstats/crashstats/jinja2/crashstats/daily.html, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/crashes_per_day.js, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/daily.js, webapp-django/crashstats/signature/jinja2/signature/signature_report.html, webapp-django/crashstats/signature/static/signature/js/signature_report.js, webapp-django/crashstats/signature/static/signature/js/signature_tab.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_aggregations.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_graph.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_graphs.js, webapp-django/crashstats/signature/static/signature/js/signature_tab_reports.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1305807 is about trying to get rid of ALL `<script>` tags. I got started and did the Crashes per user and the Signature report. 
I think there's more yet to be done but I didn't want the PR to get too big. So let's start with this. 
The commits don't close the bug automatically but I'll close this branch with this to start.
=> Bug 1305807 remove inline scripts in crashes per user

docs/production-install.rst
We create the RPM on a build box using a local install of Python
2.7.11 so the socorro-virtualenv/ that gets created points to Python
libs that don't exist on a standard CentOS install.
This adds a warning about that and a link to the bug in question. This
is a stopgap until it gets fixed.
This is a docs change, so quick r?
=> Add warning about how production RPM is broken

webapp-django/crashstats/tokens/jinja2/tokens/home.html
This might not solve it. But perhaps. 
It's not valid HTML to have an empty `action` attribute like that. Don't know if that's what's causing the browser to do weird things like submitting the form. Kinda reminds me of how it was dangerous to generate HTML like this `<img src="" ...>` because some browsers thought it would be a valid URL and crazy things could happen. 
Also, the form is always going to be there. It's never non-existent. If you're signed in, with or without any permissions, you can use the form to generate tokens.
=> bug 1309266 - API Tokens form going nuts

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
@lonnen this is more of a political decision than a code one, so I'm asking you for review.
=> Fixes bug 1305616 - Stop storing memory_report into Elasticsearch.

socorro/processor/breakpad_transform_rules.py
This way, you don't get a big fat python exception to worry about when it's nothing to worry about. 
Also, the performance of doing `os.path.isfile(some_path)` is probably a billion times faster than all other the bigger I/O bound operations that happen inside the processor.
=> fixes bug 1306022 - don't include traceback if it's not a problem

webapp-django/crashstats/authentication/jinja2/auth/login_failure.html, webapp-django/crashstats/base/jinja2/footer_nav.html, webapp-django/crashstats/crashstats/context_processors.py, webapp-django/crashstats/crashstats/jinja2/crashstats/login.html, webapp-django/crashstats/settings/base.py
No matter how I tried, it always looked so untidy and misaligned when the link was there in the right-hand lower corner. 
Considering that a large majority of people don't struggle with Google Sign-In, I think it's better to put it on the left with the other footer links.
=> fixes bug 1309731 - link to Google Auth wiki page

webapp-django/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html, webapp-django/crashstats/topcrashers/static/topcrashers/js/topcrashers.js
Apart from some minor jshint fixes, I did refactor how the `all_signatures` variable worked. I thought it was race condition problem in how jquery executes it's `always` promise. Turns out, that wasn't a problem but I wasn't testing it correctly. However, I decided this is better. 
It used to do this:
```javascript
var all_signatures = {}
function loadajax(callback) {
$.ajax(...)
.done(function(result) {
all_signatures = result
})
.always(function() {
callback(all_signatures)
})
}
function otherfunction() {
...do something with global all_signatures...
}
loadajax(otherfunction)
```
Instead it's like this now:
```javascript
//var all_signatures = {}
function loadajax(callback) {
$.ajax(...)
.done(function(result) {
all_signatures = result
callback(all_signatures)
})
}
function …
```
=> bug 1305807 - remove inline scripts in topcrashers

e2e-tests/README.md, e2e-tests/pages/base_page.py, e2e-tests/pages/crash_report_page.py, e2e-tests/pages/crash_stats_nightly_builds_page.py, e2e-tests/pages/crash_stats_per_day.py, e2e-tests/pages/crash_stats_top_crashers_by_site_page.py, e2e-tests/pages/crash_stats_top_crashers_page.py, e2e-tests/pages/home_page.py, e2e-tests/pages/super_search_page.py, e2e-tests/pages/uuid_report.py, e2e-tests/pages/version.py, e2e-tests/requirements.txt, e2e-tests/setup.cfg, e2e-tests/tests/conftest.py, e2e-tests/tests/test_crash_reports.py, e2e-tests/tests/test_layout.py, e2e-tests/tests/test_search.py, e2e-tests/tests/test_smoke_tests.py
Initial move of the end-to-end functional tests out of QA's repo and into the project repo.
-- Oct 10 --
Adding a few more requirements - thanks @peterbe for the meeting today -
> Let's merge this once the tests pass or skip
=> Move e2e tests into Socorro's project repo

socorro/siglists/prefix_signature_re.txt
Like https://bugzilla.mozilla.org/show_bug.cgi?id=1308795, there is no vcruntime140.dll symbol into socorro now.  So we should add it to prefix skiplist.
When we used old vc, we add MSVCRT120.DLL to skiplist by https://bugzilla.mozilla.org/show_bug.cgi?id=1161067.
=> Bug 1308824 - add vcruntime140.dll to skiplist

webapp-django/crashstats/profile/jinja2/profile/profile.html, webapp-django/crashstats/profile/static/profile/js/profile.js, webapp-django/crashstats/settings/bundles.py
That file was conflicting with our timeutils.js file, causing an error in the parsing of crash reports dates.
=> Fixes bug 1304108 - Removed unneeded JS file for the profile page.

e2e-tests/README.md
See https://webqa-ci.mozilla.com/view/Socorro/ - we renamed those jobs and dropped ".saucelabs" since nearly everything uses it, so is now implied.
=> Remove ".saucelabs" from build/job URLs

socorro/cron/jobs/featured_versions_automatic.py, socorro/unittest/cron/jobs/test_featured_versions_automatic.py
I appreciate this is a bit hard to test manually. But I've done it. Perhaps you can simply trust me with the manual testing.
Here's what I did:
```
$ pg_dump -p 5433 -h localhost -U breakpad_rw -a -t product_versions -t products  breakpad  > /tmp/stagedbstuff.sql
$ psql socorro_integration_test < /tmp/stagedbstuff.sql
```
Now, I have in my local PG a bunch of realistic `product_versions` data. 
Then I run crontabber like this:
```
$ python socorro/cron/crontabber_app.py --admin.conf=../local-crontabber.ini 
```
In my `../local-crontabber.ini` the postgres credentials are set up to point to my local `socorro_integration_test` database. And the last couple of lines of that ini file are these:
```
jobs='''
#socorro.cron.jobs.bugzilla.BugzillaCronApp|1d …
```
=> bug 1260420 - set featured versions by product-defails.m.o

socorro/external/crashstorage_base.py, socorro/unittest/external/test_crashstorage_base.py
I feel like I totally stressed through this. Lots of things going on today. 
This PR adds a test that does break unless you apply the fix. 
Also, this change does make the whole processor work. I've tested it by making the the crash gets sent in correctly (to my personal AWS S3 bucket). 
Let's get this to prod soon.
=> fixes bug 1311697 - deep copy SocorroDotDict better

socorro/processor/processor_app.py, socorro/unittest/processor/test_processor_app.py
I've tested this quite extensively. E.g.
https://sentry.prod.mozaws.net/operations/socorro-stage/issues/362120/
https://sentry.prod.mozaws.net/operations/socorro-stage/issues/362112/
The crucial part is the new lines inside `processor_app.py`. 
The most important thing is how the exception is juggled. 
If anything goes wrong in any of the crashstoage classes, the processor collects all exceptions into an instance of a `PolyStorageError`. That's why it's important to loop over over this. It might be more than 1 exception. If you don't do this iteration **iff** it's a an error inside one of the crashstorage classes you get errors in Sentry like this: https://sentry.prod.mozaws.net/operations/socorro-stage/issues/362043/ (scroll down and look at the "Exception".
And because it might NOT be a …
=> bug 1231783 - Send all processor errors to sentry

webapp-django/crashstats/base/ga.py, webapp-django/crashstats/base/tests/test_ga.py
Certificate verification is failing. We debated several options (details
in the bug) and then decided to set verify_ssl=False for this specific
call. Because we're doing that, we nixed all possible PII, too.
r?
=> Fixes bug 1305129: GA ssl handshake fix

webapp-django/crashstats/base/context_processors.py, webapp-django/crashstats/base/ga.py, webapp-django/crashstats/base/jinja2/crashstats_base.html, webapp-django/crashstats/crashstats/pipelinecompilers.py, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/google_analytics.js, webapp-django/crashstats/crashstats/tests/test_pipelinecompilers.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/settings/bundles.py, webapp-django/crashstats/settings/test.py
I don't know how much you know about Google Analytics. 
I had to do a bunch of research myself. Perhaps it's good if you have to do some research of your own to check that I'm doing the right thing. 
The most important change here is that the GA ID is now super hardcoded. 
Yes, it spells trouble for other companies that tries to use our webapp, but does that even exist any more? And also, GA will filter out any traffic that comes from domains not recognized in GA Admin. 
I did the same for Air Mozilla (which uses the non-360 GA still), because it's just not realistic that someone will run that site under a different domain. https://github.com/mozilla/airmozilla/blob/master/airmozilla/base/static/js/google-analytics.js#L2
=> bug 1305807 - move google analytics to not be inline

socorro/external/crashstorage_base.py
**tl;dr here's the executive summary of my measurements...**
```
____OLD_WAY____
time per uuid 0.252148882035
____NEW_WAY____
time per uuid 0.170331147409
average time just to make the pure dict copy 0.0462440675305
```
I took 31 random uuids, instrumented some `t0=time.time(); do_something(); t1=time.time()` in the master branch. Ran a bunch of processing and dumped all the measurements to a file. 
Then I wrote this new code, and put time measurements again. This time I had to do one measurement for making the pure dict first and 3 measurements for each cloning. 
See, 31 uuids --> 3x31=93 measurements. And with the new way, 31+3x31=124. 
It's promising. This small sample indicates that it'll be ~30% faster this new way just for this "region" of the code. In other words, processing won't …
=> fixes bug 1313676 - Optimize how crashes are cloned in processor

webapp-django/bin/bootstrap.sh, webapp-django/crashstats/settings/base.py
@willkg I honestly don't know how this script gets executed. Ideally, I'd like for it to be executed with the usual `env consul -prefix ....` stuff but I don't know where that happens and @jdotpz is on PTO today. 
I'm hopeful that this fix will unbreak our broken Google Analytics in stage and prod.
=> bug 1314258 - run './manage.py collectstatic' with env vars

socorro/collector/wsgi_breakpad_collector.py, socorro/unittest/collector/test_wsgi_breakpad_collector.py
The dogstatsd client uses the defaults (localhost and 8125 and no key
prefix), so that's why it's ignoring the key prefix we assigned.
I could fix that code, but that would affect all the metrics. Instead,
I'm manually adding the prefix.
=> Bug 1293776: Fix prefix

alembic/versions/5bafdc19756c_drop_server_status_table.py
There is no mention of this view being defined. It might be a lurking relic from the extreme dark olden times. 
I dare not attempt to run this on the stage DB because then it won't test that this migration actually works when it gets applied on stage. 
There might be other views that lurk. 
Here's a list of all views we have:
```
breakpad=> select table_name from INFORMATION_SCHEMA.views WHERE table_schema = ANY (current_schemas(false));
table_name
----------------------------
crashes_by_user_build_view
crashes_by_user_rollup
crashes_by_user_view
current_server_status
product_info
default_versions
default_versions_builds
home_page_graph_build_view
home_page_graph_view
index_bloat
performance_check_1
product_crash_ratio
product_os_crash_ratio
product_selector
(14 rows)
```
So I did some …
=> fixes bug 1300367 - remove view current_server_status too

socorro/external/es/supersearch.py, socorro/unittest/external/es/base.py, socorro/unittest/external/es/test_supersearch.py
Fixes a bug with the way Super Search manages fields. A field that had no namespace (ie. that is in the root of the crash document) became `.field` instead of `field`, thus preventing any filtering or aggregating on it.
=> Fixes bug 1316144 - Allow querying root fields in Super Search.

socorro/cron/jobs/upload_crash_report_json_schema.py, socorro/schemas/__init__.py, socorro/schemas/crash_report.json, socorro/unittest/cron/jobs/test_upload_crash_report_json_schema.py
Here's how I configured it when running locally:
```
[[class-UploadCrashReportJSONSchemaCronApp]]
bucket_name=peterbe-crash-stats-telemetry
access_key=AKIA...
secret_access_key=SECRETYSECRET
```
I'm pretty sure we run crontabber with `socorro/common` as a prefix should it should automatically pick up the access_key and secret_access_key but I'm not so sure about the `bucket_name`. The only place this is elsewhere written down is for that `[[storage3]]` or whatever it's called in processor's crashstorage list. 
I'll update the bug with the necessary consulate instructions that I think we need.
=> bug 1312006 - Upload crash_reports.json to S3

.pep8, requirements.txt, socorro/external/postgresql/crashstorage.py, socorro/processor/legacy_processor.py, socorro/unittest/external/rabbitmq/test_priorityjobs.py, socorro/unittest/lib/test_converters.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/settings/bundles.py, webapp-django/crashstats/signature/tests/test_views.py
Killing a couple of birds here. 
There are still lots of pep8 errors in `./socorro/` but at least none of the exceptions we made are a problem. 
Also, I took the opportunity to upgrade all the libs related to flake8 and that uncovered some important fails we had on dicts.
=> fixes bug 1131253 - Stop ignoring certain PEP8 exceptions

socorro/external/crashstorage_base.py, socorro/external/es/crashstorage.py, socorro/unittest/external/test_crashstorage_base.py
This changes the PolyCrashStorage code such that it only does a deep
copy of the processed crash if the crash storage says it mutates the
crash data.
Currently, we have 5 crash storage classes configured in production.
This change will reduce the number of deepcopies we're doing from 5 to
1.
r?
=> Fixes bug 1318448: reduces deepcopies we do in the processor

socorro/external/crashstorage_base.py
The StatsdCounter is a duck-typed crash storage so it doesn't have an
is_mutator().
So what we're saying now is "if the crash storage has an is_mutator and
that returns True, then deepcopy". The underlying assumption is that
crash storages without an is_mutator aren't mutating the crash data.
=> Fix is_mutator() call

minidump-stackwalk/stackwalker.cc
To be serialized ...
This was crashing for us in sprintf on Linux (not on Mac weirdly).
```
#include <limits>
#include <iostream>
int main()
{
std::cout << std::numeric_limits<uint64_t>::max() << std::endl;
return 0;
}
./a.out | wc -c
21
```
=> A large uint64_t can take more than 17 chars

socorro/external/es/supersearch.py, socorro/unittest/external/es/test_supersearch.py
Any larger number than this is likely to be too resource intensive.
=> fixes bug 1295212 - cap facet size

webapp-django/crashstats/api/views.py
I just don't think it's feasible that we'd want to disable the public API any more.
=> fixes bug 1105349 - Remove app_api_all waffle flag

socorro/siglists/irrelevant_signature_re.txt, socorro/siglists/prefix_signature_re.txt
For a crash stack trace like this:
> mozalloc_abort
> abort
> __rust_start_panic
> std::panicking::rust_panic_with_hook::hc303199e04562edf
> std::panicking::begin_panic::h6ed03353807cf54d
> std::panicking::begin_panic_fmt::hc321cece241bb2f5
> core::panicking::panic_fmt::h27224b181f9f037f
> core::panicking::panic_bounds_check::h19e9bbc59320a57e
> rust_url_capi::rusturl_get_path
> mozilla::net::nsStandardURL::GetPath
this commit will change the crash signature from this:
> [@ mozalloc_abort | abort | __rust_start_panic ]
to this:
> [@ mozalloc_abort | abort | __rust_start_panic | rust_url_capi::rusturl_get_path ]]
=> Fixes bug 1319298 - Handle some rust functions in signature generation.

webapp-django/crashstats/settings/base.py, webapp-django/crashstats/tokens/utils.py
@willkg I don't know how environmentally equipped you are to review and test this. 
Testing is actually kinda messy. Enabled the raven DSN we use for socorro-stage. Then I put in a temporary `raise` and tested it with:
```
curl -H "Auth-token: e85659f64c734013a39df04a74a716b4" http://socorro.dev/api/UploadedSymbols/\?end_date\=2016-11-29\&start_date\=2016-11-01
```
(note token, it just for my laptop)
Here's what it looks like:
https://sentry.prod.mozaws.net/operations/socorro-stage/issues/370785/
The most important change is that now the `Auth-Token` is scrubbed.
=> Auth-Token and raven

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
Now it looks like this:
At first I thought this a bit ugly and we should instead re-render with error messages in the form. 
However, that's [not what we do with any other form validation errors](https://github.com/mozilla/socorro/blob/7a0329ba25ee2c306f783cf4484fbaa7d2a3387f/webapp-django/crashstats/crashstats/views.py#L700).
=> fixes bug 1321367 - BadArgumentError in Crashes per Day on bad date

webapp-django/crashstats/crashstats/views.py
The change is small but important. What it does now is that instead, by default, it selects NO platforms. I.e. the 3 checkboxes are not checked. Only if you select one, does the platform parameter go to supersearch. 
This solves the problem for platforms like FennecAndroid that has no crashes under either Windows, Mac OS X or Linux.
=> fixes bug 1319483 - ignore platform if not selective

webapp-django/crashstats/base/jinja2/crashstats_base.html, webapp-django/crashstats/status/context_processors.py
Now, when I do `curl http://socorro.dev/monitoring/healthcheck/?elb=true` it doesn't need to do any SQL queries.
=> fixes bug 1322615 - Don't look for status messages in JSON endpoints

webapp-django/crashstats/base/jinja2/macros/pagination.html
Now the search result page is only ~300KB instead of ~700KB each time. 
(Only applicable when there's a LOT of pages possible)
=> fixes bug 1323314 - Excessive whitespace from pagination.html

webapp-django/crashstats/settings/base.py, webapp-django/crashstats/topcrashers/forms.py, webapp-django/crashstats/topcrashers/tests/test_views.py, webapp-django/crashstats/topcrashers/views.py
=> fixes bug 1323123 - unable to switch result size in top crasher

webapp-django/crashstats/manage/jinja2/manage/analyze-model-fetches.html, webapp-django/crashstats/manage/views.py
This makes it easier to see what % we get. 
Looks like this:
=> bug 1308218 - track cache hits percentage

webapp-django/crashstats/api/views.py
=> fixes bug 1321324 - UnicodeEncodeError on handling 400 errors

socorro/external/es/supersearch.py, socorro/unittest/external/es/test_supersearch.py
I first thought I could validate the input early in the webapp but when I saw [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#time-units) and decided it's too risky to get it right. Better to ask for forgiveness than "seek permission". 
Here's what you get now:
=> fixes bug 1323235 - Validate input on _histogram_interval.date

socorro/external/boto/connection_context.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/symbols/tests/test_views.py, webapp-django/crashstats/symbols/views.py
boto supports IAM roles as long as no keys are passed when creating connections. This works in my v254 deployment for S3 crash storage and symbol uploads from EC2 instances with IAM role that has S3 access. I patched rpm install instead of building from source though, but I think this covers everything.
=> unblocking support for AWS IAM roles instead of hardcoding access keys

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/correlation.js
The problem is due to rounding, when you have a value smaller than 0.1 but really close to it.
=> Bug 1330275 - Fix alignment issue with some correlation results

socorro/processor/rules/memory_report_extraction.py, socorro/unittest/processor/rules/memory_reports/good.json, socorro/unittest/processor/rules/test_memory_report_extraction.py
The new measurements are: gfx-textures, host-object-urls, heap-overhead,
images, js-main-runtime.
@adngdb, @EricRahm: please review!
=> Fixes bug 1330819 - Extract more measurements from memory reports.

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
Local testing indicates that this code works, but there's some funny stuff going on due to the dash vs. underscore issue that @adngdb fixed recently in #3664.
This is an example of a crash report where all 16 fields are displayed when this new code is running:
http://localhost:8000/report/index/c012f28b-cc09-48ba-9cfd-1e6c32170202
But the tooltips only work for 5 of the fields: explicit, images, private, resident, vsize. These happen to be the fields that do not contain a dash/underscore!
And this is an example of a crash report where only those 5 fields are displayed:
http://localhost:8000/report/index/1d882d32-39a1-42d7-b24d-841262170202
Most of the crash reports I've looked at are like this. In fact, I've only found one crash report where all 16 fields are displayed.
@adngdb, any ideas …
=> Bug 1291173 - Show key measurements from the memory report for each crash report.

scripts/breakpad-taskcluster.sh, scripts/build-breakpad.sh
This fixes local builds that don't use the Breakpad snapshot because
upstream Breakpad made a breaking API change.
=> Pin the revision of Breakpad to build in build-breakpad.sh to the revision used in the snapshot.

socorro/siglists/prefix_signature_re.txt
In [bug 1338574](https://bugzilla.mozilla.org/show_bug.cgi?id=1338574) I'm adding two new variants of MOZ_CRASH, each with its own function. IIUC, these need to be added to the prefix signature list so we don't group all crashes utilizing these functions together. See also [bug 1341035](https://bugzilla.mozilla.org/show_bug.cgi?id=1341035).
=> Add MOZ_CrashOOL and MOZ_CrashPrintf to the prefix signature list

e2e-tests/Jenkinsfile, e2e-tests/tox.ini
This patch enables publishing of structured logs from the e2e tests to ActiveData, which will allow us to track results over time and help us to identify tests that need attention.
=> Submit e2e test results to ActiveData

e2e-tests/tox.ini
pytest-metadata has a 1.2.0 release, today: https://pyup.io/changelogs/pytest-metadata/
@willkg r?  and a merge when/if you r+?  Thanks!
=> Bump pytest-metadata

socorro/schemas/crash_report.json
This undoes https://github.com/mozilla/socorro/commit/5559de74654697828dd4cceba6b0cd8130150102#diff-82e3b30a9c5737b0a5e278a3d095bf27 and https://github.com/mozilla/socorro/commit/543cbc06659b7bf3796d43575c3f2452e5475a13#diff-82e3b30a9c5737b0a5e278a3d095bf27
=> fixes bug 1343619 - Revert crash_reports.json to state BEFORE Feb 2017

e2e-tests/tox.ini
@willkg r?
Build-passing output, below:
```
Started by user Stephen Donner
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/stephendonner/socorro.git
> /usr/local/git/bin/git init /var/lib/jenkins/jobs/socorro.adhoc/workspace@script # timeout=10
Fetching upstream changes from https://github.com/stephendonner/socorro.git
> /usr/local/git/bin/git --version # timeout=10
Setting http proxy: proxy.dmz.scl3.mozilla.com:3128
> /usr/local/git/bin/git fetch --tags --progress https://github.com/stephendonner/socorro.git +refs/heads/*:refs/remotes/origin/*
> /usr/local/git/bin/git config remote.origin.url https://github.com/stephendonner/socorro.git # timeout=10
> /usr/local/git/bin/git config --add remote.origin.fetch …
```
=> Update to latest e2e dependency versions

socorro/schemas/validate_and_test.py
It works!
```
▶ python socorro/schemas/validate_and_test.py
socorro/schemas/crash_report.json is a valid JSON schema
Fetching data...
https://crash-stats.mozilla.com/api/SuperSearchFields/
Testing 100 random recent crash reports
https://crash-stats.mozilla.com/api/RawCrash/?crash_id=60935f48-8d17-485c-a8e7-232ae2170222
https://crash-stats.mozilla.com/api/ProcessedCrash/?crash_id=60935f48-8d17-485c-a8e7-232ae2170222
Traceback (most recent call last):
File "socorro/schemas/validate_and_test.py", line 79, in <module>
main()
File "socorro/schemas/validate_and_test.py", line 73, in main
jsonschema.validate(processor.combined, schema)
File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/jsonschema/validators.py", line 478, in validate
cls(schema, *args, …
```
=> fixes bug 1343623 - validate_and_test.py should test more realistically

socorro/schemas/README.md, socorro/schemas/validate_and_test.py
I've tried it locally with a bunch of queries and it seems to work. 
One thing to look out for, the default number of hits returned by the SuperSearch API is 100. So if you paste in 5 URLs that all yield lots of hits, you're going to be testing the JSON Schema against 500 crashes. 
CC @adngdb
=> fixes bug 1344217 - let validate_and_test.py accept Super Search queries

webapp-django/crashstats/signature/jinja2/signature/signature_summary.html, webapp-django/crashstats/signature/static/signature/css/signature_report.less, webapp-django/crashstats/signature/static/signature/js/signature_tab.js
This uses the column-count CSS property to display inner panels in columns, thus leading to a better use of white space when there are long results. It also reorders summary panels to keep the same display order than now.
Assigned to @lonnen for he is the Grand Master of UI.
=> Fixes bug 1345504 - Made better use of space in Signature report.

e2e-tests/Jenkinsfile
(Sadly, needed due to a change in Pipeline Model/plugins.)
@davehunt @willkg @m8ttyB ?
=> Pass in 'xterm' to ansiColor()

e2e-tests/Jenkinsfile
@willkg / @davehunt @m8ttyB r?
Passing ad-hoc build here: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/socorro.adhoc/35/console
See https://issues.jenkins-ci.org/browse/JENKINS-42857
=> Reformat PYTEST_ADDOPTS args, due to Jenkins issue

scripts/crons/crontabber.sh
[The `lock` function](https://github.com/mozilla/socorro/blob/master/scripts/crons/socorrorc#L16) is used in other `.sh` files that I doubt we use but I'd rather deal with that separately.
=> bug 1341755 - don't bash lock crontabber

e2e-tests/tests/test_crash_reports.py
As discussed in the team meeting today, Seamonkey has been chosen for deprecation. @stephendonner identified several failing e2e tests in the test suite.
* https://bugzilla.mozilla.org/show_bug.cgi?id=1349763
* https://bugzilla.mozilla.org/show_bug.cgi?id=1349766
We decided to remove Seamonkey checks from these effected testcases.
=> remove Seamonkey from crashreport tests

socorro/external/http/crashstorage.py
poster.encode wants to seek through the file provided to find its length, StringIO provides full file-like interface.
You can see the code that caused problems here:
https://bitbucket.org/chrisatlee/poster/src/97d3c6fcb87785d1838549301f0092dec4229abf/poster/encode.py?at=default&fileviewer=file-view-default#encode.py-116
=> Replace DumpReader with StringIO

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/supersearch/tests/test_views.py, webapp-django/crashstats/topcrashers/tests/test_views.py
I know this looks like a lot but it's not. 
It's a leftover legacy from when we switched from mocking the middleware to implementations. I also did some cleaning up for stuff that was made global and didn't need to be. 
Sooo much less mocking now.
=> fixes bug 1352440 - Cleanup old use of mocking

webapp-django/crashstats/manage/forms.py, webapp-django/crashstats/manage/tests/test_views.py
I looked the docs and there appears to be no way to use meta fields to override `required` for ModelForm classes. 
https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/#overriding-the-default-fields
=> fixes bug 1353482 - Create 0-permission API tokens in admin

webapp-django/crashstats/base/jinja2/crashstats_base.html, webapp-django/crashstats/base/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/home/tests/test_views.py, webapp-django/crashstats/home/views.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/topcrashers/tests/test_views.py, webapp-django/crashstats/topcrashers/views.py
This basically makes the home page, Top Crashers, Crashes Per Day work again if the product *has* active versions but *no featured* versions.
=> fixes bug 1352385 - Use active versions if 0 featured versions

webapp-django/crashstats/settings/base.py
Assuming we don't use flash, java and other plugins, we shouldn't run them at all even from our origin.
Our CSP object-src currently falls back to the default-src of 'self' allowing clients to run plugins from our origin. 
This PR locks things down further to prevent plugin execution in the unlikely event that someone can inject object/embed html and upload a plugin to our domain.
=> Add object-src 'none' to CSP

scripts/breakpad-taskcluster.sh
The breakpad-taskcluster script was pulling whatever version of GCC is in use by the tip of mozilla-central, which is currently GCC 4.9.x. Unfortunately the rest of Socorro's automation is building with an older version, and it doesn't properly link the static libs produced by that compiler.
[This is the latest Breakpad build](https://tools.taskcluster.net/task-inspector/#YtM2cNnHQ16_A53PgDsGYQ/0) I triggered using these changes. It should have automatically updated the taskcluster index that we pull the Breakpad tarball from, so hopefully the Travis build will succeed.
Also, while I was there I changed the example task in the script to be YAML instead of JSON, because the Taskcluster task-creator tool accepts YAML now.
=> Fix Breakpad build in taskcluster by using a slightly-older GCC.

e2e-tests/tox.ini
@willkg @m8ttyB r?
Passing build here, against staging: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/socorro.adhoc/20/console
(Ignore, if you will, the failing S3-publishing portion, due to the limitation of the environment where this ad-hoc test build was run.)
Full console log here: https://gist.github.com/stephendonner/7227687c29d114b1fb9e007e43b11147
=> Update test requirements

e2e-tests/tests/test_api.py
cc @willkg @m8ttyB 
Another SeaMonkey thing. Thus I'm not going to scrutinize this problem too much. 
I do see SeaMonkey crashes coming in to stage. But none of the recent ones come from any of *active* SeaMonkey versions.
=> fixes bug 1356571 - ignore version checking on certain products

webapp-django/crashstats/crashstats/models.py
This is removing the public facing API endpoint. In a few weeks, once we know for sure that removing it didn't break anything, I'll remove the underlying implementation.
=> Fixes bug 1351706 - Removed GCCrashes public API endpoint.

webapp-django/crashstats/base/utils.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/tests/test_views.py
CC @willkg 
Check out the new `requests_retry_session()` function. I think it can be useful. In particular because bugzilla can be quite flaky. 
If you do it like this, it'll retry on even making a connection which is akin or our web head not having a reliable network. 
Also, I tested this code by running it in a little test file, with decent backoff, whilst my WiFi was switched off. Then, whilst it was sitting there, I turned on the WiFi and, voila, got a 200 OK eventually. 
So, with 3 retries (connection errors) the worst that can happen is that it takes 0.3+0.6+1.2=2.1 seconds. And if it keeps timing out, it'll take a total of 5+0.3+5+0.6+5+1.2=17.1 seconds. But that's very unlikely to happen because timeouts are not systemic, unlike broken DNS or 500 errors.
=> fixes bug 1357159 - Stop using SocorroCommon.fetch for bugzilla API

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
Assuming you're using stage data, open https://crash-stats.allizom.org/report/index/c7c20b2e-ad32-487a-9363-fa5080170414 locally and see that it breaks before applying this PR. 
CC @willkg  if you're curious.
=> fixes bug 1357536 - UnicodeEncodeErrors on broken raw crashes

e2e-tests/Jenkinsfile, e2e-tests/tox.ini
@willkg  / @davehunt r?
Will, Dave put up a blog post about why he/we are doing so, in http://davehunt.co.uk/2017/04/10/reporting-test-results-to-treeherder
We probably shouldn't merge this until we figure out and fix (here) or ask for "socorro-tests" to be a recognized (and perhaps unique?) name in Treeherder.
Right now, "socorro" submits to Treeherder, itself, which is pretty cool:
https://treeherder.mozilla.org/#/jobs?repo=socorro
=> Submit to Treeherder; bump shared-library version

e2e-tests/Jenkinsfile
@davehunt @willkg r?  Now that the Jenkins issue is fixed, we can restore our originally intended formatting style, for readability.
Adhoc has one (unrelated) failure: https://fx-test-jenkins-dev.stage.mozaws.net:8443/view/Web/job/socorro.adhoc/28/console, which also exists on master: https://fx-test-jenkins-dev.stage.mozaws.net:8443/view/Web/job/socorro.adhoc/30/console
=> Restore original PYTEST_ADDOPTS formatting

socorro/processor/mozilla_processor_2015.py, socorro/processor/rules/addons_rewrite.py, socorro/unittest/processor/rules/test_addons_rewrite.py
The addons field as it is now is not very useful for aggregating and searching, as it is a list of mixed ids and versions. We thus want to change it so that ids and versions are associated. For example, ["aaa", "12", "bcd", 1] would become ["aaa:12", "bcd:1"].
@marco-c What do you think about that new format? Is that going to work fine in Telemetry?
=> DO NOT MERGE: Fixes bug 1250132 - Added a Rule to rewrite addons.

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
The addons field as it is now is not very useful for aggregating and searching, as it is a list of mixed ids and versions. We thus want to change it so that ids and versions are associated. For example, ["aaa", "12", "bcd", 1] would become ["aaa:12", "bcd:1"].
=> Fixes bug 1250132 - Changed the Addons generation rule.

socorro/lib/transform_rules.py, socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
The change to the addons field format in bug 1250132 broke the ThemePrettyNameRule rule. This commit makes that rule use the current format.
=> Fixes bug 1362061 - Use actual new addons format in ThemePrettyNameRule.

e2e-tests/tox.ini
Changelog is here, FWIW: https://github.com/davehunt/pytest-metadata/commit/9eb23a5f48d105ead2b0f0cfbdd7cabee0a4aa21
Ad-hoc run (passing): https://gist.github.com/stephendonner/781e346b7356dec7625894a5fbeba81a
r?
=> Bump pytest-metadata to 1.4.0

webapp-django/crashstats/base/utils.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py
I didn't bother writing a test because then we'd have to mock urllib3 from within the requests vendor package. 
I've tried a similar solution on my songsear.ch for many weeks and it's been great.
=> fixes bug 1362371 - Don't assume BZAPI always works

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_views.py
This displays the optional "thread_name" property from the json dump
generated by the stackwalker in the crashing stack header.
Example: <h2> Thread 3, Name: Timer</h2>
=> Fixes bug 1361308 - Display thread names of the crashing stacks.

README.rst, docs/index.rst
We should point at a tag for the last known good release rather than a single
commit sha. This fixes that.
r?
=> Change commit sha to a tag

socorro/lib/transform_rules.py, socorro/processor/processor_2015.py, socorro/unittest/lib/test_transform_rules.py
So this PR just tackles *one* problem. It injects itself in every `._predidate(...)` and `._action(...)` call. Only. 
In [processor_2015.py it does a loop and calls .act() on every rule in a set](https://github.com/mozilla/socorro/blob/fc6841672e8179cd6721a52cdc1a34d233338bf2/socorro/processor/processor_2015.py#L231-L236).
I *could* inject this sentry code in the `Rule.act` method (which is overwritten in `TransformRule.act` by the way) but I don't think that's safe. 
I actually wanted to be very defensive here. I didn't want to mess too much which how the whole rule act of predicate and action works. What I just try to do is stop swallowing real Python exceptions whenever a `_predicate` or `_action` is called on **any** rule. 
Who knows. There could be some rule where exceptions is …
=> bug 1362434 - send processor exceptions to sentry

socorro/processor/breakpad_transform_rules.py, socorro/unittest/processor/test_breakpad_transform_rules.py
The JitCrashCategorizeRule assumed a crashing_thread was always present in the json_dump, and that turned out not to always be true. We want to verify that there is one before running the rule.
=> Fixes bug 1362125 - Fixed KeyError in JitCrashCategorizeRule.

socorro/unittest/external/es/base.py, socorro/unittest/external/es/test_supersearch.py
This fixes two things about the elasticsearch tests:
1. reduces errors due to the cluster not being ready
2. fixes a test that assumed the cluster was at localhost:9200 which it might
not be
=> Fix elasticsearch tests

socorro/external/postgresql/server_status.py, socorro/unittest/external/postgresql/test_crash_data.py, socorro/unittest/external/postgresql/test_server_status.py
The postgresql server_status test stomped would overwrite two files, run the
test, and then delete the files altogether. This fixes that behavior by mocking
out the "read the file from disk" function so we're still testing the code
itself, but not stomping on the files in question.
There was another postgresql test that had the database host, username, and
password hardcoded. This changes those to use the relevant environment
variables.
=> Fix postgresql tests

scripts/defaults, scripts/test.sh, socorro/unittest/external/fs/test_fsdatedradixtreestorage.py, socorro/unittest/external/fs/test_fslegacydatedradixtreestorage.py, socorro/unittest/external/fs/test_fsradixtreestorage.py
The filesystem tests were modifying crash data in ./crashes. These code changes
add a resource.fs.fs_root environment variable and fix a bunch of tests that
were generating their own configuration to use it.
=> Fix filesystem tests

e2e-tests/tox.ini
We've been running with 2.14.x for a couple days now, across the rest of our Web-testing suites without issue.  Changelog here: http://docs.python-requests.org/en/latest/community/updates/#id3
Full passing run against staging, here: https://gist.github.com/stephendonner/572ef96548fd31b9d186b55264dc061f
@willkg / @m8ttyB r?
=> Upgrade 'requests' to latest version

socorro/siglists/prefix_signature_re.txt
Adding Clear() and the dtor are enough to split the crashes in different protocols into separate signatures.
=> Bug 1364193 - Add MessageChannel::Clear to the skip list

socorro/siglists/prefix_signature_re.txt
This fixes [bug 1364982](https://bugzilla.mozilla.org/show_bug.cgi?id=1364982).
=> Bug 1364982 - Add mozilla::detail::nsStringRepr::{First,Last} to prefix signature list

socorro/external/crashstorage_base.py, socorro/external/es/crashstorage.py, socorro/unittest/external/es/base.py, socorro/unittest/external/es/test_crashstorage.py
The raw_crash nowadays contain a key called "StackTraces" that contains a pretty big string. Storing it in Elasticsearch has a pretty high cost in terms of disk space and memory. This thus adds a new redactor, specifically made for the raw_crash, that we want to use every time we send a crash to Elasticsearch.
@willkg this is quite opinionated, and I would like to know what you think about a few things in here. 
1. This means we will deepcopy the raw_crash as well as the processed_crash for every crash we process (only once, though, since the ES crashstorage is the only one that mutates crashes).
2. This means we modify the raw_crash, which is something we want to avoid, but in this case I don't think there's anyway around it (other than asking the Firefox team to not send that data in …
=> Fixes bug 1362048 - Redacted away StackTraces from raw_crash in ES.

Makefile, docker-compose.yml, docker/Dockerfile, docker/Dockerfile.processor, docker/Dockerfile.webapp
This nixes building the test service since it uses the same image as the webapp
service.
This pulls the redundant parts from building the processor and webapp images
into a base image and reorders some things to make that more convenient.
The end result is that it went from taking 15 minutes to 8 minutes to do "make
dockerbuild" on my local machine. I suspect/hope CircleCI gets similar results.
If this isn't sufficient, then I think future gains are going to be harder since
we'll need to reduce individual steps and I'm not sure what's left to cut/slim
down.
=> Fixes bug 1366046 - speed up "make dockerbuild"

docker/set_up_stackwalk.sh
It's possible for a developer to have build artifacts from building stackwalk on
their host machine which won't work when building in the container. This fixes
the script to delete build artifacts before building.
=> Fixes bug 1367071 - delete build artifacts before building

e2e-tests/tox.ini
(As per usual, keeping these up-to-date along with our other Web-automation projects.)
@willkg fancy an r?
```Started by user Stephen Donner
Checking out git ${REPOSITORY} to read e2e-tests/Jenkinsfile
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/stephendonner/socorro.git
> /usr/bin/git init /var/lib/jenkins/jobs/socorro.adhoc/workspace@script # timeout=10
Fetching upstream changes from https://github.com/stephendonner/socorro.git
> /usr/bin/git --version # timeout=10
> /usr/bin/git fetch --tags --progress https://github.com/stephendonner/socorro.git +refs/heads/*:refs/remotes/origin/*
> /usr/bin/git config remote.origin.url https://github.com/stephendonner/socorro.git # timeout=10
> /usr/bin/git config --add remote.origin.fetch …
```
=> Update pytest, pytest-metadata, and selenium to latest

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
In order to make queries easier, we want to ensure that all addons have the same format of addon_identifier:addon_version. We thus add a placeholder version to addons that miss it, to make things consistent.
=> Fixes bug 1363712 - Use a placeholder in addons without version.

Makefile, docker/README.rst, docker/run_tests_in_docker.sh
This improves the test infrastructure in docker for development. It adds a
"dockertestshell" make rule which sets up the docker environment with the repo
directory mounted in the container and then starts a shell. With this,
developers can run individual tests and also pass in different arguments to the
test runners.
This also documents all that in the docker README.
=> Fixes bug 1368698 - Improve tests infrastructure for dev

alembic/versions/a5e0f0bc87d6_removed_foreign_key_between_bug_.py, socorro/cron/jobs/bugzilla.py, socorro/external/postgresql/models.py, socorro/unittest/cron/jobs/test_bugzilla.py
This makes the bugzilla cron job stop writing any data into the bugs table. It also removes the foreign key from bug_associations to bugs in a migration, which is needed for the cron job to keep working.
=> Fixes bug 1368498 - Do not use bugs table in bugzilla cron job.

docker/run_tests_in_docker.sh
When you run "make dockertest" it copies the contents of the repository
directory into /app in a data container and then runs the tests in that. The
problem is that it doesn't remove files that have been removed.
This fixes the script to remove all the files in /app and then copy the files
from the repository directory into /app. In this way, it better handles files
that have been removed.
=> Fix "make dockertest" to sync files better

socorro/cron/jobs/bugzilla.py, socorro/unittest/cron/jobs/test_bugzilla.py
This query used to be a very long, hand-written URL, using the old bugzilla query system that returned CSV data. With this, it now uses the REST API instead, manipulating JSON data with the requests library. The query is much simpler to read and has only the few arguments it actually needs. Also, the query is not configurable anymore, because that option was never used and it would have made the code less maintainable.
=> Fixes bug 1370484 - Refactored bugzilla query to use REST API and JSON.

requirements.txt, socorro/app/socorro_app.py, socorro/external/es/crashstorage.py, socorro/unittest/app/test_socorro_app.py, socorro/unittest/external/es/base.py, socorro/unittest/external/es/test_crashstorage.py, webapp-django/crashstats/crashstats/models.py
I had to implement a new metrics infrastructure before I could do anything. But I think that's good in the long run. We can probably retire a bunch of the statsd stuff we've got now and add more granular metrics capture to relevant parts.
The metrics infrastructure degrades to logging metrics data if statsd isn't set up. This re-uses existing statsd configuration keys, so theoretically, it should just work without requiring configuration changes.
r?
=> Fixes bug 1372999 - add document size metrics for elasticsearch crashstorage

socorro/app/socorro_app.py
The LoggerWrapper didn't have a .exception() method. It's a handy shortcut
that's used in a bazillion places and if Socorro is going to wrap Logger, it
should mimic it properly.
r?
=> Add a proper exception to LoggerWrapper

socorro/app/socorro_app.py
This fixes the configman options for statsd_host and statsd_port so they look in
the right place for values.
r?
=> Fixes bug 1372999 - fix statsd host/port configuration

socorro/external/postgresql/staticdata.py
This should prevent fresh socorro installation from wrong state of
report_partition_info table.
Think this relates Bug 1123742.
=> Fixed missing_symbols partition creation

socorro/app/fetch_transform_save_app.py, socorro/cron/buildutil.py, socorro/database/cachedIdAccess.py, socorro/database/database.py, socorro/database/transaction_executor.py, socorro/external/boto/crashstorage.py, socorro/external/crashstorage_base.py, socorro/external/es/index_creator.py, socorro/external/es/query.py, socorro/external/es/super_search_fields.py, socorro/external/es/supersearch.py, socorro/external/fs/filesystem.py, socorro/external/postgresql/base.py, socorro/external/postgresql/crashstorage.py, socorro/external/postgresql/dbapi2_util.py, socorro/external/postgresql/postgresqlalchemymanager.py, socorro/lib/transform_rules.py, socorro/lib/util.py, socorro/lib/ver_tools.py, socorro/processor/breakpad_transform_rules.py, socorro/processor/hybrid_processor.py, socorro/processor/legacy_processor.py, socorro/processor/mozilla_processor_2015.py, socorro/processor/processor_app.py, socorro/processor/signature_utilities.py, socorro/processor/skunk_classifiers.py, socorro/processor/support_classifiers.py, socorro/unittest/external/test_crashstorage_base.py
This fixes instances of `except Exception, e` (deprecated syntax) to `except Exception as e` (correct syntax and the only one supported by Python 3).
https://docs.python.org/3.0/whatsnew/3.0.html#changed-syntax
https://www.python.org/dev/peps/pep-3110/
There are a couple of other fixes that accidentally pop in, too.
r?
=> Fix instances of "except Exception, e" and some other things

docker/config/processor.env
The value we use in -prod is the empty string. This fixes a bad value that came
about from the way I pulled the -prod configuration to generate the
configuration files.
=> Fix boto prefix configuration value

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/reprocessing.js, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
@luser is going to like this! Mind you, it's only applicable on a "per report index page" basis. 
The honest truth is that just because you press that "Reload this page without cache" link and load it again, it will ignore our memcache but the crash might not have been processed yet.
=> fixes bug 1376913 - Refresh the report index page after reprocessing

docs/howto.rst, docs/index.rst
This fixes one of the options in the toctree declaration such that the docs
build a toctree.
It also fixes a syntax error and caps the number of levels in the toctree.
=> Bug 1373997 - fixes toctree issue

socorro/external/es/data/super_search_fields.json
Before I forget, I found something odd whilst doing this. 
I compared the output of https://crash-stats.mozilla.com/api/SuperSearchFields/ with the contents of `socorro/external/es/data/super_search_fields.json` and found that, beyond `telemetry_environment` there was 1 more field that was only in the prod SuperSearchFields: `dump`. It looks like this::
```
{
"default_value": null,
"is_mandatory": false,
"form_field_type": "StringField",
"has_full_version": false,
"query_type": "string",
"permissions_needed": [],
"storage_mapping": {
"index": "not_analyzed",
"type": "string"
},
"namespace": "processed_crash",
"description": "",
"is_returned": false,
"in_database_name": "dump",
"data_validation_type": "str",
"is_exposed": false,
"form_field_choices": [],
"name": "dump"
}
```
Should that …
=> fixes bug 1379662 - add TelemetryEnvironment to super_search_fields.json

socorro/unittest/cron/jobs/test_bugzilla.py, socorro/unittest/cron/jobs/test_drop_old_partitions.py, socorro/unittest/cron/jobs/test_featured_versions_automatic.py, socorro/unittest/cron/jobs/test_ftpscraper.py, socorro/unittest/cron/jobs/test_matviews.py
No output is good:
```
▶ flake8 socorro/unittest/cron/jobs
▶ flake8 socorro/cron/jobs
```
=> bug 1377254 - pep8 all crontabber apps

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/static/crashstats/css/tree.css, webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/settings/bundles.py
CC @adngdb @lonnen 
Looks like this:
I'm not convinced this is the best way to display the data. The advantage is that it's simple. You can ⌘-F and find what you're looking for. 
Another alternative is to use the JSON syntax highlighter we use in the SuperSearch documentation:
Then you can still use ⌘-F. 
At least it's there. 
But the PR lacks tests (since I'm not sure the work is ideal yet).
Another feature we could consider is one of those jQuery plugins (they all look kinda icky) where you can click little plus and minuses.
=> fixes bug 1379665 - Telemetry tab on report index

socorro/processor/mozilla_processor_2015.py, socorro/processor/mozilla_transform_rules.py
This rule kicks up a KeyError if the raw crash is missing the keys it checks. I
went to fix that, but then noticed there are no tests for this rule and it's to
fix a situation that was a problem over 2 years ago. I don't think this is
relevant anymore.
Given that, this removes the rule altogether.
=> fixes bug 1382505 - remove FennecBetaError20150430 rule

socorro/processor/general_transform_rules.py, socorro/unittest/processor/test_general_transform_rules.py
Minor changes to the code so that it always uses getitem notation and switched out `eq_` for assert.
After that, I fixed `json_dump` access to use `.get()` and default to `{}`.
That fixes the specific issue in the bug.
=> 1382506 json dump

webapp-django/crashstats/base/finders.py, webapp-django/crashstats/base/tests/test_finders.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/settings/bundles.py
The way I tested this was to edit `bundles.py` and insert some junk on any of the `source_filenames` tuples. Then running `rm -fr static && ./manage.py collectstatic --noinput` it would fail. 
Also, if you run in `DEBUG=True` mode and first `rm -fr static`, then pipeline will do these lookups on the fly during render and if you've messed with `bundles.py` you get errors like this:
```
Traceback (most recent call last):
File "/opt/boxen/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
self.result = application(self.environ, self.start_response)
File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
return self.application(environ, …
```
=> fixes bug 1382781 - test asset generation doesn't miss source files

webapp-django/crashstats/settings/base.py
It's bothered me for too long. Couldn't stand to see it any longer.
=> fixes bug 1383950 - webapp project is always called crashstats

socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
* reduce some extra lines
* convert the things that were using attribute notation to getitem notation
* clean up data structure set up in the tests
* convert tests to use {} instead of DotDict for all non-config things
Cleaning up this code now will make the PR when I move signature stuff around for a cli a lot easier since there will be fewer things that are changing.
At some point, we might start using a lib for easier deep-item access in trees, but that's still on the drawing board and I want to move forward on cli signature generation now.
r?
=> bug 1383113 - convert signature rules to getitem notation

socorro/processor/signature_utilities.py, socorro/unittest/processor/test_signature_utilities.py
If the condition is a dict with a "name" key, then this worked fine. However,
Socorro would occasionally see conditions that were just strings.
This fixes the rule behavior to work with strings as well.
=> fixes bug 1385962 - Handle AsyncShutdownTimeout string conditions

webapp-django/crashstats/manage/jinja2/manage/supersearch_fields_missing.html
I wanted to do more but decided not to. 
Once ES5 is ready, we're going to **re-land** https://github.com/mozilla-services/socorro/pull/3854/files#diff-c6eb45ff84ef342b75c7ca9e0a9ddf36 and thus I don't want to make it more complicated by introducing a merge conflict. 
Once this lands, at least the crazy horizontal scrolling will go away
See note in bug what else can/should be done.
=> bug 1386234 - hide junk missing supersearchfields keys

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/static/crashstats/css/report_index.css
Before:
After:
Other keys that contain other crazy unicode characters is probably best to just leave as is. 
Note; this doesn't so much to do with "unicode junk". It just makes it so that any key that becomes visually longer than 250 pixels gets truncated.
=> fixes bug 1386237 - Display "junk" field keys better in report index

webapp-django/crashstats/tokens/forms.py, webapp-django/crashstats/tokens/tests/test_views.py
The choice of 2,000 chars is quite arbitrary. 
The risk of this bug is low. But anybody can sign in and create API tokens to their hearts content. However, they can't create them with permissions unless the user's permissions are elevated.
So if a rogue user bombards this field it could fill up unnecessarily.
=> fixes bug 1379705 - length restriction on token notes field

socorro/unittest/processor/__init__.py, socorro/unittest/processor/rules/test_memory_report_extraction.py, socorro/unittest/processor/test_signature_utilities.py, socorro/unittest/processor/test_skunk_classifiers.py, socorro/unittest/processor/test_support_classifiers.py
We had this function in three different places and one of those instances was
slightly different than the other two. Seems like it helps to have a centralized
"fake processor" configuration that is used everywhere.
This centralizes that code and updates the other files to use it.
=> Clean up create_basic_fake_processor definitions and usage

Makefile, docker/config/docker_common.env, docker/config/processor.env, docker/run_setup_postgres.sh, scripts/socorro, socorro/external/postgresql/setupdb_app.py
This moves the alembic_config to docker_common.env so it's available in both the
processor and webapp containers.
This adds a urlwait to docker/run_setup_postgres.sh to force it to wait for
postgres db to be ready for connections before trying to setup tables and run
migrations.
This moves the database name to a variable that exists already so it's not
hard-coded.
This removes the code in setupdb_app that prevents logging lines from happening
because that makes understanding what happened and debugging it much much
harder.
=> fixes bug 1386781 - fix issues in run_setup_postgres.sh

webapp-django/crashstats/supersearch/form_fields.py, webapp-django/crashstats/supersearch/tests/test_form_fields.py
Go to any signature report and add `&accessibility=föö` or something. Or just look at the new unit test :)
By the way, that whole `to_python` didn't have any test coverage at all before.
=> fixes bug 1388333 - UnicodeEncodeError in signature report

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/correlation.js
CC @marco-c 
First of all, this PR is two commits. The first one interesting, the second one just some ESLint cleanups. 
The big change is that the report index page has been erroring ever since I [landed this](https://github.com/mozilla-services/socorro/commit/b27f15d85c9abbc63ce2e30e0d8f693f7cf65d2f).
Now, I'm failing forward by instead making the list of channels be a list of 1 item and it's the channel that the individual crash belongs to. 
So if the crash you're looking at is one that belongs to Firefox Beta it only display correlations based on that channel.
=> Bug 1388419 correlations js errors on report index

socorro/cron/crontabber_app.py
This syncs the crontabber.jobs value that we have in -prod with DEFAULT_JOBS
enabling us to run all the jobs we're running in -prod in local dev
environments.
=> bug 1388130 - copy -prod crontabber jobs to DEFAULT_JOBS

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
Not a vert important feature but I wanted to test something that had been bugging me for ages. Turns out it's a 4 year old bug. 
Basically, now the list of related bugs is a tab of its own instead of a little blurb after the list of basic crash Details.
=> fixes bug 974972 - Make Bug list on report/index more visible

docker/run_update_release_data.sh, docs/gettingstarted.rst, socorro/cron/jobs/ftpscraper.py, socorro/external/postgresql/postgresqlalchemymanager.py, socorro/external/postgresql/staticdata.py
This adds lookup table data population and documented run lines that add release
data to the db. These make it possible to go to
http://localhost:8000/home/product/Firefox and have it mostly work.
Note that this only pulls release data for Firefox. Each additional product
takes another like 10 minutes to run. The thinking is that we're primarily
working on Firefox crashes, so if someone needs release data for something else,
they can adjust the scripts accordingly. If we need to make that more flexible,
we can make that change later.
=> bug 1387100 - improve webapp in dev environment

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
This adds a pass to remove bad keys from the raw_crash part of the document
before indexing it into Elasticsearch.
Good keys contain one or more ascii alpha-numeric characters plus underscore and
hyphen. Everything else is invalid and gets removed.
=> fixes bug 1382727 - remove bad keys from ES documents

docker/fetch_normalization_data.py, docker/run_update_release_data.sh
This adds a script to fetch normalization data. It has to run after we've run ftpscraper, so I stuck it in the `run_update_release_data.sh`. I'm thinking at some point, we'll want to rename that script, but I don't have better ideas at the moment.
This PR lets us do the following:
1. run `make dockersetup`
2. run `docker-compose run processor docker/run_update_release_data.sh`
3. now the adi url endpoint will work for localhost:8000
=> Add script to fetch normalization data

bin/build_env.py, docker/config/crontabber.env, docker/config/processor.env, docker/config/webapp.env, docker/run_crontabber.sh, docker/run_processor.sh, docker/run_webapp.sh
This redoes how behavior configuration works. Previously, docker-compose would
inject the behavior configuration into the docker container environment. It can
do this because it's being run in a working directory that has the socorro code
in it, so the necessary env files exist *outside* the container it's running.
When we go to run these containers in a server environment or any environment
where you don't have the socorro repo as the working directory, then the
behavior configuration needs to be pulled in from *inside* the container.
This fixes the run_ scripts so that if an indicator flag isn't in the
environment, it pulls the appropriate env file in and executes the component in
the new environment with the behavior configuration.
=> fixes bug 1389218 - redo behavior configuration in docker environment

socorro/cron/jobs/ftpscraper.py
Found this low hanging fruit. Today, about 10% of the URLs going through `download` cause a 404.
=> avoid unnecessary 404s when finding candidate builds

bin/activate_socorro, bin/socorro_env.sh, socorro/scripts/add_crashid_to_queue.py
This adds a socorro_env script that launches bash in a modified environment with
the Python virtual environment activated and with all the configuration loaded.
This makes running Socorro scripts much easier.
So instead of:
```
$ . /data/socorro/socorro-virtualenv/bin/activate
$ envconsul -prefix some/nonsense mycmd
$ envconsul -prefix some/nonsense someothercmd
```
You can do:
```
$ /data/socorro/bin/socorro_env.sh
(socorro) $ mycmd
(socorro) $ someothercmd
```
=> Add socorro_env script

docs/components/crashstorage.rst, docs/components/crontabber.rst, docs/components/processor.rst, docs/components/webapp.rst, docs/gettingstarted.rst
I made some changes based on Jonathan's suggestions. The big issue was that the
documentation about running "make dockerupdatedata" was after the link sending
you off to the webapp documentation, so he missed it. This fixes that flow and
adds some more details which are probably helpful to know.
=> Update and clean up some getting started docs

docker/Dockerfile.processor, docker/run_socorro_aws.sh, docker/set_up_awscli.sh, scripts/socorro_aws_s3.sh
* add awscli to the processor in a place where it shouldn't affect anything
* create socorro_aws_s3.sh script and friends that wrap aws by pulling
configuration out of the environment making it easier to use
The end result of this is that we can copy files into and out of the s3
container, see what's in there, manipulate buckets, and so on.
=> bug 1388449 - add socorro_aws_s3.sh script

socorro/external/es/data/super_search_fields.json
The winsock_lsp field is being indexed using the keyword analyzer. That's fine,
except this field value is pretty big and exceeds the maximum size.
This changes that to ignore any values larger than 30000 in size.
=>  fixes bug 1381877 - ignore winsock_lsp gt 30000

socorro/external/es/data/super_search_fields.json
How I tested this:
```
docker/as_me.sh scripts/fetch_crash_data.py ./samplecrashdata 20e25952-7271-44da-8e0a-816260170815
docker/as_me.sh scripts/socorro_aws_s3.sh mb s3://dev_bucket/
docker/as_me.sh scripts/socorro_aws_s3.sh sync ./samplecrashdata s3://dev_bucket/
docker-compose run processor scripts/add_crashid_to_queue.py socorro.normal 20e25952-7271-44da-8e0a-816260170815
docker-compose up webapp
open http://localhost:8000/report/index/20e25952-7271-44da-8e0a-816260170815#tab-metadata
```
And the fields are there even though I'm not signed in. Meaning, they're displayed in that table because they're in the super search fields.
=> Bug 1390880 add accessibilityinprocclient and accessibilityclient to super search fieldsjson

config/crontabber.ini-dist, socorro/cron/crontabber_app.py
Gently removing all remnants of this now deprecated stored procedure. 
Earlier today [I removed it from consulate `socorro/crontabber/crontabber.jobs`](https://bugzilla.mozilla.org/show_bug.cgi?id=1390847#c3).
I want to make sure it not running in -prod admin any more doesn't break anything. 
After this I can start to really remove all its code.
=> bug 1390847 - remove update-crash-adu-by-build-signature as default job

setup.py, webapp-django/crashstats/supersearch/models.py
Super search fields come from a Python module now and are handed around and some
of the users mutate the value. Because of that, we want to hand around a copy of
the structure--not the structure itself. This fixes that.
Additionally, this cleans up some comments that were wrong because we're not
storing the fields in JSON anymore.
=> bug 1100354 - fix fields mutations

docker/run_webapp.sh
For local development, the webapp runs with DEBUG=True which sources static
files without needing to run collectstatic. Thus running collecstatic is costly
and not helpful, so we should nix it.
=> fixes bug 1393533 - remove collectstatic before running webapp

alembic/versions/77395783fce5_remove_explosiveness_remnants.py
For some reason the `Explosiveness` class in `models.py` [was removed](https://bugzilla.mozilla.org/show_bug.cgi?id=1231672#c2) but no alembic migration was made for deleting the actual table.
=> fixes bug 1231672 - Delete explosiveness table

docker/create_weekly_tables.py, socorro/external/postgresql/staticdata.py
* updates report_partition_info contents based on what's in -prod today
* improves create_weekly_table.py so that it tells you what it did (yay!)
* fixes a bug in create_weekly_table.py where it'd do stuff, but didn't commit
it which is kind of useless
=> fixes bug 1394869 - update report_partition_info and fix create_weekly_table.py

docker/run_update_data.sh, socorro/cron/jobs/ftpscraper.py
This adds a cachedir configuration property letting you specify a directory on
disk to cache .json files. It defaults to "don't cache on disk", but this
enables the disk cache for the local dev environment.
=> fixes bug 1395681 - cache .json files on disk for ftpscraper

alembic/versions/07c6633fa1b6_delete_signature_summaries.py
I double-checked the order of strings like that with:
```
▶ cat dummy.py
table_names = ['signature_summary_os_20130603', 'signature_summary_os', 'signature_summary_os_20130610']
table_names.sort(reverse=True)
print(table_names)
▶ python dummy.py
['signature_summary_os_20130610', 'signature_summary_os_20130603', 'signature_summary_os']
```
=> fixes bug 1394909 - correct order of table deletions with partitions

socorro/cron/jobs/ftpscraper.py
This helps us know whether the file-based cache is helping or not without being
overly verbose.
=> Add cache hits summary to ftpscraper

webapp-django/crashstats/settings/base.py
For boto connections, we use RegionalS3ConnectionContext and subclasses. This
family of connection contexts default to OrdinaryCallingFormat rather than
SubdomainCallingFormat. This is important because we have periods in our bucket
names and thus SubdomainCallingFormat doesn't work.
However, when I picked the default for resource.boto.calling_format in the
original commit, I looked at S3ConnectionContext rather than
RegionalS3ConnectionContext and thus used the wrong one and now everything is
hosed in -stage and Sentry is giving me dirty looks late on a Friday just before
the weekend.
This fixes all of that.
=> fixes bug 1397857 - fix calling format

alembic/versions/a38b03765a79_drop_plugins_reports_tables.py, socorro/external/postgresql/crashstorage.py, socorro/external/postgresql/models.py, socorro/external/postgresql/staticdata.py
When I started working on this, I discovered that it appears that we're still actively writing to these tables. I can't find any reference to it ever being queried. Which kinda makes sense since it used to be used by the search we had before we had super search. 
So I'm going to be careful and first make a PR that deprecates the writes. Then we'll let that go into stage and check that all is well with the world.
=> fixes bug 794524 - drop plugins_report table

socorro/scripts/fetch_crash_data.py
This fixes the script to not print out the API token. So now it does this if there's an api token in the environment:
```
./docker/as_me.sh bash
I have no name!@b0fde87e0e55:/app$ ./scripts/fetch_crash_data.py ./crashdata 39342dd1-4cf4-4ad5-9d90-722160170912
Using api token: 5555xxxxxxxxxxxxxxxxxxxxxxxxxxxx
Working on 39342dd1-4cf4-4ad5-9d90-722160170912...
Fetching 39342dd1-4cf4-4ad5-9d90-722160170912
Fetching 39342dd1-4cf4-4ad5-9d90-722160170912 -> upload_file_minidump
```
And this if there is no api token in the environment:
```
I have no name!@b0fde87e0e55:/app$ SOCORRO_API_TOKEN= ./scripts/fetch_crash_data.py ./crashdata 39342dd1-4cf4-4ad5-9d90-722160170912 
Working on 39342dd1-4cf4-4ad5-9d90-722160170912...
Fetching 39342dd1-4cf4-4ad5-9d90-722160170912
I have no …
```
=> Fix fetch_crash_data.py to not print out API token

docker/fetch_normalization_data.py
When fetching normalization data, we really need valid product versions. If
there aren't any valid product versions, then we should throw our hands in the
air and give up with an error.
=> bug 1399459 - halt if there are no versions

socorro/signature/signature_utilities.py
It would be nice to add `core::result::unwrap_failed<hashglobe::FailedAllocationError>`, but it apparently is transformed in the signature into a generic `unwrap_failed<T>` per https://crash-stats.mozilla.com/report/index/d54a2975-9c55-4567-a92f-c755c0170903 :/
=> Add rust oom signature

docs/components/processor.rst, scripts/fetch_crashids.py, socorro/scripts/__init__.py, socorro/scripts/fetch_crash_data.py, socorro/scripts/fetch_crashids.py
This adds a `scripts/fetch_crashids.py` script that will generate a list of crash ids based on specified parameters.
In this first pass, we're keeping the parameters pretty limited to date and number and a url. We can enhance that later as needs arise.
To test, first get into a bash session in the processor container:
```
$ docker-compose run processor bash
```
Then to get command help:
```
app@...:/app$ ./scripts/fetch_crashids.py --help
```
To pull 100 crashes for Firefox from yesterday:
```
app@...:/app$ ./scripts/fetch_crashids.py
```
To pull 5 crashes for Firefox from September 1st:
```
app@...:/app$ ./scripts/fetch_crashids.py --date=2017-09-01 --num=5
```
To pull 100 crashes from the results of a Super Search query:
```
app@...:/app$ ./scripts/fetch_crashids.py …
```
=> 1398116 fetch crashids

socorro/siglists/prefix_signature_re.txt
Here's the change in signatures:
```
app@90ae9bd26804:/app$ python -m socorro.signature 7b1e019c-68c0-4c55-8ddc-99fe30170913
Crash id: 7b1e019c-68c0-4c55-8ddc-99fe30170913
Original: stdext::hash_map<T>::operator[]
New:      stdext::hash_map<T>::operator[] | mozilla::ipc::IToplevelProtocol::ShmemCreated
```
=> fixes bug 1400085 - add stdext::hash_map<T>::.* to prefix list

docker-compose.yml, docs/components/processor.rst
This completes the local development crash ingestion pipeline by adding the
Antenna service and pointing it to the local S3 `dev_bucket`.
=> bug 1400076 - add Antenna service

docs/components/webapp.rst, requirements.txt, webapp-django/crashstats/settings/base.py
This works really well actually. We talked about the confusion of why there's a `docker/config/docker_common.env` (the webapp part) and `docker/config/local_development.env` but I hope that doesn't affect this. 
Basically, when I follow the instructions I mention in `webapp.rst` I get something really close to prod. I get DEBUG disabled and I get uwsgi. And since the instructions "force" to seting `DEBUG=False` as part of it I don't need to explain how to temporarily mess with your `my.env` file. 
When I go back to regular `docker-compose up webapp` things work great still. If I edit a file like `documention.less` simply editing that file (and Ctrl-S) doesn't restart the runserver but if I make that change AND edit any .py file it does restart runserver and the changes I made in the .less …
=> fixes bug 1399299 - how to run webapp with DEBUG=False

socorro/scripts/fetch_crash_data.py, socorro/scripts/fetch_crashids.py, socorro/signature/README.rst, socorro/signature/__main__.py
This makes it muuuuch easier to test and regression test signature generation
changes.
OMG--this is so amazing. For example, with pull #3992, I could have done this instead:
```
app@175a03e184c1:/app$ ./scripts/fetch_crashids.py --num=5 "--signature-contains=std::_Hash<T>" | xargs python -m socorro.signature
Crash id: 65d1e40a-be91-442c-a244-6f73c0170915
Original: std::_Hash<T>::lower_bound
New:      std::_Hash<T>::lower_bound | CDevice::CreateRasterizerState_Worker
Crash id: c1a47f6d-f686-4888-bfe7-d980e0170915
Original: std::_Hash<T>::lower_bound
New:      std::_Hash<T>::lower_bound | CDevice::CreateRasterizerState_Worker
Crash id: 265e6b4f-36b1-4ad6-9190-c62810170915
Original: shutdownhang | ZwWaitForKeyedEvent | RtlSleepConditionVariableCS | …
```
=> fixes bug 1400402 - add --signature-contains to fetch_crashids script

docker/config/docker_common.env, docker/config/local_development.env, webapp-django/bin/ci.sh, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/symbols/views.py
The local dev environment requires that we can specify host, port, and whether
to use a secure connection in order to connect to the local S3. Other parts of
Socorro already handle this, but symbol upload didn't.
This fixes that.
=> fixes bug 1399120 - fixes symbol upload in local dev environment

docker/config/docker_common.env, docker/config/local_development.env
This moves another couple of environment variables that should never get set
this way in a server environment into the local_development.env file where they
should be.
=> bug 1399979 - move environment vars around

docker/config/alembic.ini, docker/config/local_dev.env
Prior to this fix, alembic had the wrong sqlalchemy.url, so it was tricky to do
migration testing in the local dev environment.
=> fixes bug 1394834 - fix alembic in local dev environment

docker/config/local_dev.env, docker/config/never_on_a_server.env, docker/config/test.env
This removes a bunch of unneeded vars from local_dev.env and moves a few others
to better files.
=> bug 1296238 - reduce vars in local_dev.env

socorro/siglists/irrelevant_signature_re.txt
Any assertion within media/webrtc/trunk/webrtc (webrtc imported code) ends up in rtc::FatalMessage::~FatalMessage right now, regardless of which assert it is.
=> fixes bug 1400301 Add rtc::FatalMessage -- webrtc.org's impl for RTC_CHECK/RTC_DCHECK/etc

webapp-django/crashstats/settings/base.py
fixes: https://bugzilla.mozilla.org/show_bug.cgi?id=1390530
As April pointed out these domains the HSTS preloaded, so this will only help people with older browsers that don't support HSTS.
This also makes things consistent with the img-src.
r? @peterbe or @willkg
=> bug 1390530 - Add https scheme to crash-stats CSP srcs

socorro/signature/rules.py
GCC 6 includes an optimizer that identifies hot and cold code sections and marks
them. That messes up signatures because it includes a number at the end that
changes.
This strips the frame function of that tawdry bit so as to make signatures
bucket better.
=> fixes bug 1397926 - remove [clone .cold.xxx] from signatures

docs/architecture/signaturegeneration.rst, socorro/siglists/README.rst
We had a wiki page that sort of walked through the process for requesting
signature generation changes. We changed that wiki page to point to these docs,
but didn't have a process in these docs. This adds that.
This also cleans up the process for reviewing changes to signature generation.
=> Update signature generation documentation

socorro/lib/util.py, socorro/signature/rules.py, socorro/unittest/lib/test_util.py, socorro/unittest/signature/test_rules.py
This fixes the UnicodeEncodeError in AbortSignature by stripping abort_message
of unicode characters.
This also fixes a bucketing issue for "unable to find a usable font (...)" where
the ... part contains a number of different fonts, thus all these crashes are
falling into separate buckets. This removes that parenthesized bit.
=> fixes bug 13785966 - fix UnicodeEncodeError in AbortSignature

e2e-tests/Jenkinsfile
@chartjes r?  This small change was recommended by a core Jenkins CI project member, and brings this repo in-line with all the other web-automation suites.
Full passing output: https://gist.github.com/stephendonner/55f723f7b804b8e5f3df0ddcfe84c892
=> Move fxtest-library include into pipeline block

socorro/processor/breakpad_transform_rules.py
If you process a crash, it sets "additional_minidumps". However, if you
re-process a crash, it appends to that field. That's totally not the right thing
to do.
This fixes it so that it always resets the value of that field.
=> fixes bug 1280374 - reset additional_minidumps every time

socorro/siglists/irrelevant_signature_re.txt
We have a number of shutdownhang signatures where the stack is rife with
"uninteresting" bits such that the signature gets truncated before getting to
something interesting or relevant or actionable.
This adds a bunch of things to the irrelevant list such that they don't show up
in the signature.
I did some regression testing and these strings only show up in shutdownhang
crashes. If that changes, we should rethink them on a string-by-string basis.
=> bug 1402037 - improve shutdownhang signatures

e2e-tests/pages/base_page.py, e2e-tests/tests/test_crash_reports.py
After some discussion it has been decided that this test is not providing enough value, especially as it has been marked as expected to fail for at least six months.
=> Bug 1292594 - Remove test_that_products_are_sorted_correctly

alembic/versions/77856f165be7_bug_1403172_fix_fennecandroid_api_16.py, socorro/cron/jobs/ftpscraper.py, socorro/external/postgresql/staticdata.py
FennecAndroid builds are now coming from the mozilla-central-android-api-16
repository, so we need to add support for that otherwise we don't see builds.
=> fixes bug 1403172 - add android-api-16 and mozilla-central-android-api-16

e2e-tests/tests/test_crash_reports.py
Bug 1351757 was resolved as invalid, and the SeaMonkey product is expected in the list.
=> Restoring SeaMonkey to list of expected products

docker-compose.yml
Bug #1407980 covers how Antenna says absolutely nothing helpful if the bucket it needs to use isn't there. That's annoying and should get fixed.
In the meantime, we (Socorro) can use the dev `bin/run_web.sh` script from the Antenna container which creates the bucket if it doesn't exist and then runs Antenna instead of using the image default command. That gets us around our issue nicely.
This implements that.
To test, run:
```
$ docker-compose up antenna
```
Towards the top of the output, you will see this line:
```
antenna_1        | Checking to see if bucket "dev_bucket" exists...
```
Then depending on if the bucket exists for you, you might also see these lines:
```
antenna_1        | An error occurred (404) when calling the HeadBucket operation: Not Found
antenna_1        | Bucket not …
```
=> bug 1407980 - use antenna dev script to alleviate missing bucket issue

docker-compose.yml, docker/config/local_dev.env, docker/config/local_dev_submitter.env, docker/run_submitter.sh
This adds the submitter as a docker service with configuration and a run script.
This is different than other services because the configuration conflicts with
configuration for other services.
For now, I'm just slapping this together for the purposes of being able to test
changes to the submitter in the local development environment. If we decide to
use this for other purposes, we can redo it then.
=> bug 1405679 - add submitter as a docker service

socorro/signature/__init__.py, socorro/signature/__main__.py, socorro/signature/rules.py, socorro/unittest/signature/test_rules.py
If `MozCrashReason` is `"MOZ_RELEASE_ASSERT(parentBuildID == childBuildID)"`, then
stomp on the signature with `"parentBuildID != childBuildID"`. This allows all
these crashes to end up in the same bucket where the original signature is
likely to be bogus since there are two different builds involved.
This also adds `raw_crash['MozCrashReason']` to the list of things that we use to
generate signatures.
I tested this out in this bug comment with the specific crashes and Andrew approved the output.
I think to test, we should let Travis/Circle do their thing. You can also rerun what I did in this comment and verify the output is the same:
https://bugzilla.mozilla.org/show_bug.cgi?id=1408448#c6
=> fixes bug 1408448 - stomp on signature when parentBuildID != childBuildID

minidump-stackwalk/get-minidump-instructions.cc, minidump-stackwalk/stackwalker.cc, scripts/build-breakpad.sh
Tested locally by rebuilding my processor container with the new breakpad version and successfully processing the crash from [bug 1400952](https://bugzilla.mozilla.org/show_bug.cgi?id=1400952). I was able to get proper symbols for the crashing thread, and a proper signature.
=> Fix bug 1400952: Update Breakpad to a more recent version.

docker-compose.yml, docker/config/local_dev_submitter.env, socorro/scripts/add_crashid_to_queue.py, socorro/submitter/breakpad_submitter_utilities.py, socorro/submitter/submitter_app.py, socorro/unittest/submitter/test_breakpad_post.py
This adds support for posting to multiple urls. It's a little tricky to test--we want to test both the single value and the multiple value situations.
For single value do this:
1. in terminal 1, run `docker-compose run submitter bash` and then `./docker/run_submitter.sh`
2. in terminal 2, run `docker-compose up antenna`
3. in terminal 3, run `./docker/as_me.sh bash` and then the following:
3.1. `./scripts/fetch_crashids.txt --num=1 > tosubmit.txt`
3.2. `cat tosubmit.txt | ./scripts/fetch_crash_data.py ./crashdata`
3.3. `./scripts/socorro_aws.sh sync ./crashdata s3://dev_bucket/`
3.4. `cat tosubmit.txt | ./scripts/add_crashid_to_queue.py socorro.stagesubmitter`
That downloads a crash, puts it in s3, and tosses the crashid in the `socorro.stagesubmitter` queue.
The submitter will wake up …
=> bug 1405679 - submitter urls

setup.cfg, webapp-django/crashstats/supersearch/static/supersearch/js/socorro/date_filters.js
Flatpickr now returns a list of selected dates instead of a single date object,
so the onChange callbacks have been updated to unpack the list being returned.
The callbacks themselves were also moved to the initial config object, although
this isn't strictly necessary.
The .eslintrc config was also updated to support the object function shorthand
being used in this patch.
=> Fix bug 1412281: Update how we configure flatpickr.

docker/config/local_dev.env, docker/config/processor.env, socorro/processor/breakpad_transform_rules.py, socorro/unittest/processor/test_breakpad_transform_rules.py
This removes some dead code and then redoes the mdsw command line. This comment covers the context of these changes:
https://bugzilla.mozilla.org/show_bug.cgi?id=1407997#c2
Generally, we're adding a symbol tmp path to the default command line and also adding a kill_timeout variable. Adding these two things lets us handle the local development environment, -stage, and -prod configuration needs using the default.
To test:
1. run the tests (or wait for Circle CI and Travis to be happy)
2. run the processor in the local development environment and verify mdsw is running with appropriate values and producing output
1. in terminal 1, run `dc up processor`
2. in terminal 2, run `./docker/as_me.sh bash` and then do:
```
you@processor:/app$ ./scripts/fetch_crashids.py --num=1 > id.txt …
```
=> fixes bug 1407997 - redo mdsw command line config

CONTRIBUTING.rst
Follow-up fix from https://github.com/mozilla-services/socorro/pull/4062#discussion_r147842265.
=> Clarify how to add dependencies to the constraints file.

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/static/crashstats/css/screen.less, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/views.py
That test is more or less a copy-paste of the test above it with minor changes. Ideally I'd also like to test something about the "hidden" class being present but it seemed kind of awkward to do and falls into the "frontend is getting replaced soon anyway" area. But I can totally add it if we think we need it.
I also tested this manually against three crashes from the [query spohl provided](https://bugzilla.mozilla.org/show_bug.cgi?id=1406121#c4).
=> Fix bug 1406121: Display all threads when no crashing thread is available.

webapp-django/crashstats/settings/base.py
This cleans up the logging configuration and removes vestiges of CEF and playdoh
which we don't use anymore.
This also adds py.warnings because we really want to see those so we can fix
them which will reduce future headaches.
=> fixes bug 1413210 - Clean up logging configuration

webapp-django/package-lock.json, webapp-django/package.json
This should be the version of d3-sankey we were using before, instead of the
latest version.
I had trouble testing this locally, because there is [a bug in d3-sankey that triggers when links in the chart all have a value of 0](https://github.com/d3/d3-sankey/pull/39). In our case, we hit this bug when none of the crontabber tasks have any dependencies. When I run crontabber locally, it populates the database with data about some crontabber tasks, but none of them have dependencies: https://gist.github.com/Osmose/3b39699117677ebc2991ea7ec0d02168
It looks like this is normally not an issue since crontabber on the servers and other dev environments has at least one job with a dependency. Fixing that issue requires a more extensive rewrite of the crontabber page that I don't think we should …
=> Fix bug 1413164: Downgrade to d3-sankey 0.4.2.

docker-compose.yml
This fixes the statsd container in the local development environment which didn't work at all. Now it uses graphite which isn't exciting, but does work and lets you see statsd metrics over time.
To test:
1. do `docker-compose up processor`
2. process some crashes
3. go to `http://localhost:8080` (eighty eighty) to view graphite and view the metrics generated
=> fixes bug 1413703 - Fix statsd container so it works

.pyup
I'm following the steps from the checklist on https://github.com/mozilla-services/foxsec/, which says to add this config, then notify secops that we want to enable pyup.
=> Bug 1411036: Add pyup configuration.

socorro/siglists/prefix_signature_re.txt
This fixes signatures like this one:
```
app@processor:/app$ python -m socorro.signature 10fb304e-2d3b-4b39-aad7-6a4e90171101
Crash id: 10fb304e-2d3b-4b39-aad7-6a4e90171101
Original: OOM | large | NS_ABORT_OOM | nsTArrayInfallibleAllocator::ResultTypeProxy nsTArray_base<T>::EnsureCapacity<T>
New:      OOM | large | NS_ABORT_OOM | nsTArrayInfallibleAllocator::ResultTypeProxy nsTArray_base<T>::EnsureCapacity<T> | nsHtml5TreeBuilder::createElement
```
You can see other signatures like this:
https://crash-stats.mozilla.com/search/?signature=~nsTArrayInfallibleAllocator&product=Firefox&date=%3E%3D2017-11-06T11%3A35%3A52.000Z&date=%3C2017-11-13T11%3A35%3A52.000Z&_sort=-date&_facets=signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_col …
=> fixes bug 1416168 - add nsTArrayInfallibleAllocator to prefix list

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py
There are three different urls that yield crontabber state information:
- /api/CrontabberState/
- /monitoring/crontabber/
- /crontabber-state/
All three of them use the CrontabberState model.
This PR adjusts that model to redact some information from the response thus
fixing all three of those endpoints.
=> fixes bug 1416905 - redact crontabber error details

docker/run_crontabber.sh, docker/run_update_data.sh, socorro/app/for_application_defaults.py, socorro/cron/crontabber_app.py, socorro/unittest/cron/crontabber_tests_base.py, socorro/unittest/cron/jobs/test_bugzilla.py, socorro/unittest/cron/jobs/test_clean_missing_symbols.py, socorro/unittest/cron/jobs/test_clean_raw_adi.py, socorro/unittest/cron/jobs/test_clean_raw_adi_logs.py, socorro/unittest/cron/jobs/test_drop_old_partitions.py, socorro/unittest/cron/jobs/test_elasticsearch_cleanup.py, socorro/unittest/cron/jobs/test_featured_versions_automatic.py, socorro/unittest/cron/jobs/test_fetch_adi_from_hive.py, socorro/unittest/cron/jobs/test_ftpscraper.py, socorro/unittest/cron/jobs/test_matviews.py, socorro/unittest/cron/jobs/test_missingsymbols.py, socorro/unittest/cron/jobs/test_truncate_partitions.py, socorro/unittest/cron/jobs/test_upload_crash_report_json_schema.py, socorro/unittest/cron/jobs/test_weekly_reports_partitions.py, socorro/unittest/cron/setup_configman.py, socorro/unittest/cron/test_crontabber_app.py
This redoes crontabber jobs configuration such that it can take a Python dotted path to a string with the configuration.
In order to do that, we also had to redo things so that CronTabberApp was a valid socorro app. This means it now works with the socorro script.
This updates the related docker scripts to use the new way to run it.
In doing all that, I discovered the tests weren't consistent in how they set up a config manager. This fixes tests, too.
This supports the current configuration model as well as the new one (Python dotted paths), so we can make configuration changes after this lands and deploys all the way to -prod.
To test:
1. run `make dockerupdatedata` -- that runs crontabber with a single job
2. run `docker-compose up crontabber` -- that runs the crontabber container and …
=> fixes bug 1388130 - redo crontabber jobs configuration

socorro/external/postgresql/staticdata.py
This populates the `product_productid_map` table and makes it possible to test PR #4210.
To test, run `make dockersetup` in this branch. That'll populate the table. Then you can switch to the PR #4210 branch and verify the API endpoint works.
"product_name" is a foreign key, so I only added rows for products that are in the products table.
=> fixes bug 1418881 - populate product_productid_map table

docker/config/local_dev.env, docker/config/test.env, socorro/external/boto/crashstorage.py, socorro/unittest/external/boto/test_crashstorage.py
This allows us to set the `bucket_name` value without having to specify it in the
`destination4` configuration key like we do now.
That makes it easier for us to move crashstorage classes around without bumping
into an environment configuration variable which will be defined in a different
place in the new infrastructure.
This will help us fix TelemetryS3 issues with the docker-based infrastructure.
=> fixes bug 1410167 - fixes TelemetryS3CrashStorage bucket_name

socorro/processor/mozilla_processor_2015.py, socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
The AuroraVersionFixitRule checks the crash and stomps on the version if
the crash is from Firefox with specific build ids. The build ids are
for builds that are on the aurora channel for devedition product, but have
a .0b1 beta-style version.
We're fixing the crashes in the processor because the alternative was to
work through the ball of spaghetti that is ftpscraper, the stored procedures,
and related database table data to figure out why it's doing everything WRONG!
The Socorro team therapist suggested we do a processor rule now and rewrite
ftpscraper later and/or switch to buildhub.
=> fixes bug 1418037 - add AuroraVersionFixitRule

.circleci/config.yml
this is an intermediary step to revamping our circleci config. my team is still figuring out best practices for circleci 2.0. this should, at the very least, stop pushing tons of tags to dockerhub (triggering lots of builds in new-stage) and ensure that we build properly tagged docker containers on socorro tags.
=> circle config: add a workflows section so we build tags

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/urls.py, webapp-django/crashstats/crashstats/views.py, webapp-django/crashstats/settings/base.py
Rather than fix the existing `/status/revision/` endpoint to work with the docker-based infrastructure, I implemented the `/__version__` endpoint we want to switch to anyhow. We can leave `/status/revision/` as is for now.
To test, switch to this branch and then do `docker-compose up webapp` and go to http://localhost:8000/__version__ . Because this is the local dev environment, you'll seee `{}`.
=> fixes bug 1419856 - implements /__version__ endpoint

socorro/cron/jobs/upload_crash_report_json_schema.py, socorro/unittest/cron/jobs/test_upload_crash_report_json_schema.py
This fixes the `UploadCrashReportJSONSchemaCronApp` cron job to use similar
logic to determine the bucket name to use to save the schema file as the
`TelemetryBotoS3CrashStorage` class does.
=> fixes bug 1410167 - fix UploadCrashReportJSONSchemaCronApp bucket name

docker/config/local_dev.env, socorro/cron/jobs/monitoring.py, socorro/unittest/cron/jobs/test_monitoring.py
Turns out the directory layout in the RPM build is not the same as in the repo. Thus, running the dependency check on staging failed because it determines the path to `package.json` relative to it's location in the repo.
This fixes the issue by making the path to the package.json file configurable.
You can test this locally by running `make dockerdependencycheck`.
=> Bug 1411036: Add package_json_path config to dependency check cronjob.

docker/config/processor.env, socorro/processor/breakpad_transform_rules.py, socorro/unittest/processor/test_breakpad_transform_rules.py
This drops the private-symbols-url and public-symbols-url configuration
variables for a single symbols-urls variable that takes a comma-delimited
list of strings.
Now we can add arbitrary number of urls in the order we want them
checked.
=> fixes bug 1383067 - redo symbols-urls conf in BreakpadStackwalker2015

socorro/siglists/prefix_signature_re.txt
This adds that frame to the prefix list allowing signature generation
to proceed to the next frame.
Example:
```
you@processor:/app$ python -m socorro.signature f9a31f4f-7ddd-4d10-ab06-064080171203
Crash id: f9a31f4f-7ddd-4d10-ab06-064080171203
Original: nsStringBuffer::FromDataCanaryCheckFailed
New:      nsStringBuffer::FromDataCanaryCheckFailed | mozilla::dom::Element::GetAttribute
you@processor:/app$
```
=> fixes bug 1422639 - prefix nsStringBuffer::FromDataCanaryCheckFailed

scripts/build-breakpad.sh
Built this locally with no issues, and processed 100 or so crashes with no issues locally as well.
If you want to try this locally, edit `set_up_stackwalk.sh` and comment out the if statement around the "Build breakpad" line so that the docker build will manually build breakpad. Build the docker containers, process some crashes, and check that there were no processing errors.
=> Fix bug 1421988: Update Breakpad.

webapp-django/crashstats/crashstats/jinja2/crashstats/bugzilla_comment.txt, webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
The text gets URL-escaped separately, and given that the text is just shoved in a textbox, there's not really anything we're defending against via escaping anyway.
=> Fix bug 1423211: Do not escape stack frames in pre-filled Bugzilla comments.

e2e-tests/Jenkinsfile
@chartjes r?
Sorry for the noisy PRs - Sauce Labs has had two separate failed attempts to deploy the permanent fix for Firefox 57, and suggested we implement this, rather than having to continue waiting.
Passing build here: https://pastebin.com/kycRigiV
I'll close the existing PR to get it out of the way, and return with the proper fix, once they've deployed successfully and I've tested.
Sound good?
=> Update to Firefox 57, in Sauce Labs

scripts/rawadimover_integration_test.sh, socorro/cron/crontabber_app.py, socorro/cron/jobs/fetch_adi_from_hive.py
This implements a third fetch-adi-from-hive cron app. This variation has
a source db and a dest db and copies the data in the raw_adi table over.
This has no unit tests. There is a single integration test that's run
as a shell script by hand and it requires manual verification.
=> fixes bug 1407655 - implement RawADIMoverCronApp

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
moves window pretty name lookup table into the name prettifying rule, refactors, and documents the rule. removes one more instance of direct database access from the processor.
=> fixes bug 1346993 - OSPrettyVersionRule

socorro/unittest/cron/jobs/test_bugzilla.py, socorro/unittest/cron/setup_configman.py
This fixes `test_bugzilla.py` which is hanging for me right now and thus I can't run tests locally.
This also fixes the logger-related warning in that file for bug 1419585.
=> Fix test bugzilla

socorro/cron/crontabber_app.py
We're not going to do missing symbols with the new infra, so this removes that crontabber app from running in -stage-new.
This is termporary to quell errors we're seeing. We'll be able to remove the crontabber app from all the environments soon.
=> Remove MissingSymbolsCronApp from -stage-new list

setup.cfg, socorro/external/crashstorage_base.py, socorro/unittest/cron/jobs/test_monitoring.py, socorro/unittest/processor/test_processor_app.py
This fixes the socorro tests such that all warnings are now considered
errors. This also fixes the handful of warnings that were getting kicked
up.
This doesn't fix the webapp tests--we'll do that in another PR.
=> bug 1419585 - all warnings are errors for socorro tests

socorro/external/boto/crash_data.py, webapp-django/crashstats/crashstats/models.py
This adds logging for boto fetch errors. Previously, error messages
were getting thrown away.
This also fixes logging for crashstats models. Previously the logging
configuration didn't cover them, so they were silently ignored.
=> bug 1425492 - log boto fetch errors

socorro/cron/crontabber_app.py
The fake one and the rawadimover one were set to run at the wrong time
in relation to the adu jobs that need that data. This fixes that.
=> fixes bug 1426144 - fix job spec for fetch-adi-from-hive jobs

socorro/processor/processor_app.py, socorro/unittest/processor/test_processor_app.py
The part of the processor that fetches raw crash metadata and dumps and
then stores bits on disk could fail and when it did, it'd log something, but
unless someone was watching the logs at the time, no one would ever know.
This fixes that in the same way we capture other processing errors--it
sends any errors to sentry assuming sentry is configured.
=> bug 1426225 - capture fetch raw crash errors

docs/requirements.txt
This fixes building docs on readthedocs.
=> Downgrade Commonmark to 0.5.4

socorro/siglists/prefix_signature_re.txt
`_platform_memmove$VARIANT$Haswell` is already in the list, so this nixes
the Haswell part and generalizes it across the other variations.
This also adds the `__platform_memmove$VARIANT$` version, too, with the
double-underscore.
=> fixes bug 1309102 - add _platform_memmove things to prefix list

docker-compose.yml, docs/howto.rst
This makes it easier to use programs like Postico to inspect the database during development.
=> Expose postgres on a port to make connecting via a client easier.

docker/run_build_docs.sh, docs/Makefile
This fixes the docs build scripts such that readthedocs will copy the
e2e-tests README before building the docs. Otherwise, the e2e-tests README
doesn't get compiled into the docs on readthedocs.
To test this, run `make dockerdocs` and verify that `docs/tests/e2e_readme.md` exists.
=> fixes bug 1429434 - fix e2e-tests README missing in RTD

docs/howto.rst, socorro/scripts/reprocess.py
This adds some crude documentation for reprocessing crashes including some
hand-wavey warnings about being cautious about adding crash ids to the queue
faster than they can be processed.
=> fixes bug 1426186 - add reprocessing howto

docs/tests/system_checklist.rst, webapp-django/crashstats/crashstats/static/crashstats/js/socorro/crashes_per_day.js, webapp-django/crashstats/home/static/home/js/home.js, webapp-django/crashstats/settings/bundles.py, webapp-django/crashstats/signature/static/signature/js/signature_tab_graphs.js
This should fix the JS errors on the home, crashes-per-day, and signature graphs pages. It also makes debugging JS a bit easier by not using some minified files in development, and updates the system checklist docs to remind people (mostly me) to check the JS console while testing the webapp.
=> Fix bug 1429829: Use functions for `interpolate` param of metricsgraphics.js

socorro/signature/rules.py, socorro/unittest/signature/test_rules.py
The change was pretty minor.
Then I went looking for related tests and in the process of doing that, decided to change the test case names to something related to what they were testing so I didn't have to do so much work reading them next time around.
In the process of doing that, I found a couple of tests that were identical duplicates and one test that was testing the same thing as another test and so I removed those.
There are < 4000 crashes in the current corpus that are affected by this change. We could reprocess them after landing and deploying this, but I don't think that's necessary.
=> fixes bug 1371428 - nix quotes

socorro/signature/generator.py, socorro/signature/rules.py, socorro/unittest/signature/test_rules.py
Prior to this, it was possible (though rare) to have two spaces in a row
in signatures. That's tough because the webui shows that as a single
space and if you search for the single-space version, you won't get any
results.
This fixes that by establishing that signatures can't have more than 1
consecutive whitespace character. Further, this makes sure that all
non-space whitespace characters are converted to space and this
happens all before we truncate the signature.
I also changed SigTrunc to SigTruncate because "trunc" is an unnecessary
abbreviation.
=> fixes bug 1424659 - nix consecutive spaces in signatures

socorro/siglists/prefix_signature_re.txt
ReleaseData is a generic function used to destroy string data.
=> Bug 1431167 - Add ReleaseData to the prefix list

socorro/external/crashstorage_base.py, socorro/unittest/external/test_crashstorage_base.py
While working on [bug 687630](https://bugzilla.mozilla.org/show_bug.cgi?id=687630) I ran into an issue while processing crashes, and the error couldn't be output properly because `PolyStorageError` had been called with no arguments, which `PolyStorageError.__str__` could not properly handle.
This makes the method more robust to weird arguments so that it will print out the errors that occurred even if there are no arguments given. It also slightly changes the format of what was output, but none of the tests were relying on this anyway.
=> Make the string representation of PolyStorageError more robust.

docker-compose.yml
This switches the local development environment to use the Mozilla
Elasticsearch 1.4.5 image. This is what we're using in the new infra
so it behooves us to use it locally, too.
If Circle is fine with it, then it should work fine.
=> fixes bug 1406025 - switch to mozilla ES image

docker/run_setup.sh, docker/run_update_data.sh, socorro/cron/crontabber_app.py
This makes it easier to set up initial crontabber bookkeeping state in
the local development environment without having to run all the crontabber
jobs.
Mike: Do you think this helps? Is it good enough for a first pass? We can also do one for marking jobs as failed. I think that covers basic cases and after that it's probably easier to drop into psql and edit the db manually.
=> bug 1431442 - add "mark-success" to crontabber app

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
Given that the original reporter for the bug didn't have a strong opinion on where else to linkify build IDs, I figure we can do it in the easiest and most prominent spot it appears in, and let people reopen the bug if they want it elsewhere.
=> Fix bug 687630: Linkify Build ID in crash report to BuildHub.

socorro/external/es/connection_context.py
If the `elasticsearch_urls` are all https, then we should be passing in
`verify_certs=True` and `use_ssl=True` args into the Elasticsearch
connection.
=> fixes bug 1416340 - use secure args for ES connections

docs/services/elasticsearch.rst, socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
This does three things:
1. clean up a bit of Elasticsearch code in a fundamental way
2. update the documentation because that helped figure out how I needed to do things
3. implement truncating values for fields analyzed with the "keyword" analyzer
I did some analysis on our data before implementing value truncating. That's covered in comment 4 and comment 5 in bug 1407625 (https://bugzilla.mozilla.org/show_bug.cgi?id=1407625). I can expand on that if that's helpful.
The unit tests cover testing the scenarios pretty well. I don't think I'd bother with manual testing.
The one thing the changes don't do is emit any kind of signal that a value was truncated, so we'll never really know. There's no way to add post-processing notes to crash data like we do in the processor rules. We can log …
=> fixes bug 1407625 - truncate values in Elasticsearch

socorro/processor/mozilla_transform_rules.py
This adds buildids for all the .0b2 versions which are all also aurora channel.
=> fixes bug 1433988 - update AuroraVersionFixitRule re: 59.0b2

webapp-django/crashstats/api/views.py
This PR is pretty benign. Essentially, we drop the GraphicsDevices API endpoint without affecting any of the internal stuff which the signature report still uses.
Why bother with this now? It means that going forward it's not a publicly supported API endpoint, so it's not the case that someone could start using it between now and when we want to take all that code out.
I'd do more and take the rest of the code out, but the signature report still relies on it. I think we'd have to convert the model to use Elasticsearch before we could take out all the postgres-related bits. I'll write up a bug for that.
=> fixes bug 1430786 - remove /api/GraphicsDevices/ endpoint

.pyup.yml
@chartjes @willkg r?
I accidentally broke this by renaming "default.txt" to "requirements.txt" while following other conventions, in https://github.com/mozilla-services/socorro/pull/4305/files#diff-a7ef0f98e17ba791a95fa5364e74d1a2
This fixes that; sorry!
https://github.com/mozilla-services/socorro/blob/52ba35616ccd86b3674a251a3574b88f6ae0260f/e2e-tests/requirements/requirements.txt
=> Fix path to e2e-tests' requirements.txt file for Pyup

socorro/external/es/crashstorage.py, socorro/unittest/external/es/test_crashstorage.py
This changes the Elasticsearch crash store to convert pseudo-boolean
values to True and False which get converted to true and false in JSON
and sent to Elasticsearch. Elasticsearch 2.0+ isn't ok with pseudo-boolean
values like 0 and 1.
=> fixes bug 1429598 - fixes pseudo-booleans in Elasticsearch

webapp-django/crashstats/crashstats/jinja2/crashstats/crashes_per_day.html
This adds a message about rates to the crashes-per-day graph with a link to Mission Control which has better crash rate data.
This also deletes some dead code.
=> fixes bug 1434678 - add message about rates to crashes-per-day graph

alembic/versions/0193b4725f32_bug_1132858_remove_extensions.py, socorro/external/postgresql/models.py, socorro/external/postgresql/staticdata.py
The extensions table was a partitioned table, so this creates a migration
to remove the table, all the partitions, and the `report_partition_info` record.
It also removes the model in the code.
=> fixes bug 1132858 - remove the extensions table

e2e-tests/pages/home_page.py, webapp-django/crashstats/crashstats/static/crashstats/css/screen.less
Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1434902
=> Fix bug 1434902: Removes references to graph on the home page, which is no longer in use.

scripts/deploy_bug.py
Previously we removed the merge commits from the list of commits that got
displayed and then figured out the commit to tag by looking at the last commit
in that list. However, that's wrong--we really want the last commit and not
the last non-merge commit especially since the last commit is likely to be
a merge commit.
This fixes that. It also cleans up the code a bit.
=> fixes bug 1436537 - fixes sha to tag with in deploy_bug.py

docs/gettingstarted.rst
This clarifies that you have a local development environment with no crash
data in it and that you need to process some crashes to add some. It also
moves the link to the processor chapter up a bit so it's clearer where those
docs are.
@lonnen Does this help at all with bug 1437414?
=> fixes bug 1437414 - clarify crash data situation in getting started

docker/run_tests_in_docker.sh
This fixes ctrl-c when running "make dockertest".
=> fixes bug 1437632 - make test run interactive

socorro/cron/jobs/monitoring.py, socorro/unittest/cron/jobs/test_monitoring.py
The unit tests should be sufficient for testing this, I think.
Once this lands we'll need to add a new config value to the crontabber staging instance with the Pyup API key.
=> Fix bug 1437223: Add config for Pyup API key.

docker/run_recreate_s3_buckets.sh, socorro/cron/jobs/upload_crash_report_json_schema.py, socorro/unittest/cron/jobs/test_upload_crash_report_json_schema.py
This fixes the `upload_crash_report_json_schema` [1] to have the same `resource_class` default as `TelemetryBotoS3CrashStorage` which it's related to. This should fix the problem we have in the new infra where something something cross regions something something.
This also fixes that job running in the local dev environment. So you can now do:
```
$ make dockersetup
$ make dockerupdatedata
$ docker-compose up crontabber
```
and watch crontabber do some stuff and run the ... well, run *that* job without failing.
[1] Typing this 10 times a day burns 100 calories and should be part of a daily health regimen.
=> fixes bug 1432884 - upload_crash_report_json_schema s3 fix

config/package/usr/lib/systemd/system/socorro-processor.service
The processor service was still using the "socorro" script, but we nixed that.
This updates the service file to run the processor app directly.
=> fixes bug 1438969 - fix processor service

webapp-django/crashstats/api/urls.py, webapp-django/crashstats/authentication/urls.py, webapp-django/crashstats/crashstats/urls.py, webapp-django/crashstats/documentation/urls.py, webapp-django/crashstats/home/urls.py, webapp-django/crashstats/manage/urls.py, webapp-django/crashstats/monitoring/urls.py, webapp-django/crashstats/profile/urls.py, webapp-django/crashstats/signature/urls.py, webapp-django/crashstats/sources/urls.py, webapp-django/crashstats/tokens/urls.py, webapp-django/crashstats/topcrashers/urls.py
Setting a namespace for an included URLConf without an app_name attribute was
deprecated in 1.9:
https://docs.djangoproject.com/en/dev/releases/1.9/#passing-a-3-tuple-or-an-app-name-to-include
=> Fix deprecation warning raised during tests.

webapp-django/crashstats/settings/test.py
Certain built-in cache backends in Django, such as the local memory cache, have
a maximum number of cache entries they can hold at any given time. By default,
this is 300.
During the intermittently-failing test, requests to the report_index view would
cause not only model fetches for raw and unredacted crashes to be cached, but
also hashed names of processed static files (thanks to PipelineCachedStorage).
The amount of cache entries would grow beyond the max cache size, causing the
cache to be culled.
The local memory cache culls by removing a fraction of cache entries in a
non-deterministic way that relies on the ordering of entries in a dictionary.
The result is that sometimes, but not all the time, the cache entries being
tested were culled, and the test failed. Increasing the cache …
=> Fix bug 1438915: Set cache entry limit higher during tests.

e2e-tests/Jenkinsfile
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1439028 after chatting in IRC.
This would add 5-minute SCM polling + a daily run, via cron, of our e2e-tests, only (currently) in our Jenkins instance, here: https://qa-master.fxtest.jenkins.stage.mozaws.net/
These values are in the job configs, manually, but I'd like to move them here for better visibility + consistency.
Passing ad-hoc, here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/socorro.adhoc/129/console
=> Add 5-minute SCM polling; run daily via cron

docker/config/local_dev.env, docker/config/test.env, socorro/cron/jobs/upload_crash_report_json_schema.py, socorro/external/boto/crashstorage.py, socorro/unittest/cron/jobs/test_upload_crash_report_json_schema.py, socorro/unittest/external/boto/test_crashstorage.py
After the settings overhaul where we now store behavior configuration in
Python files and the `PolyCrashStorage` doesn't namespace using indexes, we
no longer need the hack to set the telemetry `bucket_name`.
This removes that code.
=> fix bug 1438921 - remove hacky telemetry bucket_name configuration

docker/config/local_dev.env, socorro/processor/processor_app.py
The default should be what we use in server environments--not what we use
in local dev environments. This fixes the various values scattered around
so there are fewer of them and they're correct in defaulty ways.
Also, we don't need `resource.signature.*` anything anymore.
=> bug 1439928 - fix mdsw config values

e2e-tests/Jenkinsfile
@chartjes @willkg - let me know if I should file a bug; I figured this was a small-enough change to initially put it up for r?
I've landed this change in all our other Jenkinsfile-using automation projects, too.
Per the 3rd best practice on https://github.com/jenkinsci/pipeline-examples/blob/0b834c0691b96d8dfc49229ba6effd66470bdee4/docs/BEST_PRACTICES.md#jenkinsfiles-and-multibranch
=> Add Groovy hashbang

docs/requirements.txt
This needs to be version 0.5.4. This adds a pyup:ignore in the hope that that
prevents it from updating again.
=> Downgrade CommonMark

socorro/cron/jobs/fetch_adi_from_hive.py
This PR adds a dry-run version of the `FetchADIFromHiveCronApp` as well as makes the changes for bug 1440745.
This is a work-in-progress.
=> bug 1440745 - add DryRunFetchADIFromHiveCronApp

webapp-django/crashstats/crashstats/static/crashstats/css/base/variables.less, webapp-django/crashstats/crashstats/static/crashstats/css/components/simplebox.less, webapp-django/crashstats/supersearch/static/supersearch/css/search.less
Fixes [#1442380](https://bugzilla.mozilla.org/show_bug.cgi?id=1442380)
This corrects `/base` prefix on `image-path`, pretty simple. I've tested this locally, and confirmed on stage that the images are simply pointing to the wrong location. I've also updated the paths that use `image-path` as well to avoid multiple `/img`s in image paths.
=> 1442380: Fix image-paths

requirements/default.txt
I tested with a `make dockerbuild`. I checked the docker build output and saw it downloading the `.tar.gz` file for the package, along with lines confirming it ran `setup.py install` for the package. That's different from the output when it was using a binary.
I also ran `docker-compose up webapp` and confirmed the `UserWarning` is gone now.
I also processed some crashes to ensure the app is still Postgres-ing correctly. Seems to work fine.
I humbly suggest we do not include this in [deploy 310](https://bugzilla.mozilla.org/show_bug.cgi?id=1442031). I can merge it afterwards.
=> Fix bug 1442677: Disable wheel binary packages for psycopg2.

webapp-django/crashstats/crashstats/static/crashstats/css/base.less
Fixes [#1436071](https://bugzilla.mozilla.org/show_bug.cgi?id=1436071)
Pretty simple. We don't use the YUI javascript library and most (if not all) UI styling is done through jQuery UI.
=> bug 1436071 - Remove YUI copyright

webapp-django/crashstats/monitoring/views.py
If one of the jobs has a `last_run` of `null` (it was running for the first time), then `/monitoring/crontabber` would error out with a `TypeError`. This fixes that by changing that code to only look at non-None `last_run`.
=> fix bug 1441318 - fix crontabber status error

socorro/external/crashstorage_base.py
This fixes the config value output when running SocorroApps to have a readable value for options using this class.
To test:
1. Checkout latest master.
2. Run `docker-compose up processor`. Confirm the output for the `destination.storage_namespaces` config value looks like this:
```
destination.storage_namespaces: <socorro.external.crashstorage_base.StorageNamespaceList object at 0x7fc27787ff50>
```
3. Checkout this branch.
4. Run `docker-compose up processor`. The config value output should look like this now:
```
destination.storage_namespaces: StorageNamespaceList(['postgres', 's3', 'elasticsearch', 'statsd', 'telemetry'])
```
I couldn't find where `to_str` was used so I didn't bother keeping it around.
=> Replace StorageNamespaceList.to_str with __repr__.

scripts/deploy_bug.py
This switches to 7 character sha prefixes in deploy_bug.py script so
it matches github's partial sha in the "recent commit" section when
tagging a release.
=> Switch to 7 character sha prefixes

socorro-cmd, socorro/external/boto/upload_telemetry_schema.py, socorro/unittest/external/boto/test_upload_telemetry_schema.py
This app can be run using the `socorro-cmd` in an appropriate environment for
uploading the Telemetry schema to the Telemetry S3 bucket.
=> fix bug 1440712 - add "upload_telemetry_schema" app

minidump-stackwalk/stackwalker.cc, webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/tests/test_views.py
We have added information about the certificate used to sign modules to Windows crash reports. We would like to surface that information in a report's module list displayed on crash-stats.
This PR adds the required processing to the stackwalker and modifies the webapp to add that information as a new column in the module list.
Regression tests have been added for the webapp parts.
These cert annotations have been available on Nightly 60 since March 2, 2018, so there should already be some reports submitted that contain the relevant annotations.
=> Fix bug 1434495 by surfacing module cert info from crash reports

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/crontabber_state.js
This fixes display of next run and last success so that it shows actual dates
and times rather than than a delta between then and now encoded in vague
English prose.
This also tweaks the sankey links so the lines have a fixed width making the
graph legible (at least, on my local machine). I think to fix this further
requires someone to really get to know sankey (which has no docs) or switch
libs or roll our own.
=> bug 1442148 - tweak crontabber state page

webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/home/jinja2/home/missing_product.html, webapp-django/crashstats/home/tests/test_views.py, webapp-django/crashstats/home/views.py
If you go to `/home/product/<PRODUCTNAME>` and that product doesn't exist, it
would kick up an unhelpful 404. Now it kicks up a 404, but with a bit more
text.
=> fix bug 1146030 - improve missing product page

webapp-django/crashstats/settings/base.py
see: https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/socorro/puppet/modules/socorro/templates/http_webapp.conf.erb#L35-L39 for uri
=> webapp: configure csp report uri

e2e-tests/Dockerfile
Full, passing ad-hoc build here: https://pastebin.com/qvb4dG5J
Just bumps us to the latest point release (which we've done on our other web-automation projects, now).
@willkg r?
=> Update to latest geckodriver, 0.20.1

socorro/signature/__main__.py, socorro/signature/rules.py, socorro/unittest/signature/test_rules.py
This fixes signature generation to ignore specifiers and return types when matching against the signature list.
=> fix bug 1448957 - ignore specifiers and return types in signature generation

socorro/scripts/fetch_crashids.py
* add "today" as a valid value for `--date`
* add "now" as a valid value for `--date` that is like "today", but
sets sort order to `-date` and adds cache-busting bits
=> fix bug 1453476 - add "today" and "now" to fetch_crashids

docker/config/local_dev_submitter.env, docker/run_tests_in_docker.sh, socorro/external/boto/connection_context.py, socorro/external/boto/crashstorage.py, socorro/external/es/super_search_fields.py, socorro/processor/breakpad_transform_rules.py, socorro/processor/processor_2015.py, socorro/processor/processor_app.py, socorro/schemas/crash_report.json, socorro/schemas/validate_and_test.py, socorro/unittest/external/boto/test_connection_context.py, socorro/unittest/external/boto/test_crashstorage.py, socorro/unittest/processor/test_breakpad_transform_rules.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/settings/base.py
This does two things:
1. remove all the keybuilder nonsense since it got in my way
2. add a processing rule for `MinidumpSha256Hash` and the bits required to make sure that field is indexed correctly in Elasticsearch, available for searching in super search, and in the telemetry crash report
=> fix bug 1275374, 1409427 - add minidump_sha256_hash to telemetry crash data

e2e-tests/Pipfile.lock
@davehunt @Osmose r?
Sorry, I broke this *somehow* (https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/socorro.adhoc/232/console); I verified it's fixed (again) both locally and remotely (passing ad-hoc in https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/socorro.adhoc/233/console).
The *now-fixed* Pipfile.lock's sha hash matches the error message about the expected value we're seeing in Jenkins:
Broken build, master:
```
07:47:40 Step 14 : RUN pipenv install --system --deploy
07:47:40  ---> Running in ebb25ba84a51
07:47:41 Aborting deploy.
**07:47:41 Your Pipfile.lock (8f9aeb) is out of date. Expected: (451ad5).**
07:47:41 The command '/bin/sh -c pipenv install --system --deploy' returned a non-zero code: 1
```
Fixed build, up-to-date master + PR:
Now seeing …
=> [e2e-tests] Fix/replace Pipfile.lock with correct, auto-generated version

README.rst
After the AWS account migration, the code in this repo is no longer
being used.  Since it is going to rot, stop directing people to it.
=> Remove link to deprecated infra code

alembic/versions/e70541df7ed7_bug_1458641_fix_reports_clean.py
The `reports-clean` crontabber app relies on a stored procedure that should have
been updated when we removed the `update_channels_map` table. This adds a migration
to do that.
=> fix bug 1458641: fix reports-clean crontabber app

.circleci/config.yml, scripts/deploy-dockerhub.sh
This re-adds the `deploy-dockerhub.sh` script which Circle needs to push the images it built to Dockerhub.
I looked to see if we were using it, but because the thing that mentions it is in `.circleci/config.yml`, and that starts with a `.`, it got skipped by ripgrep. Oops.
=> Fix bug 1450286: re-add deploy-dockerhub.sh script

socorro/cron/jobs/update_signatures.py, socorro/unittest/cron/jobs/test_update_signatures.py
`build_id` is stored as a numeric in the db, so we need to convert it
before saving it.
I'm puzzled as to why it worked locally and doesn't work on -stage. Maybe they're different versions of postgres? Maybe they're configured differently in some way I'm not aware of?
Anyhow, pretty sure this should fix it. It's trivial to verify on -stage.
=> fix bug 1375434: fix build_id storage

socorro/cron/jobs/update_signatures.py, socorro/unittest/cron/jobs/test_update_signatures.py
Some crashes don't have a build id which is why they don't "intify" well.
This skips those because we don't consider them when figuring out
first build and first date.
=> fix bug 1375434: handle crashes with no build id

e2e-tests/Dockerfile
This won't affect the Sauce-Labs run jobs in Jenkins, but will when run locally.
Build-log with previously-existing intermittent failure:
```
Stephens-MacBook-Pro:e2e-tests stephendonner$ docker run -it socorro-tests
=============================================== test session starts ===============================================
platform linux2 -- Python 2.7.12, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python2.7
cachedir: .pytest_cache
driver: Firefox
sensitiveurl: mozilla\.org
metadata: {'Python': '2.7.12', 'Driver': 'Firefox', 'Capabilities': {}, 'Base URL': 'https://crash-stats.allizom.org', 'Platform': 'Linux-4.9.87-linuxkit-aufs-x86_64-with-Ubuntu-16.04-xenial', 'Plugins': {'variables': '1.7.1', 'selenium': '1.12.0', 'xdist': '1.22.2', 'mozlog': '3.7', 'html': '1.17.0', …
```
=> Bug 1460134 - [e2e-tests] Update Firefox in Docker image to 60.0

docs/tests/system_checklist.rst
Just a few minor fixes, and a link to the /e2e-tests/ directory's README, off master.
I'm sure once I spend more time with this I'll have a few more.
@Osmose @willkg r?
=> Minor typo fixes; link to e2e-tests' README for running tests

e2e-tests/Jenkinsfile
Bumps us up to Firefox 60.0 in Sauce Labs.
@davehunt @willkg @Osmose r?
Passing adhoc build against prod, here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/socorro.adhoc/237/
=> Fix bug 1460517: [e2e-tests] Update to Firefox 60.0 in Sauce Labs

e2e-tests/pages/crash_stats_top_crashers_page.py, e2e-tests/tests/test_crash_reports.py
@davehunt @Osmose @willkg r?
Ad-hoc job here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/socorro.adhoc/244/console
=> Bug 1461889 - [e2e-tests] Remove test_that_only_(plugin, browser)_reports_have_(plugin, browser)_icon tests

alembic/versions/fd76c8bb0d78_bug_1459276_reports.py
This fixes the migration to account for `reports_user_info` being a partitioned
table.
Second verse, same as the first.
=> bug 1459276: fix migration problem with reports_user_info

.gitignore, Makefile, docker-compose.yml, docker/Dockerfile.python3, docker/config/test.env, docker/run_tests.sh, docker/run_tests_in_docker.sh, docker/run_tests_python3.sh, requirements/constraints.txt, requirements/default.txt, socorro/external/es/supersearch.py, socorro/external/postgresql/connection_context.py, socorro/external/postgresql/setupdb_app.py, socorro/external/rabbitmq/crashstorage.py, webapp-django/crashstats/crashstats/form_fields.py, webapp-django/crashstats/crashstats/utils.py, webapp-django/crashstats/settings/base.py, webapp-django/crashstats/settings/bundles.py
This adds a couple of make rules and shell scripts to give us scaffolding
with which we can iterate over fixing code to make it work in both
Python 2 and Python 3.
In order to get the tests to run at all, I had to fix a bunch of Python
3 issues. I also hoisted six to first-class dependency status.
This doesn't connect that with CI because linting fails epically. We'll do
that later.
=> fix bug 1460035: implement python 3 test scaffolding

webapp-django/crashstats/base/jinja2/crashstats_base.html
Fixes: https://bugzilla.mozilla.org/show_bug.cgi?id=1461464
Crash Stats uses Google Sign-In, so it is helpful to know which account is signed in on every page.
- Added the user email on bottom right of every page if the user is logged in
- Should the tooltip on the `Your Profile` link be removed? It says `You are signed in as {{ request.user.email }}`, so it seems slightly redundant now.
- Should the placement or wording around the address be changed? For example, it could be: `Your are signed as {{ request.user.email }}` instead of just the email address.
=> Started showing the user's Google Sign-In email address on every page.

CONTRIBUTING.rst, docs/index.rst
I need a place I can point new contributors to that makes sure they're
ready to contribute. This adds that.
=> Tweak contributor docs

socorro/signature/rules.py, socorro/unittest/signature/test_rules.py
This includes the commits from PR #4466, but signed by me.
We just enabled "require signed commits" on the repo, so we have to figure out the workflow for working around that for contributors. I think this might be the best one that doesn't require us to change how people normally contribute.
To "test" this, you can either take my word for it (I used `git cherry-pick`) or verify it's the same changes that are in PR #4466.
=> fix bug 1440233 - ignore rust hashes in signature generation

socorro/siglists/prefix_signature_re.txt
This adds wcsrtombs to the prefix list so signature generation continues.
Example output:
```
you@processor:/app$ python -m socorro.signature 129cbcd4-248a-45c9-9b89-3a4460180604
Crash id: 129cbcd4-248a-45c9-9b89-3a4460180604
Original: wcsrtombs
New:      wcsrtombs | wcsrtombs | wcsrtombs | js::CloneFunctionReuseScript
```
=> fix bug 1465908: add wcsrtombs to prefix list

e2e-tests/Pipfile, e2e-tests/Pipfile.lock
Ad-hoc build here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/socorro.adhoc/255/console
And sorry, not (really) sorry; a point release to pytest snuck in too - but IMHO we might as well take it, here?
@Osmose @willkg @davehunt r?
=> Fix bug 1467567, by adding 'future' to our requirements for Python 2

docs/service/webapp.rst
- added --service-ports to webapp docs on how to debug
- `--service-ports` allows ports to be exposed, so the website can be visited
- this should be more intuitive for people reading the documentation
=> added --service-ports to webapp docs on how to debug

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/reprocessing.js
fixes bug https://bugzilla.mozilla.org/show_bug.cgi?id=1467412
- updated crash reprocessing jQuery notation in `reprocessing.js`
- when doing a crash reprocess, JavaScript type errors could appear in the console because:
- as of jQuery 3.0, `jqXHR.error()`, and `jqXHR.complete()` callback methods were replaced by `jqXHR.fail()`, and `jqXHR.always()`
- documentation: https://api.jquery.com/jquery.post/
1. do the whole socorro setup and process some crashes: https://socorro.readthedocs.io/en/latest/service/processor.html#example-using-all-the-scripts
2. give your user `crashstats.reprocess_crashes` permission or change instances of the string `request.user.has_perm('crashstats.reprocess_crashes')` to the string `True` in `report_index.html`
3. press the `Reprocess this crash` button
4. see …
=> fix bug 1467412: updated crash reprocessing jQuery notation

.circleci/config.yml
`docker:stable` is based on alpine, hence changing package manager invocations.
`curl` is no longer needed.
=> Bug 1468435: circle config: switch base image to docker:stable, install compose via pip

socorro/unittest/siglists/test_siglists.py, socorro/unittest/signature/test_rules.py
This nixes the use of TestCaseBase which makes the siglists tests more
portable.
This also fixes the signature tests which were instantiating SignatureTool
classes. Those classes don't take a config anymore, so these tests shouldn't
be passing in config anymore.
=> bug 1463756: minor cleanup to signature tests

e2e-tests/Dockerfile
Here's a local build, with the same, pre-existing single failure (in the Docker run) testsuite: https://gist.github.com/stephendonner/fe911ccddec03da386cd61a8767a6e62
Sauce Labs (which is what Jenkins uses, currently) is fine: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/socorro.adhoc/267/console (https://gist.github.com/stephendonner/65dd3fb88e125354f2838776f43125a5)
@Osmose @davehunt r?
=> Fix bug 1469443 [e2e-tests] - Update geckodriver to latest, 0.21.0

socorro/external/boto/crash_data.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/tests/test_models.py
fixes bug https://bugzilla.mozilla.org/show_bug.cgi?id=1467280
- RawCrash API does not handle malformed crash IDs well. It does extra work and returns `500`
- started returning 404 on RawCrash API requests with malformed crash IDs
=> fix bug 1467280: started returning 404 on RawCrash API requests with malformed crash IDs

.circleci/config.yml, Makefile, docker/run_lint.sh, docker/run_tests.sh
This fixes linting and testing so there's a single make rule for linting and
one for testing. This fixes Circle configuration so it runs both.
To test:
1. run `make lint`
2. run `make test`
3. make sure Circle ran both lint and test
=> fix bug 1468763: fix lint and test rules

.circleci/config.yml
fixes bug https://bugzilla.mozilla.org/show_bug.cgi?id=1460708
- added one step in the CI to run the tests in Python 3
- only some tests have been set as passing Python 3 through `https://github.com/mozilla-services/socorro/blob/master/docker/run_tests_python3.sh`
- we are in the process of transitioning from Python 2 to 3
- we want to make sure that things currently working stay that way
- thus, we want to run the tests in Python 3 in addition to what we currently have
It seems that `make dockertest3` automatically builds the `socorro_python3` image since `.docker-build3` is set as a prerequisite.  I guess `make dockerbuild3` could be added instead explicitly to the `Build Docker images` CI step instead, or as a command in the `Run tests in Python 3` step.
=> fix bug 1460708: added Python 3 test running to CI

webapp-django/crashstats/profile/jinja2/profile/profile.html
All the pages on crash stats have a link to the admin in the footer. There's
no need to have admin links sprinkled around the site. They're not chocolate
chips.
This removes some from the profile page which were erroring out after I
nixed the "manage:home" view.
=> fix bug 1469978: nix all the admin links

docker/run_tests_python3.sh, socorro/lib/threaded_task_manager.py, socorro/lib/util.py, socorro/unittest/lib/test_task_manager.py, socorro/unittest/lib/test_threaded_task_manager.py, socorro/unittest/lib/test_treelib.py
Modified socorro.lib folder to pass python 3 testing. 
Errors fixed: 
* An error occurred when reporting class names and descriptions of expected results in test functions. This changed from python 2 to 3. Python 2 returned the class name and the value of the error. Python 3 returned a qualified class name(absolute reference) and the value of the error. So we modified test expectation to just return its value and removed a redundant verification of the error type. 
* We then resolved implementation difference of range() function between python 2 and 3 by converting the iterator generated in python 3 to a list for value comparison. 
* Fixed import changes in python 2 to 3 using the six lib. 
* Lastly we fixed a function that sanitized strings to return as the default type of string in the …
=> fix bug 1467308 update socorro.lib

scripts/deploy_bug.py
The `deploy_bug.py` script spits out all the commits that will get deployed.
This adjusts that output to also specify the authors. The hope is that
this makes it easier to figure out who needs to verify what before a
prod deploy.
Example of old output:
```
323c77c: bug 1462749: move graphics devices to django admin
f24fa3c: fix bug 1462749: remove last vestiges of old admin
d820f11: Fix create_recent_indices_app to create last 2 weeks
```
Example of new output:
```
323c77c: bug 1462749: move graphics devices to django admin (willkg)
f24fa3c: fix bug 1462749: remove last vestiges of old admin (willkg)
d820f11: Fix create_recent_indices_app to create last 2 weeks (willkg)
```
It's showing the github username of the person. For us, I think that will generally work. We could show something …
=> Fix deploy_bug.py to show authors

socorro/signature/rules.py, socorro/unittest/signature/test_rules.py
I fixed `OOMSignature#action` to catch `ValueError`.
I added a test in `test_rules.py`. Could you check it? Thanks.
=> Bug 1393037 Catch ValueError on raw_crash.OOMAllocationSize conversion

webapp-django/crashstats/signature/jinja2/signature/signature_summary.html, webapp-django/crashstats/signature/static/signature/css/signature_report.less, webapp-django/crashstats/signature/tests/test_views.py, webapp-django/crashstats/signature/views.py
fixes bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1436702
- made the Signature Summary tab Product table respect the selected filters for the signature report
Previously, this table had behavior different from the other tables to make it display data from the last 7 days instead of the data range specified in the filters.
- this was a specific request of a crash investigator that is no longer here
- this created confusion for users
1. process the following crashes:
```
99ead0d8-891f-443e-839a-fd2410180619
237d327b-6ef5-4d7c-bf54-77f040180619
59533cca-a632-4b24-8390-336830180619
b0e81e01-edd3-4db0-81fe-369ee0180618
a98fb7fd-44a1-435a-9a54-03eae0180618
ee829ff0-330f-4fbf-8637-fef9d0180618
f7d0972b-1973-4c11-9498-21ee50180618
```
here are the dates associated with these crashes:
``` …
```
=> fix bug 1436702: made the Signature Summary tab Product table respect the selected filters 

socorro/external/boto/connection_context.py, socorro/external/boto/crashstorage.py, socorro/external/es/crashstorage.py, socorro/unittest/external/boto/test_connection_context.py, socorro/unittest/external/es/test_crashstorage.py
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1454482
This patch is a work in progress.
This patch is based off #4391.
- added metric for the time to index a crash
- successes and failures have a different metric
- provide better timing data for document indexing in elasticsearch
@sciurus I can make other changes within this patch. Does this patch still make sense? What other things would it be helpful to have timings on?
=> bug 1454482: add timing captures for ES

socorro/signature/__main__.py
This fixes a bug created when I switched the code from `tree_get` to
`glom`. `glom` requires the default to be a keyword argument.
=> bug 1460447: fix errant glom call

socorro/signature/siglists/irrelevant_signature_re.txt, socorro/signature/siglists/prefix_signature_re.txt
fixes bug https://bugzilla.mozilla.org/show_bug.cgi?id=1471379
- moved `CrashReporter::TerminateHandler` from the prefix to the irrelevant list
- added 3 new signatures to the irrelevant list
When looking at the crashes for the signature https://crash-stats.mozilla.com/report/index/4943e3d5-4e4a-4c83-b627-a41330180606, users indicated that they wished that the crashes could be better differentiated in https://bugzilla.mozilla.org/show_bug.cgi?id=1467582.
Here are example signature differences:
https://crash-stats.mozilla.com/report/index/4943e3d5-4e4a-4c83-b627-a41330180606
```
Crash id: 4943e3d5-4e4a-4c83-b627-a41330180606
Original: CrashReporter::TerminateHandler | std::__terminate
New:      CFPasteboardPromiseDataUsingBlock
``` …
=> fix bug 1471379: updated signature lists

docker/run_tests_python3.sh, socorro/external/boto/connection_context.py, socorro/external/boto/crashstorage.py, socorro/external/crashstorage_base.py, socorro/unittest/external/boto/test_crash_data.py, socorro/unittest/external/boto/test_crashstorage.py
In testing the raw dump data there was an error in the test value
returning as a binary string. This value was failing in comparison to
the expected unicode value for python 3. Placing print statements in
class level functions didn’t tell us much.So we traced the function from
top to bottom and bottom to top. This pushed over the deep end as we
found ourselves in the boto service source code. We couldn’t find the
exact time this conversion of the test value occurred. To solve this
issue we made the assumption data being used in raw dump is binary. So
we change the test value to be a binary string and also changed the
expected comparison to be a binary string as well. The implementation of
the function iteritems() changed from python 2 to 3. Similar to the
range function the change in …
=> bug 1469718: all the changes for sub dir socorro.external.boto

webapp-django/crashstats/base/jinja2/crashstats_base.html
fix bug https://bugzilla.mozilla.org/show_bug.cgi?id=1474368: preserve URL params after login
- we want to preserve query parameters when going back to the original page after a login
- this problem was introduced in #4471 when switching from Google Sign-In to OpenID Connect
- changed the login link to include the full path with query parameters instead of the just the path
1. be logged out
2. go to a signature page (/signature/?...)
3. click the `Login` button and complete the login
4. expect to back to the same signature page instead of being taken to a page that display indicating that a parameter is required
=>  fix bug 1474368: preserve URL params after login 

CONTRIBUTING.rst, docker/run_lint.sh, docker/run_tests.sh, jest.config.js, webapp-django/.babelrc, webapp-django/.eslintignore, webapp-django/package-lock.json, webapp-django/package.json, webapp-django/staticfiles/.eslintrc, webapp-django/staticfiles/index.js, webapp-django/staticfiles/report-index/index.js, webapp-django/staticfiles/report-index/page-heading/index.js, webapp-django/staticfiles/report-index/page-heading/page-heading.test.js, webapp-django/staticfiles/setup-tests.js, webapp-django/webpack.config.js
fixes bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1474441.
The base branch is updated version of #4494 
- we want to be able to run tests against the new React-based front end
in order to ensure quality
- added Jest and Ezyme to the project
- added file to set up the Jest tests
- added documentation on how to run Jest tests
- added temporarily barebones ReportIndex React component
- added PageHeading React component
- added Enzyme tests for this component
1. `make build` to have new `node_modules`
2. visit `/report/index/< crashId >/new` and expect to see the same thing as the image below
3. run `make test` and expect the tests to succeed
4. try to follow the new documentation on running the tests in the shell
=> fix bug 1474441: added Jest and Enzyme

socorro/signature/siglists/irrelevant_signature_re.txt
"__fixunsdfsi" is a compiler intrinsic for floating point number conversions. There are many other floating point intrinsic functions, but for now we can just add this one. We're seeing crashes on Android ARM devices, like [Firefox bug 1475482](https://bugzilla.mozilla.org/show_bug.cgi?id=1475482).
https://gcc.gnu.org/onlinedocs/gccint/Soft-float-library-routines.html
=> fix bug 1475482 - Skip "__fixunsdfsi"

webapp-django/crashstats/base/jinja2/macros/signature_startup_icons.html, webapp-django/crashstats/base/tests/test_utils.py, webapp-django/crashstats/base/utils.py, webapp-django/crashstats/signature/jinja2/signature/signature_summary.html, webapp-django/crashstats/signature/static/signature/css/signature_report.less, webapp-django/crashstats/signature/views.py, webapp-django/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html, webapp-django/crashstats/topcrashers/views.py
fixes bug https://bugzilla.mozilla.org/show_bug.cgi?id=1344864
- being able to distinguish startup crashes from non-startup crashes is useful
- added icons and text to the signature summary tab that indicate startup crash statistics
- these are the same icons as those found on the topcrashers page
I split the changes into three commits:
- first commit does the refactoring of topcrashers
- needed to extract some of the functionality used to generate topcrashers data because part of it will be used to generate signature summary data
- started generating data through classes instead of a dictionary
- extracted computations into methods
- this extraction should also be useful for https://bugzilla.mozilla.org/show_bug.cgi?id=1472335
- second commit adds the startup stats to the signature …
=> fix bug 1344864: added startup stats to the signature summary

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/middleware.py, webapp-django/crashstats/crashstats/tests/test_middleware.py, webapp-django/crashstats/settings/base.py
This switches the middleware from looking at the `X_FORWARDED_FOR` header
and all its interetingness to looking at the `X_REAL_IP` header which
is set by nginx module we're using.
=> fix bug 1476697: switch from X_FORWARDED_FOR to X_REAL_IP

socorro/signature/siglists/irrelevant_signature_re.txt, socorro/signature/siglists/prefix_signature_re.txt, socorro/signature/siglists/signature_sentinels.txt
* removes `std::panicking::*` from the prefix list because that's covered
in the irrelevant list, so it doesn't have any effect
* add `panic_abort::` to the irrelevant list so it gets skipped over
=> bug 1475820: tweak rust panic symbols in siglists

Makefile, docker/run_ftpscraper_wrapper.sh, docker/run_update_data.sh, docs/gettingstarted.rst, setup.cfg, socorro-cmd, socorro/cron/jobs/ftpscraper.py, socorro/scripts/__init__.py, socorro/scripts/add_crashid_to_queue.py, socorro/scripts/replay_ftpscraper.py, socorro/unittest/scripts/__init__.py, socorro/unittest/scripts/test_add_crashid_to_queue.py, socorro/unittest/scripts/test_replay_ftpscraper.py
This adds a ftpscraper wrapper script to be used in local development environment which keeps a log of ftpscraper and if the log is less than 7 days old, it'll just replay the log on the next run.
For me, it takes 10 minutes to run ftpscraper. On the second run, replaying the log takes about 10 seconds. This radically reduces the amount of time it takes to slick and rebuild my local development environment which I do a lot.
To test:
1. run `make setup` which slicks the db and everything
2. run `make updatedata` which runs ftpscraper and will create an ftpscraper log in `./.cache/ftpscraper.log`
3. run `make setup` which slicks the db again
4. run `make updatedata` which will replay the ftpscraper log
=> fix bug 1478741: add ftpscraper wrapper

socorro/lib/raven_client.py, socorro/processor/mozilla_transform_rules.py, socorro/processor/processor_app.py, socorro/signature/generator.py, socorro/unittest/__init__.py, socorro/unittest/processor/__init__.py, socorro/unittest/processor/test_breakpad_transform_rules.py, socorro/unittest/processor/test_general_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py, socorro/unittest/processor/test_processor_app.py, socorro/unittest/signature/test_signature_generator.py
This does two big things:
1. clean up a bunch of processor code in regards to redundant setup
2. unify the two "let's capture something and send it to sentry" mechanisms we had and also fix them to use `exc_info` rather than exception values
This gives us two nice things:
1. the signature generation code no longer has anything about sentry in it--that's helpful for merging the two forks of signature generation
2. we can reuse send-this-to-sentry in other parts of the processor which was previous hard-ish
=> fix bug 1479097: sentry cleanup in processor

webapp-django/crashstats/crashstats/views.py
As pointed out by @willkg, the uses for these lines of code were removed in https://github.com/mozilla-services/socorro/commit/6a73678611b5dd63f7c10154128e8d0a6fd330f8.
=> removed unused code from report_index

webapp-django/crashstats/authentication/management/commands/auditgroups.py, webapp-django/crashstats/authentication/tests/test_auditgroups.py
This changes the dryrun argument for the auditgroups command to a "persist"
argument. It also fixes the argument value parsing which was busted before.
=> bug 1477782: change dryrun to persist

webapp-django/crashstats/settings/base.py
The search page does XHR requests when switching between searches. Other
pages do similar things. When the SessionRefresh middleware handles those
requests, it can return a 403 or a redirect, but the js can't handle that.
This fixes the SessionRefresh middleware to ignore those urls and not
refresh the session on them.
=> fix bug 1473068: fix session refresh errors with xhr

socorro/signature/siglists/prefix_signature_re.txt
Signature generation output:
```
app@processor:/app$ socorro-cmd signature 84b9b036-f933-4df2-b8cc-9b4170180703 5e440243-dd5c-4987-97df-1a6340180723
Crash id: 84b9b036-f933-4df2-b8cc-9b4170180703
Original: static void std::alloc::rust_oom
New:      static void std::alloc::rust_oom | static struct style::media_queries::media_list::MediaList style::media_queries::media_list::MediaList::parse
Crash id: 5e440243-dd5c-4987-97df-1a6340180723
Original: static void std::alloc::rust_oom
New:      static void std::alloc::rust_oom | static void rayon::iter::plumbing::bridge_producer_consumer::helper<T>
```
=> fix bug 1477726: add std::alloc::rust_oom to prefix list

webapp-django/crashstats/settings/base.py
This adds another url used by the supersearch page to the exempt urls
list.
=> fix bug 1473068: fix session refresh errors with xhr (buginfo)

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
I recently refactored signature generation using the code from the
socorro-siggen fork. One thing I missed was making sure `proto_signature`
made it into the processed crash.
This fixes that bug, adds a test to make sure everything that needs
to be in the processed crash makes it there, and fixes the spelling
of "canonical".
=> fix bug 1481828: fix proto_signature in SignatureGeneratorRule

webapp-django/crashstats/api/jinja2/api/documentation.html
This adds the js that the page needs that got removed in the docs overhaul.
=> fix bug 1481302: fix API test drive button

socorro/signature/rules.py, socorro/signature/tests/test_rules.py, socorro/signature/utils.py
Previously, the code assumed the source file was something like `"foo.rs"`.
That was horrifically wrong. This fixes that.
=> fix bug 1481282: correctly normalize frames based on source file

alembic/versions/9f7bb4445d7a_bug_1483318_inactive_products.py, socorro/external/postgresql/models.py, socorro/external/postgresql/staticdata.py, webapp-django/crashstats/crashstats/utils.py
This fixes the code so that it doesn't show inactive products in the listing. It also goes through and updates the "sort" column of the "products" table so that all products except specified ones are now inactive.
=> fix bug 1483318: don't show inactive products

.circleci/config.yml
The Python 3 tests step takes 4 minutes to run out of 18 minutes for an
entire CI pass. That's signficant.
We're putting Python 3 work on the back burner for now becuase we've got
other things to work on. It'll save us a lot of time to stop running
the Python 3 tests in CI for now. We'll re-enable them when Python 3
work is on the front burner again.
=> fix bug 1483564: comment out Python 3 tests

alembic/versions/b8da3a85f665_bug_1481696_focus.py, webapp-django/crashstats/crashstats/utils.py
This adds Focus as a supported product.
This also fixes a problem in local development environments where if you
haven't set up ES, it causes the product home page to throw HTTP 500s.
=> bug 1481696: add focus

socorro/signature/rules.py, socorro/signature/tests/test_rules.py, socorro/signature/tests/test_utils.py, socorro/signature/utils.py
This reimplements collapse, adds documentation, adds tests, and fixes the case where it shouldn't collapse a rust trait method.
=> fix bug 1477013: fix signature generation for rust trait methods

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
This reworks the ProductRewrite rule so it logs what it did in the crash
report better. It also adjusts the rule to act as a "this is where we're
going to do all the product rewriting" place.
This adds product rewriting logic for Focus GV. That's using GeckoView,
but incoming crash reports are using `ProductName=Fennec`. So the ProductRewrite
rule was convering those to FennecAndroid. This will then convert it to
Focus if the `ProcessType=content`.
We should remove this as soon as we can, but it'll fix an existing issue
we have right now.
=> bug 1481696: add processor rule to fix Focus crashes

socorro/signature/rules.py, socorro/signature/tests/test_rules.py, socorro/signature/tests/test_utils.py, socorro/signature/utils.py
Symbols for Linux and OSX don't have prefixes and return types, but symbols
for Windows do now (this wasn't the case until recently). That creates
a problem where signature's aren't matching between the platforms.
On Windows you might get this:
void mozilla::layers::Grouper::ConstructGroupInsideInactive
On Linux and OSX you'd get this:
mozilla::layers::Grouper::ConstructGroupInsideInactive
This fixes that by stripping prefixes (static, etc) and return types
(void, void *, etc) from function signatures during normalization.
=> fix bug 1478383: drop prefix and return type in function signatures

setup.py, socorro/app/socorro_app.py, socorro/lib/raven_client.py, socorro/lib/revision_data.py, socorro/unittest/processor/test_mozilla_transform_rules.py, webapp-django/crashstats/settings/base.py
In the old infrastructure, we had a "socorro_revision.txt" file that
was generated when we built the socorro package. We don't do that anymore.
Now we generate a version.json file when socorro is deployed.
This updates the revision acquiring code to use the correct file.
=> fix bug 1485411: fix revision information acquisition

socorro/lib/raven_client.py, socorro/lib/revision_data.py, socorro/unittest/processor/test_mozilla_transform_rules.py, webapp-django/crashstats/settings/base.py
When Socorro deploys to stage, there's no git tag, so the version is "".
Since that's a value in the dict, it never gets set to "unknown" so
then it doesn't get sent to sentry. It'd be better if we sent the
commit sha in this case.
=> fix bug 1485411: fix revision in sentry in stage

socorro/external/es/index_creator.py, socorro/external/es/super_search_fields.py, socorro/unittest/external/es/test_super_search_fields.py
This adds `doc_values=True` to fields that are either not strings or explicitly
have `index=not_analyzed`. Per the ES docs, this will cause ES to store data
on disk for sorting and aggregations rather than in memory which should
reduce some of our memory problems when doing aggregations.
=> fix bug 1323033: add doc_values=True to ES mapping

socorro/external/es/super_search_fields.py, socorro/unittest/external/es/test_super_search_fields.py
Elasticsearch 1.4 seems to drop `doc_values=True` for boolean fields as
observed by the mapping we use to create the index has these properties,
but the mapping we get when querying Elasticsearch afterwards doesn't.
The documentation suggests boolean values should work with `doc_values=True`.
Given that, we're going to re-add it since it doesn't seem to break
anything even if it has no effect.
=> bug 1323033: Apply doc_values=True to boolean fields

docker/config/my.env.dist
In a local development environment, you probably don't want 16
processor threads running. You're much more likely to want something
like 2.
This makes that change to my.env.dist. Developers can change the
number to meet their specific needs.
=> fix bug 1436063: set processor threads in my.env.dist

docker/run_tests_python3.sh, socorro/signature/rules.py, socorro/signature/tests/test_siglists.py, socorro/signature/tests/test_utils.py
* remove a couple of files from the list of files to test in python 3
that don't exist anymore
* fix issues with signature generation code and tests that caused
them to fail in python 3
=> Fix signature generation with python 3

webapp-django/crashstats/topcrashers/views.py
If we add a new product, but it hasn't gotten any crash reports, then
there are no versions and topcrashers errors out.
The version it needs it solely to figure out which version to select
in the drop down menu. So we set it to "" if there are no versions.
=> fix bug 1487381: fix topcrasher IndexError bug

webapp-django/crashstats/api/jinja2/api/documentation.html
SuperSearch is super super super long. Having a table of contents at the
top of the page makes it much easier to see which APIs are available
and also get to that part of the page quickly without excessive scrolling.
=> Add table of contents to API documentation

Makefile
9 out of 10 socorro engineers don't build docs on a regular basis, so it
doesn't make sense to spend time building the image for building docs
every time someone runs "make build".
This adjusts things so building the docs image is done when only when
building the docs.
=> Adjust docs building so "make build" doesn't build docs image

docker/config/local_dev.env, socorro/external/postgresql/version_string.py, socorro/lib/cache.py, socorro/lib/datetimeutil.py, socorro/processor/mozilla_transform_rules.py, socorro/processor/processor_2015.py, socorro/unittest/lib/test_cache.py, socorro/unittest/processor/test_mozilla_transform_rules.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/models.py
This:
1. creates a webapp API called `VersionString` that returns ... well, ... version strings
2. creates a new `ExpiringCache` that has a ttl in addition to max size because we didn't have one and I wasn't enamored with the ones I saw (though cachetools might be a good choice)
3. rewrites the `BetaVersionRule` to use the new cache and new `VersionString` API
To test:
1. go to `http://localhost:8000/api/` and test the `VersionString` API using product/version/builds
2. set `processor.version_string_api` to `http://webapp:8000/api/VersionString/` in your `my.env` file, then process a recent crash from the beta channel with a build that's in your db and make sure it gets the right version
=> fix bug 1346891: betaversionrule

socorro/processor/mozilla_transform_rules.py
Incoming FirefoxReality crash reports have the wrong ProductName, so they're
getting put in the FennecAndroid bin. This rewrites the ProductName for crash
reports that have `Android_Manufacturer=Oculus` to FirefoxReality.
=> fix bug 1474037: add rewrite rule for FirefoxReality

socorro/processor/mozilla_transform_rules.py
This removes the FirefoxReality processor ProductRewrite bit. It's not correct and we don't need it, so this nixes it.
=> fix bug 1474037: revert FirefoxReality processor rule change

webapp-django/crashstats/crashstats/tests/test_utils.py, webapp-django/crashstats/crashstats/utils.py
For products that don't have build information in `product_versions` table,
we pull versions for crash reports from Elasticsearch. This increases the
window we look at when doing that.
=> fix bug 1491431: get versions from bigger window

docker-compose.yml, socorro/processor/processor_2015.py, socorro/processor/processor_app.py
The processor no longer needs postgres to function. This removes the
configuration from the app and the service from the docker-compose file
(which only affects the local development environment).
There are also a couple of cosmetic tweaks to code because I just
couldn't help myself.
=> fix bug 1346883: remove postgres from processor

socorro/signature/rules.py, socorro/signature/tests/test_rules.py
This adjusts the code to remove `const` at the end of function names
to also remove ref qualifiers `const&`, `&`, and `&&`. That way they
don't interact poorly with the code that removes types and specifiers.
=> fix bug 1488774: remove cv/ref qualifiers in function names

socorro/signature/rules.py, socorro/signature/tests/test_utils.py, socorro/signature/utils.py
There were two situations and a bug that were causing signature
generation to generate signatures of an empty string.
The bug was stomping on the signature regardless of what `CSignatureTool`
figured out. We only want to stomp on the signature if we have a valid
signature. That's fixed in this commit.
The two situations that weren't handled correctly both involve a space
between the last token and the previous token where the two tokens
together are the function name, args, and some `[clone .cold.xyz]` suffix.
This fixes that by making sure we're not losing bits.
=> fix bug 1493200: fix empty string signature generation

socorro/processor/general_transform_rules.py, socorro/unittest/processor/test_general_transform_rules.py
If an `os_name` can't be pulled from the minidump for whatever reason,
then set it to `"Unknown"` which works with the webapp interface better
rather than `""` which doesn't. This allows us to search for these
crashes and it makes it clearer that Socorro wasn't able to figure
out the `os_name` rather than who-knows-what-happened.
Also, this switches the `OSInfoRule` to use glom and getitem notation.
=> fixi bug 1389197: fix os_name to be "Unknown" and not empty string

alembic/versions/84445597d92f_1459216_drop_signature_products.py, socorro/external/postgresql/models.py
We don't use these tables anymore, so we should remove them.
=> fix bug 1459216: drop signature_products and signature_products_rollup

socorro/lib/transform_rules.py
Processor transform rules are part of the processor so the key should
start with "processor". This fixes that.
=> fix bug 1470704: fix rule metrics key

socorro/signature/rules.py, socorro/signature/tests/test_rules.py
For this one kind of operator overloading, it ends up with this signature
that breaks the expectations for the `drop_prefix_and_return_type` code.
So instead of running that, we skip it. That prevents it from turning
into `"&"`.
=> fix bug 1488774: fix another cause of & signatures

socorro/signature/tests/test_utils.py, socorro/signature/utils.py
It's possible for the function name to end with not one, but TWO
`[clone .cold.xxx]` things. This fixes the handling to cover that.
=> fix bug 1493200: fix the double-clone vexing variation

socorro/signature/tests/test_utils.py, socorro/signature/utils.py
The token merging should only happen if there are at least two tokens. This
fixes that.
=> fix bug 1493200: fix an infinite loop

scripts/1463121-signatures-migration.sql
Prod came from an alternate reality where the laws of unique constraints
are somehow different. This reworks the data migration to deal with that
and while I was doing that, I figured I'd add better comments and better
data migration hygiene.
=> bug 1463121: fix data migration script to work in prod

webapp-django/crashstats/manage/admin.py
This will make it easier to verify that the `crashstats_signature` table
is growing at the same pace as the `signatures` table. Further, it shows
all the tables in the db so it'll surface other possible issues like whether
there are tables that shouldn't be there.
=> bug 1463121: Add row counts for non-pg tables to debug view

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/tests/test_views.py
The implementation cache was helpful once, but I don't think it's helpful
anymore. It does cache mocks and other things, so it seems more trouble
than it's worth, so I'm removing it for now.
=> fix bug 1496495: remove implementation cache in webapp

docker/run_tests_python3.sh, docs/crashstorage/crashstorage.rst, docs/socorro_app.rst, socorro/cron/crontabber_app.py, socorro/cron/jobs/bugzilla.py, socorro/cron/mixins.py, socorro/external/boto/crashstorage.py, socorro/external/es/crashstorage.py, socorro/external/postgresql/base.py, socorro/external/postgresql/dbapi2_util.py, socorro/external/rabbitmq/crashstorage.py, socorro/lib/transaction.py, socorro/processor/processor_2015.py, socorro/unittest/external/rabbitmq/test_crashstorage.py, socorro/unittest/lib/test_transaction.py
When we vendored crontabber, we added a clause to the exception handling
in the `transaction_executor` which crontabber had in its version. This
fixes that code so it's not importing the postgres code. That way
it's generalized again.
Additionally, this removes code and tests for the `abandon_transaction`
feature that isn't used.
=> Clean up transaction_executor

socorro/lib/javautil.py, socorro/unittest/lib/test_javautil.py, socorro/unittest/processor/test_mozilla_transform_rules.py
This fixes java stacktrace parsing to handle cases where there's an exception
class, but no message. Previously, this would raise a `MalformedJavaStackTrace`
exception. Now it should parse correctly.
=> fix bug 1497131: fix java stacktrace parsing for no message case

socorro/signature/siglists/prefix_signature_re.txt
Signature generation output:
```
app@socorro:/app$ socorro-cmd signature ccc7caae-6430-4c35-89a2-ebe720181004
Crash id: ccc7caae-6430-4c35-89a2-ebe720181004
Original: mbrtoc32
New:      mbrtoc32 | mozilla::URLPreloader::BackgroundReadFiles
```
=> fix bug 1496732: add mbrtoc32 to prefix list

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py, webapp-django/crashstats/crashstats/utils.py, webapp-django/crashstats/signature/views.py
This reworks `get_pairs` to do a single SQL query. It also ditches all the
caching work which I think is done at the wrong granularity.
=> bug 1457747: rewrite GraphicsDeviceManager.get_pairs()

webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/utils.py
This fixes a `KeyError` from the last PR. Further, I adjusted the output of the hex vs. name in the report view to match what we do in the signature report.
=> bug 1457747: fix KeyError issue in report_index view

webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_models.py
This was the one minor difference between the rewrite I did which is on stage and the old code which is in prod.
=> bug 1493768: fix ordering of /api/Bugs results

socorro/external/postgresql/version_string.py, socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/crashstats/models.py
This fixes the problem with b99 where there are two different version
strings and the VersionString API code picked the "first" one, but it's
unsorted, so it's really a random one and random isn't awesome here.
=> fix bug 1499714: further restrict VersionString by channel

webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report.js
This changes the Telemetry Environment pane to show the raw value in the
case where the JSON doesn't parse.
This doesn't fix the original problem. I'm still fuzzy as to whether the data coming in is already broken or whether it breaks in the myriad of transformation, escaping, and unescaping passes it goes through. We can push figuring that off until later.
=> bug 1491778: show raw value when TelemetryEnvironment doesn't parse

webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/crashstats/models.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/crashstats/utils.py, webapp-django/crashstats/manage/admin.py, webapp-django/crashstats/supersearch/views.py
This fixes the API code so that it can use model_name and model_name +
"Middleware" when looking up models for handling. This allows us
more leeway when naming middleware api classes.
=> fix bug 1501346: fix api use of classnames

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
We no longer need to rewrite incoming Focus crashes, so we can remove
this rule now.
=> fix bug 1484755: remove Focus rewrite rule

socorro/lib/versionutil.py, socorro/unittest/lib/test_versionutil.py, webapp-django/crashstats/crashstats/tests/test_utils.py, webapp-django/crashstats/crashstats/utils.py
This handles the kinds of versions we have on Crash Stats including
"catch-all" versions like 62.0b which covers all the betas. Rewriting
it allows us to save it to the db as a string and also use it
elsewhere in the code.
=> fix bug 1502038: rework version sorting

socorro/lib/versionutil.py, socorro/unittest/lib/test_versionutil.py, webapp-django/crashstats/crashstats/utils.py
The previous nav bar iteration handled bad versions better than the rewrite.
This fixes the rewrite so it's on par, though I think it's actually better
in that bad versions are junked at the start rather than let through.
=> fix bug 1502038: handle bad versions

socorro/processor/mozilla_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
Previously, we tossed on a b99, but it turns out that Buildhub had the right
version, but because we were doing a limit 1 and not sorting, it'd
intermittently come up with the right version and the wrong version. Yay!
This fixes that and ditches the whole b99 thing and now we're in a much better
place!
=> fix bug 1501780: fix the rc case

docker/run_update_data.sh, socorro/external/es/create_recent_indices_app.py, socorro/external/es/index_creator.py
This also fixes `clear_recent_indices_app` to be a little less clunky in what
it's doing in regards to the args passed in. And it fixes `run_update_data.sh`
which was running crontabber and apps wrong.
=> bug 1503591: tweak create_recent_indices to have a dry run mode

webapp-django/crashstats/api/tests/test_cleaner.py, webapp-django/crashstats/api/tests/test_jinja_helpers.py, webapp-django/crashstats/api/tests/test_views.py, webapp-django/crashstats/authentication/tests/test_auditgroups.py, webapp-django/crashstats/authentication/tests/test_makesuperuser.py, webapp-django/crashstats/base/tests/test_finders.py, webapp-django/crashstats/base/tests/test_jinja_helpers.py, webapp-django/crashstats/base/tests/test_utils.py, webapp-django/crashstats/base/tests/testbase.py, webapp-django/crashstats/crashstats/tests/test_decorators.py, webapp-django/crashstats/crashstats/tests/test_form_fields.py, webapp-django/crashstats/crashstats/tests/test_forms.py, webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py, webapp-django/crashstats/crashstats/tests/test_middleware.py, webapp-django/crashstats/crashstats/tests/test_utils.py, webapp-django/crashstats/crashstats/tests/test_views.py, webapp-django/crashstats/documentation/tests/test_views.py, webapp-django/crashstats/graphics/tests/test_views.py, webapp-django/crashstats/manage/tests/test_utils.py, webapp-django/crashstats/monitoring/tests/test_views.py, webapp-django/crashstats/profile/tests/test_views.py, webapp-django/crashstats/sources/tests/test_views.py, webapp-django/crashstats/supersearch/tests/test_form_fields.py, webapp-django/crashstats/supersearch/tests/test_forms.py, webapp-django/crashstats/supersearch/tests/test_utils.py, webapp-django/crashstats/supersearch/tests/test_views.py, webapp-django/crashstats/tokens/tests/test_views.py
This converts some classes to subclass object rather than a TestCase thing.
For those tests, I switched to using fixtures where I could.
This removes all the `self.assert*` type calls except one that checks num
queries. There's a pytest-django fixture that does the same thing, but we'd
have to convert the class first. Tricky.
This removes all the `unittest.TestCase` subclassing. There are still a bunch
that subclass Django's TestCase. That'll require more work to remove since we
have a bunch of scaffolding that is intertwined with that.
=> bug 1504067: first pass at removing unittest things

socorro/processor/mozilla_transform_rules.py, socorro/processor/processor_2015.py, socorro/unittest/processor/test_mozilla_transform_rules.py, socorro/unittest/processor/test_processor_2015.py
This re-adds the `product_versions` lookup code for the case where Buildhub
doesn't know anything about that `(product, build_id, channel)`. This
is a temporary fix to deal with latency in Buildhub knowing about new
builds.
=> fix bug 1504281, 1492213: BetaVersionRule should degrade gracefully; add metrics

docker/run_tests_python3.sh, socorro/app/fetch_transform_save_app.py, socorro/lib/task_manager.py, socorro/lib/threaded_task_manager.py, socorro/lib/transaction.py, socorro/unittest/external/rabbitmq/test_crashstorage.py
per PEP 479, this removes explicit calls and attempts to detect StopIteration that trigger warnings in 3.6+, which was breaking tests. I used `future.generator_stop` to force these into errors, but there's no backport to 2.x of that so I ended up removing before commit.
I don't like how many tests I removed here. I'm not convinced they had much value, and I left a multi-queue test that covers most of what they were already covering.
=> fix bug 1503439 - stop using StopIteration

socorro/processor/mozilla_transform_rules.py, socorro/processor/processor_2015.py, socorro/unittest/processor/test_mozilla_transform_rules.py, webapp-django/crashstats/manage/admin.py
Buildhub has a Kinto API and an Elasticsearch API. This switches the
BetaVersionRule to use the Elasticsearch API which is MUCH faster
and will work with Buildhub2.
=> fix bug 1505030: switch BetaVersionRule to use Buildhub ES API

docker/run_tests_python3.sh, socorro/external/crashstorage_base.py, socorro/external/fs/crashstorage.py, socorro/unittest/external/fs/test_fspermanentstorage.py
This gets all the fs crashstorage tests working in Python 3.
=> fix bug 1469718: convert socorro/external/fs to Python 3

socorro/external/boto/crashstorage.py, socorro/external/crashstorage_base.py, socorro/external/es/crashstorage.py, socorro/external/fs/crashstorage.py, socorro/lib/external_common.py, socorro/lib/util.py, socorro/processor/breakpad_transform_rules.py, socorro/processor/processor_2015.py, socorro/processor/processor_app.py, socorro/unittest/app/test_generic_fetch_transform_save_app.py, socorro/unittest/cron/jobs/test_ftpscraper.py, socorro/unittest/external/boto/test_crashstorage.py, socorro/unittest/external/postgresql/test_base.py, socorro/unittest/external/rabbitmq/test_connection_context.py, socorro/unittest/external/rabbitmq/test_crashstorage.py, socorro/unittest/external/rabbitmq/test_reprocessing.py, socorro/unittest/external/rabbitmq/test_rmq_new_crash_source.py, socorro/unittest/external/test_crashstorage_base.py, socorro/unittest/lib/test_external_common.py, socorro/unittest/lib/test_task_manager.py, socorro/unittest/lib/test_threaded_task_manager.py, socorro/unittest/lib/test_util.py, socorro/unittest/processor/__init__.py, socorro/unittest/processor/test_breakpad_transform_rules.py, socorro/unittest/processor/test_general_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py
This removes one of the DotDicts from the codebase. Now there's only the
configman DotDict.
One architectural change this required was in crashstorage. Previously,
`save_raw_and_processed` would take DotDicts for the `raw_crash` and
`processed_crash`. Now the processor converts the two crash structures
into dicts before calling `save_raw_and_processed`.
=> fix bug 1505797: remove socorro's DotDict

docker/run_tests_python3.sh, socorro/processor/breakpad_transform_rules.py, socorro/processor/mozilla_transform_rules.py, socorro/processor/processor_app.py, socorro/scripts/fetch_crashids.py, socorro/unittest/processor/test_mozilla_transform_rules.py, socorro/unittest/processor/test_processor_app.py, socorro/unittest/scripts/test_add_crashid_to_queue.py, socorro/unittest/scripts/test_replay_ftpscraper.py
This also updates `socorro/unittest/scripts/` because I didn't feel like writing up a bug for that--there isn't much there.
=> fix bug 1505591: update socorro/unittest/processor tests in Python 3

webapp-django/crashstats/documentation/jinja2/documentation/products.html
There have been a lot of changes in Socorro's management of products and
versions. This updates the product documentation accordingly. It also
adds links to relevant examples for Firefox and GeckoView based products.
=> Update "new product" docs

requirements/default.txt, socorro/external/boto/connection_context.py, socorro/external/boto/crashstorage.py, socorro/processor/breakpad_transform_rules.py, socorro/processor/mozilla_transform_rules.py, socorro/signature/README.rst, socorro/signature/rules.py, socorro/signature/tests/test_rules.py, socorro/unittest/processor/test_breakpad_transform_rules.py, socorro/unittest/processor/test_mozilla_transform_rules.py, webapp-django/crashstats/api/views.py, webapp-django/crashstats/supersearch/tests/common.py
minidump-stackwalker was failing with exit code 134 because there was no
raw crash data to work on. There was no raw crash data to work on because
ujson and json handle parsing errors differently. Particularly, ujson
would shrug when trying to JSON serialize a configman DotDict. That's
really unhelpful.
This fixes the underlying issue (need to convert configman DotDict
to a dict before serializing to JSON), purges ujson from the codebase,
and fixes some tests that were testing what happens if the constants
of the universe were different which will never be the case.
=> fix bug 1506781: fix silent ujson errors

socorro/cron/jobs/archivescraper.py, socorro/processor/mozilla_transform_rules.py
This adjusts the logging line for when the new `BetaVersionRule` lookup differs
from the existing `BetaVersionRule`. We can use this data to generate new
entries in the `crashstats_productversion` table.
=> bug 1507916: improve difference logging

scripts/insert_missing_versions.py
This adds a script for adding the missing versions between 40 and 49
for Firefox that aren't available on archive.mozilla.org to the
`crashstats_productversion` table.
It's pretty easy to run:
```
$ docker-compose run app shell python scripts/insert_missing_versions.py
```
We'll run this on stage and prod and that'll add the missing versions and then the `BetaVersionRule` should be fine with this lookup.
=> bug 1507916: add missing versions

docker/run_crontabber.sh
Crontabber isn't running because the "main()" bit was taken out of the
Python module. Need to run it via socorro-cmd now.
=> fix bug 1503383: fix crontabber

socorro/cron/jobs/archivescraper.py, socorro/unittest/cron/jobs/test_archivescraper.py
This fixes a theoretical problem that we haven't seen, yet, where
archivescraper is scraping at a time when there's an rc build, but
no final build for a given version. In this scenario, archivescraper
would create a version entry, but that would be wrong and then
incoming crash reports would pick up the wrong version.
For example, say there's a 64.0b4 build1 build. That gets added
as 64.0b4rc1--that's fine. It would also get added as 64.0b4 (final)
but that's not correct because later, there'd be a 64.0b4 build2.
So any incoming crashes for 64.0b4rc1 would get the version 64.0b4.
This fixes it so that it checks the /releases/ page for all the
released version and if that version isn't on the page, it doesn't
create an entry for the final version. I think that's correct, but
since this …
=> fix bug 1510435: fix edge case where there's an rc, but no final

docker-compose.yml
This updates the local dev and test environments to use PostgreSQL 9.5.
=> bug 1497956: upgrade postgres to 9.5 in local dev environment

socorro/cron/jobs/bugzilla.py
Today, the BugzillaCronApp is timing out when reading from Bugzilla. This
increases the timeout to 30 seconds for that app because it seems it needs
more time to read.
=> bug 1511163: increase BugzillaCronApp timeout

docker-compose.yml
This upgrades the local development environment and the test environment to
PostgreSQL 9.6.
We're in the process of upgrading to 9.5 right now, so we'll want to wait until that's done before we land this.
=> bug 1497957: upgrade to postgre 9.6

webapp-django/package-lock.json
Somehow, when I generated package-lock.json after removing underscore.js, it
removed a bunch of stuff we still need. This broke the dependency checker.
This re-adds that.
=> fix bug 1506722: re-add missing dependencies

Makefile, scripts/build-breakpad.sh, scripts/run_mdsw.sh
Building the breakpad client requires using depot_tools which only work with
Python 2. This fixes the `build-breakpad.sh` script so it makes sure depot_tools
are using Python 2 in the Docker container.
This adds a `scripts/run_mdsw.sh` script which runs minidump-stackwalker just
like we do in the processor, but outside of the processor. This makes it
a lot easier to debug issues with minidump-stackwalker.
=> bug 1515805: fix breakpad client building in image; add scripts

socorro/signature/cmd_signature.py
siggen still supports Python 2.7, so we need to re-add this `__future__`
line.
=> Re-add __future__ statement for siggen
