- socorro/processor/mozilla_transform_rules.py
gzip can throw an EOFError when reading the blob. This adds handling
for that.
> fix bug 1518143: add EOFError to handled errors in OutOfMemoryBinaryRule

- scripts/build-breakpad.sh
Once this lands, we can run the taskcluster task that uses this script to update the client binary. Once the binary is built, we'll need to trigger another stage deploy so that stage mdsw picks it up..
> fix bug 1515805: update breakpad client to 1459e5df

- webapp-django/crashstats/crashstats/jinja2/crashstats/bugzilla_comment.txt
Bugzilla switched to Markdown for formatting and the bugs that were created
from Bugzilla looked ter-rib-ble. This fixes that and reduces some of the
unnecessary boilerplate.
> fix bug 1518576: fix bug description when filing bugs from crash reports

- README.rst
Needed something to trigger another deploy to stage for updating breakpad, and removing this 1.5-year-old warning seemed like a good candidate.
> Remove warning from last year in README.

- socorro/external/es/crashstorage.py
This removes index name caching code which never kicked in because
the cache was never updated.
> fix bug 1113583: remove index name caching code

- setup.cfg
The `build/` directory holds breakpad-client-related build stuff that's
external to this project, but has a bunch of Python files that have
linting issues. This excludes them.
> Exclude build/ from linting

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index_not_found.html
- webapp-django/crashstats/crashstats/tests/test_views.py
This improves the crash report not found page. It explains several reasons
why the crash report may not be available and what to do about it. This
includes the possibility that the crash report is no longer on our system.
> fix bug 1299460: improve crash not found page

- socorro/external/es/base.py
- socorro/external/es/create_recent_indices_app.py
- socorro/external/es/index_creator.py
- socorro/external/es/query.py
- socorro/external/es/super_search_fields.py
This fixes `create_recent_indices` in the case where you run it at the
beginning of the year and it doesn't create the YYYY00 index.
In working on this, I cleaned up some related code and nixed
a base class that wasn't very helpful.
> fix bug 1519528: fix missing index

- webapp-django/crashstats/base/jinja2/crashstats_base.html
This swaps the "file a bug" link with "super search" because the latter
is heavily used and it's better to put it on the right-most side for
easier mousing.
> bug 1511032: move bug link over

- socorro/external/es/super_search_fields.py
This fixes the analysis for graphics adapter id and graphics device id
so the values are not tokenized into smaller parts. Firefox sends
values like 0x8000 which tokenizes into a single token. Fennec, however,
sends values like "Imagination Technologies" which gets broken into two
tokens and then we end up with two facets which messes up the Graphics
Adapter section in the signature summary report.
This fixes that.
> fix bug 1508215: make graphics adapter/device keywords

- socorro/processor/breakpad_transform_rules.py
- socorro/unittest/processor/test_breakpad_transform_rules.py
When running minidump-stackwalker as an external process, it'd use `shell=True`
because the command line was complicated and involved redirection. Instead
of doing that, we can use `shlex.split` to split it into arguments and do
the redirection in the `subprocess.Popen` call. Then we're not using `shell=True`
which has security implications.
> fix bug 1389186: stop doing shell=True

- socorro/processor/general_transform_rules.py
- socorro/processor/processor_2015.py
- socorro/unittest/processor/test_general_transform_rules.py
We want to move the de-nulling step from the collector to the processor. This
makes the raw crash data more authentic in regards to what we got from the
client. Further, it reduces the work that the collector needs to do.
> bug 1357246: add de-nulling to processor

- socorro/lib/search_common.py
This removes the user-provided value from the error message. It's a
possible security issue depending on what is done with the text. We
could escape it or change it, but I think that reduces its helpfulness
and it's better to just nix it.
> fix bug 1401274: nix the user-provided value

- webapp-django/crashstats/signature/jinja2/signature/signature_report.html
- webapp-django/crashstats/signature/static/signature/js/signature_tab_correlations.js
- webapp-django/crashstats/signature/views.py
This moves the list of supported products for correlations to the view
code and fixes the JS to build the options based on that. The correlations.js
code still has its own list of supported products, but we can fix that
another day.
This also adjusts the jinja template such that if the specified product
isn't supported by correlations, it won't show the correlations tab at
all.
> fix bug 1315109: don't show correlations tab if not supported

- webapp-django/crashstats/crashstats/context_processors.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/jinja2/crashstats_base.html
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/settings/base.py
This fixes the display of the build id in the report view so that it shows
the build id, a humanized version of the build id date, and then an explicit
link to the Buildhub data for that build.
This also adds the channel to the Buildhub link--that will focus the data
better. That'll help a little with bug #1056217.
This also moves the buildhub base url to settings--we shouldn't have had
it hardcoded in the template.
> fix bug 606630: show friendly build date

- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
This changes the bug summary from:
```
Crash in OOM | Small
```
to something easier to parse:
```
Crash in [@ OOM | Small]
```
which matches how we do crash signatures elsewhere.
> fix bug 1377632: fix crash signature bug summary

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
Since the date processed field comes from Socorro, we can guarantee that it
is in UTC. We can do the same for the submitted datetime stamp. We can't do
that for other datetime stamps because they come from the client and who
knows what state it's in.
This adds a UTC label to the "Date processed" field in the report view.
> fix bug 1146956: add UTC label to date processed field

- webapp-django/crashstats/settings/base.py
This tweaks the server logging settings for the webapp. It removes
`django.request` and adds `django.server`. That'll show incoming HTTP requests.
This also fixes all the loggers to use the same `LOGGING_LEVEL`.
> bug 1525614: adjust server logging settings for webapp

- socorro/processor/mozilla_transform_rules.py
- socorro/processor/processor_2015.py
- socorro/unittest/processor/test_mozilla_transform_rules.py
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/test_models.py
This redoes the `BetaVersionRule` (again) to use a new `VersionString` API in the webapp. This fixes the processor so it no longer touches the database directly (again).
> fix bug 1510658: redo BetaVersionRule to use VersionString API in webapp

- docker/run_update_data.sh
This changes "make updatedata" to also run the insert_missing_versions.py
script after running the archivescraper crontabber job.
> Add missing versions to "make updatedata"

- socorro/processor/mozilla_transform_rules.py
This fixes the code to also track cache misses for the BetaVersionRule.
> bug 1510658: track cache misses for BetaVersionRule

- docker/config/gunicorn_config.py
- docker/run_webapp.sh
This sets gunicorn up with a config file to configure logging. It uses
existing webapp environment variables and mimics the way the webapp sets
up logging so that a local dev environment gets the console and server
environments get mozlog.
> fix bug 1525614: use mozlog for gunicorn

- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/urls.py
- webapp-django/crashstats/crashstats/views.py
- webapp-django/crashstats/monitoring/tests/test_views.py
- webapp-django/crashstats/monitoring/urls.py
- webapp-django/crashstats/monitoring/views.py
- webapp-django/crashstats/urls.py
This implements the `__heartbeat__` and `__lbheartbeat__` dockerflow endpoints
for the webapp. It reworks the existing `healthcheck` code and deprecates
the old version. We can remove that as soon as we update the infrastructure.
This also moves `__version__` from the crashstats app to the monitoring
app; seems to be a more appropriate place.
> fix bug 1419899: implement __heartbeat__ and __lbheartbeat__

- socorro/processor/mozilla_transform_rules.py
- socorro/processor/processor_2015.py
- socorro/unittest/processor/test_mozilla_transform_rules.py
There was a processor rule for copying the `Winsock_LSP` value from the
raw crash to the processed crash, but nothing can use or access it
in the processed crash.
This removes that rule.
> fix bug 1393416: stop copying Winsock_LSP to processed crash

- socorro/app/socorro_app.py
- socorro/lib/task_manager.py
- socorro/unittest/app/test_socorro_app.py
We no longer run Socorro apps in a way that requires they handle `SIGHUP` and restart with updated configuration. Given that, we can remove this code.
> bug 1529342: remove sighup handling

- socorro/lib/versionutil.py
- socorro/unittest/lib/test_versionutil.py
This adds a really basic "version validator" and tweaks the version
sorting code to ignore invalid versions.
> fix bug 1530674: fix version sorting to ignore invalid versions

- docker/run_setup_postgres.sh
Running "python socorro/scripts/db.py" does nothing--it just loads
the module. We need to run "socorro-cmd db" now. This fixes that.
> Fix db setup

- socorro/cron/jobs/verify_processed.py
- socorro/lib/raven_client.py
This adds Sentry error reporting for unhandled errors in the multiprocessing code. It also changes the number of workers and makes that configurable. This particular problem is network-i/o-heavy, so more worker processes speeds that up significantly.
> fix bug 1534402: fix error handling in multiprocessing code

- webapp-django/crashstats/crashstats/admin.py
- webapp-django/crashstats/crashstats/models.py
When looking at `MissingProcessedCrashes`, in the Django admin, this now
shows the collected date as well as whether the crash has been processed.
This will make it easier to deal with missing crashes.
> bug 1534617: add "is_processed" check

- webapp-django/crashstats/settings/base.py
The old link points to the old web UI for Buildhub1. Changing it to the new one, which incidentally, isn't operating on a path prefix. 
This change would resolve https://github.com/mozilla/buildhub2/issues/366
> Change Buildhub base URL

- socorro/cron/jobs/archivescraper.py
- socorro/cron/jobs/verify_processed.py
- socorro/unittest/cron/jobs/test_archivescraper.py
- socorro/unittest/cron/jobs/test_verify_processed.py
- webapp-django/crashstats/crashstats/management/__init__.py
- webapp-django/crashstats/crashstats/management/commands/__init__.py
- webapp-django/crashstats/crashstats/management/commands/dumppv.py
This switches verifyprocessed to use `concurrent.futures` and then restructures archivescraper to also use `concurrent.futures`.
The end result of this on a fresh local dev environment is a massive performance improvement:
* **before**: between 30 and 40 min
* **after**: under 3 min
This will significantly improve development. I slick my environment once a week, so this will save me 30 minutes a week.
archivescraper runs every hour in server environments and takes about 10 min. Since crontabber is synchronous and only runs one job at a time, this blocks all other jobs from running. Improving performance in server environments will improve crontabber job start times.
Using `concurrent.futures` should fix our error handling, too. With the previous implementation using just multiprocessing, …
> bug 1536147: make archivescraper faster

- docker/config/test.env
- scripts/process_crashes.sh
- socorro/external/pubsub/crashqueue.py
- socorro/external/rabbitmq/crashstorage.py
- socorro/processor/processor_app.py
- socorro/unittest/external/pubsub/__init__.py
- socorro/unittest/external/pubsub/test_crashqueue.py
- socorro/unittest/external/rabbitmq/test_reprocessing.py
- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/api/views.py
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/test_models.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/tests/testbase.py
- webapp-django/crashstats/crashstats/views.py
- webapp-django/crashstats/settings/base.py
- webapp-django/crashstats/settings/test.py
- webapp-django/pytest.ini
This implements the necessary Pub/Sub bits in the webapp. I tried to keep it similar to how RabbitMQ was used with the hope that we could switch back and forth, but that didn't work out so well. The webapp is pretty hard-coded to use one or the other and I didn't want to put the work into abstracting it out since this is an interim problem that will go away soon.
Because the webapp is in Pub/Sub mode, this adjusts the processor to also be in Pub/Sub mode. That means we need to:
1. do the configuration changes in the infra
2. switch Antenna to Pub/Sub mode
3. land this
4. nix socorro-pigeon
all around the same time.
> fix bug 1527346: switch webapp to use Pub/Sub

- docker/config/local_dev.env
- docker/run_update_data.sh
* `--force` doesn't do anything in crontabber, so we don't need to use it
* remove `LOGGING_LEVEL=DEBUG` which makes the webapp very very verbose
> Minor fixes

- .readthedocs.yml
ReadTheDocs supports configuration from the web admin or from a config
file. This switches to the config file so we can track configuration in
version control with everything else.
> Switch to readthedocs config file

- webapp-django/crashstats/crashstats/admin.py
This fixes the query so that it pulls the list of crash ids rather than
all the information, then create a bunch of instances, and then take
the crash ids from those instances. That's a lot of extra work.
> bug 1536903: improve bulk processing performance

- socorro/external/pubsub/crashqueue.py
This reduces the number of Pub/Sub pulling operations by changing it to pull up
to 5 messages at a time from each queue. Further, it reduces the number of
times it pulls from the priority queue such that it only pulls from the
priority queue once per pass rather than twice per pass.
The theory is that this will increase the throughput for crash processing
on the standard queue which is where the vast majority of our messages
are.
> bug 1527345: reduce Pub/Sub pulling

- docker/Dockerfile
- docker/Dockerfile.docs
- docker/run_tests.sh
- docker/run_tests_in_docker.sh
- docker/set_up_ubuntu.sh
The last time I attempted this, I hit all kinds of problems with compiling the breakpad client and minidump-stackwalk and abandoned the effort. Since then, one of the breakpad client updates we did must have covered all the problems I had because this update was easy peasy.
> bug 1539272: switch to 3.6.8-slim-stretch

- .circleci/config.yml
The first CI step sets up docker-compose which is then used to set up
a test environment and run the tests. Something changed yesterday or
today and that no longer works.
This updates the first step to what's in CircleCI's documentation.
> bug 1540248: fix setting up docker-compose in CI

- socorro/external/pubsub/crashqueue.py
Previously, the code published crash ids one at a time waiting for each
to go through. This fixes it to send them in a batch, then make sure
they all went through.
> bug 1540858: fix /api/Reprocessing timeouts

- webapp-django/crashstats/authentication/admin.py
- webapp-django/crashstats/crashstats/admin.py
This reworks the `UserAdmin` to make it clearer who has access to what data on
the site. Further, it adds `PolicyException` status and also links to
create/delete/edit policy exceptions.
> bug 1539130: redo admin for PolicyException

- webapp-django/crashstats/cron/tests/test_utils.py
This fixes a couple of tests that fail at 8:00pm EDT.
> bug 1493687: fix tests that fail at 8:00pm EDT

- socorro/signature/cmd_signature.py
- socorro/signature/siglists_utils.py
- socorro/signature/tests/siglists/test-invalid-sig-list.txt
- socorro/signature/tests/test_siglists.py
- socorro/signature/utils.py
This removes Python 2 bits from signature generation. We no longer need to
support Python 2 with siggen.
> bug 1513346: remove python 2 bits from signature generation

- socorro/signature/siglists/prefix_signature_re.txt
Signature generation examples:
```
app@0c19f53ebd15:/app$ socorro-cmd fetch_crashids --url="https://crash-stats.mozilla.com/search/?signature=%3D__clear_cache&product=FennecAndroid&date=%3E%3D2019-03-29T18%3A36%3A00.000Z&date=%3C2019-04-05T18%3A36%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature" --num=5 | socorro-cmd signature
Crash id: 9a38cdc3-d98f-4296-94c0-0ed830190405
Original: __clear_cache
New:      __clear_cache | __clear_cache | Gecko_StartBulkWriteString
Crash id: d24ab32c-71aa-428e-950f-2ba210190405
Original: __clear_cache
New:      __clear_cache | __clear_cache | base.apk@0x143ce5d
Crash id: bbe160b2-603b-4444-86f9-4db4a0190405 …
```
> bug 1541090: add __clear_cache to prefix list

- webapp-django/crashstats/crashstats/apps.py
- webapp-django/crashstats/settings/base.py
For some reason, when I added markus, I put the configuration where it
configures markus. That should be in settings so it's clearer what's going
on from settings. This fixes that.
> Move markus configuration to settings

- docker/config/local_dev.env
- socorro/cron/crontabber_app.py
- socorro/unittest/cron/test_crontabber_app.py
- webapp-django/crashstats/cron/__init__.py
- webapp-django/crashstats/monitoring/management/__init__.py
- webapp-django/crashstats/monitoring/management/commands/__init__.py
- webapp-django/crashstats/monitoring/management/commands/depcheck.py
- webapp-django/crashstats/monitoring/tests/test_depcheck.py
- webapp-django/crashstats/settings/base.py
This rewrites the monitoring crontabber app as a Django command.  "monitoring"
wasn't very descriptive of what it did, so I renamed it to depcheck.
> bug 1542392: rewrite monitoring crontabber app as Django command

- socorro/signature/siglists/prefix_signature_re.txt
GCGraphBuilder got renamed to CCGraphBuilder a long time ago, but the prefix list was never updated.
> Bug 1544449 - Fix NoteXPCOMChild class name.

- docs/service/webapp.rst
The ``webpack`` container and build process was removed, and is no longer needed to run the ``webapp``.
> bug 1514294: Remove webpack from webapp docs

- webapp-django/crashstats/crashstats/models.py
The processor requires this key to process raw crash files, and it doesn't contain PII. The crash report won't include a useful signature or a thread, but this may allow some contributions.
> bug 1544543: Add uuid to allowed keys for RawCrash

- docker/config/oidcprovider-fixtures.json
[django-oidc-provider 0.7.0](https://django-oidc-provider.readthedocs.io/en/latest/sections/changelog.html) updated the [data model for clients](https://github.com/juanifioren/django-oidc-provider/pull/271), and [mozilla-parsys](https://github.com/mozilla-parsys/docker-test-mozilla-django-oidc) (which provides our [oidcprovider base image](https://github.com/mozilla-services/socorro/blob/master/docker/Dockerfile.oidcprovider)) updated to this version. This synchronizes the fixtures with [upstream changes](https://github.com/mozilla-parsys/docker-test-mozilla-django-oidc/commit/5f3750531fe4506fd0447ce16934bd8a294d34b9), so the provider will work for new development environments.
To see the issue, rebuild the image on master:
```
docker-compose stop oidcprovider
docker-compose build …
```
> fix bug 1544872: Update fixture for oidcprovider 0.7.0

- docs/service/processor.rst
- socorro/scripts/pubsub.py
* Drop the 2-year-old note about extracting the processor code, which means we might get to it this year.
* Allow ``socorro-cmd pubsub publish`` to read IDs from ``stdin``, like ``socorro-cmd fetch_crash_data``.
* Move ``SOCORRO_API_TOKEN`` docs to a new section, higher in the doc.
> bug 1544919: Update processor docs and pubsub publish command

- webapp-django/crashstats/signature/jinja2/signature/signature_report.html
- webapp-django/crashstats/signature/static/signature/js/signature_report.js
- webapp-django/crashstats/signature/tests/test_views.py
- webapp-django/crashstats/signature/views.py
Users shouldn't be able to view comments if they don't have `view_pii`
permissions.
> bug 1544497: fix comments tab in signature report

- docs/localdevenvironment.rst
- docs/service/webapp.rst
Update the docs to reflect my best guess at current workflows:
* Add note for signing up with ``oidcprovider`` in dev. I have further changes I want to make, but I first filed as issues in [mozilla-parsys](https://github.com/mozilla-parsys/docker-test-mozilla-django-oidc).
* Move static assets note into new section, with example ``docker-compose.override.yml`` and macOS note. Move instructions for production-like assets as a subsection.
* Simplify and organize the permission sections, which felt like an introduction to django.contrib.auth. Add a link to the official docs to cover content I removed.
* Permissions and default groups are now in ``signal.py``. I think they should be in a data migration, but that can be a future discussion / PR, depending on how often permissions are changed. …
> bug 1544919: Refresh webapp service docs

- webapp-django/crashstats/tokens/jinja2/tokens/home.html
As suggested on https://github.com/mozilla-services/socorro/pull/4894#discussion_r276246228, add a note that to download crash data, an API token needs both the ``View Personal
Identifiable Information`` and ``View Raw Dumps ``permissions.
I was tempted to also change ``<b>`` to ``<strong>`` and ``<br>`` to separate ``<p>`` elements. I resisted.
> bug 1544919: Add note for API token permissions for crash data

- socorro/scripts/pubsub.py
As mentioned in https://github.com/mozilla-services/socorro/pull/4894#pullrequestreview-228362039, in a ``for``/``else`` statement, the ``else`` clause is called when the ``for`` loop completes without breaking, but the code was written as if it was called for an empty loop. I believe I was confused with [Jinja's for / else loop](http://jinja.pocoo.org/docs/2.10/templates/#for) 🤦‍♂️.
Since the "no crashids" case is [handled in ``main``](https://github.com/jwhitlock/socorro/blob/d33376d6a8b67d531839ba5a350aac885eb32c6a/socorro/scripts/pubsub.py#L203-L207) (by printing usage help), it doesn't need to be handled here as well.
> bug 1544919: Remove incorrect "no ids" message

- docker/set_up_ubuntu.sh
- docs/service/processor.rst
- scripts/process_crashes.sh
This fixes `./scripts/process_crashes.sh` to pull from stdin if there are no crashid args and stdin is not a tty.
```shell
$ make shell
app@afdfe895c928:/app$ ./scripts/process_crashes.sh 
Usage: process_crashes.sh CRASHID [CRASHID ...]
app@afdfe895c928:/app$ echo 4854438d-dd83-44d5-967b-155d70190418 | scripts/process_crashes.sh 
<copious output>
app@afdfe895c928:/app$ scripts/process_crashes.sh 4854438d-dd83-44d5-967b-155d70190418
<copious output>
```
> bug 1544919: fix scripts/process_crashes.sh to take from stdin

- socorro/scripts/__init__.py
- socorro/scripts/fetch_crash_data.py
- socorro/scripts/pubsub.py
- socorro/scripts/reprocess.py
- socorro/unittest/scripts/test_init.py
``FallbackToPipeAction`` centralizes the logic for taking ``crashids`` from either the positional arguments or a piped list, so both work:
```shell
cat crashids.txt | xargs socorro-cmd fetch_crash_data ./crashdata
cat crashids.txt | socorro-cmd fetch_crash_data ./crashdata
```
It works in the ``argparse`` framework so that omitting both is a parsing error, which displays the default usage message.
> bug 1544919: Add FallbackToPipeAction

- webapp-django/crashstats/monitoring/management/commands/depcheck.py
This fixes the depcheck command to tell us if it's using a safety api key.
Otherwise we have no idea.
This also fixes what it does if the key is bad. Before it would raise
an error with the text `"b''"`. Now it tells you the api key is invalid.
Isn't that nice.
> bug 1542392: fix depcheck to tell us if it's using a safety api key

- webapp-django/crashstats/crashstats/admin.py
The ``LogEntry`` view allows seeing admin actions (either manual or from tools) as a list. It should be read-only, for auditing purposes, but until Django 2.1, there wasn't a supported way to mark a view as read-only.
Use Django 2.1's default ``has_view_permission`` to drop the ``has_change_permission`` hack, and drop the unneeded ``has_module_permission`` method.
Borrow some ideas from [yprez/django-logentry-admin](https://github.com/yprez/django-logentry-admin/blob/master/logentry_admin/admin.py):
* Change the ``user_email`` column name to "Admin"
* Change the ``get_edited_object`` column to "Object", use the email address when the object is a ``User``, and link to admin details page if available
* Change the ``action_name`` column to "Action"
* Change the ``get_change_message`` column …
> bug 1546978: Update permissions, refresh LogEntry admin view

- webapp-django/crashstats/tokens/jinja2/tokens/home.html
The RawCrash API uses ``crash_id``, not ``uuid``, for the querystring parameter. Fix the example to use the correct parameter.
> bug 1548830: Fix API token examples

- socorro/processor/breakpad_transform_rules.py
- socorro/unittest/processor/test_breakpad_transform_rules.py
This adds `SIGKILL` and `SIGABRT` to logging and processor notes so we can more
easily find crash reports which didn't process well.
We can add other signals as they pop up in the exit code graphs on Datadog.
> bug 1549540: surface signal issues from minidump-stackwalk

- docs/howto.rst
* SOCORRO_REPROCESS_API_TOKEN needs to be set
* Split fetch_crashids command from reprocess command
* Note that default of 100 crashids are returned
* Add example of using a search URL
> Update reprocessing docs

- contribute.json
- docker/config/my.env.dist
- docs/crashstorage/elasticsearch.rst
- docs/index.rst
- docs/overview.rst
- docs/service/processor.rst
- docs/service/webapp.rst
- docs/tests/system_checklist.rst
- scripts/deploy_bug.py
- socorro/processor/processor_2015.py
- socorro/schemas/README.rst
- socorro/schemas/validate_and_test.py
- socorro/scripts/fetch_crash_data.py
- socorro/scripts/fetch_crashids.py
- socorro/scripts/reprocess.py
- socorro/signature/cmd_signature.py
- webapp-django/crashstats/documentation/jinja2/documentation/memory_dump_access.html
Switch the preferred production domain from crash-stats.mozilla.com to .org in code and docs.
> bug 1550028: Switch to crash-stats.mozilla.org

- socorro/external/es/super_search_fields.py
In the signature report, one of the facets is on android manufacturer. Because
it wasn't being indexed as a keyword, it was getting tokenized and then faceted
on the tokens. This fixes that.
> bug 1549297: fix android manufacturer faceting

- webapp-django/crashstats/settings/base.py
When the requested ``Host`` header is not in ``ALLOWED_HOSTS``, the user gets a ``400 Bad Request``, and a message is logged to ``django.security.DisallowedHost``. This can be useful when setting up a server or monitoring, and then becomes annoying when random requesters set the wrong host.
For local testing, set ``SENTRY_DSN=https://bad-id@sentry.127.0.0.1.nip.io/0``, tail the webapp logs, and make a request via a disallowed hostname, like http://oidcprovider:8000/. Before this PR, the [logging integration](https://docs.sentry.io/platforms/python/logging/) sends it as an event, and after, it does not.
> bug 1543097: Do not send DisallowedHost to Sentry

- webapp-django/crashstats/sentrylib.py
- webapp-django/crashstats/tests/test_sentrylib.py
The ELB adds several headers, including ``X-Forwarded-For`` and ``X-Real-IP``, that include the user's IP address. They are moved to ``sentry.interfaces.Http`` when saved in Sentry (load the JSON for a Sentry issue to see).
> bug 1543097: Sanitize ELB headers 

- socorro/external/boto/crash_data.py
When a file is missing when using the boto crashstorage, log as a warning, using a dictionary of log format parameters, rather than as a pre-formated error. Changing from ``.error`` to ``.warning`` avoids creating a Sentry issue when logging, and changing to a format string avoids string formatting if the log isn't picked up by a handler.
> bug 1552973: Log missing boto files as warnings

- docker-compose.yml
This adds an elasticsearch7 container that listens on port 9201. This allows you to run elasticsearch 1.4 and 7.1 simultaneously so we can implement and test necessary code changes as well as implement and test migration scripts.
The elasticsearch7 container isn't used by anything, so this doesn't affect the local dev environment.
To run the elasticsaerch7 container, you'd do:
```
$ docker-compose up elasticsearch7
```
Once we have this in master, it makes it easier to go back and forth between a master and elasticsearch 1.4 setup and a branch and elasticsearch 7.1 setup.
> bug 1393889: add elasticsearch7 service

- socorro/processor/breakpad_transform_rules.py
- socorro/processor/processor_2015.py
Remove ``>2 /dev/null`` from the commmand_line parameter, which is used to call mini dump stack walk (mdsw). This would be valid for a bash command, but they are passed as symbol directories to mdsw when called by Python's ``subprocess.Popen``.
This code didn't work the way I expected. I expected that the default value for ``command_line`` in ``BreakpadStackwalkerRule2015`` would be used to call ``stackwalker``, but instead it is the config from ``Processor2015`` that is used. What is the purpose of ``required_config`` in rules?
> bug 1553251: Remove bad params from mdsw command

- webapp-django/crashstats/cron/management/commands/cronrun.py
``sentry_sdk.capture_error`` was wrong (should be ``.capture_exception``), and instead of double-logging, send just the error-level log to sentry.
Replaces PR #4946.
> bug 1553327: cronrun: log, don't capture exception

- socorro/signature/siglists/irrelevant_signature_re.txt
See crashes like:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1549316
* https://bugzilla.mozilla.org/show_bug.cgi?id=1553665
I did try to test this manually but the `make shell` stuff ends up abruptly
with:
/app/docker/socorro_entrypoint.sh: Permission denied
And I tried a bunch of things without luck.
So I hope someone can poke at it for me instead
> Bug 1553665 - Add libc to the signature prefixes.

- docker/config/local_dev.env
- scripts/run_mdsw.sh
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/base.py
- socorro/processor/rules/breakpad.py
- socorro/processor/rules/memory_report_extraction.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_breakpad.py
- socorro/unittest/processor/rules/test_general.py
- socorro/unittest/processor/rules/test_memory_report_extraction.py
- socorro/unittest/processor/rules/test_mozilla.py
- socorro/unittest/processor/test_processor_pipeline.py
This adjusts the `ProcessorPipeline` to own configuration of the rules in the
pipeline. Configuration is now defined on that class and it passes in necessary
data through init args to the rules that require it.  In this way, rules are
just transformation classes and aren't configman-style classes.
This adds logging of the pipeline rules and their configuration. This will
make it a lot easier to notice and debug rules problems in the future.
Doing this also fixed configuration for the `JitCrashCategorizeRule` which was
totally busted and probably has been for some time. Now rule configuration is
namespaced which allows us to configure both the `BreakpadStackwalkerRule2015`
and `JitCrashCategorizeRule`.
This also removed all the confusing duplicated (and triplicated in some places) …
> bug 1553314: remove configuration from Rules

- socorro/processor/processor_pipeline.py
The JitCrashCategorizeRule only kicks off for crashes with certain
properties including requiring certain things in the signature. If this
runs *before* signature generation, then it'll never do anything since
the predicate will never be met. This fixes that.
To test:
1. process d02ac76e-eee6-4206-8026-c08f10190523 using master branch; then check http://localhost:8000/api/UnredactedCrash/?crash_id=d02ac76e-eee6-4206-8026-c08f10190523 and look for "classifications" key--it's not there
2. process it using this branch and re-check--it is there :tada:
> bug 1553838: fix JitCrashCategorizeRule

- socorro/processor/processor_pipeline.py
This defaults to the old keys for environment variables that got changed until
we can change them in stage/prod.
> bug 1553314: default to old keys for environment variables

- socorro/processor/processor_pipeline.py
This reverts commit ea27aad459ff2f6ada808c37e06821e7e1989bc8.
We don't need this anymore since the config change landed, so I'm reverting it.
> Revert "bug 1553314: default to old keys for environment variables"

- socorro/lib/cache.py
- socorro/unittest/lib/test_cache.py
`__len__` should return an `int`--not raise an exception. This fixes that
and fixes the tests to use `len()` rather than looking at the internal
structure.
> bug 1554986: fix __len__ in ExpiringCache

- webapp-django/crashstats/settings/base.py
Add more URLs to ``OIDC_EXEMPT_URLS``, which prevents XHR requests from being checked for session expiration and getting a login redirect.
These are defined as attributes in a block in ``signature_report.html``:
https://github.com/mozilla-services/socorro/blob/750dece05d3877a281e7e401f3cd7fd559340ece/webapp-django/crashstats/signature/jinja2/signature/signature_report.html#L19-L25
I've reworked ``OIDC_EXEMPT_URLS`` to use URL names, which are [reversed once in the middleware](https://github.com/mozilla/mozilla-django-oidc/blob/e780130deacccbafc85a92f48d1407e042f5f955/mozilla_django_oidc/middleware.py#L44-L65), so that the templates will line up with the settings. I've also added the attribute names as comments, to make it easier to find one from the other.
There are two pages, for …
> bug 1473068: Expand OIDC_EXEMPT_URLS for more XHR usage

- socorro/signature/siglists/prefix_signature_re.txt
It avoid crash reports signatures stopping at e.g. `BaseAllocator::malloc`. (e.g. bug 1544552)
> bug 1544552: Add `BaseAllocator` to the prefix signature list

- webapp-django/crashstats/crashstats/static/crashstats/css/base/fonts.less
- webapp-django/crashstats/crashstats/static/crashstats/css/base/variables.less
Stop loading Fira Sans from the CDN, rather than add a CSP exception, as tried and discussed in PR #4927. 
Reduce the default font list to a boring set. Here's what Helvetica looks like:
> bug 1545446: Remove Fira-Sans, reduce font list

- webapp-django/crashstats/supersearch/static/supersearch/css/search.less
- webapp-django/crashstats/supersearch/static/supersearch/js/socorro/search.js
This fixes the product/version/etc input box widths in super search so they're vaguely responsive
and have more helpful widths.
Full screen (on my machine):
Smaller screen (on my machine):
> bug 1545446: fix input box widths in super search

- socorro/signature/siglists/prefix_signature_re.txt
This is in mozglue and signature generation shouldn't stop on them but rather
continue onwards.
> bug 1557012: add Allocator<T>::malloc to prefix list

- docker/config/test.env
- product_details/FennecAndroid.json
- product_details/README.rst
- webapp-django/crashstats/crashstats/jinja2/crashstats/product_home.html
- webapp-django/crashstats/crashstats/jinja2/crashstats_base.html
- webapp-django/crashstats/crashstats/tests/test_utils.py
- webapp-django/crashstats/crashstats/utils.py
- webapp-django/crashstats/settings/base.py
This implements manually-curated featured versions. They exist in the
`product_details/` directory. People can edit and create pull requests using the
GitHub interface. Using GitHub for process flow significantly reduces the
complexity of the implementation. This is probably a good enough first pass
and we can adjust that as needs necessitate.
If a file exists, Crash Stats will use that to set the featured versions which
show up on the product home page and in the "featured version" part of the
current versions drop down in the menu. If a file does not exist or can't be
retrieved, Crash Stats will calculate the featured versions based on the
existing crash report data. Featured versions are cached for an hour after
which they're figured again, so if anything goes wrong, we just have to …
> bug 1552898: implement manual featured versions

- webapp-django/crashstats/settings/base.py
This fixes the `PRODUCT_DETAILS_BASE_URL`. I fixed part of it in the previous PR, but missed the domain, so it's returning 404s right now.
> bug 1552898: fix product details url

- product_details/FennecAndroid.json
Fennec releases are riding the ESR68 train, so the correct Nightly version to use is 68.0a1. We are not officially publishing anything with a newer version.
> Update Fennec Nightly version to 68.0a1

- socorro/signature/siglists/prefix_signature_re.txt
This adds `mozilla::ipc::WriteIPDLParam` to the prefix list so signature generation continues beyond it. By itself, it's too general a bucket.  It'd help to know what the `T` actually is, but that breaks normalization.  Continuing to the next frame should clarify the bucket.
> bug 1561697: add mozilla::ipc::WriteIPDLParam to prefix list

- webapp-django/crashstats/monitoring/views.py
Previously, the webapp and the crash storage connection context built
Elasticsearch clients differently. When we updated urllib3 to 1.25.3, the one
the webapp built for `/monitoring/heartbeat/` started failing with SSL handshake
errors. This fixes that one to use `RequestsHttpConnection` which the rest
of Socorro uses.
> bug 1563261: fix /monitoring/heartbeat/ Elasticsearch connection

- docker-compose.yml
- docker/config/local_dev.env
- docs/service/webapp.rst
The [nip.io DNS service](https://nip.io), plus a [docker-compose links alias](https://docs.docker.com/compose/compose-file/compose-file-v2/#links), allows the OIDC provider to work without updating ``/etc/hosts``.
> bug 1562665: Use nip.io to avoid /etc/hosts change

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
Filter a ``MozCrashReason`` prefix that may contain sensitive data in the full message.
> bug 1567528: Filter MozCrashReason with eval msg

- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/views.py
A processed dump may contain a surrogate character in the range U+DC80 to U+DCFF, used to represent non-decodable bytes on POSIX systems (see [PEP 0383](https://www.python.org/dev/peps/pep-0383/)). By default, these can not be encoded in UTF-8, and an error handler is needed. This escapes the characters, so (for example) U+DF03 becomes the string "\udf03" in the UTF-8 encoding.
There are a number of possible [error handlers](https://docs.python.org/3/library/codecs.html#error-handlers), and I picked ``backslashreplace``, which makes the surrogate easy to see for humans. I tried ``surrogatepass`` first, but it is meant for use with ``surrogateescape`` for round-trip encoding of unicode with surrogates. Browsers seem to be happy to ignore the surrogates, but tests and ``smart_text`` were …
> bug 1552709: Escape surrogates on report index

- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/api/views.py
- webapp-django/crashstats/signature/views.py
- webapp-django/crashstats/supersearch/views.py
When an API endpoint has a parameter that takes a list of strings, a null character (``\x00``) in the strings will cause an Internal Server Error:
```
/api/Bugs/?signatures=null%00
```
After this change, it will become a validation error, returning a 400:
```
{
"errors": {
"signatures": [
"Null characters are not allowed."
]
}
}
```
While I was reading the API code and determining how to test this change, I found several untested code paths, and code that can be better written in Python 3. I believe the first three commits fix this particular bug, and the remaining 5 commits improve the existing code. If this is too much for one PR, I can split it, or abandon the refactor.
> bug 1564551: Validation error for null characters, plus API view updates

- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/api/views.py
If a non-class is passed as the model, return ``False`` instead of raising a ``TypeError``. This can happen if a name is passed that is a valid non-class attribute of one of the model modules, such as ``/api/time``.
This regression was introduced in PR #4982, which hasn't yet been deployed to production, so I continued to use [bug 1564551](https://bugzilla.mozilla.org/show_bug.cgi?id=1564551). I can open a new bug if we want to track regressions in new bugs.
To avoid future regressions, add tests to confirm behavior for a variety of inputs.
> bug 1564551: Expand and test is_valid_model_class

- socorro/external/es/super_search_fields.py
This adds `dom_fission_enabled` as a search field. It's a flag, so it "exists" or "doesn't exist". I tested it with a51d232a-ac9c-4174-bcca-17ebd0190723.
> bug 1563317: add DOMFissionEnabled to search

- docker/run_crontabber.sh
- socorro/processor/processor_pipeline.py
This prevents cronrun from hanging for more than an hour.
> bug 1563230: wrap cronrun in a timeout

- docker/Dockerfile.oidcprovider
- docker/oidcprovider/createuser.py
- docs/service/webapp.rst
This lets you do the following:
```
docker-compose up -d oidcprovider
docker-compose exec oidcprovider /code/manage.py createuser USER PASSWORD EMAIL
```
Then you'll have a user account in the running oidcprovider container. Couple this with `makesuperuser` and that's all you need to script account creation for local dev environment purposes.
This fixes my needs without a lot of mumbo-jumbo. The account that gets created exists only in the running container--it's not persisted to the host or across other oidcprovider containers.
To test:
1. `docker-compose stop oidcprovider`
2. `docker-compose build --no-cache oidcprovider`
3. `docker-compose up -d oidcprovider`
4. `docker-compose exec oidcprovider /code/manage.py USER PASSWORD EMAIL`
This also handles the case where the account already …
> bug 1563222: add createuser script to oidcprovider container

- docker/config/oidcprovider-fixtures.json
Use better names for the OIDC test clients, and skip confirmation entirely, to further streamline local development.
I piggybacked on [bug 1563222](https://bugzilla.mozilla.org/show_bug.cgi?id=1563222), because I noticed the weird test client name on the confirmation screen while reviewing PR #4991. If you'd like to track under a new bug, I can file it.
> bug 1563222: Drop confirmation of OIDC provider

- socorro/external/es/super_search_fields.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
This adds a new "modules_in_stack" field which is a semicolon-delimited
set of "module/debugid" strings for modules that are in the stack of the
crashing thread.
The value is indexed using the semicolon_analyzer, so each string ends
up as a single term. This allows us to use supersearch "startswith" for
finding crash reports with a specified module in the stack (e.g.
"libfenix.so") and "has term" for finding crash reports with a specified
"module/debugid" in the crashing thread of the stack. The latter helps
us reprocess crash reports for which we just uploaded symbols.
> bug 1559223, 1542964: add modules_in_stack to processed crash

- docker/run_tests_in_docker.sh
When we were doing the Python3 migration, we added a USEPYTHON
environment variable to determine which Python binary to use. We don't
need that anymore--all the related machinery is gone.
> Remove vestiges of Python 3 migration

- socorro/signature/siglists/prefix_signature_re.txt
After this change, signature generation will continue past wayland-related frames to something helpful.
> bug 1581517: add wayland symbols to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
Example:
```
app@socorro:/app$ socorro-cmd signature 5067a98a-741e-4fed-bdda-f18010190915
Crash id: 5067a98a-741e-4fed-bdda-f18010190915
Original: __memcpy_sse2_unaligned_erms
New:      __memcpy_sse2_unaligned_erms | mozilla::AudioBufferWriter::Write
```
> bug 1581800: add __memcpy_sse2_unaligned_erms to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
This replaces the previous change with a more general one that catches more `__memcpy` things.
Example:
```
app@socorro:/app$ socorro-cmd signature 5067a98a-741e-4fed-bdda-f18010190915 c1d99ea6-4e00-42d2-b2dc-e892b0190917 0e8d5ad2-3382-4e6d-be37-bf7cf0190917
Crash id: 5067a98a-741e-4fed-bdda-f18010190915
Original: __memcpy_sse2_unaligned_erms
New:      __memcpy_sse2_unaligned_erms | mozilla::AudioBufferWriter::Write
Crash id: c1d99ea6-4e00-42d2-b2dc-e892b0190917
Original: __memcpy_sse2_unaligned
New:      __memcpy_sse2_unaligned | libxul.so@0x2c61875 | org.chromium.5DpjkS (deleted)@0xc92f
Crash id: 0e8d5ad2-3382-4e6d-be37-bf7cf0190917
Original: __memcpy_ssse3
New:      __memcpy_ssse3 | soundtouch::FIFOProcessor::receiveSamples
```
> bug 1581800: add __memcpy.* to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
This adds a bunch of architecture-specific memset implementations to the
prefix list so that signature generation continues beyond those frames.
```
app@socorro:/app$ socorro-cmd signature 654bc83b-da3b-47f9-afbe-9a5c50190926 c81483f6-ddbe-48de-ab5f-5dbdd0190930 0eadb932-9899-4684-b2fd-b91380190929 d61cf817-4adc-4f05-95bb-ceaf10190927 8b3d254e-b6d4-49ab-853d-06c6d0190901  d1e87e20-62bc-4661-9386-905920190506
Crash id: 654bc83b-da3b-47f9-afbe-9a5c50190926
Original: avx::memset32
New:      avx::memset32 | SkDraw::drawPaint
Crash id: c81483f6-ddbe-48de-ab5f-5dbdd0190930
Original: sse2::memset32
New:      sse2::memset32 | SkDraw::drawPaint
Crash id: 0eadb932-9899-4684-b2fd-b91380190929
Original: neon::memset32
New:      neon::memset32 | …
```
> bug 1584951: add memset implementation variations to prefix list

- CONTRIBUTING.rst
- README.rst
- docs/index.rst
- product_details/README.rst
irc.mozilla.org is going away soon. This removes references to it.
> Remove IRC references

- socorro/signature/siglists/prefix_signature_re.txt
This adds a bunch of stack-checking functions to the prefix list so that
signature generation can proceed past them.
> bug 1589604: add gsignal and friends to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 42625bd8-af4b-40da-a23b-26c500191021 e4d195e0-86be-4a40-8ea2-ad6860190907 1012cd66-1ea1-4013-adbe-e46f70191021
Crash id: 42625bd8-af4b-40da-a23b-26c500191021
Original: raise | abort | __assert_fail_base
New:      raise | abort | __assert_fail_base | __assert_fail | std::_Rb_tree<T>::_M_insert_unique<T>
Crash id: e4d195e0-86be-4a40-8ea2-ad6860190907
Original: raise | abort | mozilla::detail::MutexImpl::lock | __fortify_fail_abort | __chk_fail
New:      raise | abort | mozilla::detail::MutexImpl::lock | __fortify_fail_abort | __chk_fail | g_spawn_sync
Crash id: 1012cd66-1ea1-4013-adbe-e46f70191021
Original: raise | abort | __libc_message
New:      raise | abort | __libc_message | __fortify_fail_abort | …
```
> bug 1590096: add more libc functions to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
```
socorro-cmd signature 43d8524c-7ab9-4f65-b220-caf710190501 465e3022-1e37-4dd8-80bc-da15c0190614 16bafed3-c66e-4b98-ba6e-9dfcc0190913 3faed5f6-1f83-45e9-8f6c-cac080190611
f44243f3-3d83-46f2-b760-248470190524 0b9dbbf4-8926-40fa-be1c-d71ef0190501 c739d507-2dbe-4ff2-ab8e-fa14c0190502 ebdead20-fc46-4b86-8d31-4a68e0190810 49d8181e-8b4a-4355-bda4-40d9d0191026 81699798-498d-44ee-93d1-7d9430190731 3cb984b0-e93d-4181-a289-5b4540190607 b2db67a2-4081-4d85-b839-0893e0191018 c7551462-4fe6-4dfb-b016-418b60190531 c7551462-4fe6-4dfb-b016-418b60190531 9049638d-4066-4e91-923f-dc3060190625 9049638d-4066-4e91-923f-dc3060190625 feee4cef-45b0-4c44-a798-ea1040191025
1a8a4124-23a5-4b0a-8203-29b740191029 1c305869-da99-4298-8ff9-01cc70190702 31ac5a8a-763b-4342-b234-9cf280190916 …
```
> bug 1592208: add more c functions to prefix list

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
We've done a lot of symbol uploading for libc binaries for Linux
distributions. Instead of skipping these frames, we want to include them
in the signature and move past them.
```
app@socorro:/app$ socorro-cmd signature b206311b-2b61-497c-a0b7-2978b0190522
Crash id: b206311b-2b61-497c-a0b7-2978b0190522
Original: mozilla::layers::MappedYCbCrTextureData::CopyInto
New:      libc-2.29.9000.so@0xa6735 | mozilla::layers::MappedYCbCrTextureData::CopyInto
```
> bug 1594468: move libc* lines from irrelevant list to prefix list

- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
This removes the severity=critical bit from filing bugs.
> bug 1594508: don't file bugs as "critical"

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 2927b970-0948-40d2-8511-a16d50191107
Crash id: 2927b970-0948-40d2-8511-a16d50191107
Original: __pthread_mutex_lock
New:      __pthread_mutex_lock | free | core::ptr::real_drop_in_place | servo_arc::Arc<T>::drop_slow
```
> bug 1594665: add __pthread_mutex_lock to prefix list

- docker/run_lint.sh
- requirements/constraints.txt
- requirements/default.txt
`pip check` reports if there is a mismatch between requirements and the installed packages. This is sometimes missed by auto-update tools, or is too complicated to resolve.
This PR also updates the AWS packages to get consistent versions:
* [jsonschema](https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst) 2.6.0 → 3.1.1: Support Draft 6 and 7, ECMA 262 dialect regular expressions
* awscli 1.16.271 → 1.16.276: Bump for botocore
This includes these constraint updates:
* botocore 1.12.239 → 1.13.12: Remove vendored requests, API updates
* boto3 1.9.112 → 1.10.12: Support botocore 1.13
* cfn-lint 0.19.1 → 0.24.8: Support botocore 1.13
* aws-sam-translator 1.11.0 → 1.15.1: Support botocore 1.13 and jsonschema 3.1
* pyrsistent 0.15.5 - New requirement of jsonschema
> Add pip check to linters, update AWS requirements

- CONTRIBUTING.rst
This fixes some things in the contributing docs:
1. we don't have an auto-closer anymore
2. we use black for Python code formatting
3. might as well include component=General in the link rather than talk about it
> Update contributing docs

- docker/Dockerfile
- docker/run_lint.sh
Moving "pip check" to the build step makes it fail faster if there are
issues.
> Move "pip check" from lint step to build step

- docker/Dockerfile
- docker/set_up_ubuntu.sh
Make some changes to the Docker build size:
* Following [Docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run), remove the apt cache at the end of package installs. This reduced the final image size almost 1%. It does require that `apt-get update` is run again when installing dev tools in the socorro_breakpad build, however, so it can potentially slow down builds without caches.
And, some more suggested by @willkg:
* Move breakpad package installs to ``socorro_breakpad``, to reduce final image size.
* Fix quoting in ``set_up_ubuntu.sh``.
* Combine some commands to reduce layers.
* Run ``collectstatic`` as app user, rather than ``chown`` afterwards, to eliminate a duplicate layer.
> bug 1597334: Adjust Dockerfile for size

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
This covers the first pass of signature generation changes:
bug #1599146: add __cxa_rethrow
Example: https://crash-stats.mozilla.org/report/index/229b74eb-9ef2-4f18-aef2-966ab0191125
```
app@socorro:/app$ socorro-cmd signature 229b74eb-9ef2-4f18-aef2-966ab0191125
Crash id: 229b74eb-9ef2-4f18-aef2-966ab0191125
Original: __cxa_rethrow
New:      objc_addExceptionHandler | -[NSOpenGLLayer drawInOpenGLContext:pixelFormat:forLayerTime:displayTime:]
```
bug #1599147: add objc_exception_rethrow
Example: https://crash-stats.mozilla.org/report/index/cff884cf-a283-491f-bfe2-d1ff80191125
```
app@socorro:/app$ socorro-cmd signature cff884cf-a283-491f-bfe2-d1ff80191125
Crash id: cff884cf-a283-491f-bfe2-d1ff80191125
Original: __cxa_rethrow
New:      objc_exception_rethrow | …
```
> bug 1599146, 1599147, 1599149, 1599151: signature changes pass 1

- socorro/signature/siglists/prefix_signature_re.txt
This covers four more bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1599152 : add objc_retain
https://crash-stats.mozilla.org/report/index/7e836f20-bdd7-4776-854d-d69b30190909
```
app@socorro:/app$ socorro-cmd signature 7e836f20-bdd7-4776-854d-d69b30190909
Crash id: 7e836f20-bdd7-4776-854d-d69b30190909
Original: objc_retain
New:      objc_retain | CoreFoundation@0x9d8d8
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1599155 : add CALayerRetain
https://crash-stats.mozilla.org/report/index/cf7f771e-f5aa-4230-9e7e-825bf0190903
```
app@socorro:/app$ socorro-cmd signature cf7f771e-f5aa-4230-9e7e-825bf0190903
Crash id: cf7f771e-f5aa-4230-9e7e-825bf0190903
Original: CALayerRetain
New:      CALayerRetain | CA::Layer::thread_flags_
``` …
> bug 1599152, 1599155, 1599156, 1599165: second pass on signature generation changes

- socorro/signature/siglists/prefix_signature_re.txt
This is a third round of signature generation changes.
https://bugzilla.mozilla.org/show_bug.cgi?id=1599157 : add __cxxabiv1::failed_throw
```
app@socorro:/app$ socorro-cmd signature 70ff8c5d-172d-40f3-8ef7-367050190705
Crash id: 70ff8c5d-172d-40f3-8ef7-367050190705
Original: __cxxabiv1::failed_throw
New:      __cxxabiv1::failed_throw | +[NSObject isMemberOfClass:]
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1599162 : add __semwait_signal
```
app@socorro:/app$ socorro-cmd signature 449bc42d-da64-4ac1-ba1e-608e30190709
Crash id: 449bc42d-da64-4ac1-ba1e-608e30190709
Original: shutdownhang | __semwait_signal
New:      shutdownhang | __semwait_signal | usleep
```
This isn't much better, but further improvement can be done in future PRs. …
> bug 1599157, 1599162, 1599164, 1599167, 1599168, 1599222: third round of signature generation changes

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 0b794045-87ec-4649-9ce1-73ec10191120 6f80238c-83ef-4eee-8b0a-06ee60191121 da9f75f7-852b-4e30-90cd-1fb0c0191126
Crash id: 0b794045-87ec-4649-9ce1-73ec10191120
Original: NXMapRemove
New:      NXMapRemove | -[NSControl sendAction:to:]
Crash id: 6f80238c-83ef-4eee-8b0a-06ee60191121
Original: NXMapRemove
New:      NXMapRemove | +[NSEvent isSwipeTrackingFromScrollEventsEnabled]
Crash id: da9f75f7-852b-4e30-90cd-1fb0c0191126
Original: NXMapRemove
New:      NXMapRemove | __CFCSetMakeBitmap
```
> bug 1599506: add NXMapRemove to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 88d033b1-11f3-40d6-a3ee-f11000191202 338f872c-8846-41fe-9791-28f280191202 ad3aabd7-09be-43a2-a03c-bdeb80191202
Crash id: 88d033b1-11f3-40d6-a3ee-f11000191202
Original: AllocInfo::Get<T>
New:      AllocInfo::Get<T> | moz_malloc_size_of
Crash id: 338f872c-8846-41fe-9791-28f280191202
Original: shutdownhang | AllocInfo::Get<T>
New:      shutdownhang | AllocInfo::Get<T> | TransformPassParameter_dtor
Crash id: ad3aabd7-09be-43a2-a03c-bdeb80191202
Original: AllocInfo::Get<T>
New:      AllocInfo::Get<T> | _msize
```
> bug 1600951: add AllocInfo::Get<T> to prefix list

- socorro/signature/cmd_signature.py
- socorro/signature/tests/test_utils.py
- socorro/signature/utils.py
This only affects the signature command line utility and doesn't affect
signature generation. It makes it easier to copy/paste crash ids from
various sources (bugzilla, urls, etc) to test signature generation.
To test:
```
app@socorro:/app$ socorro-cmd signature https://crash-stats.mozilla.org/report/index/0b794045-87ec-4649-9ce1-73ec10191120
Crash id: 0b794045-87ec-4649-9ce1-73ec10191120
Original: NXMapRemove
New:      NXMapRemove | -[NSControl sendAction:to:]
```
> bug 1599779: support other crashid forms in signature command

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature bp-456817ac-baef-4ecf-a79d-f2bb30191203 bp-0457571e-65d7-46a1-a7e9-801dd0191203 bp-d89453bc-36e7-4d93-9e18-d814b0191203
Crash id: 456817ac-baef-4ecf-a79d-f2bb30191203
Original: shutdownhang | moz_malloc_size_of
New:      shutdownhang | moz_malloc_size_of | ICUReporter::Free
Crash id: 0457571e-65d7-46a1-a7e9-801dd0191203
Original: moz_malloc_size_of
New:      moz_malloc_size_of | mozilla::EventListenerManager::SizeOfIncludingThis
Crash id: d89453bc-36e7-4d93-9e18-d814b0191203
Original: moz_malloc_size_of
New:      moz_malloc_size_of | sqlite3DbFree
```
> bug 1601223: add moz_malloc_size_of to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature bp-1a9ebfb8-1234-4966-b30a-aa0870191209 bp-d9b67a17-2e1c-4494-9825-e3be60191208
Crash id: 1a9ebfb8-1234-4966-b30a-aa0870191209
Original: objc_exception_throw | -[NSObject doesNotRecognizeSelector:]
New:      objc_exception_throw | -[NSObject doesNotRecognizeSelector:] | ___forwarding___ | __forwarding_prep_0___ | mozilla::gl::GLContextCGL::MigrateToActiveGPU
Crash id: d9b67a17-2e1c-4494-9825-e3be60191208
Original: objc_exception_throw | -[NSObject doesNotRecognizeSelector:]
New:      objc_exception_throw | -[NSObject doesNotRecognizeSelector:] | ___forwarding___ | __forwarding_prep_0___ | mozilla::gl::GLContextCGL::MigrateToActiveGPU
```
> bug 1602342, 1602343, 1602344: siglist changes

- webapp-django/crashstats/crashstats/management/commands/verifyprocessed.py
Previously, verifyprocessed would do an ES search using the default date range which is a week ago to today. If the crash it was looking at was outside of that range, it wouldn't get found.
This fixes it to look at the day the crash id says the collector picked it up.
> bug 1603308: fix date range for ES lookup

- webapp-django/crashstats/crashstats/management/commands/updatemissing.py
- webapp-django/crashstats/crashstats/management/commands/verifyprocessed.py
- webapp-django/crashstats/crashstats/tests/test_updatemissing.py
- webapp-django/crashstats/crashstats/tests/test_verifyprocessed.py
- webapp-django/crashstats/cron/__init__.py
This splits verifyprocessed into two tasks. Checking existing known missing processed crashes to see if they've since been processed only needs to happen once a day and it doesn't need to backfill since it checks all the known missing crashes.
Moving that to a separate task will reduce the runtime for verifyprocessed. Further, because verifyprocessed *is* a backfill task, if it needs to run for a bunch of days, it doesn't repeat the unnecessary work of updatemissing.
> bug 1603308: move update missing task into updatemissing command

- webapp-django/crashstats/crashstats/management/commands/verifyprocessed.py
In prod, it's taking too long for a worker to work through an entropy chunk. This lowers the chunk size from 5 to 4 and increases the timeout from 10 minutes to 15 minutes. The hope is that this gives workers enough time to finish an entropy chunk and not timeout.
> bug 1603308: adjust verifyprocessed entropy chunk size and timeout

- webapp-django/crashstats/crashstats/admin.py
- webapp-django/crashstats/crashstats/models.py
This removes the check to see if a missing processed crash is still
missing from the Django admin page. The check only checked S3 and not
elasticsearch, so it wasn't right. Further, it took FOREVER to run
making the Django admin page super slow.
> bug 1604317: remove missing processed check from admin

- docker-compose.yml
- docker/config/local_dev.env
- docker/config/test.env
- docker/run_setup.sh
- socorro/external/pubsub/crashqueue.py
- socorro/external/sqs/__init__.py
- socorro/external/sqs/crashqueue.py
- socorro/scripts/sqs_cli.py
- socorro/unittest/external/sqs/__init__.py
- socorro/unittest/external/sqs/conftest.py
- socorro/unittest/external/sqs/test_crashqueue.py
- webapp-django/crashstats/crashstats/configman_utils.py
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/settings/base.py
This adds the bits to Socorro to consume from and publish to AWS SQS. This adds tests and some configuration, too.
The default continues to be Google Pub/Sub. This makes no changes to how things run in production. After this lands, we'll figure out the migration plan.
Next steps on this:
1. I need to self-review it.
2. I need to set this up with real AWS SQS queues and Antenna and make sure the whole thing works.
> bug 1602121: add queue consuming and publishing for AWS SQS

- socorro/processor/processor_app.py
This adds a new timing `processor.process_crash` that covers the length of time it takes to download the raw crash data, process it, and save the processed crash.
> bug 1605716: add processor.process_crash timing

- socorro/external/es/super_search_fields.py
- socorro/processor/rules/mozilla.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
This finishes the transition from `java_stack_trace_full` (which was poorly
named and caused problems in the Elasticsearch crash storage code) to
`java_stack_trace_raw` (which doesn't).
> bug 1503344: remove java_stack_trace_full

- socorro/external/es/crashstorage.py
- socorro/unittest/external/es/test_crashstorage.py
Elasticsearch gets sad when crash reports contain values which have more than 32,766 utf-8 encoded characters. This adds some code to truncate those fields before saving to Elasticsearch.
This fixes saving `java_stack_trace` and `java_stack_trace_raw` for StackOverflow errors which can get up to 100k characters long and make Elasticsearch sad.
To test:
1. run the processor
2. process a crash report for a Java Stack Overflow error like 844d5678-e15f-4974-bcf1-d51d90191230
3. watch the logs and make sure it saves in Elasticsearch without kicking up a maxbyteslengthexceeded error
> bug 1606450: truncate long string values for Elasticsearch

- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/test_models.py
This fixes `/api/Reprocessing` to validate crash ids before submitting them. This reduces failures in the processor when it gets crash ids that aren't crash ids.
To test:
Use the /api/Reprocessing API and send in an invalid crash id. Easiest thing to do is test it with the API reference docs.
http://localhost:8000/api/#Reprocessing
> bug 1581567: validate crash ids in /api/Reprocessing

- socorro/app/fetch_transform_save_app.py
- socorro/external/boto/crashstorage.py
- socorro/external/crashqueue_base.py
- socorro/external/crashstorage_base.py
- socorro/external/es/crashstorage.py
- socorro/external/pubsub/crashqueue.py
- socorro/external/sqs/crashqueue.py
- socorro/lib/task_manager.py
- socorro/lib/threaded_task_manager.py
- socorro/processor/processor_app.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/breakpad.py
- socorro/processor/symbol_cache_manager.py
- socorro/signature/rules.py
- socorro/unittest/app/test_fetch_transform_save_app.py
- socorro/unittest/external/test_crashstorage_base.py
- socorro/unittest/lib/test_task_manager.py
- socorro/unittest/processor/__init__.py
We used to do deploys by stopping the processor service, updating the code, and then starting it again. That was a long time ago. Now we create a bunch of new processor nodes and then kill off the old processor nodes. Because of that, we no longer need the quit check code that allows the processor to shut down nicely.
To test the local dev environment:
1. run the processor
2. process a crash
3. hit ctrl-c and shut down the processor
> bug 1597730: remove quit check

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report.js
When the report view page is loaded, the correlations tab is hidden. JavaScript in the page goes to fetch correlation data and if it gets some, then it unhides the tab so as to show correlations data. The
problem here is that unhiding the tab causes the tabs to the right to jump.
This changes the code so that the tab is always shown and when there's no correlations data, it states there's no correlations data. This fixes the UI jumping which keeps biting me. It also reduces confusion around why the tab isn't showing up in some cases.
While doing this, I also unhid the Telemetry Environment tab. That will now show all the time and when there's no TelemetryEnvironment data, it'll state there's no data.
> bug 1552976: fix correlations tab

- docs/howto.rst
- webapp-django/crashstats/documentation/jinja2/documentation/docs_base.html
- webapp-django/crashstats/documentation/jinja2/documentation/memory_dump_access.html
Previously, the documentation only talked about memory dumps, but the process for requesting access covers both memory dumps and private user data.
This fixes the language so that's clearer.
> bug 1605806: fix language around requesting pii access

- minidump-stackwalk/stackwalker.cc
Recently, the crash reporter was changed so it sends a JSON blob with the annotations in it. When that happened, the type of the `ModuleSignatureInfo` value changed from a JSON-encoded string to an
object. stackwalker expected a JSON-encoded string, so if it was an object, it'd ignore it. Thus it didn't capture the signed-by information for modules.
This fixes that by supporting both JSON-encoded string and `Json::Value` values of `ModuleSignatureInfo`.
> bug 1605429: fix stackwalker to work with ModuleSignatureInfo as object

- webapp-django/crashstats/cron/management/commands/cronrun.py
- webapp-django/crashstats/cron/tests/test_cronrun.py
Previously, if `cronrun` hit an `OngoingJobError`, it would stop running any jobs. This fixes it to continue through the list of jobs that are ready to run even if one of them throws an `OngoingJobError`.
> bug 1581927: fix cronrun to run jobs despite OngoingJobError

- socorro/lib/javautil.py
- socorro/unittest/lib/test_javautil.py
Previously, we only saw "Caused By:" lines that were indented by one tab. Now we're seeing them unindented which is kicking up a `MalformedJavaStackTrace` exception.
This fixes the parsing to handle both situations.
> bug 1607519: fix Caused By handling in java stack trace parser

- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
This fixes `raw_crash["ModuleSignatureInfo"]` to always have a JSON-encoded string value so the rest of the processor doesn't have to handle both cases.
> bug 1607806: make ModuleSignatureInfo always a JSON-encoded string

- socorro/lib/util.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
`raw_crash["ModuleSignatureInfo"]` is a `DotDict` which doesn't work with `json.dumps`. This fixes the code to convert it to a dict and then `json.dumps` it.
> bug 1607806: fix converting ModuleSignatureInfo values

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature https://crash-stats.mozilla.org/report/index/d5a4148d-d3b3-4103-bf64-26aef0200108
Crash id: d5a4148d-d3b3-4103-bf64-26aef0200108
Original: __pthread_cond_wait
New:      __pthread_cond_wait | mozilla::ipc::MessageChannel::WaitForSyncNotify | mozilla::ipc::MessageChannel::Call | mozilla::plugins::PPluginScriptableObjectChild::CallNPN_Evaluate
app@socorro:/app$ socorro-cmd signature https://crash-stats.mozilla.org/report/index/bc2c76e7-b0ba-4ff7-8c12-73f0d0200107
Crash id: bc2c76e7-b0ba-4ff7-8c12-73f0d0200107
Original: __pthread_cond_wait
New:      __pthread_cond_wait | pa_cond_wait
```
> bug 1609121: add __pthread_cond_wait to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature https://crash-stats.mozilla.org/report/index/71d58118-c7f9-4323-aa58-9a0530191212 https://crash-stats.mozilla.org/report/index/ea51ec67-1cf3-4057-b6ad-a1c950200105
Crash id: 71d58118-c7f9-4323-aa58-9a0530191212
Original: mozilla::ipc::Shmem::OpenExisting
New:      mozilla::ipc::Shmem::OpenExisting | mozilla::ipc::IToplevelProtocol::ShmemCreated | mozilla::layers::PVideoBridgeParent::OnMessageReceived
Crash id: ea51ec67-1cf3-4057-b6ad-a1c950200105
Original: mozilla::ipc::Shmem::OpenExisting
New:      mozilla::ipc::Shmem::OpenExisting | mozilla::ipc::IToplevelProtocol::ShmemCreated | mozilla::layers::PCompositorManagerParent::OnMessageReceived
```
> bug 1608870: added mozilla::ipc::Shmem items to prefix list

- docs/conf.py
- docs/index.rst
- docs/spec_crashreport.rst
This adds a specification for the format of crash reports submitted to Socorro. It's specific to what Socorro accepts and how it accepts it.
This is a v0 specification. In Firefox 73, we added support for a `extra` field which has a JSON-encoded value covering all the crash report annotations. I want to cover that, too, but I think that's crash report v1 and I'll write that up after this one is approved and merged.
There are a few other things that might be interesting to cover:
1. important-to-include annotations and what they mean: ProductName, ReleaseChannel, Version, ...
2. links to documentation on minidump structure
What other things should get covered here?
> bug 1608111: initial crash report v0 specification

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 57e55e97-8d71-4ca9-b143-0708b0200116
Crash id: 57e55e97-8d71-4ca9-b143-0708b0200116
Original: __security_check_cookie | sandbox::PolicyRule::AddStringMatch
New:      sandbox::PolicyRule::AddStringMatch
```
> bug 1609247: move __security_check_cookie to irrelevant list

- docs/index.rst
- docs/spec_crashreport.rst
Originally, I was thinking the JSON-encoded value bits constitute a new version of the specification. However, since we decided that the collector would accept crash reports and the processor would fix them, I don't think it's necessary to have a new version of the specification.
Thus, this updates the specification with the new bits plus it adds a very minimal "debugging" section.
> bug 1608111: add single JSON-encoded value bits to specification

- docker/Dockerfile
While GNU coreutils chown supports `.` (albeit with a bunch of caveats), we should update all uses of `.` to `:` because that's the current way to separate uid and gid.
> bug 1610249: switch . to : in chown calls

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature a70cb2cd-0fe1-4087-976f-a820b0200123
Crash id: a70cb2cd-0fe1-4087-976f-a820b0200123
Original: mozilla::DOMEventTargetHelper::AddRef
New:      mozilla::DOMEventTargetHelper::AddRef | struct nsTimerImpl::Callback& const nsTimerImpl::Callback::operator=
```
> bug 1610792: add mozilla::DOMEventTargetHelper::AddRef to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
This is needed to disambiguate: https://crash-stats.mozilla.com/signature/?product=Firefox&signature=core%3A%3Aptr%3A%3Areal_drop_in_place%20%7C%20core%3A%3Aptr%3A%3Areal_drop_in_place%20%7C%20servo_arc%3A%3AArc%3CT%3E%3A%3Adrop_slow&date=%3E%3D2019-07-07T19%3A03%3A00.000Z&date=%3C2020-01-07T19%3A03%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-platform&_sort=-version&_sort=-date&page=1
> Add servo_arc::Arc<T>::drop_slow to the prefix list

- scripts/build-breakpad.sh
This fixes issues we're having when trying to build breakpad.
> bug 1612924: update breakpad to 216cea7bca53fa441a3ee0d0f5fd339a3a894224

- socorro/signature/siglists/prefix_signature_re.txt
This is a rebased version of PR #5206.
```
app@socorro:/app$ socorro-cmd signature  bp-9804c04c-a25e-4a54-85d0-e61150200202 bp-e08fb9b2-3af5-4265-b9bd-04fea0200131
Crash id: 9804c04c-a25e-4a54-85d0-e61150200202
Original: shutdownhang | Gecko_FinalizeCString
New:      shutdownhang | Gecko_FinalizeCString | PLDHashTable::~PLDHashTable | TelemetryOrigin::DeInitializeGlobalState
Crash id: e08fb9b2-3af5-4265-b9bd-04fea0200131
Original: OOM | large | NS_ABORT_OOM | Gecko_SetLengthCString
New:      OOM | large | NS_ABORT_OOM | Gecko_SetLengthCString | mozilla::URLPreloader::URLEntry::ReadLocation
app@socorro:/app$ 
```
> Bug 1612921 - Add some CString functions to the prefix list

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
Instead of stomping on the existing signature (derived from the frames in the stack), this changes the code to prepend the `IPCError-xxx | ShutDownKill` string.
> bug 1612569: improve ShutDownKill signatures

- socorro/external/es/super_search_fields.py
Previously, the values were getting tokenized when indexed and that
caused problems when looking at `ipc_shutdown_state` facet. This fixes
that by switching it to the keyword analyzer which doesn't tokenize.
To test, process crash reports with `ipc_shutdown_state` values. Then use supersearch and do a facet on that. The facet options should be something like:
* `SendFinishShutdown (sent)`
and not something like:
* `sendfinishshutdown`
* `sent`
> bug 1616253: fix aggregation for ipc_shutdown_state

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
This adds `RustMozCrash` and `mozglue_static::panic_hook` to the irrelevant list. If they show up in stacks, they'll get skipped over in signature generation.
This also adds `core::ops::function::Fn::call<T>` to the prefix list so it's included in the signature, but generation continues past it.
These changes let us differentiate between causes for crash reports that are all currently getting a signature of `RustMozCrash`.
> bug 1616837: add RustMozCrash to irrelevant list

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
Previously, we adjusted the rule to always prepend `IPCError-content/browser | <error>`, but we only really wanted to do that for ShutDownKill crashes--not the other kinds of IPC channel errors.
This fixes it so that ShutDownKill crashes get that bit prepended and the signatures for other crashes don't.
```
app@socorro:/app$ socorro-cmd signature 9e4d772e-719e-4711-a688-122e80200204 bp-9c65dbfc-1862-4eb4-9e88-187b10200225 bp-7fd5c699-d230-462d-a8ac-aa96a0200225
Crash id: 9e4d772e-719e-4711-a688-122e80200204
Original: IPCError-browser | ShutDownKill | gfxHarfBuzzShaper::SetGlyphsFromRun
New:      IPCError-browser | ShutDownKill | gfxHarfBuzzShaper::SetGlyphsFromRun
Same?:    True
Notes:    (1)
SignatureIPCChannelError: IPC Channel Error prepended
Crash id: …
```
> bug 1617918: fix IPC Channel Error signature generation rule

- scripts/find_crashes_with_field.py
- scripts/remove_field.py
This generalizes and improves a script for finding all the crash reports that have a specified field.
This also generalizes the script for removing data from specified crash reports.
> bug 1617911: improve tools for fixing crash report data

- docker-compose.yml
- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature  https://crash-stats.mozilla.org/report/index/709d791b-1f4f-4b2e-8cff-235380200302
Crash id: 709d791b-1f4f-4b2e-8cff-235380200302
Original: mozilla::CheckCheckedUnsafePtrs<T>::Check
New:      mozilla::CheckCheckedUnsafePtrs<T>::Check | mozilla::detail::SupportCheckedUnsafePtrImpl<T>::~SupportCheckedUnsafePtrImpl | mozilla::dom::indexedDB::(anonymous namespace)::FactoryOp::~FactoryOp
```
> bug 1619606: add mozilla::CheckCheckedUnsafePtrs<T>::Check to prefix list

- scripts/delete_crash_data.py
- scripts/permadelete_crash_data.py
- scripts/remove_field.py
This implements a script that can be run in a server environment to remove crash report data from crashstorage destinations.
Usage: `python scripts/permadelete_crash_data.py <CRASHIDSFILE>`
This has no tests, yet. I tested it manually. Need to add tests for the bug.
> bug 1619962: crash report deletion script

- product_details/FennecAndroid.json
Drop nightly version as users were migrated to Fenix.  Beta is kept at 68.6b for now as 68.7b hasn't shipped (and might never ship).
> Update Fennec versions for 68.6 release

- socorro/external/es/crashstorage.py
- socorro/unittest/external/es/test_crashstorage.py
The Elasticsearch crash storage code tries to be really forgiving for bad data. One of the things it does is truncate absurdly long string values. Strings are unicode, but are stored in Elasticsearch as utf-8, so the truncation code encodes as utf-8 to get the length.
This handles the situation where the string value can't be encoded as utf-8. In that case, probably best to consider it bad dta and replace it with "BAD DATA"
> bug 1619646: add handling for UnicodeEncodeError in truncating

- docs/crashstorage.rst
- docs/tests/system_checklist.rst
- socorro/external/boto/crashstorage.py
- socorro/external/crashstorage_base.py
- socorro/external/es/crashstorage.py
- socorro/external/fs/crashstorage.py
- socorro/processor/processor_app.py
- socorro/schemas/validate_and_test.py
- socorro/unittest/external/boto/test_crashstorage.py
- socorro/unittest/external/es/test_crashstorage.py
- socorro/unittest/external/fs/test_fspermanentstorage.py
- socorro/unittest/external/test_crashstorage_base.py
- socorro/unittest/processor/test_processor_app.py
Previously, we had a save_processed and a `save_raw_and_processed`. `save_processed` is only called by `save_raw_and_processed` and `save_raw_and_processed` is misnamed--it doesn't save the raw crash since doing that would irrecoverably change our record of what we got from the collector.
This cleans up naming and reduces these two functions down to a single `save_processed_crash`. We pass in the `raw_crash` and `processed_crash` so crashstorage can combine them into a crash report, but no crashstorage should ever stomp on the original `raw_crash` data.
Since this changes `save_raw_and_processed` into `save_processed_crash` and that's part of metrics names, this will change those metrics and we need to update the dashboards.
To test:
1. run `make test` and `make lint`
2. run the processor …
> bug 1623064: rework save_processed and save_raw_and_processed

- socorro/lib/javautil.py
- socorro/unittest/lib/test_javautil.py
There was a case where JavaStackTrace parsing would hit a multiline message where one of the lines was empty. In this case, the parser would get confused and state the JavaStackTrace was malformed.
This fixes that by restricting the check to just None allowing for empty lines.
> bug 1607519: fix JavaStackTrace parsing

- socorro/processor/processor_pipeline.py
- socorro/processor/rules/general.py
- socorro/unittest/processor/rules/test_general.py
This adds a `DeNoneRule` that will remove keys from the raw crash that have a `None` value. These come from crash annotations the crash reporter packs into a JSON-encoded value in the crash report. Previously, I think these would end up with empty strings.
The field we seem to be having the most problems with is `BuildID`.
This also adds some metrics code for the `DeNoneRule` and `DeNullRule` so we can see how often they're kicking off so as to identify bugs in the crash reporter.
> bug 1608116: add DeNoneRule

- docker/config/local_dev.env
- webapp-django/crashstats/crashstats/utils.py
- webapp-django/crashstats/settings/base.py
The featured versions list is calculated for most products based on existing crash reports. This allows the list to be dynamic and change quickly which is helpful during releases. However, this means that calculating the list is vulnerable to junk data and bugs.
This adjusts the calculation slightly in that it adds a minimum count threshold. I picked 50 after looking at all the existing products on Socorro. Going lower increases the likelihood that junk data affects the featured versions. Going higher increases the likelihood we hit an issue with less-used products where versions take a really long time to show up.
We can tweak the number a little as circumstances come up, but I think if products have a problem with it, they should do what Fennec is doing and manually maintain a list of …
> bug 1622932: fix featured versions

- webapp-django/crashstats/crashstats/jinja2/crashstats_base.html
- webapp-django/crashstats/settings/base.py
- webapp-django/crashstats/signature/jinja2/signature/signature_report.html
- webapp-django/crashstats/supersearch/jinja2/supersearch/search.html
This fixes a couple of issues raised by ZAP.
Static assets are served by whitenoise which is adding this header:
```
Access-Control-Allow-Origin: *
```
Since we're not hosting static assets on a CDN, we don't need this so we should disable it.
This adds data-no-csrf attribute to three forms:
* quick search form in the navbar
* super search form on the super search page
* signature search form
These forms all use GET method and they're search forms, but ZAP doesn't know that, so we're adding the attribute so ZAP doesn't report them as failures.
> bug 1596106: security fixes

- Makefile
- docker-compose.yml
- docker/config/local_dev.env
- docker/run_tests.sh
- docker/run_tests_in_docker.sh
- docs/localdevenvironment.rst
We can run one localstack container that handles both services, so this fixes things accordingly.
Further this updates localstack to 0.10.8.
The issue is intermittent and I can't reproduce it locally. Hopefully one of these two things reduces CI failures because the SQS container isn't really up, yet.
> bug 1624403: reduce localstack containers

- docker/config/local_dev.env
- docker/config/test.env
- docs/localdevenvironment.rst
- scripts/process_crashes.sh
- scripts/socorro_aws_s3.sh
AWS S3 bucket names can't have underscores in them. This fixes the names in the local dev environment to comply with that.
AWS SQS queue names *can* have underscores, but I figured it's easier on my brain if names all have the same conventinos so I changed those, too.
This only affects the local dev environment.
> bug 1624403: fix bucket and queue names

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature https://crash-stats.mozilla.com/report/index/6c300571-a7fa-4812-ae43-5d4850200319 https://crash-stats.mozilla.com/report/index/0b2e2416-9785-475a-b362-714260200319
Crash id: 6c300571-a7fa-4812-ae43-5d4850200319
Original: syscall
New:      syscall | std::vector<T>::operator=
Crash id: 0b2e2416-9785-475a-b362-714260200319
Original: syscall
New:      syscall | g_thread_pool_new
```
> bug 1624790: add "syscall" to prefix list

- socorro/external/es/crashstorage.py
- socorro/processor/processor_app.py
Elasticsearch crashstorage has problems with the `java_stack_trace_full` field. We removed it a while back, but crash reports processed before we removed it still have the field in the processed crash file.
This adds it to the `forbidden_keys` list for Elasticsearch. We can remove the forbidden key in August 2020.
> bug 1619638: remove java_stack_trace_full before indexing in Elasticsearch

- docker/run_tests.sh
- docker/run_tests_in_docker.sh
- scripts/waitfor.py
This adds a waitfor script that does an HTTP connection and waits for a certain response code. This switches the SQS check to use that so we can avoid HTTP 502 bad gateway which passes urlwait, but hoses CI.
> bug 1624403: switch SQS check to use waitfor script

- webapp-django/crashstats/crashstats/management/commands/verifyprocessed.py
updatemissing can't find processed crash data in Elasticsearch where the crash came in on one day and was processed the next day. This happens around midnight.
This increases the date range to look at and also nixes the `_results_number` which I don't think we need to pass in.
To test:
1. process some crashes
2. use `socorro-cmd es list` to get the list of indexes, then use `socorro-cmd es list_crashids <INDEX>` to figure out which index to delete, then `socorro-cmd es delete <INDEX>` to delete the index with crashes in it
3. run `cd webapp-django` then `./manage.py verifyprocessed` which creates a missing processed crash item
4. run `./manage.py updatemissing` and it'll say it didn't update any missing crashes
5. reprocess the crashes
6. run `./manage.py updatemissing` and it'll say it …
> bug 1625154: fix updatemissing to work across date bounds

- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
This allows grouping of Fenix nightly crash reports until they change the version number to something Socorro understands better.
> bug 1624911: change Fenix nightly versions from "Nightly..." to "0.0a1"

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
We've got lots of products that aren't like Firefox and Fennec and adding the "b0" at the end is disasterous. I don't even know how to spell that word it's so bad.
This changes the rule to only operate on Firefox, Fennec, and FennecAndroid.
> bug 1626618: change BetaVersionRule to only work on supported products

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
This adds `CxxThrowException` to the irrelevant list. `_CxxThrowException` is already there and the frame isn't helpful for signatures.
This adds `__abi_WinRTraiseCOMException` and `__abi_WinRTraiseException` to the prefix list so signature generation continues beyond them.
```
app@socorro:/app$ socorro-cmd signature bp-d0371db3-c844-43ea-94c3-19c9e0200329 bp-2282557f-868a-4a95-8db1-ab4580181218 bp-4c1410c4-c35e-4a04-b767-de09a0200401
Crash id: d0371db3-c844-43ea-94c3-19c9e0200329
Original: CxxThrowException
New:      __abi_WinRTraiseCOMException | __abi_WinRTraiseException | Windows::UI::Xaml::Application::LoadComponent
WARNING: 2282557f-868a-4a95-8db1-ab4580181218: does not exist.
Crash id: 4c1410c4-c35e-4a04-b767-de09a0200401
Original: CxxThrowException
New: …
```
> bug 1626801: add CxxThrowException and friends to sig lists

- product_details/FennecAndroid.json
Bump release to 68.7.0, and remove beta due to the migration to fenix
> Update fennec versions

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
Having `CxxThrowException` in the prefix and show up in the signature fixes some bucketing.
> bug 1626801: move CxxThrowException to prefix list

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
The values are `"true"` and `true` and it should be `"1"`. The crash reporter was fixed to always send `"1"`, but we have to handle crash reports for all the broken versions.
> bug 1626048: fix SubmittedFromInfobar values

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 9200a1e1-e1a2-4b17-89fb-19d560200402
Crash id: 9200a1e1-e1a2-4b17-89fb-19d560200402
Original: RpcpRaiseException
New:      RpcpRaiseException | RpcRaiseException | NdrpSendReceive
```
Not wildly helpful here, but it might help some other signatures.
> bug 1626801: add RpcpRaiseException to prefix list

- scripts/run_mdsw.sh
It was looking at the wrong environment variable for the command pathname. That changed a while ago, but the change missed this script.
> bug 1628311: fix scripts/run_mdsw.sh

- socorro/signature/siglists/prefix_signature_re.txt
`core::result::unwrap_failed<T>` was in the prefix list already. This generalizes it to cover both cases.
```
app@socorro:/app$ socorro-cmd signature bp-589682e0-9e35-4095-b622-c194c0200409 bp-541a1dbc-e389-46ae-b311-ea22c0200414 bp-3d3b59a9-2bf1-4eb9-bcff-cbb540200414 bp-a8edddbc-edba-489f-8340-675c70200413
Crash id: 589682e0-9e35-4095-b622-c194c0200409
Original: core::result::unwrap_failed
New:      core::result::unwrap_failed | neqo_qpack::encoder::QPackEncoder::encode_header_block
Crash id: 541a1dbc-e389-46ae-b311-ea22c0200414
Original: core::result::unwrap_failed
New:      core::result::unwrap_failed | style::rule_tree::StrongRuleNode::ensure_child
Crash id: 3d3b59a9-2bf1-4eb9-bcff-cbb540200414
Original: core::result::unwrap_failed<T> | …
```
> bug 1629854: add core::result::unwrap_failed to prefix list

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/tests/test_views.py
This cleans up some of the language (in my opinion) and also adds the "this data is sensitive" warning to the section that has links to downloading raw crash data and minidumps.
> bug 1054508: add warning to raw crash data and minidumps section

- socorro/processor/rules/breakpad.py
- socorro/unittest/processor/rules/test_breakpad.py
This switches from getattr notation to getitem notation in the breakpad processor rules. We're transitioning off of DotDict and dict doesn't support getattr notation.
I did this in a few passes:
* switch from getattr to getitem in the `breakpad.py` file and get tests to pass
* remove `DotDict` usage in the `test_breakpad.py` file and get tests to pass
* read through both files for anything I missed
To test:
1. run tests and linting
2. process some crashes
> bug 1383113: switch from getattr to getitem notation in breakpad rules

- socorro/processor/rules/breakpad.py
This removes the last bit of DotDict usage in the breakpad processor rules that I missed in an earlier pass.
> bug 1383113: remove DotDict usage in breakpad rules

- socorro/processor/rules/mozilla.py
- socorro/signature/tests/__init__.py
- socorro/signature/tests/test_signature_generator.py
- socorro/unittest/__init__.py
- socorro/unittest/processor/__init__.py
- socorro/unittest/processor/rules/test_breakpad.py
- socorro/unittest/processor/rules/test_general.py
- socorro/unittest/processor/rules/test_memory_report_extraction.py
- socorro/unittest/processor/rules/test_mozilla.py
- socorro/unittest/processor/test_processor_app.py
This updates the mozilla processor rules to getitem notation and removes `DotDict` usage.
To test:
1. run tests
2. process some crashes
> bug 1383113: switch mozilla processor rules to getitem notation

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature e6e85e81-a2e0-4356-ab68-6b1790200425
Crash id: e6e85e81-a2e0-4356-ab68-6b1790200425
Original: pthread_mutex_trylock
New:      pthread_mutex_trylock | mozilla::detail::MutexImpl::lock | mozilla::wr::RenderThread::RegisterExternalImage
```
> bug 1633473: add pthread_mutex_trylock to prefix list

- webapp-django/crashstats/crashstats/utils.py
None of our products are going to hit 1024 any time soon. We don't have the problem with other versions, so for now, let's just exclude version 1024 and push off a better fix which will likely require a lot more work until later.
> bug 1622932: explicitly exclude "1024" version

- socorro/external/crashstorage_base.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/external/boto/test_crashstorage.py
- socorro/unittest/external/es/test_crashstorage.py
- socorro/unittest/external/test_crashstorage_base.py
- socorro/unittest/processor/rules/test_mozilla.py
Seems like there was a UserId in raw crashes a while ago and someone wrote code in the processor to stomp on those values. We don't need this anymore, so we can remove it.
> bug 1633501: remove vestigal user_id bits in processor

- requirements/default.txt
- socorro/lib/versionutil.py
- socorro/unittest/lib/test_versionutil.py
- webapp-django/crashstats/crashstats/utils.py
This converts versions into semver `VersionInfo` instances and uses those for sorting. Generally, this works, but there are some hacks:
1. Firefox/Fennec versions aren't valid semver, so I changed the parser we had before to parse those versions and generate semver `VersionInfo` instances.
* 75.0a1 -> 75.0.0-alpha.1
* 75.0b2 -> 75.0.0-beta.2
2. ESR releases need to sort *after* normal regular releases. The only way to do that with semver that I could figure is to mark everything with prerelease bits so that they sort correctly.
* 68.0.2esr -> 68.0.2-xsr
Note that "xsr" parses alphabetically after alpha, beta, and release.
3. Firefox/Fennec have release candidates of betas so we have to add "rc" to everything.
* 75.0b2 -> 75.0.0-beta.2.rc.999
* 75.0.1 -> 75.0.1-release.rc.999
* 68.0.2esr …
> bug 1625515: redo version parsing and sorting

- socorro/signature/siglists/prefix_signature_re.txt
This is needed for crashes like: https://crash-stats.mozilla.org/report/index/af37f4f7-0c5d-4818-bc26-a86f10200506
> Add core::option::expect_none_failed to the prefix list

- webapp-django/crashstats/crashstats/tests/test_utils.py
- webapp-django/crashstats/settings/base.py
The file link comes up much faster than the annotate link does. If users want annotations, they can easily switch to the annotate link after the file link comes up.
> bug 1608873: switch from hg annotate to hg file link

- webapp-django/crashstats/crashstats/management/commands/bugassociations.py
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/test_bugassociations.py
- webapp-django/crashstats/settings/base.py
This adds a `BZAPI_TOKEN` setting. The `bugassociations` job and `BugzillaBugInfo` model will use it if it's available.
To test:
1. process some crashes
2. do `make shell` and `cd webapp-django` and `manage.py cronrun --job=bugassociations`
It should work fine and not log that it's using a token.
3. Set up an account and API token on https://bugzilla-dev.allizom.org/ and set in `my.env`:
```
BZAPI_BASE_URL=https://bugzilla-dev.allizom.org/rest
BZAPI_TOKEN=yourtoken
```
4. run `manage.py cronreset bugassociations` and then `manage.py cronrun --job=bugassociations`
It should run and log that it used a token.
> bug 1616718: fix code to use bugzilla api token if available

- webapp-django/crashstats/monitoring/jinja2/monitoring/index.html
- webapp-django/crashstats/monitoring/tests/test_views.py
- webapp-django/crashstats/monitoring/urls.py
- webapp-django/crashstats/monitoring/views.py
We no longer use these endpoints for monitoring anymore, so we can remove them.
> bug 1630968: remove deprecated monitoring endpoints

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
This adds `hashbrown::raw::RawTable<T>::new_uninitialized<T>` to the prefix list so signature generation can continue.
This adds `mozalloc_handle_oom`, `gkrust_shared::oom_hook::hook`, `std::alloc::rust_oom`, and `rust_oom` to the irrelevant list because they're all indicators of the OOM and otherwise not helpful.
```
app@socorro:/app$ socorro-cmd signature e4802059-f714-46b0-84c6-e76460200523 34da10d4-80ac-4142-862f-76b0a0200520
Crash id: e4802059-f714-46b0-84c6-e76460200523
Original: OOM | large | mozalloc_abort | mozalloc_handle_oom | gkrust_shared::oom_hook::hook | std::alloc::rust_oom | hashbrown::raw::RawTable<T>::new_uninitialized<T>
New:      OOM | large | mozalloc_abort | hashbrown::raw::RawTable<T>::new_uninitialized<T> | …
```
> bug 1640942: improve rust OOM signatures

- webapp-django/crashstats/crashstats/jinja2/crashstats/bugzilla_comment.txt
If the crash report represents a java error, then there's a `JavaStackTrace` annotation and Crash Stats puts that in the crash report. However, the backticks were in the wrong place in respects to if/for blocks and so it was missing the end set.
While fixing that, I tweaked the description a bit.
> bug 1641316: fix bugzilla bug creation for java errors

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/static/crashstats/css/base/layout.less
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/documentation/jinja2/documentation/docs_base.html
- webapp-django/crashstats/documentation/jinja2/documentation/protected_data_access.html
- webapp-django/crashstats/documentation/tests/test_views.py
- webapp-django/crashstats/documentation/urls.py
- webapp-django/crashstats/documentation/views.py
- webapp-django/crashstats/signature/jinja2/signature/signature_report.html
- webapp-django/crashstats/signature/static/signature/css/signature_report.less
- webapp-django/crashstats/supersearch/jinja2/supersearch/search.html
Over the years, Crash Stats has evolved how it talks about data that can only be seen by people who have been vetted and granted access to it.
This goes through and changes all the language to talk about "protected data" and "protected data access". This updates the url where the protected data access policy exists and provides a redirect for the original policy url. This reduces wasted space on the report view and adds a statement at the top explaining what can be seen and why with links to documentation on requesting protected data access. This adds exclamation marks to some sensitive fields--we should add more as we find them.
The goals of this work are three-fold:
1. use consistent language
2. make it clearer what is and isn't protected
3. make it clearer what users can see depending …
> bug 1611131: improve language around protected data and access

- webapp-django/crashstats/crashstats/static/crashstats/css/base/layout.less
This removes an errant `display: flex`.
> bug 1611131: fix protected-info css

- socorro/external/es/super_search_fields.py
This removes the "dump" field which wasn't used and wasn't exposed.
This also switches the "uuid" field from `not_analyzed` to `keyword`. I did some searches and facets and it still works fine.
> bug 1497353: remove not_analyzed fields

- socorro/external/es/super_search_fields.py
This changes `telemetry_environment` to be like `json_dump` and not searchable.
I verified that you can specify it as a column and get it back in the response, so everything continues to work except that it's no longer searchable.
> bug 1497353: make telemetry_environment not searchable

- socorro/signature/siglists/prefix_signature_re.txt
Here's a signature generation run for two signatures:
```
app@socorro:/app$ socorro-cmd signature 955b6def-f591-480f-9a5a-500340200610
Crash id: 955b6def-f591-480f-9a5a-500340200610
Original: libc.so@0x1cca6 | libc.so@0x5b415 | libc.so@0x5348d | libart.so@0x233305
New:      libc.so@0x1cca6 | libc.so@0x5b415 | libc.so@0x5348d | libart.so@0x233305 | dalvik-allocation stack (deleted)@0x51da13
app@socorro:/app$ socorro-cmd signature c8359231-1e7b-4f51-ab74-b199e0200610
Crash id: c8359231-1e7b-4f51-ab74-b199e0200610
Original: libc.so@0x6b410 | libc.so@0x1dbd0 | libart.so@0x4377e0
New:      libc.so@0x6b410 | libc.so@0x1dbd0 | libart.so@0x4377e0 | libart.so@0x437ef0 | libart.so@0x522a3c | libart.so@0x24b9d0 | libart.so@0x2d61d8 | libart.so@0x315814 | libart.so@0x4e2378 | …
```
> bug 1644234: add libart.so to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
Signature generation examples:
```
app@socorro:/app$ socorro-cmd signature aafd3c93-7bfa-460c-a896-93f390200610 8a4b7d41-c233-4cc8-885a-569660200610
Crash id: aafd3c93-7bfa-460c-a896-93f390200610
Original: FindElementCommon
New:      FindElementCommon | ClientSideCacheContext::FindInSharedCache
Crash id: 8a4b7d41-c233-4cc8-885a-569660200610
Original: FindElementCommon
New:      FindElementCommon | TryGetGlyphElement<T>
```
> bug 1646675: add FindElementCommon to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 7757e29c-012e-46df-a487-15c560200629
Crash id: 7757e29c-012e-46df-a487-15c560200629
Original: mozilla::detail::nsTStringRepr<T>::Equals
New:      mozilla::detail::nsTStringRepr<T>::Equals | mozilla::dom::ContentChild::RecvNotifyAlertsObserver
```
> bug 1649774: add mozilla::detail::nsTStringRepr<T>::Equals to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
This swaps out `::Equals` for `::` which will cover all the member functions.
```
app@socorro:/app$ socorro-cmd signature 7757e29c-012e-46df-a487-15c560200629
Crash id: 7757e29c-012e-46df-a487-15c560200629
Original: mozilla::detail::nsTStringRepr<T>::Equals
New:      mozilla::detail::nsTStringRepr<T>::Equals | mozilla::dom::ContentChild::RecvNotifyAlertsObserver
app@socorro:/app$ socorro-cmd signature 6210c03a-a844-4d99-8bd6-d04370200709
Crash id: 6210c03a-a844-4d99-8bd6-d04370200709
Original: mozilla::detail::nsTStringRepr<T>::First
New:      mozilla::detail::nsTStringRepr<T>::First | mozilla::HTMLEditor::InsertTextWithQuotationsInternal
```
> bug 1651336: add mozilla::detail::nsTStringRepr<T>:: to prefix list

- docker/Dockerfile
- socorro/unittest/processor/rules/test_mozilla.py
- webapp-django/crashstats/crashstats/models.py
This upgrades to 3.8.5. In doing that, we switched from stretch to buster as the base image. That required a tweak to the debian packages we install.
The switch from 3.7 to 3.8 also required us to fix a test which had a line that now kicks up a syntax error.
It also required us to fix a test that relied on an iterator over dict keys being stable even if you're deleting the underlying structure. I'm not sure what changed between Python 3.7 and 3.8 to cause the test to fail, but I didn't spend a lot of time looking since the fix is a good defensive thing to do anyhow.
To test:
1. build
2. run tests
3. test the processor by processing crashes with minidumps
> bug 1649810: upgrade to python 3.8.5

- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/utils.py
Firefox and Fennec have trains based on MAJOR number of the version, but
Fenix has trains based on MAJOR.MINOR. This adjusts the figuring for
featured versions to take that into account.
> bug 1658023: rework featured_versions to be based on MAJOR.MINOR

- webapp-django/crashstats/crashstats/utils.py
This fixed featured versions figuring for Firefox and Fennec where
version numbers can be like 79.0b2.
> bug 1658023: handle Firefox versions correctly

- webapp-django/crashstats/crashstats/jinja2/crashstats_base.html
- webapp-django/crashstats/crashstats/jinja2/macros/signature_startup_icons.html
- webapp-django/crashstats/crashstats/static/crashstats/css/base.less
- webapp-django/crashstats/crashstats/static/crashstats/css/components/statusicon.less
- webapp-django/crashstats/crashstats/utils.py
- webapp-django/crashstats/settings/bundles.py
- webapp-django/crashstats/signature/jinja2/signature/signature_summary.html
- webapp-django/crashstats/signature/views.py
- webapp-django/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html
- webapp-django/crashstats/topcrashers/tests/test_views.py
- webapp-django/crashstats/topcrashers/views.py
- webapp-django/package-lock.json
- webapp-django/package.json
This adds indicators to the signature report summary and topcrashers
report to indicate if all of the crash reports have DOMFissionEnabled as
well as an indicator if some of the crash reports have
DOMFissionEnabled.
This also removes the remnants of font-awesome stuff we had before which
wasn't in use and replaces it with an updated font-awesome. font-awesome
is used for the fission icon.
> bug 1659795: add fission indicators to signature/topcrashers reports

- webapp-django/crashstats/crashstats/utils.py
This increases the criteria for "potential fission crash" to "at least
50% of crashes" to reduce false positives.
> bug 1659795: change criteria for "potential fission crash"

- product_details/Fenix.json
- product_details/Fennec.json
- product_details/FennecAndroid.json
- product_details/Firefox.json
- product_details/FirefoxReality.json
- product_details/Focus.json
- product_details/GeckoView.json
- product_details/GeckoViewExample.json
- product_details/README.rst
- product_details/ReferenceBrowser.json
- product_details/SeaMonkey.json
- product_details/Thunderbird.json
- socorro/scripts/fetch_crashids.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/bug_comment.txt
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/conftest.py
- webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/views.py
- webapp-django/crashstats/productlib.py
- webapp-django/crashstats/settings/base.py
This reworks the "create a bug" stuff so that each product can specify multiple (text, url template) combinations for where to file bugs. Because it's a url template, it can be a Bugzilla url or a GitHub url or whatever else.
In doing that, I tied the report view to products so I had to fix some tests that had the product hard-coded to something that wasn't in the test fixtures.
This also tweaks `fetch_crashids` so it can take a product--I was getting a little tired of specifying supersearch urls.
> bug 1657465: support creating github issues

- product_details/Fenix.json
This redoes the "create a bug" links for Fenix per Roger's suggestions.
Couple of unexciting things:
1. There's no link back to the crash report. With bugzilla, it replaces "bp-xxxxxxxxx" with a link to the crash report on Crash Stats. GitHub doesn't do this (obviously). So we'd need to explicitly create the link. This PR doesn't do that.
2. For Fenix crashes, it'd probably help if device information were included. I'm not sure what information is specifically helpful, though.
I figure we can improve after we get some more feedback.
> bug 1657465: redo Fenix "create a bug" links

- docker/config/test.env
- webapp-django/crashstats/crashstats/jinja2/crashstats/bug_comment.txt
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
- webapp-django/crashstats/settings/base.py
To test:
1. process a fenix crash report so you have something to work with
2. look at the report view for that crash report and at the Bugzilla tab (that should get renamed) and click on the create a bug links
3. verify that there is now a crash report url and not the bp-xxxxxx text in the issue description
> bug 1657465: fix crash report link in create-a-bug links

- webapp-django/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html
This fixes the platform count column when looking at a specific platform in the topcrashers report. Looking at the code history, I suspect this has been broken for years. :cry: 
To test:
1. process 100 crashes
2. look at topcrashers report for all platforms, then for a specific platform--the counts for that platform should not be an empty field
> bug 1654028: fix platform count in topcrashers report

- webapp-django/crashstats/settings/base.py
- webapp-django/crashstats/signature/urls.py
- webapp-django/crashstats/supersearch/urls.py
- webapp-django/crashstats/urls.py
This adds the two prefix url matches to `OIDC_EXEMPT_URLS` to cover
signature graphs and aggregations so they don't try to redirect to OIDC
login.
> bug 1473068: add signature urls to OIDC_EXEMPT_URLS

- webapp-django/crashstats/cron/__init__.py
- webapp-django/crashstats/cron/management/commands/cleanse_cronlog.py
- webapp-django/crashstats/cron/tests/test_cleansecronlog.py
This adds a `cleanse_cronlog` command and schedules it to run once a week.
It'll delete cron log entries older than 6 months.
> bug 1603663: add cleanse_cronlog

- socorro/processor/rules/mozilla.py
To test:
1. process 48c08f87-06c1-4e30-8793-24bf70200908 without this fix and it'll spit out a traceback in the logs, but nothing in the processor notes
2. process 48c08f87-06c1-4e30-8793-24bf70200908 with this fix and it won't spit out anything in the logs, but it will add a processor note
> bug 1663670: handle zlib errors when decompressing memory report

- docs/signaturegeneration.rst
- socorro/signature/cmd_doc.py
- socorro/signature/pipeline.rst
- socorro/signature/siglists/README.rst
* cleanup and improve overview
* remove duplicate content
* add philosophy on signature generation which helps guide future
changes
* add example cases where adding a symbol to the irrelevant list is the
right thing to do
* fix the pipeline docs generator command to make the rule name bold
for easier reading
> Improve signature generation docs

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
Symbols that have `$VARIANT$` in them are platform-specific variants with
the platform in the symbol name which prevents signatures from
coalescing across platforms.
This adds `$VARIANT$` to the irrelevant list such that *all* symbols that
have this bit in them will be skipped over during signature generation.
```
app@socorro:/app$ socorro-cmd signature 2ce1acf5-9caa-47cc-9380-5e7870200910 08a036a0-f6a2-4052-bb8d-b13090200910
Crash id: 2ce1acf5-9caa-47cc-9380-5e7870200910
Original: _platform_memmove$VARIANT$Merom | nsTArray_Impl<T>::ReplaceElementsAtInternal<T> | mozilla::TrackBuffersManager::InsertFrames
New:      nsTArray_Impl<T>::ReplaceElementsAtInternal<T> | mozilla::TrackBuffersManager::InsertFrames
Crash id: 08a036a0-f6a2-4052-bb8d-b13090200910
Original: …
```
> bug 1662720: add *$VARIANT$* symbols to irrelevant list

- product_details/Fenix.json
- product_details/Fennec.json
- product_details/FennecAndroid.json
- product_details/Firefox.json
- product_details/FirefoxReality.json
- product_details/Focus.json
- product_details/GeckoView.json
- product_details/GeckoViewExample.json
- product_details/ReferenceBrowser.json
- product_details/SeaMonkey.json
- product_details/Thunderbird.json
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/tests/conftest.py
- webapp-django/crashstats/crashstats/views.py
- webapp-django/crashstats/productlib.py
Most products don't have data on Buildhub. For products that don't, Crash Stats shouldn't show a Buildhub link because it doesn't make any sense.
> bug 1664509: only show Buildhub link if product has buildhub data

- docs/tests/system_checklist.rst
- webapp-django/crashstats/api/jinja2/api/documentation.html
- webapp-django/crashstats/api/static/api/css/documentation.less
- webapp-django/crashstats/documentation/jinja2/documentation/supersearch/home.html
- webapp-django/crashstats/documentation/static/documentation/js/documentation.js
- webapp-django/crashstats/documentation/views.py
We really want users to be specifying a User-Agent if they're using the APIs. It helps us help them. This fixes the docs to specify that.
Further, it fixes the supersearch documentation to work better when there's no version data.
While I was there, I also made some updates to the system checklist.
> bug 1665126: add note about user-agent

- docker/socorro_entrypoint.sh
- socorro/signature/siglists/irrelevant_signature_re.txt
From Gabriele: Crash signatures that include heap failures on Windows
tend to be very, very long as the first few frames are taken by Windows
own error-handling machinery. It might be better to ignore those frames
entirely in signature generation to make the interesting part of the
stack stand out.
```
app@socorro:/app$ socorro-cmd signature b1ccbc43-9695-4ecb-ba98-d95830200929 e1c9683d-0bc2-4911-b727-7726c0200929
Crash id: b1ccbc43-9695-4ecb-ba98-d95830200929
Original: RtlReportFatalFailure | RtlReportCriticalFailure | RtlpHeapHandleError | RtlpHpHeapHandleError | RtlpLogHeapFailure | RtlFreeHeap | Dns_HeapFree
New:      RtlFreeHeap | Dns_HeapFree
Crash id: e1c9683d-0bc2-4911-b727-7726c0200929
Original: RtlReportFatalFailure | RtlReportCriticalFailure | …
```
> bug 1667741: add Windows heap failure error handling to irrelevant list

- webapp-django/crashstats/crashstats/jinja2/crashstats/bug_comment.txt
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
If the reason (extracted from the minidump) and `MozCrashReason` are available, add them to the bug description.
To test:
1. process a crash that has a `Reason`, but no `MozCrashReason` and verify that bugs created with that include a `Reason: ` line in the description (https://crash-stats.mozilla.org/report/index/bce9d31c-9785-4b66-8b6f-b382d0200929)
2. process a crash that has a `Reason` and a `MozCrashReason` and verify that bugs created with that include a `Reason: ` line and a `MOZ_CRASH Reason: ` line in the description (https://crash-stats.mozilla.org/report/index/1f36ff08-cc80-4733-b439-591eb0200929)
3. process a crash that has a `MozCrashReason` that has naughty bits in it, log in so you can see the raw version of the data, and make sure the `MOZ_CRASH Reason: ` line in the bug …
> bug 1667158: add reason and mozcrashreason to bug descriptions

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
This adds a bunch of frames to the irrelevant and prefix list related
to X11/GDK/glib error functions.
One note is that this adds "handle_error" to the irrelevant list, but
that's a prefix for "handle_errorf" which we added to the prefix list.
> bug 1667734: add frames to irrelevant and prefix lists

- socorro/signature/siglists/irrelevant_signature_re.txt
_XReply is an x11 function that waits for a reply packet and triggers an
error if it gets back an XError which is what we see in crash reports,
so it's not very interesting.
> bug 1668381: add _XReply to irrelevant list

- webapp-django/crashstats/crashstats/jinja2/crashstats/bug_comment.txt
- webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
`MozCrashReason` only gets generated in cases where the `reason` is `SIGSEGV` or `EXCEPTION_BREAKPOINT` so the reason isn't helpful. This changes the template to show `MozCrashReason` or `Reason` or nothing.
Bugzilla comments use Markdown for formatting, so we need to put the `MozCrashReason`/`Reason` in backticks so the values aren't kicking off Markdown formatting inadvertently.
To test:
1. process a crash report with a `Reason`, but no `MozCrashReason` and check bug link--should show `Reason` in backticks
2. process a crash report with a `Reason` and a `MozCrashReason` and check bug link--should show `MozCrashReason` in backticks
> bug 1669163: fix formatting for reason/moz_crash_reason in bug links

- webapp-django/crashstats/crashstats/jinja2/crashstats/bug_comment.txt
The reason was being escaped by the bug creation template, but it
shouldn't be. This marks the relevant fields as safe.
> bug 1669163: fix reason in bug report creation

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 4ec1c321-8d50-49c7-88fc-6876d0201021
Crash id: 4ec1c321-8d50-49c7-88fc-6876d0201021
Original: OOM | large | NS_ABORT_OOM | nsTSubstring<T>::Append
New:      OOM | large | NS_ABORT_OOM | nsTSubstring<T>::Append | mozilla::net::WebSocketChannelChild::RecvOnMessageAvailableInternal
```
> bug 1672386: add nsTSubstring<T>::Append to prefix list

- .circleci/config.yml
When doing things in CircleCI that interact with docker hub, we want to
log in so we're not affected by rate-limiting.
> bug 1669247: add dockerhub auth

- .circleci/config.yml
This changes DOCKER_USERNAME to DOCKER_USER and DOCKER_PASSWORD to
DOCKER_PASS. This switches to using DOCKERHUB_REPO.
This cleans up the "push to dockerhub" step so it's more like the
Dockerflow one. That pushes a "latest" *only* when the branch is main,
pushes a tag *only* when it's a real tag. This stops pushing individual
commit images by sha--those are now "latest" and there's only one of
them.
> bug 1669247: conform to Dockerflow standards

- socorro/signature/siglists/irrelevant_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 9305172a-e7a8-49e0-9894-2c38b0201112 bb91e742-f3ec-4018-8608-a00b70201113
Crash id: 9305172a-e7a8-49e0-9894-2c38b0201112
Original: std::io::stdio::_eprint
New:      <env_logger::Logger as log::Log>::log
Crash id: bb91e742-f3ec-4018-8608-a00b70201113
Original: std::io::stdio::_eprint
New:      env_logger::{{impl}}::log
```
> bug 1676900: add std::io::stdio::_eprint to irrelevant list

- webapp-django/crashstats/signature/static/signature/js/signature_tab_reports.js
jquery-tablesorter gets the value type wrong some how and thus sorts the values in the column wrong. If we "hard-code" it to be "text", then it sorts alphabetically which is correct.
There are a bunch of tables in Crash Stats, but I'm fixing this one specifically figuring we can generalize later if that's appropriate.
> bug 1676593: fix adapter_driver_version sorting in signature report

- webapp-django/crashstats/crashstats/static/crashstats/js/socorro/tablesorter_utils.js
- webapp-django/crashstats/settings/bundles.py
- webapp-django/crashstats/signature/static/signature/js/signature_tab_reports.js
Hex addresses were getting sorted alphanumerically. This fixes the address value so that it gets converted to a base 10 int and then sorted.
> bug 1032227: fix sorting of hex addresses in signature report

- requirements.txt
* Bump pytz from 2020.1 to 2020.4 (from PR #5622)
* Bump packaging from 20.4 to 20.7 (from PR #5618)
> Updates 20201202

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/documentation/jinja2/documentation/protected_data_access.html
This cleans up the language about protected data near things like minidump links. The goal is to make it much clearer what is expected of the user in regards to protected data.
This also switches out the old terms "personal data" for the new term "protected data" in the data policy.
> bug 1681388: clean up protected data language and links

- socorro/external/es/super_search_fields.py
I can't tell why `remote_type` was originally protected data. The values in that field suggest it's fine to make public and it's a public field in the crash ping data set so I'm making it public in Crash Stats.
> bug 1678739: make remote_type public

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
This normalizes `anonymous namespace' (Windows) and (anonymous
namespace) (Mac/Linux) to (anonymous namespace).
> bug 1672847: normalize anonymous namespace variations

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/views.py
This fixes the raw info and minidump links so it's clearer what they
link to--it always confuses me and I work on the site.
This also modifies the note that minidumps are protected data by
additionally stating they should not be shared with third-parties.
> bug 1681388: specify minidump sharing policy near links

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/signature_sentinels.txt
For Linux assertions, the interesting stuff comes fater
`__GI___assert_fail`, so this adds that as a sentinel and then adds it to
the irrelevant list so it doesn't also show up in the signatures.
```
socorro-cmd signature bp-eda13b8d-e4ad-48a5-ad3a-d2bf80201208 bp-c8110dcc-0c70-44be-b387-0bdd20201208 bp-4aa0a5e6-21ee-4d24-951c-855240201208 bp-3e212630-f206-460d-a570-1da3b0201208
Crash id: eda13b8d-e4ad-48a5-ad3a-d2bf80201208
Original: __GI_raise
New:      libwayland-client.so.0@0x639c
Crash id: c8110dcc-0c70-44be-b387-0bdd20201208
Original: __GI_raise
New:      libwayland-client.so.0@0x639c
Crash id: 4aa0a5e6-21ee-4d24-951c-855240201208
Original: raise | abort | __assert_fail_base.cold | __GI___assert_fail
New:      poll_for_event
Crash id: …
```
> bug 1681347: fix Linux assertion crash signatures

- socorro/signature/rules.py
The crash ping data seems to have crashing_thread as a str. I figured it's prudent to fix the code to handle both str and int cases.
> Force crashing_thread to be an int

- socorro/signature/rules.py
We changed `dump_syms` to yield a better symbol for cases where we have a
dll without symbols. The better symbol is structured like:
```
<unknown in foo.dll>
```
The `< >` triggers the collapsing types in the CSignatureTool
normalization code. This adds an exception so that these frames don't
get converted to `<T>`.
> bug 1685178: fix signature generation for unknown in dll frames

- docker/Dockerfile
- docker/Dockerfile.docs
- requirements.in
- requirements.txt
In the previous attempt to upgrade from Python 3.8 to 3.9, I hit
problems with building lxml and sasl. Since then, the lxml problem went
away.
sasl is a dependency of pyhs2. That library is both unused (we don't use
Hive) and unmaintained (since 2016). I removed that which removed the
sasl and thrift dependencies.
That unblocked upgrading to Python 3.9.
> bug 1674791: update to Python 3.9.1

- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/static/crashstats/css/base/tables.less
- webapp-django/crashstats/crashstats/static/crashstats/css/pages/report_index.less
The crash reporter in android-components which Fenix uses captures
breadcrumbs and puts it in the Breadcrumbs annotation.
This adds a processor rule to validate it and add it to the processed
crash and then display it in the Details of the report view.
This marks it as protected data, so if you don't have access to that,
you can't see it.
This doesn't make it searchable. I decided not to deal with that until I
know more about how people want to search it (or even if people do want
to search it).
> bug 1671276: process breadcrumbs and show on details page

- socorro/external/es/supersearch.py
- socorro/unittest/external/es/test_supersearch.py
When someone does a supersearch and specifies a date range, we don't
want to try to search indices that are outside the retention policy. In
September, I wrote some code that I thought correctly removed indices
that weren't valid, but I didn't think about how our index templates
include a week number, but not a year.
This fixes that code so it's not longer doing bad comparisons with index
names and instead figures out the set of valid indices and intersects
that with the set getting searched.
This is the correct fix for the test failure I saw last week.
> bug 1643339: re-fix cutoff policy code

- docker/Dockerfile
This updates minidump-stackwalk to 2021.01.11.
> bug 1683873, 1683871: update minidump-stackwalk to 2021.01.11

- socorro/unittest/external/es/test_super_search_fields.py
This one test is failing sometimes. I'm pretty sure it's a
race-condition between the state of ES indices and what the test is
doing to setup the indices it needs for the test.
This adds some `health_check` calls which should enforce the cluster is
good for the test to continue.
> Fix flakey ES test with more state-checking

- socorro/external/es/super_search_fields.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/views.py
If you don't have protected data access, then on the Details tab, you
see the "JavaStackTrace (redacted)" key with the java_stack_trace value.
It doesn't show up at all on the Metadata tab.
If you do have protected data access, then on the Details tab, you see
JavaStackTrace (Raw) key with the java_stack_trace_raw value and on the
Metadata tab, you see JavaStackTrace with the java_stack_trace_raw
value.
If you have protected data access, this is confusing because you're
seeing both the raw value in the Details tab and the sanitized value in
the Metadata tab and they have the same value which makes it seem like
Crash Stats is not sanitizing the value correctly.
This fixes that by changing the "Metadata" tab to "Crash annotations",
splitting that data into "public" and "protected" sections, …
> bug 1682931: reduce JavaStackTrace confusion

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
This changes things like `$_52` to `$` in signatures so that they group
better.
```
app@socorro:/app$ socorro-cmd signature ffa98c79-33e2-4983-9f13-2f96e0210126
Crash id: ffa98c79-33e2-4983-9f13-2f96e0210126
Original: mozilla::dom::indexedDB::(anonymous namespace)::QuotaClient::ShutdownWorkThreads::$_52::__invoke
New:      mozilla::dom::indexedDB::(anonymous namespace)::QuotaClient::ShutdownWorkThreads::$::__invoke
```
> bug #1688249: remove lambda number from signature

- socorro/signature/siglists/irrelevant_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature bp-e17483cd-347e-46fb-ab61-fdc320210131
Crash id: e17483cd-347e-46fb-ab61-fdc320210131
Original: OOM | large | mozalloc_abort | alloc::alloc::__alloc_error_handler::__rg_oom
New:      OOM | large | mozalloc_abort | std::fs::read::inner
```
> Bug 1690034: add _rust_alloc_error_handler to irrelevant list

- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/urls.py
- webapp-django/crashstats/crashstats/views.py
- webapp-django/crashstats/urls.py
These files were served with staticfiles before. The Django docs say
that's not "hardened for production", so I reworked them to be memoized
views.
> bug 1416014: redo favicon.ico and contribute.json

- socorro/lib/requestslib.py
- socorro/lib/util.py
- socorro/unittest/lib/test_util.py
- webapp-django/crashstats/crashstats/models.py
This drops the `backoff_factor` to 0.1 and the default timeout to 3. This makes it less likely that trying to request a resource from a
non-responsive service (*cough*Bugzilla*cough*) doesn't end up exceeding Gunicorn's timeout value at which point Gunicorn kills the process.
I also dropped the waitlist generator from `[2, 2, 2, 2, 2]` to `[1, 1,1, 1, 1]` which might alleviate a similar issue in the crashstorage code where it's trying to push something to AWS S3 and has to retry a few times.
> bug 1691393: drop defaults for http requests

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/jinja2/crashstats_base.html
This is a first pass at adding summary information for the page so when
systems like Matrix/Slack show a summary of the url of a crash report
view page, it has something more helpful to show.
> bug 1688203: improve crash report view summary in Matrix

- socorro/scripts/fetch_crashids.py
This fixes `fetch_crashids` so it's possible to specify getting crashids
for all products rather than a specific product. Previously, it
defaulted to Firefox, so there wasn't a way to specify "all products".
To test:
```
$ make shell
app@socorro:/app$ socorro-cmd fetch_crashids --num=5
app@socorro:/app$ socorro-cmd fetch_crashids --num=5 --product=all
```
> bug 1688880: fix fetch_crashids to work for all products

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/static/crashstats/css/base.less
- webapp-django/crashstats/crashstats/static/crashstats/css/base/typography.less
- webapp-django/crashstats/crashstats/static/crashstats/css/components/note.less
- webapp-django/crashstats/documentation/jinja2/documentation/supersearch/home.html
- webapp-django/crashstats/documentation/static/documentation/css/documentation.less
- webapp-django/crashstats/profile/jinja2/profile/profile.html
This adds a note that shows up in the Profile page and the report view if `your_crash` is true stating that we're no longer collecting Email data and the subsequent consequences.
In order to make the note standout, I repurposed the side-note from the documentation.
> bug 1692504: add note to Profile and report view re: email

- webapp-django/crashstats/crashstats/static/crashstats/css/components/panel.less
This reduces the specificity of the CSS rule matching li items and
adding the list-style. This fixes the column buttons in the signature
report Reports tab and also the tabs in the search results so they don't
show discs anymore.
> bug 1693265: fix select buttons in signature report

- webapp-django/crashstats/crashstats/static/crashstats/css/components/panel.less
This fixes the aggregation headers in the signature report summary tab.
It used "header", so I had to fix the title class tweak I did a few
commits ago.
> bug 1693265: fix signature report summary headers

- socorro/processor/rules/mozilla.py
hyphen is a valid module name character, so it shouldn't get removed in
sanitizing. This also adds A-Z.
> bug 1603747: fix modules_in_stack for modules with hyphens

- webapp-django/crashstats/api/views.py
- webapp-django/crashstats/settings/base.py
- webapp-django/crashstats/tokens/middleware.py
This stops creating/saving django sessions for API endpoint requests. This also nixes the anoncsrf cookie since we don't need that with the API.
To test:
1. run the webapp
2. log in and create an API token
3. use curl to hit the SuperSearch endpoint a few times:
```
curl -v -H "Auth-Token: TOKEN" http://localhost:8000/api/SuperSearch/
```
4. verify that no cookies are set in the response
5. verify that ```select count(*) from django_session``` doesn't change
> bug 1262424: don't create/save django session for API endpoints

- webapp-django/crashstats/crashstats/jinja2/crashstats/signup.html
- webapp-django/crashstats/crashstats/static/crashstats/css/components/panel.less
This redoes the headers on the signup page so they match more of the
site. Further, this tweaks the li CSS so it doesn't affect the rest of
the site.
To test:
1. run the webapp
2. go to `http://localhost:8000/signup/` and verify it looks ok
3. log in and go to the API Tokens page, create a token with multiple permissions, and verify the permissions show correctly
> bug 1693265: fix signup page layout

- socorro/signature/siglists/irrelevant_signature_re.txt
```
$ socorro-cmd signature 773fb3cf-cd3b-4721-928e-371490210224 9ffa8dfa-efd0-40ae-a5a4-d82a10210224 af565290-30b1-4543-a67c-857d50210223 20610573-2fff-4dfb-97bc-253330210222
Crash id: 773fb3cf-cd3b-4721-928e-371490210224
Original: mozalloc_abort | abort | g_assertion_message
New:      mozalloc_abort | abort | set_button_image_get_info_cb
Crash id: 9ffa8dfa-efd0-40ae-a5a4-d82a10210224
Original: mozalloc_abort | abort | g_assertion_message
New:      mozalloc_abort | abort | ensure_surface_for_gicon
Crash id: af565290-30b1-4543-a67c-857d50210223
Original: mozalloc_abort | abort | g_assertion_message.cold
New:      mozalloc_abort | abort | ensure_surface_for_gicon
Crash id: 20610573-2fff-4dfb-97bc-253330210222
Original: mozalloc_abort | abort …
```
> bug 1694894: add glib assertion bits to irrelevant list

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
For macOS >= 11, the "pretty version" consists of just the major version
part of the os_ver from system_info from the minidump.
For example, this system_info value:
```
"system_info": {
"cpu_arch": "arm64",
"cpu_count": 8,
"cpu_info": "",
"os": "Mac OS X",
"os_ver": "11.2.1 20D74"
},
```
now yields os_pretty_version value "macOS 11".
> bug 1693579: fix os_pretty_version for macOS >= 11

- socorro/external/boto/crash_data.py
- webapp-django/crashstats/api/views.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/jinja2/crashstats/signup.html
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/static/crashstats/css/base/reset.less
- webapp-django/crashstats/crashstats/static/crashstats/css/base/typography.less
- webapp-django/crashstats/crashstats/static/crashstats/css/components/panel.less
- webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report.js
- webapp-django/crashstats/crashstats/tests/conftest.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/views.py
This redoes the "Raw data and minidumps" tab so that the links are at
the top and a syntax-highlighted and more usable version of the
minidump-stackwalk output is below it.
This fixes the data links so they're generated in the view code using
API endpoints rather than an odd crashstats view. This fixes the
RawCrash model to have a class method for figuring out the binary
filename rather than a static template.
This redoes how we do list-style CSS by adding a couple of
tailwind-inspired classes and putting them in the typography base file.
> bug 1696910: fix data links and redo "raw data and minidumps tab"

- socorro/signature/siglists/signature_sentinels.txt
This removes `mozilla::detail::MutexImpl::unlock` from the sentinels list. There's a problem with stack unwinding so having this in the sentinels list causes crash reports with different causes to unhelpfully end up with the same signature.
```
app@socorro:/app$ socorro-cmd signature ab8322f0-31ff-4723-8d9f-ca4f80210216 28027409-e582-4bee-ad01-c51bc0210216 9cbd629b-b449-4758-a77c-6c03e0210216
Crash id: ab8322f0-31ff-4723-8d9f-ca4f80210216
Original: mozilla::detail::MutexImpl::unlock | free | moz_arena_malloc
New:      js::GCMarker::processMarkStackTop
Crash id: 28027409-e582-4bee-ad01-c51bc0210216
Original: mozilla::detail::MutexImpl::unlock | free | moz_arena_malloc
New:      js::GCMarker::eagerlyMarkChildren
Crash id: 9cbd629b-b449-4758-a77c-6c03e0210216 …
```
> bug 1692983: remove mozilla::detail::MutexImpl::unlock from sentinels

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
There are two permissions involved in showing the links. Originally, I
split the links into two separate sections--one for each permission.
However, that adds a lot of visual junk to the top of the screen and
it's hard to parse.
This reduces the two sections into a single section in a kind of
"whatever--close enough" mode. In reality, there's only one group we use
and that group has both permissions, so while they're two separate
things, it's not the case that someone would have one but not the other.
> bug 1696910: reduce data links

- socorro/signature/cmd_signature.py
This adds a markdown output format to signature generation cli that's
useful for Bugzilla and GitHub comments. It makes it easier to parse the
output.
> Add markdown format to signature generation cli

- webapp-django/crashstats/monitoring/views.py
This changes the cache_key that we use to test cache set/get with such
that it's unique. I think this will prevent race conditions from two
webapp things doing the cache set/get test at the same time from bumping
into one another creating a spurious error.
> bug 1699122: make cache key in __heartbeat__ unique

- docs/products.rst
- product_details/FennecAndroid.json
This adds the minimum support for FennecAndroid so that viewing Fennec
crash reports doesn't kick up an HTTP 500.
We can remove this file in 6 months when the Fennec data has expired.
This also adds a note to the product documentation about this.
> bug 1700172: re-add FennecAndroid product support

- docker/Dockerfile
This picks up the following two fixes:
`01a5aa3`: Surface the `LastErrorValue` in json output (#17) (Gankra)
`5896847`: Remove the frame limit on the `crashing_thread` preview (Gankra)
> bug 1700770: update minidump-stackwalk

- requirements.in
- requirements.txt
* Bump requests from 2.24.0 to 2.25.1 (from PR #5730)
> Updates 20210401 2

- socorro/signature/siglists/prefix_signature_re.txt
Recreating @jrmuizel pr #5732. This should help separate the signatures on bug 1695379.
Examples:
```
app@socorro:/app$ socorro-cmd fetch_crashids --signature-contains=Emplace | socorro-cmd signature
Crash id: acc562ff-6ab4-46cb-aafd-1545c0210404
Original: OOM | large | mozalloc_abort | moz_xmalloc | std::vector<T>::_Emplace_reallocate<T>
New:      OOM | large | mozalloc_abort | moz_xmalloc | std::vector<T>::_Emplace_reallocate<T> | gl::Program::loadBinary
Crash id: 06ada910-8946-4ce9-9b9b-cdca80210404
Original: OOM | large | mozalloc_abort | moz_xmalloc | std::vector<T>::_Emplace_reallocate<T>
New:      OOM | large | mozalloc_abort | moz_xmalloc | std::vector<T>::_Emplace_reallocate<T> | gl::Program::loadBinary
Crash id: …
```
> bug 1702984: add std::vector<T>::_Emplace_reallocate<T> to the prefix list

- socorro/external/es/super_search_fields.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
- webapp-django/crashstats/settings/base.py
Previously, we set the `process_type` value to `None` if there was no
ProcessType annotation. This is the case for "main" aka "browser" aka
"parent" process crashes. Then in Supersearch we handled "browser"
search as "does not have a ProcessType". That's awkward when you want to
look at an aggregate of the `process_type` field since "does not exist"
won't show up in the aggregate. Yuck.
This redoes all that nonsense. Now the default `process_type` is "parent"
because that's the word that's used in the gecko code so we maintain
terminology. All crash reports will have a `process_type` in the processed
crash going forward. This lets us remove the hard-coded "browser means
does not exist", it fixes the weirdness with aggregates, the Process
Type field shows up in all crash reports in the …
> bug 1701357: change default `process_type` to parent

- socorro/external/es/super_search_fields.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/tests/test_views.py
There are several values for process_type that a crash report can have.
If it is "content", then we want to additionally show the RemoteType
value, but only if the user has protected data access.
If it is "plugin", then we want to additionally show data about the
plugin process.
This cleans the template code up so that's clearer both in the template
code and also in the rendered template.
> bug 1701357: redo display of process_type in Details tab

- socorro/lib/search_common.py
- socorro/unittest/lib/test_search_common.py
- webapp-django/crashstats/settings/base.py
After the process_type changes, the TopCrasher report had a "parent"
filter and a "browser" filter. If you were looking at TopCrashers by
process type, that split the parent process crash reports into two
separate lists. That would eventually fix itself as data expired, but
it's incredibly inconvenient right now.
This changes the TopCrashers report filters by changing Supersearch to
treat "process_type=parent" and "process_type=browser" filters as "crash
reports where process_type is parent OR has no ProcessType".
That makes TopCrashers report "parent" type filter work correctly
regardless of when the crash report was processed.
> bug 1701357: fix topcrasher report process type filter

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature d869361c-382f-420e-85e2-b42ce0210414 1cf5e9c6-0d2c-4b4f-a4bc-47ceb0210414 d554208b-f8c3-49bf-bc45-c6dd60210408 e5a88ff7-7bc8-4193-b527-cafa90210411 17a969a9-b000-47cf-a378-193e20210410
Crash id: d869361c-382f-420e-85e2-b42ce0210414
Original: NS_CycleCollectorSuspect3
New:      NS_CycleCollectorSuspect3 | <T>::operator() | __crt_seh_guarded_call<T>::operator()<T>
Crash id: 1cf5e9c6-0d2c-4b4f-a4bc-47ceb0210414
Original: NS_CycleCollectorSuspect3
New:      NS_CycleCollectorSuspect3 | L10nRootTranslationHandler::Release
Crash id: d554208b-f8c3-49bf-bc45-c6dd60210408
Original: NS_CycleCollectorSuspect3
New:      NS_CycleCollectorSuspect3 | std::_Tree<T>::_Erase
Crash id: …
```
> bug 1705027: add NS_CycleCollectorSuspect3 to prefix list

- webapp-django/crashstats/crashstats/utils.py
- webapp-django/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html
The percent of total crashes diff between previous and current should go
"up" when moving towards 100 and "down" when moving towards 0. Given
that, We want current - previous to figure out the difference.
This also adds "helpful" up/down arrows to make the TopCrashers lines
easier to skim without having to read the hover text.
> bug 1704872: fix operands for percent_of_total_crashes_diff calculation

- socorro/external/es/super_search_fields.py
Previously, you couldn't query "adapter_vendor_id has terms
Qualcomm"--you'd get an empty result set. However "adapter_vendor_id has
terms 0x8086" would work.
This changes the query type to string and now you can do
"adapter_vendor_id contains Qualcomm" or "adapter_vendor_id is Qualcomm"
and those work fine.
> bug 1671593: fix adapter_device_id and adapter_vendor_id querying

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
- socorro/signature/utils.py
Signature generation used to mutate the stack frames adding a
"normalized" key to them. Not only do we not use that, but there's
another bit of code elsewhere that used to remove it because it was
unhelpful.
This gets rid of the normalized caching altogether. It adds a test to
make sure we're not mutating in the future. It reduces some code around
generating signatures from a stack which suggested that these tools had
the same API but was a lie.
> bug 1699492: fix mutation issues in signature generation

- socorro/processor/rules/mozilla.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/tests/test_utils.py
- webapp-django/crashstats/crashstats/utils.py
- webapp-django/crashstats/crashstats/views.py
This improves the data in the Extensions tab by combining the data in
the "Add-ons" crash report annotation with the data in the
"addons.activeAddons" Telemetry Environment section.
> bug 974968, 1629943: improve Extensions tab

- webapp-django/crashstats/signature/jinja2/signature/signature_report.html
- webapp-django/crashstats/signature/views.py
This fixes the correlations tab in the signature report so it shows up
all the time (no more hidden tabs) and also moves the "is this a
correlations product" check to JS.
> bug 1705573: fix correlations tab in signature report

- docker/Dockerfile
- socorro/unittest/external/es/test_crashstorage.py
https://github.com/mozilla-services/minidump-stackwalk/releases/tag/2021.04.19
`18140ad`: Include the list of unloaded modules in the output (#22) (gabrielesvelto)
`dc9ecb5`: Print out subcodes when dealing with __fastfail() exceptions on Windows (gabrielesvelto)
`6d0ace7`: Add the unpacked PGO data to the list of ignored files (gabrielesvelto)
`e91df29`: Make the stackwalker print out the name of NTSTATUS error codes (gabrielesvelto)
> Update minidump-stackwalk to 2021.04.19

- socorro/signature/siglists/prefix_signature_re.txt
This adds KiRaiseUserExceptionDispatcher, KiFastSystemCall, and SetEvent
to the prefix list so that signature continues past them to Firefox
frames.
```
app@socorro:/app$ socorro-cmd signature 1e66cc1e-a574-4a16-9baf-fdc7f0210421
Crash id: 1e66cc1e-a574-4a16-9baf-fdc7f0210421
Original: KiRaiseUserExceptionDispatcher
New:      KiRaiseUserExceptionDispatcher | KiFastSystemCall | sbupd.dll
app@socorro:/app$ socorro-cmd signature 6818b0d9-28d0-454f-924a-4efa10210421
Crash id: 6818b0d9-28d0-454f-924a-4efa10210421
Original: KiRaiseUserExceptionDispatcher
New:      KiRaiseUserExceptionDispatcher | SetEvent | (anonymous namespace)::wasapi_stream_reset_default_device
```
> bug 1706075: add Windows functions to prefix list

- socorro/lib/search_common.py
- webapp-django/crashstats/supersearch/form_fields.py
- webapp-django/crashstats/supersearch/static/supersearch/js/lib/dynamic_form.js
This fixes super search so all fields can use "exist/does not exist" filter. Previously, only string fields could.
This makes it a lot easier to search for crash reports that have or don't have a specific field. Previously, you'd have to hack it in some cases and in others, it wasn't possible.
For example, `ProcessType` annotation isn't included in main process crash reports. Previously, you'd have to do a facet on the `process_type` field and then subtract the total number from the total number of crash reports in that same datetime range because there  was no way to search for "crash reports that have no `process_type` field".
I tested this out by processing 50 Firefox crashes and then looking at "exists/does not exist" for these fields:
* boolean: `record_replay`
* str: `phc_kind`
* …
> bug 973894: fix super search so all fields can use exists filter

- socorro/app/fetch_transform_save_app.py
- socorro/external/boto/crashstorage.py
- socorro/external/crashstorage_base.py
- socorro/external/fs/crashstorage.py
- socorro/processor/processor_app.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/base.py
- socorro/processor/rules/breakpad.py
- socorro/processor/rules/general.py
- socorro/processor/rules/memory_report_extraction.py
- socorro/processor/rules/mozilla.py
- socorro/scripts/reprocess.py
- socorro/unittest/app/test_fetch_transform_save_app.py
- socorro/unittest/external/boto/test_crashstorage.py
- socorro/unittest/external/fs/test_fspermanentstorage.py
- socorro/unittest/external/test_crashstorage_base.py
- socorro/unittest/processor/rules/test_breakpad.py
- socorro/unittest/processor/rules/test_general.py
- socorro/unittest/processor/rules/test_mozilla.py
- socorro/unittest/processor/test_processor_app.py
- socorro/unittest/processor/test_processor_pipeline.py
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/settings/base.py
This adds basic support for multiple rulesets in a processing pipeline
and the ability to specify which ruleset to use when reprocessing a
crash report.
It adds a "regenerate_signature" ruleset which only runs the
SignatureGenerationRule.
It adds a "--ruleset" argument to the reprocess command.
It adds a "ruleset" tag to the process_crash timing metric so we can
differentiate between timings for different processing pipeline
rulesets.
The Reprocessing API validates ruleset names using a Django setting.
Invalid rulset names result in an HTTP 400.
If the processor gets a ruleset name that doesn't match a ruleset, then
it'll log an error, drop the crash id, and move on to the next one in
the queue.
This also renames "raw_dumps" to "dumps" in the processor. It's a
shorter name and we don't …
> bug 1705469: add support for multiple rulesets in a processing pipeline

- socorro/signature/generator.py
The `Result` class for signature generation didn't have a `__repr__` which
made it a pain to debug with. This fixes that by making it a dataclass.
> Change Result to be a dataclass

- socorro/signature/generator.py
This uses a typing style that works with Python 3.7.
> Fix type annotations on Result class

- .readthedocs.yml
This updates building docs to use Python 3.9 and also fixes linting
errors in `.readthedocs.yml` file.
> Fix .readthedocs.yml file and update to python 3.9

- .readthedocs.yml
ReadTheDocs doesn't support Python 3.9, yet, so set it back to 3.8.
> Set ReadTheDocs to 3.8

- socorro/external/es/super_search_fields.py
- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/api/views.py
- webapp-django/crashstats/manage/admin.py
- webapp-django/crashstats/manage/admin_urls.py
- webapp-django/crashstats/manage/templates/admin/socorro_admin_index.html
- webapp-django/crashstats/manage/templates/admin/supersearch_status.html
- webapp-django/crashstats/supersearch/models.py
This adds a super search status page to the admin where we can see the
list of indices available as well as the latest mapping. The latter will
help debug various super search problems because the mapping specifies
which fields are indexed and how.
> bug 1546800: add supersearch status page to admin

- socorro/external/es/super_search_fields.py
- webapp-django/crashstats/manage/templates/admin/supersearch_status.html
The template for index names is `socorro%Y%W`. The `%W` is the week number.
It's hard for me to figure out what the date is for a week, so I tweaked
the code to figure out the start date for that week and show that in the
indices list, too.
> bug 1546800: fix supersearch status to show dates for indices

- socorro/external/es/super_search_fields.py
The `%W` and `%w` anchor differently. This fixes the code to make sure we're
always looking at Mondays.
> bug 1546800: fix date figuring in supersearch status admin page

- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/signature/jinja2/signature/signature_summary.html
The signature report has a Product table that shows the count of crash
reports for a specific version and how many installations. The count is
a precise count of a value that has a small domain of options. The
number of installations is a cardinality aggregation of a datestamp
which has a very large domain of options and thus Elasticsearch computes
an approximate. It's possible for the number of installations to exceed
the number of crash reports which makes no sense and is confusing.
This adds "(approx)" to the column header label. It also caps the number
of installations displayed so it's never more than the number of crash
reports.
> bug 1709024: clarify Installations count in Product table of signature report

- docs/products.rst
This adds some links on how to integrate crash reporting into a product.
I don't think people are generally looking for that kind of
documentation here, but it's a natural thing to cover in Socorro's
product-support documentation.
This updates the docs on version requirements and adds some details on
the versioning schemes used by various products currently supported.
> Add links to integrating crash reporting with product; fix version notes

- docker/Dockerfile
The leftpad code in stackwalk was segfaulting when processing 0-byte
minidumps. This updates to 2021.05.27 which fixes that.
> bug 1713104: fix segfault in stackwalk for 0-byte minidumps

- docker/Dockerfile
This picks up another segfault fix where the minidump doesn't have a system info stream and the leftpad code looks at the system info stream to determine the arch.
I tested it with these crash reports:
* fef248b7-cd01-498a-bc77-353b80210527
* 6caa9e0b-c983-4225-9e2d-0c5c00210526
* 3ebab252-01ff-4646-bbd4-9c3c30210527
The first two caused segfaults that were fixed last week. The last of those three had a segfault that's fixed by minidump-stackwalk 2021.06.01.
> bug 1713104: update minidump-stackwalk to 2021.06.01

- docker/Dockerfile
This picks up the fastfail fix.
> bug 1713104: update minidump-stackwalk to 2021.06.02

- socorro/signature/siglists/prefix_signature_re.txt
This will separate out the signatures in https://bugzilla.mozilla.org/show_bug.cgi?id=1678409
> Add a useless hashbrown frame

- socorro/signature/siglists/irrelevant_signature_re.txt
That signature is coalescing very different stacks/causes.
Example crash reports from the bug:
```
app@socorro:/app$ socorro-cmd signature a9a647b0-cbec-4e80-9abc-1897e0210607
Crash id: a9a647b0-cbec-4e80-9abc-1897e0210607
Original: get_fpsr
New:      NlsGetCacheUpdateCount
app@socorro:/app$ socorro-cmd signature ba44bb89-ac6f-4ea2-81a2-99b780210609
Crash id: ba44bb89-ac6f-4ea2-81a2-99b780210609
Original: get_fpsr
New:      CTopologyCache::MarkNotInUse
app@socorro:/app$ socorro-cmd signature a69bb7de-33f0-422c-88a9-267680210609
Crash id: a69bb7de-33f0-422c-88a9-267680210609
Original: get_fpsr
New:      DoMozStackWalkThread
```
> Bug 1715634 - add get_fpsr to the irrelevant signature list

- requirements.in
- requirements.txt
- webapp-django/crashstats/settings/base.py
* Update django-waffle, boto3, awscli
* update django-waffle to 2.2.1 which fixes the Jinja2 deprecation
warning
* update boto3 from 1.17.44 to 1.17.110
* update awscli from 1.19.44 to 1.19.110
* update requests from 2.25.1 to 2.26.0
* switches from chardet to charset-normalizer
* updates from idna 2 to idna 3
* Bump humanfriendly from 9.1 to 9.2 (from PR #5819)
> Updates 20210713 2

- socorro/signature/cmd_signature.py
The signature command uses the RawCrash and ProcessedCrash APIs, but was
looking for "errors" in the JSON response instead of "error" to figure
out if there was an error. That's wrong. This fixes it.
> bug 1720162: fix error in signature command

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
- socorro/signature/tests/test_utils.py
- socorro/signature/utils.py
This marks crash reports from WER that don't have a `OOMAllocationSize` annotation, but do have a `last_error_value` as `ERROR_COMMITMENT_LEVEL` as OOM crashes.
To do that, I needed access to the crashing thread data. There was a bunch of code around accessing that which was different, so I centralized that and added tests.
While doing that, I reworked `SignatureRunWatchDog` rule so it didn't use subclassing but was instead its own rule.
```
app@socorro:/app$ socorro-cmd signature 220a1716-f404-42a0-9fb2-79a0c0210707
Crash id: 220a1716-f404-42a0-9fb2-79a0c0210707
Original: mozilla::wr::RenderCompositorD3D11SWGL::TileD3D11::Map
New:      OOM | unknown | mozilla::wr::RenderCompositorD3D11SWGL::TileD3D11::Map
```
> bug 1716742: mark last_error_value ERROR_COMMITMENT_LEVEL as OOM

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ cat crashids.txt | socorro-cmd signature
Crash id: 18c190a7-4426-4f3e-a9c5-ed29e0210713
Original: KiRaiseUserExceptionDispatcher | GetHandleInformation
New:      GetHandleInformation
Crash id: 0d5d9b1c-2885-4a5f-85b1-02bb60210713
Original: KiUserExceptionDispatch
New:      _TypeMatch
Crash id: b8da1857-f8a7-4bf7-b7d1-c093f0210714
Original: RtlFailFast2 | RtlpHandleInvalidUserCallTarget | RtlDispatchException | KiUserExceptionDispatcher | LdrpValidateUserCallTarget
New:      mozilla::layout_telemetry::AutoRecord::~AutoRecord
Crash id: ce3e50b9-565e-435f-ac4d-bd79f0210714
Original: LdrpICallHandler
New:      LdrpDispatchUserCallTarget
Crash id: 4186b4c8-dec6-4f85-be63-e86ba0210714
Original: shutdownhang | …
```
> bug 1715747: add Windows fastfail frames to irrelevant list

- socorro/signature/siglists/prefix_signature_re.txt
Example:
```
app@socorro:/app$ socorro-cmd signature ca9e27c5-0239-479c-a271-033e90210713
Crash id: ca9e27c5-0239-479c-a271-033e90210713
Original: __pthread_kill | pthread_kill
New:      __pthread_kill | pthread_kill | abort | gpusGenerateCrashLog.cold.1
```
> bug 1716611: add pthreads_kill to prefix list

- socorro/external/es/super_search_fields.py
- socorro/lib/search_common.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/lib/test_search_common.py
- socorro/unittest/processor/rules/test_mozilla.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/signature/tests/test_views.py
A long time ago, we used "browser" as the default and did some shenanigans to make it work as such. We transitioned to using "parent" as the default value and added a processor rule to fill in the default process type if there wasn't one already. Now all crash reports have a process type and we no longer use "browser".
This removes the special casing for handling "browser" as a process type and covering crash reports that didn't have one in the crash annotations.
> bug #1703407: remove handling for "browser" as a process type

- docker/Dockerfile
This picks up a fix to minidump-stackwalk such that it looks at the `ThreadNamesList` stream for threadnames before looking at the crash annotations.
> bug 1721683: update minidump-stackwalk to 2021.07.21

- docs/requirements.in
- docs/requirements.txt
* Bump sphinx from 4.1.0 to 4.1.2 (from PR #5840)
* Bump requests from 2.25.1 to 2.26.0 (from PR #5839)
> Updates 20210804 2

- socorro/signature/siglists/irrelevant_signature_re.txt
This adds:
* KiFastSystemCall
* KiUserApcDispatch
* KiUserApcDispatcher
* KiUserCallbackDispatch
* KiUserCallbackDispatcher
* LdrpDispatchUserCallTarget
* LdrpHandleInvalidUserCallTarget
Output:
```
app@socorro:/app$ socorro-cmd signature 43c6e4f0-cc39-4a29-8dd0-5ea770210804 ceed976b-4458-4c9b-8619-0f7490210730 8cacdf33-176c-4221-91bd-ee4d80210730 3be5e8e4-1153-4cb0-ae77-44cf00210804 14165c39-c22e-4562-aae9-6e6a90210804 20ce8912-5e38-4180-b569-f63680210729 a69913dd-d123-42cc-8a79-795470210731
Crash id: 43c6e4f0-cc39-4a29-8dd0-5ea770210804
Original: KiFastSystemCall | sbupd.dll
New:      sbupd.dll
Crash id: ceed976b-4458-4c9b-8619-0f7490210730
Original: RtlReleaseActivationContext | RtlDispatchAPC | KiUserApcDispatch
New:      RtlReleaseActivationContext | RtlDispatchAPC | …
```
> bug 1723465: add more windows symbols to irrelevant list

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
- socorro/signature/utils.py
This adds a signature generation rule that looks at crash_info.type reason and uses that as an indicator that the crash is an OOM.
`STATUS_FATAL_MEMORY_EXHAUSTION` and `STATUS_NO_MEMORY` are both OOM indicators.
This also adds a test for another OOM indicator I added recently but didn't add a test for.
> bug 1723474: look at reason for OOM indicator

- socorro/external/es/super_search_fields.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/models.py
I tested with 66f3bbb9-75cb-45ba-979b-b4cea0210806. It works with "is true", "is false", "exists", and "does not exist" as expected.
> bug 1723691: make windows_error_reporting searchable

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
https://bugzilla.mozilla.org/show_bug.cgi?id=1582382 moved `gkrust_shared::oom_hook` to `mozglue_static::oom_hook`, so we need to add the latter to the irrelevant list to get better signatures for rust out-of-memory crashes.
Example crashes:
```
app@socorro:/app$ socorro-cmd signature 21420c42-fbcf-4df7-8256-da45c0210812 c3058341-138b-449b-87c4-ff89a0210812 a04eaddc-0175-419d-b70b-557530210812
Crash id: 21420c42-fbcf-4df7-8256-da45c0210812
Original: OOM | large | mozalloc_abort | mozglue_static::oom_hook::hook
New:      OOM | large | mozalloc_abort | webrender_api::display_list::DisplayListBuilder::with_capacity
Crash id: c3058341-138b-449b-87c4-ff89a0210812
Original: OOM | large | mozalloc_abort | mozglue_static::oom_hook::hook
New:      OOM | large | mozalloc_abort | …
```
> Adjust signature list for `oom_hook` rename

- docs/index.rst
- docs/products.rst
This updates the docs to point to the new crashreporting matrix channel
and removes the mention of the tools-socorro mailing list which is dead.
> Update chat channel in docs

- docker/Dockerfile
- docker/Dockerfile.docs
- requirements.in
- requirements.txt
* Bump pytest from 6.2.4 to 6.2.5 (from PR #5860)
* Bump python from 3.9.6-slim to 3.9.7-slim in /docker (from PR #5854)
> Updates 20210910 2

- socorro/signature/siglists/irrelevant_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 484fa5f4-f0f3-4246-b997-c99e10210913
Crash id: 484fa5f4-f0f3-4246-b997-c99e10210913
Original: mozilla::widget::WlCrashHandler
New:      wl_array_copy | wl_log_set_handler_client
```
> bug 1730463: add mozilla::widget::WlCrashHandler to irrelevant list

- socorro/signature/siglists/irrelevant_signature_re.txt
```
app@socorro:/app$ socorro-cmd fetch_crashids --signature=_report_gsfailure --num=1 | socorro-cmd signature
Crash id: c8251b18-f378-443d-ac40-234230210919
Original: _report_gsfailure
New:      mozilla::net::nsProtocolProxyService::AsyncResolveInternal
```
> bug 1728738: add windows guard stack functions to irrelevant list

- docker/Dockerfile
This picks up 2021.09.20 of minidump-stackwalk which picks up the
changes to interpret macOS crashes.
> bug 1727733: update stackwalker to pick up macos improvements

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/views.py
This makes the raw data tab a little easier:
1. it drops use of "raw crash" which is an internal Socorro name for
"crash annotations" which is more widely understood
2. it removes the API urls which reduces some of the clutter
3. it breaks the dumps out into a separate section
> bug 1730948: improve raw data tab

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
Windows 11 shows up as versions >= 10.0.21996. That doesn't fit well
with our map-based figuring, so I tweaked the rule to cover that with an
explicit check.
This also fixes the tests so that the versions tested look like actual
versions we're getting.
> bug 1731255: add support for Windows 11 to platform_pretty_version

- socorro/signature/pipeline.rst
- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
This backs out the changes made for bug 1612569 so that shutdownkill
signatures all end up in the same bucket again.
```
app@socorro:/app$ socorro-cmd signature af1ff5c9-4cfa-4795-a0c2-279480210920
Crash id: af1ff5c9-4cfa-4795-a0c2-279480210920
Original: IPCError-browser | ShutDownKill | mozilla::ipc::MessagePump::Run
New:      IPCError-browser | ShutDownKill
Notes:    (1)
SignatureIPCChannelError: IPC Channel Error stomped on signature
```
> bug 1727149: back out shutdownkill signature changes

- socorro/signature/siglists/irrelevant_signature_re.txt
```
app@socorro:/app$ socorro-cmd fetch_crashids --signature=__GI___pthread_mutex_lock --num=1 | socorro-cmd signature
Crash id: 2e39ca47-e04c-4036-bc84-0d20c0210921
Original: __GI___pthread_mutex_lock
New:      BaseAllocator::malloc | malloc | alloc::raw_vec::finish_grow
```
> bug 1731972: add `__GI___pthread_mutex_lock` to irrelevant list

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature f215fecd-0cb9-49f3-92d1-a5aee0210924
Crash id: f215fecd-0cb9-49f3-92d1-a5aee0210924
Original: mozilla::detail::InvalidArrayIndex_CRASH
New:      mozilla::detail::InvalidArrayIndex_CRASH | mozilla::widget::ScreenGetterWayland::GetScreenForWindow
```
> bug 1732662: add mozilla::detail::InvalidArrayIndex_CRASH to prefix list

- socorro/external/es/super_search_fields.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
This pulls out the `TelemetryEnvironment.partner.distributionId` value and puts it in the `processed_crash` as `distribution_id`. This value represents which vendor build the product.
If it's not there at all (no `TelemetryEnvironment`, etc), we don't know and mark "unknown".
If it's null, we mark "mozilla".
We use the value as is for everything else.
This allows us to search and aggregate on `distribution_id`.
> bug 1732414: extract distributionId

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
```
app@socorro:/app$ socorro-cmd signature 854ac3f3-c283-466c-a80a-df9030211002
Crash id: 854ac3f3-c283-466c-a80a-df9030211002
Original: abort | wasm_rt_allocate_memory
New:      OOM | unknown | abort | wasm_rt_allocate_memory
```
> bug 1733910: add ERROR_NOT_ENOUGH_MEMORY as OOM indicator

- socorro/signature/siglists/irrelevant_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature f2856f7c-9727-4ddd-8df7-e898b0211004 a22dc1e7-e2cd-4500-8f3b-521d40211001 7b8fb40c-411e-45e6-a3c3-7f9660210930
Crash id: f2856f7c-9727-4ddd-8df7-e898b0211004
Original: g_log_default_handler
New:      g_settings_schema_get_value
Crash id: a22dc1e7-e2cd-4500-8f3b-521d40211001
Original: mozalloc_abort | abort | g_logv.cold
New:      mozalloc_abort | abort | g_malloc
Crash id: 7b8fb40c-411e-45e6-a3c3-7f9660210930
Original: g_log_structured
New:      libX11.so.6@0x4532c
```
> bug 1733907: add glib functions to irrelevant list

- socorro/signature/siglists/irrelevant_signature_re.txt
This was a sentinel frame added in rust 1.47 for trimming backtraces. We don't want to add it to the sentinel frame list because it doesn't actually communicate that it's a panic.
https://crash-stats.mozilla.org/report/index/6768f24b-e431-4f10-9cbf-c4b3c0211009 is a crash affected by this.
> Add __rust_end_short_backtrace to ignored frames

- docker/Dockerfile
This forces `cargo install` to use the lock file in rust-minidump when
building `minidump-stackwalk`. That forces it to use the same versions
of things when building the binary.
> bug 1738716: force `cargo install` to use lock file

- socorro/external/es/super_search_fields.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/general.py
- socorro/unittest/processor/rules/test_general.py
This adds a field that we can search using contains/does-not-contain and
aggregate on to help us answer questions like:
1. Which crash reports have file named xyz? For example, which have a
memory_report.
2. Which crash reports have crash annotation XYZ? For example, which
have a new crash annotation field we're not indexing yet.
This also adds a processor note with "invalidkeys" to indicate when the
crash report has keys that are malformed.
> bug 1697051: add crash_report_keys field

- socorro/processor/processor_pipeline.py
- socorro/processor/rules/breakpad.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/external/es/test_crashstorage.py
- socorro/unittest/processor/rules/test_breakpad.py
- socorro/unittest/processor/rules/test_mozilla.py
The CrashingThreadRule set crashedThread in the processed crash, but that's not used anywhere. We do have a bunch of places that need the crashing thread index and they do slightly different calculations to get it.
I changed this rule to set `processed_crash["crashing_thread"]` which has the index of the crashing thread or None.
I changed some other rules to use this information.
I didn't change anything in the webapp. Because this adds a new field `crashing_thread`, it won't be in any crash reports processed before this is deployed. I'll add a note to the bug to update the webapp side in 6 months after the old data has expired out of the system.
> bug 1740397: rework CrashingThreadInfoRule

- socorro/external/es/super_search_fields.py
This improves the description of the uptime_ts field by copying the
description for the crash annotation it's based on from
`CrashAnnotations.yaml`.
This also improves the description for the uptime field by adding some
details for how the value is calculated.
This isn't great. We really need a way to annotate fields and expose
those annotations such that we can capture historical knowledge for
these fields, bugs related to them, etc. But this is good enough for
now.
> Improve uptime_ts and uptime field docs

- docker/Dockerfile
- docker/config/local_dev.env
- docker/config/test.env
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/breakpad.py
- socorro/processor/rules/mozilla.py
- socorro/signature/rules.py
- socorro/unittest/processor/rules/test_breakpad.py
- webapp-django/crashstats/crashstats/utils.py
This adds a new MinidumpStackwalkRule that runs the rust-minidump
minidump-stackwalk binary on minidumps to walk the stack, symbolicate
symbols, and extract other information.
This adds a configuration option `processor.minidump_stackwalk` for
flipping between BreakpadStackwalkerRule2015 and MinidumpStackwalkRule.
If it's set to "rust", then it uses MinidumpStackwalkRule. All other
values including being unset will use BreakpadStackwalkerRule2015.
This also fixes a bunch of code looking at the json_dump output to
better handle when a key exists, but the value is None.
> bug 1737691: add new MinidumpStackwalkRule

- socorro/external/es/crashstorage.py
- socorro/external/es/super_search_fields.py
- socorro/processor/rules/breakpad.py
- socorro/unittest/processor/rules/test_breakpad.py
This adds a value for when breakpad stackwalker processes the minidump.
It also adds the field as a keyword field to the index so we can search
and aggregate on it.
> bug 1711897: add stackwalk_version to index

- webapp-django/crashstats/crashstats/jinja2/macros/pagination.html
This increases the page padding from 2 to 4 in the pagination links in
search results. 4 makes it easier to skip ahead further without hitting
almost every page.
> bug 1741529: increase page padding in pagination links

- socorro/external/es/crashstorage.py
- socorro/unittest/external/boto/test_crashstorage.py
- socorro/unittest/external/es/test_crashstorage.py
- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/test_views.py
completeddatetime and startedDateTime were deprecated in favor of completed_datetime and started_datetime. This removes the old forms.
> bug 1706783: remove completeddatetime and startedDateTime

- socorro/signature/siglists/prefix_signature_re.txt
Examples:
```
app@socorro:/app$ socorro-cmd fetch_crashids --num=10 --signature=RaiseFailFastException | socorro-cmd signature
Crash id: 3615db47-200f-476f-975d-918c50211117
Original: RaiseFailFastException
New:      RaiseFailFastException | FailFastWithHR
Crash id: b8f17a20-184f-4d69-b6c6-3dad80211117
Original: RaiseFailFastException
New:      RaiseFailFastException | FailFastWithHR
Crash id: 3b1ee90a-8294-482b-b995-af03b0211117
Original: RaiseFailFastException
New:      RaiseFailFastException | FailFastWithHR
Crash id: 6ed324f9-6bb0-40d9-ba96-6e1650211117
Original: RaiseFailFastException
New:      RaiseFailFastException | FailFastWithHR
Crash id: b89bc708-d0cd-4407-b14b-9bc370211117
Original: RaiseFailFastException
New: …
```
> bug 1741764: add RaiseFailFastException to prefix list

- socorro/processor/rules/breakpad.py
- socorro/processor/rules/mozilla.py
- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
- socorro/signature/tests/test_signature_generator.py
- socorro/unittest/processor/rules/test_breakpad.py
- socorro/unittest/processor/rules/test_mozilla.py
This tweaks the code to skip minidump processing for 0-byte dump files.
There's no reason to do all the work if there's nothing there to
process.
This also improves the processor notes for downstream rules that look
for data generated by minidump processing. If the data ain't there, then
there's nothing for those rules to do. I reduced the language, added
prefixes, and in some cases, nixed the notes altogether.
> bug 1737691: skip processing for 0-byte dump files

- docker/config/local_dev.env
- socorro/processor/rules/breakpad.py
This changes localdev to use /data for symbols things. This makes it
easier to debug configuration for directories that minidump-stackwalk
needs to use.
This adds some additional logging for the contents in /tmp when we hit
an OSError.
> bug 1737691: log /tmp/symbols contents and change localdev

- docker/Dockerfile
- docker/config/local_dev.env
- socorro/processor/rules/breakpad.py
This removes some cruft from the Dockerfile that I noticed while I was tinkering with things.
This undoes the changes to localdev configuration and sets the symbols cache and symbols tmp directories to be `/tmp` based. If we point them to `/data`, then we have to have something with root access in the container to create the directories. We could do that in the Dockerfile, but then there's a mismatch between what the Dockerfile does and what configuration specifies. That's more trouble than it's worth in the local dev environment because it's unclear what we'd actually be validating. Better off defaulting everything to `/tmp`.
This also changes `MinidumpStackwalkRule` to create the symbols cache and symbols tmp directories. That way if the directories don't exist, it should be easier to …
> bug 1737691: more minidumpstackwalkrule fixes

- docker/Dockerfile
- socorro/processor/rules/breakpad.py
This changes building minidump-stackwalk to build it from a specified
rev in git.
This modifies get_version() to include the commit sha of
minidump-stackwalk installed.
This updates minidump-stackwalk to
e010de7678948eed4190f410e4c680053862c548 which picks up:
```
* 9d0aa9f fix a couple README whoopsies
* 0c90e02 post-0.9.4 release cleanup
* 101e9b1 0.9.4 release
* 5e3e346 Cleanup READMEs
* bd1a95d Be more strict about stack pointers on non-leaf ARM functions
* 66f8e16 remove miniump-tools
* 23c3ddc garbage-collect, update, and unify some dependencies
* 87eb0b4 remove dwarf_symbolizer and its dependencies
* c52bd22 post-0.9.3 RELEASES.md update
* 1e7cc1a 0.9.3 release
* df1b200 Add a timeout to symbol downloads
* 7783de7 Bump serde_json from 1.0.70 to 1.0.71
* 91a4abe Bump openssl from …
```
> bug 1737691: update minidump-stackwalk to e010de76

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/static/crashstats/css/base/tables.less
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
The "Debug" tab brings together all the metadata that's accumulated
during ingestion of a crash report from collection through processing.
The information in this tab will make it much easier to debug problems
in processing without making other tabs more confusing for everyone who
isn't me.
> bug 1743511: implement debug tab

- docker/Dockerfile
- socorro/processor/rules/breakpad.py
This fixes get_version() in MinidumpStackwalkRule to capture the sha and
the date of the revision we're using. This makes it easier to eyeball
the age of the thing we're using.
> bug 1711897: fix get_version() to capture date

- docker/Dockerfile
```
5069ee3 (HEAD -> master, official/master) Fix multi named argument bug
d6407f1 Add JSON schema document
ac28159 Remove legacy truncation fields
d50640b update RELEASES.md
4f5d185 Implement --brief argument
f3408b3 Implement cyborg output
6615352 minindump-stackwalk interface cleanup
a224c91 add a bunch of docs to minidump
833db4a Bump serde_json from 1.0.71 to 1.0.72
f934420 Give better feedback on corrupt minidumps
9d0aa9f fix a couple README whoopsies
0c90e02 post-0.9.4 release cleanup
101e9b1 0.9.4 release
```
> bug 1743680: update minidump-stackwalk to 5069ee3

- bin/process_crashes.sh
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/breakpad.py
- socorro/unittest/processor/rules/test_breakpad.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
This reworks `execute_process` so that the `MinidumpStackwalkRule` can
surface stderr as `mdsw_stderr`. It adds that to the Debug tab so it's
visible.
The combination of the exit code plus the last lines of stderr will make
debugging minidump-stackwalk easier plus it tells us a lot more about
what's bad about specific minidumps.
> bug 1743510: capture minidump-stackwalk output and surface it

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
The e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
hash is for a 0-byte minidump which we get semi-frequently. It helps to
make that more obvious in the debug view.
> bug 1743511: denote empty minidumps

- docker/Dockerfile
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/breakpad.py
This updates minidump-stackwalk to c4617dc. Changes:
```
c4617dc Make --human the default output of minidump-stackwalk
2dc160d fixup new lints
06d2e42 Json Schema Breaking Change: rename crashing_thread.thread_index to threads_index
445431c 0.9.5 release
13463d0 Document the Symbolizer interface and shim better
```
This picks up the fix for the last issue from bug #1744323. It also
changes how we run minidump-stackwalk to always pass the `--json` flag.
> bug 1744999: update minidump-stackwalk add --json flag

- requirements.in
- requirements.txt
- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/api/views.py
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/utils.py
- webapp-django/crashstats/settings/base.py
- webapp-django/crashstats/tokens/jinja2/tokens/home.html
This redoes CORS support to use django-cors-headers middleware. This
adds support for OPTIONS requests as well, which fix preflight issues.
This fixes all the responses from the API to be JSON so we're not doing
some in JSON and some in HTML.
> bug 1745454: redo cors support; fix api responses

- docker/Dockerfile
```
6ccdead confirm that unloaded module offsets are deduped
ecab5b5 Be more principled with output files in mdsw tests
de2209a Add tests for unloaded modules in mdsw
87b93fb do a better job computing unloaded_module offsets
d876fbe Unloaded modules fixes
52f112d you can never stop me from writing more docs
10d3dfd Add tests for minidump-stackwalk
13ffc20 post-release cleanup
664dcd1 0.9.6 release
1188157 Add some details and cleanup json-schema
c816898 update RELEASES.md
0bb785c Add minidump-stackwalk CLI docs to the README
```
> Update rust-minidump to 6ccdead

- docker/Dockerfile
- socorro/processor/rules/breakpad.py
- socorro/unittest/processor/rules/test_breakpad.py
When minidump-stackwalk encounters an error (empty minidump, no threads
stream, etc), the MinidumpStackwalkerRule should stomp on the
mdsw_status_string with that error code and then signature generation
can grab it to use in the signature.
This updates rust-minidump to ebb603f5:
```
ebb603f Start top-level errors with an error name.
```
Note that this changes some crash signatures.
With breakpad stackwalker, we'd have signatures like:
* EMPTY: no crashing thread identified; ERROR_NO_MINIDUMP_HEADER
* EMPTY: no crashing thread identified; ERROR_NO_THREAD_LIST
With rust-minidump minidump-stackwalker and these changes, we'll now
have:
* EMPTY: no crashing thread identified; EmptyMinidump
* EMPTY: no crashing thread identified; MissingThreadList
> bug 1745663: fix error codes in crash signatures

- webapp-django/crashstats/api/views.py
I'm adding this now because it's live in stage, but I'm probably going
to make non-trivial changes to the payload so I want to make it clear
it's in flux.
> bug 828452: add "this is unstable" note to signature api

- socorro/processor/rules/breakpad.py
- socorro/unittest/processor/rules/test_breakpad.py
I made a change to handle 0-byte minidumps and skip running
minidump-stackwalk. That's fine, but I thought it made sense to "fake"
the stackwalker_data output. That turns out to cause problems with other
processor rules that have expectations for what is and isn't in the
minidump.
This scales that back a bit so that json_dump isn't set to {} which
caused the events that lead to a KeyError.
> bug 1745663: fix KeyError caused by CrashingThreadRule

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
- socorro/signature/tests/test_utils.py
- socorro/signature/utils.py
When using offsets or module_offsets in a signature, we now strip
leading 0s in the hex so regardless of what generated the frame data, it
ends up in the signature the same way.
For example, 0x0000000000032ec0 and 0x32ec0 now get normalized to
0x32ec0.
> bug 1745816: strip leading zeros for addresses in signature generation

- docker/Dockerfile
```
2dc7ecc misc doc cleanups
76db048 Don't trust high bits of crash addresses
8bce21d disable racey test
```
This fixes rust-minidump #360.
> Update rust-minidump to 2dc7ecc3

- socorro/unittest/external/es/test_supersearch.py
- webapp-django/crashstats/monitoring/tests/test_views.py
- webapp-django/crashstats/monitoring/urls.py
- webapp-django/crashstats/monitoring/views.py
This fixes the heartbeat view so it doesn't use assert statements and it's clearer about what's failing.
This also implements a `/__broken__` endpoint to test sentry connectivity.
Also, since this is the first week of the year, this fixes a test that fails because of the way new years day falls in relation to index creation.
> bug 1748268: implement `/__broken__` view and clean up heartbeat view

- socorro/external/es/super_search_fields.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
This adjusts the code to derive `distribution_id` from `DistributionID` annotation and if that doesn't exist, then look in the `TelemetryEnvironment` for it.
While doing that, I converted the super_search_field nonsense into a `keyword_field` function.
> bug 1747846: pull distribution_id from annotation as well

- socorro/signature/siglists/irrelevant_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature 85387491-2b2e-4bd8-9b50-e16f10220105
Crash id: 85387491-2b2e-4bd8-9b50-e16f10220105
Original: {virtual override thunk}
New:      nsTimerImpl::Fire
```
> bug 1748685: add {virtual override thunk} to irrelevant list

- socorro/signature/siglists/irrelevant_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature bp-700f3223-f1a4-4201-b25d-2ac700211217
Crash id: 700f3223-f1a4-4201-b25d-2ac700211217
Original: libandroid.so@0xea22
New:      aaudio_init
```
> bug 1746700: add libandroid to irrelevant list

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
If `num_records` is 0, then treat that as if there was no `mac_crash_info` data in the `json_dump`. This allows rust-minidump to always emit the field, but Socorro will only extract it into the processed crash if there are records.
> bug 1748248: fix mac_crash_info field to require records

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
This fixes the `MacCrashInfoRule` to remove any `mac_crash_info` that's in the processed crash before it does its work. This cleans up from previous problems.
> bug 1748248: remove mac_crash_info if it's there

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature bp-0a007ca9-7590-45b4-8c3e-dab230220106
Crash id: 0a007ca9-7590-45b4-8c3e-dab230220106
Original: mozilla::ipc::IProtocol::ChannelSend
New:      mozilla::ipc::IProtocol::ChannelSend | mozilla::dom::PContentParent::SendDispatchLocationChangeEvent
```
> bug 1748865: add mozilla::ipc::IProtocol::ChannelSend to prefix list

- socorro/external/es/super_search_fields.py
- socorro/processor/rules/mozilla.py
The values possibly contain PII, so they have to be protected data. They're also sentences, so we're indexing with the standard analyzer which lets you do "has terms" and not deal with punctuation or case.
> bug 1746850: add DumperError to search

- webapp-django/crashstats/documentation/jinja2/documentation/supersearch/home.html
This is a minor fix to the operators documentation to clarify "has terms" and "contains" regarding case-sensitivity.
> bug 1714190: minor improvement to supersearch docs

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
- webapp-django/crashstats/crashstats/views.py
This fixes the processor code that extracts the mac_crash_info field to
encode it in a way that's good for indexing/searching and moving the
code to encode it in a way that's good for display to the report view.
> bug 1713355: fix mac_crash_info "is" searches

- webapp-django/crashstats/supersearch/jinja2/supersearch/macros/links.html
- webapp-django/crashstats/supersearch/jinja2/supersearch/search_results.html
- webapp-django/crashstats/supersearch/tests/test_views.py
Previously, if you do a supersearch and refined the search by clicking
on one of the field values in the results or facet results, it would add
that as an "is" query to the search. That's fine, except when there's a
filter for that field. In that case, the "is" query is OR'd with the
existing filter and I can't think of a single case where that's what you
want.
Now the refine links replace any existing filters for the field with the
"is" query.
Further, it fixes product, version, and product_type refinements to use
a term query (no prefix) instead of an "is" query ("=" prefix) so that
it works correctly with the supersearch form and site navigation.
Then I moved the code to macros because the template is really messy and
hard to read and we have a lot of complex-looking repeated logic …
> bug 1749561: fix supersearch refine links

- socorro/external/es/super_search_fields.py
I saw a single instance where the `get_fields_by_item` kicked up a
RuntimeError saying the dictionary had changed while it was iterating
through it. I don't see how that's possible with the code (maybe bad
imagination).
However, there were too many things named the same name but with
different types, so I tweaked the code to reduce that.
> bug 1749727: rename variables with same name but different types

- webapp-django/crashstats/signature/views.py
If the passed in product is an empty list (which I think is possible
because of the way the parameters are determined), then the correlations
page would die because there's no index 0 in an empty list.
This accounts for the empty list possibility by using the default
product if the determined product name is falsey (empty string, empty
list, not set, ...).
> bug 1748340: handle empty list product_name situation

- webapp-django/crashstats/supersearch/jinja2/supersearch/search_results.html
- webapp-django/crashstats/supersearch/static/supersearch/js/lib/dynamic_form.js
- webapp-django/crashstats/supersearch/static/supersearch/js/socorro/search.js
- webapp-django/crashstats/supersearch/views.py
This fixes the javascript parts of the supersearch form when you go to refine the search.
It correctly removes the "exists" filters if they exist for the field. It no longer messes up adding a filter for mac_crash_info or other fields where the values get coerced into other things.
It still adds filters for product, product_type, platform, and version rather than adding those to the simple form. I thought about trying to figure that out and then decided it's not _critical_, so I'd leave it.
> bug 1749561: fix supersearch form and refining search

- bin/run_migrations.sh
- bin/sentry-wrap.py
- docker/set_up_ubuntu.sh
- webapp-django/package-lock.json
- webapp-django/package.json
We use sentry-cli to get a heads-up when migrations fail during deploys. sentry-cli requires npm to install. That's a problem when we move to building JS/CSS files in a separate frontend container.
This drops sentry-cli in favor of a new sentry-wrap.py Python script.
> bug 1752001: replace sentry-cli with sentry-wrap.py

- socorro/lib/threaded_task_manager.py
This removes the "omg, i have nothing to do so i'm going to tell you all
about it and then wait 7 seconds and tell you the same thing again"
logging.
This also fixes some comments so they have the correct variable name.
> bug 1752565: remove thump logging from processor

- webapp-django/crashstats/api/urls.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/urls.py
- webapp-django/crashstats/crashstats/views.py
- webapp-django/crashstats/documentation/urls.py
- webapp-django/crashstats/exploitability/urls.py
- webapp-django/crashstats/manage/admin_urls.py
- webapp-django/crashstats/monitoring/urls.py
- webapp-django/crashstats/profile/urls.py
- webapp-django/crashstats/signature/urls.py
- webapp-django/crashstats/sources/urls.py
- webapp-django/crashstats/supersearch/urls.py
- webapp-django/crashstats/tests/test_sentrylib.py
- webapp-django/crashstats/tokens/urls.py
- webapp-django/crashstats/topcrashers/urls.py
- webapp-django/crashstats/urls.py
This fixes the module path for importing `re_path`.
This also fixes a test that intermittently fails in my local dev environment. I'm pretty sure it's a race condition. If it fails again, I'll look into it further.
This rewrites the views for `favicon.ico` and `contribute.json` to use `FileResponse`.
> bug 1703252: fix re_path module, intermittently failing test, and rewrite some views

- docker/Dockerfile
- docker/Dockerfile.fakesentry
This restricts upgrading pip to <22 so pip-tools works. When pip-tools
fixes the issue they've got, we can remove the restriction.
> bug 1753044: restrict pip<22

- socorro/processor/rules/mozilla.py
- socorro/signature/generator.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
This adds signature generation notes to the debug tab. Woohoo!
This also adjusts the Debug tab to clump some related things. Also,
"date_processed" is a lie, so I removed that.
> bug 1743884: add signature generation notes to debug tab

- socorro/lib/datetimeutil.py
- socorro/processor/processor_app.py
- socorro/unittest/lib/test_datetimeutil.py
This adds some code to capture the total time it takes to ingest a crash
report from collection (submitted_timestamp) to the end of processing.
This coupled with the queue size helps us understand the backlog and the
effect it has on how up-to-date the data we're looking at is.
> bug 1751799: capture total ingestion time

- docker/Dockerfile
- docker/Dockerfile.docs
- requirements.in
- requirements.txt
This updates pip-tools to 6.5.0 which fixes the issue with pip 22
allowing us to remove the pip restriction.
> bug 1753044: update pip-tools to 6.5.0 and remove pip restriction

- docs/requirements.in
- docs/requirements.txt
- requirements.in
- requirements.txt
* Bump sphinx from 4.3.2 to 4.4.0 (from PR #5991)
* Bump django-cors-headers from 3.10.1 to 3.11.0 (from PR #5990)
* Bump requests from 2.26.0 to 2.27.1 (from PR #5989)
* Bump dockerflow from 2021.7.0 to 2022.1.0 (from PR #5988)
> Updates 20220204

- docker/Dockerfile
From the bug:
* streaming symbol parsing which speeds things up and cuts down on memory usage.
* A fix for broken STACKWIN entries. This was a slight regression compared to the old stackwalker.
* An extra check to better behave with malformed minidumps.
* Support for EXC_GUARD exceptions on macOS. This is another area where we regressed compared to the old stackwalker.
* A small improvement when handling EXC_BAD_ACCESS crashes on macOS.
Commits:
```
1c5f5f8 Add KERN_FAILURE to the possible types of EXC_BAD_ACCESS exceptions on macOS
1ca3e9e Add support for macOS EXC_GUARD exceptions.
04180c3 extract into utility
85eac34 fix: Guard memory reservations with bounds checks
f0bdcc9 Bump serde_json from 1.0.74 to 1.0.75
b2bc2af hacky fix for buggy STACKWIN inputs
1554fe3 Bump insta from 1.8.0 …
```
> bug 1752424: update rust container to 1.58.1 and rust-minidump to 1c5f5f8

- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/crashstats/decorators.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/documentation/tests/test_views.py
- webapp-django/crashstats/supersearch/tests/test_views.py
This sorts the tags alphabetically because influxdb docs say that's a
good thing.
This also removes the / from the tag path values. I think that's the
cause of the issue I'm hitting in stage where tag path values are all
showing as "undefined" in Grafana. This is a bit of a guess, though,
since I can't find good documentation on what makes a valid tag value.
> bug 1750759: fix path tag value and sort tags

- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/crashstats/decorators.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/documentation/tests/test_views.py
- webapp-django/crashstats/supersearch/tests/test_views.py
This undoes the path value cleansing, but keeps caching the tag
generation and the tag order. Turns out we don't need to cleanse the
path values--I had a bug in the graph I was building.
> bug 1750759: undo path value cleansing

- docs/annotations.rst
- docs/requirements.txt
This adds some instructions for filling out the data review request for new crash annotations. Hopefully this makes it a little easier to fill out.
This also updates docs requirements.
> Add instructions for filling out data review request

- product_details/Fenix.json
- product_details/Firefox.json
- product_details/FirefoxReality.json
- product_details/Focus.json
- product_details/MozillaVPN.json
- product_details/ReferenceBrowser.json
- product_details/SeaMonkey.json
- product_details/Thunderbird.json
- webapp-django/crashstats/crashstats/jinja2/crashstats/product_home.html
- webapp-django/crashstats/crashstats/tests/conftest.py
- webapp-django/crashstats/productlib.py
This adds the ability to add additional links to the product home page. This is particularly useful for links to crash monitoring documentation for that specific product.
This also adds a link to Fenix crash monitoring documentation from Roger.
> Add Fenix crash monitoring documentation link

- socorro/processor/rules/mozilla.py
- socorro/signature/cmd_signature.py
- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
- socorro/signature/utils.py
This fixes signature generation so that it only uses processed crash
data.
> bug 1755523: end raw crash use in signature generation

- socorro/signature/siglists/prefix_signature_re.txt
```
sapp@socorro:/app$ socorro-cmd signature bp-32f63301-804f-4e9d-ba52-bfb670220301
Crash id: 32f63301-804f-4e9d-ba52-bfb670220301
Original: mozilla::ipc::SentinelReadError
New:      mozilla::ipc::SentinelReadError | mozilla::ipc::SentinelReadError | mozilla::gmp::PGMPParent::OnMessageReceived
```
> bug 1757605: add mozilla::ipc::SentinelReadError to prefix list

- socorro/signature/siglists/irrelevant_signature_re.txt
```
app@socorro:/app$ socorro-cmd signature bp-aaf62815-e6ea-4f4f-8251-cda5c0220226
Crash id: aaf62815-e6ea-4f4f-8251-cda5c0220226
Original: OOM | large | mozalloc_abort | core::ops::function::FnOnce::call_once<T>
New:      OOM | large | mozalloc_abort | core::intrinsics::const_eval_select<T>
```
> bug 1757270: add core::ops::function::FnOnce::call_once<T> to irrelevant list

- socorro/external/es/supersearch.py
- socorro/unittest/external/es/test_supersearch.py
If a user is using a regex operator and the value is malformed, this
will fix the response so it's an HTTP 400.
> bug 1671636: handle malformed search filter values

- bin/run_migrations.sh
- bin/sentry-wrap.py
- docker/config/local_dev.env
- docker/config/test.env
- socorro/app/socorro_app.py
- socorro/external/boto/upload_telemetry_schema.py
This improves error handling in sentry-wrap, switches it to use click instead of argparse, and adds "sentry-test" and "wrap-process" subcommands.
This updates the `bin/run_migrations.sh` script accordingly.
This also switches all parts of Socorro to use `SENTRY_DSN` environment variable to specify the Sentry host to use. Previously, crontabber and the webapp used `SENTRY_DSN` and the processor and upload_telemetry_schema apps used `secrets.sentry.dsn`.
> bug 1758701: add sentry-test mode to sentry-wrap

- docs/spec_crashreport.rst
This updates the list of malformed error codes in the spec to match the work done in bug 1760187.
> bug 1760187: update list of malformed error codes in spec

- docker/Dockerfile
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
This does a few things:
1. update rust to 1.59.0
2. update rust-minidump to b0af5b4 aka 0.10.1 and fix the command line arguments to minidump-stackwalk
3. rewrite ModuleURLRewriteRule
To test, process some crashes, check the symbol urls for modules, and make sure stacks look ok.
> bug 1759591: update rust-minidump to b0af5b4 (0.10.1)

- docker/Dockerfile
- docker/config/local_dev.env
Update rust-minidump to e954907 to pick up fix for --symbols-url argument specification.
```
e954907 Add unit test
3e3ef4b fix: Fall back to timestamp + size CodeIds on Windows
8570b22 make system_info::Cpu non_exhaustive
1fbe55d feat: Add rudimentary MIPS support
6cec047 fixup cli from clap update
8274cfb ref: Rename efl to eflags
ebd5dd0 Make MinidumpStream::STREAM_TYPE a u32
1754f8f pull all the platform-specific error code enums into a new module
7eed71e 0.10.1 post-release
```
> bug 1759591: update rust-minidump to e954907c

- socorro/external/es/crashstorage.py
- socorro/external/es/super_search_fields.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/external/es/test_super_search_fields.py
- socorro/unittest/external/es/test_supersearch.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
* redo how we handle flag/boolean fields in the processor and Elasticsearch crashstorage
* fix throttleable
* fix submitted_from_infobar
* fix safe_mode
* fix is_garbage_collecting
* fix has_device_touch_screen
* fix em_check_compatibility
* fix content_sandbox_enabled
* fix content_sandbox_capable
* fix addons_checked to be bool
* fix accessibility
This also fixes startup_crash, but leaves it as "null_value is False" which differs from the rest of them. This is used in the signature reports and I didn't want to spend the time to figure out what effects changing that would have now.
> bug 1755528: fix flag/boolean fields

- socorro/external/es/super_search_fields.py
- socorro/processor/rules/mozilla.py
- socorro/scripts/es.py
- socorro/unittest/external/es/test_super_search_fields.py
There are 5 flag/boolean fields that are being indexed as shorts:
* contains_memory_report
* dom_fission_enabled
* dom_ipc_enabled
* gmp_plugin
* graphics_startup_test
I tested out whether search would work across indexes where these fields were shorts in one index and booleans in another and that doesn't work. It doesn't kick up errors, but it doesn't match values correctly.
We're going to need to migrate from one type to another. This starts accumulating the data in temporary fields. In August 2022, we can delete the old fields and switch to the new fields permanently.
This also fixes `socorro-cmd es delete` which didn't work right.
> bug 1755528: fix flag/boolean fields that are shorts

- socorro/lib/cache.py
- socorro/lib/util.py
- socorro/processor/rules/breakpad.py
Importing ABC from `collections` was deprecated since Python 3.4 and removed in Python 3.10 . Use `collections.abc` instead.
> Import ABC from collections.abc for Python 3.10 compatibility.

- requirements.in
- requirements.txt
- socorro/external/boto/crashstorage.py
- socorro/lib/libjson.py
- socorro/schemas/telemetry_socorro_crash.json
- socorro/unittest/external/boto/test_crashstorage.py
- socorro/unittest/lib/test_libjson.py
This drops json-schema-reducer library for one we wrote that's more
correct in how it traverses the schema, does some light type checking,
and allows for an include predicate which we'll use later for redacting
protected data from documents.
This is based on the json schema draft-04 spec which is what our schemas
use.
It doesn't implement some of the data restrictions specified in
draft-04 (for example minItems, maxItems, etc) because we're not
currently using them.
> bug 1762271: rewrite json schema reducer

- socorro/schemas/validate_telemetry_socorro_crash.py
Since TelemetryBotoS3CrashStorage builds the crash data only using the
processed crash, we can stop fetching the raw crash in the validation
script.
> bug 1755095: fix validate_telemetry_socorro_crash.py

- socorro/external/es/super_search_fields.py
- socorro/lib/search_common.py
- socorro/processor/rules/mozilla.py
- socorro/schemas/telemetry_socorro_crash.json
- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
- socorro/signature/tests/test_utils.py
- socorro/signature/utils.py
- socorro/unittest/lib/test_search_common.py
- socorro/unittest/processor/rules/test_mozilla.py
- webapp-django/crashstats/crashstats/jinja2/macros/signature_startup_icons.html
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/test_utils.py
- webapp-django/crashstats/crashstats/utils.py
- webapp-django/crashstats/signature/jinja2/signature/signature_summary.html
- webapp-django/crashstats/signature/views.py
- webapp-django/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html
- webapp-django/crashstats/topcrashers/tests/test_views.py
- webapp-django/crashstats/topcrashers/views.py
hang_type is based on Hang and HangID crash annotations which were
removed 10 years ago. This removes them from Socorro.
> bug 1762207: remove hang_type

- docker/Dockerfile
```
d915179 appease new clippy lint
b17a4b7 Make the parser much more robust to enormous symbols.
a5c70b8 Add trace-logging to symbol resolution
7cd02d5 0.10.3 release
cf3f594 Handle 0 frame pointers on ARM64-old
db19dcd 0.10.2 post-release
77b30fc 0.10.2 Release
0776f9a meta: Draft new changelog
```
This fixes issues with parsing XUL symbols file
(https://github.com/rust-minidump/rust-minidump/pull/529).
Example crash report: 9e5f6dd5-49ab-426e-b1c4-379bd0220407
> bug 1763704: update rust-minidump to d915179e

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
The OSPrettyVersionRule extracts a major and minor version from the os
version. This improves that extraction code so it's more resilient to
interesting possibilities.
> bug 1761240: fix major/minor version figuring

- docs/annotations.rst
This improves the crash annotation docs in a few ways:
1. fixes some typos
2. clarifies which data review form to use
3. adds "for help on this step, ask in ..." notes
> bug 1768220: improve crash annotation docs

- webapp-django/crashstats/crashstats/jinja2/macros/signature_startup_icons.html
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
- webapp-django/crashstats/crashstats/utils.py
- webapp-django/crashstats/signature/jinja2/signature/signature_summary.html
- webapp-django/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html
- webapp-django/crashstats/topcrashers/tests/test_views.py
We're done with the Fission project for Firefox Desktop so we can remove
the Fission indicators.
> bug 1742869: remove fission indicators

- socorro/schemas/telemetry_socorro_crash.json
It was kicking up invalid document errors. We need to convert the
boolean True/False back to a string "1"/"0".
> bug 1768855: fix is_garbage_collecting in telemetry crash storage

- webapp-django/crashstats/crashstats/jinja2/crashstats/bug_comment.txt
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
If crashing_thread is None, then use thread 0 instead when creating the
bug report.
> bug 1770722: use thread 0 in bug report

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd fetch_crashids --signature-contains='mozilla::dom::AutoJSAPI::Init' | socorro-cmd signature
Crash id: 1034e676-ab3d-4311-af67-27d030220613
Original: mozilla::dom::AutoJSAPI::Init
New:      mozilla::dom::AutoJSAPI::Init | mozilla::ClientWebGLContext::JsWarning
Crash id: cfef8995-8855-42c4-aa8e-6479a0220613
Original: mozilla::dom::AutoJSAPI::Init
New:      mozilla::dom::AutoJSAPI::Init | nsQueryJSActor::operator()
Crash id: 250bc756-52d1-4330-88fa-dab290220613
Original: mozilla::dom::AutoJSAPI::Init
New:      mozilla::dom::AutoJSAPI::Init | _tailMerge_d3dcompiler_47.dll | mozilla::xpcom::ConstructJSMComponent
```
> bug 1774110: add mozilla::dom::AutoJSAPI::Init to prefix list

- socorro/processor/rules/mozilla.py
- webapp-django/crashstats/crashstats/management/commands/archivescraper.py
- webapp-django/crashstats/crashstats/tests/test_archivescraper.py
This fixes the BetaVersionRule which was written for a time when we
didn't have normalized, validated data. Thank goodness those days are
over-ish.
This adds Thunderbird to archivescraper scraping so we have data in the
table. This also fixes the BetaVersionRule to fix versions for
Thunderbird betas, too.
> bug 1776923: add Thunderbird version rewrite support

- socorro/external/es/crashstorage.py
We have a series of fields where the `storage_mapping` is `multi_field`, so
they're not being treated as strings and not getting truncated.
This adds some code to treat fields where the `storage_mapping` is
`multi_field` and the `full` version is a string as strings for truncation.
> bug 1777258: treat multi_field as string when truncating

- webapp-django/crashstats/signature/static/signature/js/signature_tab_graphs.js
Because Javascript doesn't guarantee the reading order will be the same as the insertion order for objects, the major version order for legend (array) and graph data (object) would not match sometimes. This was fixed by building the legend array along with lineDataArray, which contains graph data and is an array, which guarantees the reading order will be the same as insertion order.
> bug 1756264: correct graph legend

- socorro/external/es/super_search_fields.py
- socorro/processor/rules/mozilla.py
The annotation no longer exists and there are better and more reliable
ways to search for crash reports with a memory report, so we're removing
this field.
> bug 1784095: remove contains_memory_report

- socorro/external/es/super_search_fields.py
- socorro/processor/rules/breakpad.py
- socorro/schemas/processed_crash.1.schema.yaml
- socorro/schemas/telemetry_socorro_crash.json
- socorro/unittest/external/es/test_super_search_fields.py
- socorro/unittest/processor/rules/test_breakpad.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
While redoing how permissions are handled, I hit some other issues. Rather than have them clutter up an overly large PR, I pulled them out into this one.
* add description to `client_crash_date`
* fix `cpu_count` so it's in the top level of the processed crash and super search pulls it from there
* fix `stackwalk_version` so it's in the top level of the processed crash and super search and other things pull it from there
* re-add `dom_ipc_enabled` and `dom_fission_enabled`
This probably deserves a bug, but if so, I'll create one later. The gist of the issue is that I fixed these two fields in e311379ebfa8c7b09c973709b8ec48a19e12327b (March 25, 2022) so they were getting converted correctly. Then I finished up that work in ae60bf448de57cf61f99942ba08e5c901f1a0297 (July 26th, 2022) at which …
> bug 1764395: fixes minor related things

- socorro/schemas/telemetry_socorro_crash.json
This is a boolean field and we need to convert it to a string for
telemetry ingestion.
> bug 1764395: fix graphics_startup_test for telemetry ingestion

- webapp-django/crashstats/crashstats/models.py
This changes the `ProcessedCrash` API to return all the data without reducing it if the user has `view_pii` permissions. This matches what is currently in prod and makes it easier to see the final processed crash data including stackwalker output even if that's not covered by the schema.
We still have the scaffolding to do more granular permissions for if we do something like re-add `view_exploitability` or something like that.
> bug 1764395: return all data if user has view_pii for ProcessedCrash API

- docs/telemetry_socorro_crash.rst
- socorro/external/boto/upload_telemetry_schema.py
- socorro/unittest/external/boto/test_upload_telemetry_schema.py
This fixes `upload_telemetry_schema` so it doesn't fail with a
`configure_sentry` error. This fixes the unittest so it'll catch issues
like this in the future in CI.
This improves the docs for `telemetry.socorro_crash` and fixes one of
the links.
> bug 1787170: fix upload_telemetry_schema and docs

- socorro/schemas/processed_crash.schema.yaml
"reason" is pulled from "json_dump.crash_info.type" and thus it can be
either a string or null. This adds null as a valid type.
> bug 1788043: fix reason type

- docker/Dockerfile
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/breakpad.py
This updates rust-minidump to 0.14.0. It adds the "--no-color" argument
to the command line. It fixes the parsing of the stderr ERROR line to
match the new format.
> bug 1779630: update rust-minidump to 0.14.0

- socorro/processor/rules/mozilla.py
The processed crash has release_channel. ReleaseChannel isn't used by
Socorro. I think it's a holdover from a different time.
> Stop adding ReleaseChannel to processed crash

- socorro/schemas/validate_processed_crash.py
This fixes `validate_processed_crash.py` to support pattern_properties when looking at document keys that aren't in the schema. This doesn't fix schema keys that aren't in documents, but that's less critical (and more complicated) so I'm deferring that for now.
> bug 1788533: support pattern_properties better

- socorro/lib/libsocorrodataschema.py
- socorro/schemas/validate_processed_crash.py
- socorro/unittest/schemas/test_socorro_data_schemas.py
This fixes the other side of validate_processed_crash.py where it
calculates the schema keys that don't show up in any of the documents
so it handles pattern_properties in the schema.
> bug 1788533: support pattern_properties for schema keys in doc

- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/schemas/telemetry_socorro_crash.json
- socorro/unittest/processor/rules/test_mozilla.py
The Accessibility field is in a crash report and set to "Active" by the accessibility service when it is active. Otherwise it's not in the crash report at all. The processed crash schema expects a boolean. Super Search expects a boolean. The telemetry schema expects a string and the value that Socorro sent to telemetry was "Active".
This reconciles all this down to setting the value in the processed crash to True if the annotation exists and the value is "Active" and False otherwise. It converts that to a "1" for Telemetry.
> bug 17885331: fix Accessibility processing

- socorro/lib/libsocorrodataschema.py
- socorro/schemas/validate_processed_crash.py
bug 1788971: fix jsonschema deprecation warning
jsonschema was kicking up this deprecation warning:
```
DeprecationWarning: The metaschema specified by $schema was not found.
Using the latest draft to validate, but this will raise an error in the
future.
```
This fixes that by passing in the correct validator. Further, since I
think I want to be validating test data because a lot of it is wrong, I
created a function for it that we can use everywhere.
> bug 1788971: fix jsonschema deprecation warning

- socorro/external/es/super_search_fields.py
- socorro/processor/rules/breakpad.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/unittest/processor/rules/test_breakpad.py
- socorro/unittest/schemas/test_socorro_data_schemas.py
This adds `crashing_thread` and `crashing_thread_name` fields to the processed crash and to super search.
> bug 1782258: add crashing_thread and crashing_thread_name fields

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/utils.py
- webapp-django/crashstats/crashstats/views.py
When a stack has more than 100 frames, this truncates the middle in the report view so it shows the first 50, a "truncated" line, and then the last 50. This should significantly reduce the HTML involved in stack overflow bugs and make the page load _much_ faster.
Example crash report: 25e8e40f-42a1-4248-b24d-43d2e0220403
I picked 100 because it seemed like a good number and ran it by some others who agreed. However, it's kind of arbitrary. If we decide there are better numbers to truncate on, we can change it in a new bug.
> bug 1763154: truncate frames from huge stacks

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
This adds showing the truncate line for the other threads. This also
adds the trust column which wasn't there for whatever reason.
> bug 1763154: show truncate line for non-crashing threads

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/utils.py
This adds display of inline functions to the details tab of the report
view. This shows them for the crashing thread and all other threads.
> bug 1788103: show inline functions in details tab of report view

- bin/permadelete_crash_data.py
- bin/remove_field.py
- socorro/external/boto/crashstorage.py
- socorro/scripts/fetch_crash_data.py
- socorro/unittest/external/boto/test_crashstorage.py
- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/crashstats/management/commands/verifyprocessed.py
- webapp-django/crashstats/crashstats/tests/test_verifyprocessed.py
This removes the "entropy" section from the raw crash path in AWS S3. This makes it easier to work with raw crash data and also sets us up for moving to GCP where we're not planning to have an "entropy" section at all.
This also fixes the instructions in `bin/remove_field.py` to make it easier to test next time without reading through the code and the PR that created that file.
I went through and tested the following:
* loading raw crashes works with old and new key formats
* verifyprocessed works
* permadelete_crash_data works
* remove_field works
* fetch_crash_data puts crash data in new key location
In relevant places, I added notes about when the deprecated code can be removed.
> bug 1604845: remove entropy from raw_crash path

- bin/run_mdsw.sh
- socorro/external/boto/crashstorage.py
- socorro/unittest/external/boto/test_crashstorage.py
- webapp-django/crashstats/api/tests/test_views.py
- webapp-django/crashstats/crashstats/management/commands/verifyprocessed.py
- webapp-django/crashstats/crashstats/tests/test_updatemissing.py
- webapp-django/crashstats/crashstats/tests/test_verifyprocessed.py
We're effectively returning to the original v1 from ages ago. Version changing shenanigans are irritating, but in this specific case, I don't think anything else relies on the pathing except antenna and socorro. Given that I control both and I'm changing it anyhow, it seems easier in general to return to v1 which matches the other paths than to keep v2 or go to v3.
> bug 1604845: switch raw crash key version to v1

- requirements.in
- requirements.txt
- socorro/external/boto/crash_data.py
- socorro/external/boto/crashstorage.py
- socorro/external/crashstorage_base.py
- socorro/external/fs/crashstorage.py
- socorro/lib/util.py
- socorro/processor/processor_app.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/base.py
- socorro/processor/rules/breakpad.py
- socorro/processor/rules/general.py
- socorro/processor/rules/memory_report_extraction.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/external/boto/test_crashstorage.py
- socorro/unittest/lib/test_util.py
- socorro/unittest/processor/__init__.py
- socorro/unittest/processor/rules/test_breakpad.py
- socorro/unittest/processor/rules/test_general.py
- socorro/unittest/processor/rules/test_mozilla.py
This stops using `DotDict` for raw and processed crash data. When data is loaded from crash storage, it'll now be in standard Python data structures (dict, list) and needs to be accessed as such.
We were doing this already for the most part, so this is a minor change at this point.
The Socorro processor pipeline keeps notes related to processing as crash reports wind their way through the rules. At the end, the processor notes are added to the crash report. In this way, we have some visibility into processing.
Previously, `processor_meta_data` was a `DotDict` with a handful of fields. In this PR, we remove all the unused fields and then change it to a data class with a more convenient way of adding notes. Then we update all the rules and code that uses it.
To test:
1. process some crash …
> bug 1710725: stop using dotdict for raw and processed crash

- webapp-django/crashstats/api/jinja2/api/documentation.html
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/static/crashstats/css/base.less
- webapp-django/crashstats/crashstats/static/crashstats/css/base/tables.less
- webapp-django/crashstats/crashstats/static/crashstats/css/pages/report_index.less
This fixes the breaks in the report view stack table so that long sources and long function signatures don't make the table impossible to read.
It also applies widths to the columns to make table layout more stable across multiple stacks.
This gets rid of the "vertical" css class and fixes the affected tables by adding width classes making table layout more stable. The "vertical" class used a width in pixels which made it resize poorly. This switches to percentage widths for more of the layout.
> bug 1789705: fix breaks in report view stack table

- webapp-django/crashstats/api/static/api/css/documentation.less
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/static/crashstats/css/base/tables.less
- webapp-django/crashstats/crashstats/static/crashstats/css/components/table_sorter.less
- webapp-django/crashstats/crashstats/static/crashstats/css/pages/report_index.less
- webapp-django/crashstats/documentation/jinja2/documentation/supersearch/home.html
- webapp-django/crashstats/documentation/static/documentation/css/documentation.less
- webapp-django/crashstats/signature/jinja2/signature/signature_aggregation.html
- webapp-django/crashstats/signature/jinja2/signature/signature_summary.html
I threw together some width classes in an earlier commit. This tweaks the widths of the stacks table to fit the data better. This also improves a bunch of other tables to make them more stable layout-wise and remove pixel widths.
I also adjusted borders for table headers. There was a bunch of css code in random places for that. I reduced that some.
> bug 1789705: fix table column widths across the site

- webapp-django/crashstats/crashstats/static/crashstats/js/socorro/report.js
The tabs are implemented with jquery ui tab component and it's structured such that the "tab" is a li with an a child that responds to click events. But since the tab has aria-labeledby that tells screen readers to ignore the content, the a isn't clickable.
This adds James' suggested fix which adds a listener for click to the tab which then clicks the a tag.
> bug 1767566: fix clickability of tabs in report view

- socorro/signature/generator.py
- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
This prepends "bad hardware" to the signature if the reason has "STATUS_DEVICE_DATA_ERROR" in it. This reduces the likelihood we spend time looking into crash reports that we can't do anything about.
> bug 1733904: add "bad hardware" to signature for STATUS_DEVICE_DATA_ERROR

- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/supersearch/models.py
This fixes the API endpoints that derive from SocorroMiddleware to be more resilient to fuzzing.
To test, do things like this:
```
curl 'http://locahost:8000/api/SuperSearchFields/' --data ""
```
That does a POST to SuperSearchFields endpoint. In prod, that kicks up an HTTP 500 because it's using the default post function. This fixes it so now it'll return a `Method not allowed`.
> bug 1749770: fix API endpoints to be more resilient

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
If line data is None, then don't display it at all.
Test with https://crash-stats.mozilla.org/report/index/c8e640f4-6d6d-46aa-a015-9db2c0220909 . After this patch, the first inlined frame should have no line number.
> bug 1790136: don't display line "None"

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
- socorro/signature/tests/test_signature_generator.py
- socorro/unittest/processor/rules/test_mozilla.py
For crash reports where the crashing thread index either doesn't point to a thread for which we have data or it's null, this defaults the crashing thread to 0.
```
Crash id: cf56f4aa-00a4-47ab-86fe-026d60220908
Original: EMPTY: no crashing thread identified; MissingThreadList
New:      EMPTY: no frame data available; MissingThreadList
Notes:    (1)
SignatureGenerationRule: CSignatureTool: no frame data for crashing thread (0)
Crash id: ab1ed46b-eea9-49a0-abe6-acdad0220908
Original: OOM | large | EMPTY: no crashing thread identified; EmptyMinidump
New:      OOM | large | EMPTY: no frame data available; EmptyMinidump
Notes:    (1)
SignatureGenerationRule: CSignatureTool: no frame data for crashing thread (0)
Crash id: 938bd64d-cd72-4431-addc-a64f50220908 …
```
> bug 1745732: improve signatures for crash reports with thread index issues

- socorro/signature/siglists/prefix_signature_re.txt
This should help attribute the crashes tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1765793
> Add core::slice::index::slice_end_index_len_fail to the prefix list

- bin/entrypoint.sh
- bin/run_mdsw.sh
- bin/run_symbolsserver.sh
- docker-compose.yml
This fixes `run_mdsw.sh` so it works again and adds a really basic local symbols server.
> bug 1763710: prep work for looking at corrupt_symbols stuff

- docker/Dockerfile
- docker/set_up_stackwalker.sh
We've moved building the stackwalker to a separate repository that does "releases" which include a .tar.gz file. The file is like 5mb.
Then we changed the Socorro build so that it downloads the file rather than building stackwalker _again_. This will improve build times when the docker image cache isn't available or doesn't have anything useful.
> bug 1759065: stop building stackwalker every build

- socorro/signature/siglists/prefix_signature_re.txt
This signature shows up when we do signature generation based on inline stacks. e.g. https://crash-stats.allizom.org/report/index/1fbb67cf-dec1-4729-96d5-061f10220913
> Add enum$<T>::unwrap to prefix list

- socorro/external/boto/crashstorage.py
- socorro/external/crashstorage_base.py
- socorro/external/fs/crashstorage.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/breakpad.py
- socorro/processor/rules/mozilla.py
- socorro/scripts/fetch_crash_data.py
- socorro/unittest/external/boto/test_crashstorage.py
- socorro/unittest/external/test_crashstorage_base.py
- socorro/unittest/processor/rules/test_breakpad.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/views.py
This adds some code to migrate raw crash data from version 1 to version 2. It updates all the places in Socorro to use the new raw crash version 2 locations for things.
It also changes how `minidump_sha256_hash` gets populated in the processed crash. We're going to drop the `MinidumpSha256Hash` fake annotation in the raw crash that the collector adds. The information is in `dump_checksums`, so there's no need to have it in two places and the fake annotation suggests things that are confusing unless you know where it comes from.
> bug 1687987: support raw crash version 2

- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
This redoes the `BreadcrumbsRule` to use the "breadcrumbs" section of the processed crash schema for structure validation. This reduces the likelihood that one thing things it's valid but the other doesn't and it removes a bunch of janky validation code and tests.
> bug 1787929: redo BreadcrumbsRule to use schema validation

- socorro/external/boto/crashstorage.py
- socorro/lib/libsocorrodataschema.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
Something is calling resolve_references on the PROCESSED_CRASH_SCHEMA without copying it first before BreadcrumbsRule initializes which means that "definitions" isn't there. This fixes that.
> bug 1787929: fix KeyError: "definitions" issue with BreadcrumbsRule

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
This covers several areas:
* It makes Windows atomics irrelevant
* It adds several C++ Windows helper functions to the prefix list
* It makes macOS atomics and other libcs functions irrelevant
* It reorganizes some functions in the prefix list to shorten it
* It removes some functions which do not appear in crashes anymore
> Bug 1791509 - Improve handling inlined library functions

- socorro/external/boto/crashstorage.py
- socorro/external/es/super_search_fields.py
- socorro/lib/libsocorrodataschema.py
- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/schemas/__init__.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/schemas/socorro-data-1-0-0.schema.yaml
- socorro/schemas/validate_processed_crash.py
- socorro/unittest/external/boto/test_upload_telemetry_schema.py
- socorro/unittest/external/es/test_super_search_fields.py
- socorro/unittest/lib/test_libsocorrodataschema.py
- socorro/unittest/processor/rules/test_breakpad.py
- socorro/unittest/processor/rules/test_mozilla.py
- socorro/unittest/schemas/test_socorro_data_schemas.py
- webapp-django/crashstats/crashstats/management/commands/updatesignatures.py
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/conftest.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/supersearch/libsupersearch.py
- webapp-django/crashstats/supersearch/models.py
- webapp-django/crashstats/supersearch/tests/test_forms.py
- webapp-django/crashstats/supersearch/tests/test_libsupersearch.py
This is a series of commits that move things around to eventually fix super search fields to pull permissions from the processed crash schema.
First, this removes `test_mapping` because it's dead code that's not used anymore. This fixes the `BreadcrumbsRule` and other things that used `get_schema()` and fixes `resolve_references` to return a new version of the data and not mutate the input. This fixes schema validation in `validate_processed_crash` so that it can be used for validating that the schemas themselves are valid in addition to testing them against processed crash data. This also moves some webapp-centric code from `socorro/external/es/super_search_fields.py` to `webapp-django/crashstats/supersearch/libsupersearch.py`. This also fixes the `upload_telemetry_schema` test because …
> bug 1787931: fix super search fields to pull permissions from processed crash schema

- socorro/processor/processor_pipeline.py
- socorro/processor/rules/mozilla.py
- socorro/unittest/processor/rules/test_mozilla.py
- webapp-django/crashstats/crashstats/models.py
These were from the days of flash and we no longer support that, so we can remove these.
> bug 1792269: remove PluginContentURL and PluginUserComment code

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd fetch_crashids --signature=nsObserverService | socorro-cmd signature
Crash id: e99b62e6-08aa-4241-8324-0187c0221016
Original: nsObserverService::RemoveObserver
New:      nsObserverService::RemoveObserver | nsBaseWidget::~nsBaseWidget
Crash id: b02b13bc-fa05-422d-84cc-fe60a0221016
Original: shutdownhang | strlen | nsObserverService::NotifyObservers
New:      shutdownhang | strlen | nsObserverService::NotifyObservers | mozilla::DllServices::NotifyDllLoad
Crash id: cd510bf8-019e-4d3f-bbfd-a73080221016
Original: shutdownhang | strcmp | nsTHashtable<T>::s_MatchEntry | PLDHashTable::Search | nsObserverService::NotifyObservers
New:      shutdownhang | strcmp | nsTHashtable<T>::s_MatchEntry | PLDHashTable::Search | …
```
> bug 1795641: add nsObserverService to prefix list

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ socorro-cmd fetch_crashids --signature=nsINode::GetParentNode | socorro-cmd signature
Crash id: f2137a45-9edb-4fd9-9c7d-168c20221016
Original: nsINode::GetParentNode
New:      nsINode::GetParentNode | mozilla::dom::Node_Binding::get_parentNode
Crash id: daef2d39-a33c-46cd-b89b-5f9af0221016
Original: nsINode::GetParentNode
New:      nsINode::GetParentNode | nsMutationReceiver::ContentAppended
```
> bug 1795643: add nsINode::GetParentNode to prefix list

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/bug_comment.txt
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_jinja_helpers.py
- webapp-django/crashstats/crashstats/tests/test_utils.py
- webapp-django/crashstats/crashstats/utils.py
This updates signature generation to take unloaded modules into account. This uses gankra's notation where it denotes which parts are from unloaded modules from the first commit in PR #6021 . Examples:
```
app@socorro:/app$ socorro-cmd signature edcb4dbc-5516-4b15-9464-26adc0221001 1e8a0180-dd82-4051-b1ac-1006c0221001 9cc1cb90-c92a-4a31-b69c-cebfc0221001
Crash id: edcb4dbc-5516-4b15-9464-26adc0221001
Original: QueryDnsForFamily
New:      (unloaded PrxDrvPE64.dll@0x5387) | QueryDnsForFamily
Crash id: 1e8a0180-dd82-4051-b1ac-1006c0221001
Original: UserCallWinProcCheckWow
New:      (unloaded RTSUltraMonHook.dll@0xbff8) | UserCallWinProcCheckWow
Crash id: 9cc1cb90-c92a-4a31-b69c-cebfc0221001
Original: CFGControl::SetFirstVW
New:      (unloaded …
```
> bug 1746630: support unloaded modules in signature generation and report view

- docs/annotations.rst
- docs/conf.py
- docs/crashpings.rst
- docs/index.rst
- docs/stackwalk.rst
This simplifies the process for adding new crash annotations. Before it was hard to follow and hard to link to specific parts of.
This:
1. moves the crash ping schema update docs to a different place
2. breaks up "add a new annotation" from the various things you should/could do to support the new annotation for anlaysis
3. uses better terminology for things that should be clearer
4. improves the "create a bug" links to have a comment outlining the request so the reader doesn't have to guess at it
5. includes a complete template for the data review rather than requiring the reader to copy-and-paste it from somewhere else and then modify it to conform to crash annotations
This creates a new crash ping chapter that talks about crash reports and crash pings. It also outlines the process for …
> bug 1795898: update docs and overhaul crash annotation docs

- docs/products.rst
This fleshes out the minimum required annotations and also adds notes about how they're used in crash ingestion.
> bug 1760723: improve product docs re: annotations

- webapp-django/crashstats/crashstats/jinja2/crashstats/bug_comment.txt
- webapp-django/crashstats/crashstats/templatetags/jinja_helpers.py
The create-a-bug links are generated with a Jinja2 function which uses a Jinja2 template to generate the comment. Jinja2 templates are great for HTML where consecutive whitespace is no big thing, but they're awful for text output especially complex templates with if/then/else and for loops.
Over the years, we've spent a lot of time trying to get the `bug_comment.txt` template to work for the variations it needs to support.
This adds a "look, squash all cases of 2 or more line endings to just 2" `re.sub()` which makes editing the template a lot less nightmarish.
> bug 1797295: fix create-a-bug links

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/tests/test_views.py
This adds the unloaded modules to the modules tab in the report view.
One thing to note is that unloaded modules show up multiple times in the list, but have different base/end addresses. Since we're not displaying the base/end addresses in the list, it seems like there's a bug causing them to be repeated. We could not repeat them, but it seems interesting to know that a module shows up three times. We could show the base/end addresses, but I was on the fence about that. We can think about that another day.
> bug 1797742: show unloaded modules in modules tab

- socorro/signature/siglists/prefix_signature_re.txt
Here's an example crash: https://crash-stats.mozilla.org/report/index/a1270472-4d4b-4e22-8d02-25ecc0221027
> Disambiguate crashes that happen in mozilla::TimeStampValue::operator-

- product_details/Fenix.json
- product_details/Focus.json
1. Fenix, Focus, and Android-Components bug tracking is moving to Bugzilla. We won't have a separate Bugzilla product for Android Components: we'll file Android-Components bugs in the Fenix product.
2. Fenix only runs on Android, so set Fenix's default `op_sys=Android`.
3. All Focus crashes in Socorro are from Android because Focus iOS doesn't submit crash reports to Socorro, so set Focus's default `op_sys=Android`.
4. Set a default component ("General") for convenience. If the person filing the crash bug from Socorro knows a more appropriate Fenix or Focus component, they can select the other component in Bugzilla before submitting the new bug.
5. Remove the "External Software Affecting Firefox" and "Toolkit" links because they aren't relevant for Focus crashes.
> Update Fenix's and Focus's "Create a bug" links

- docker/config/test.env
This was required to run `make build` with docker-compose v2.10.2.
> bug 1791208: Quote regex in test.env

- socorro/signature/generator.py
- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
This adds a new tag "stackoverflow" to crash signatures when the reason (json_dump.crash_info.type) is "EXCEPTION_STACK_OVERFLOW". Because this is only one of a myriad of indicators and we want to expand support over time, I structured the rule like the OOMSignature rule which also has multiple indicators.
```
app@socorro:/app$ socorro-cmd signature 389b5d5b-5140-429e-b216-bfd270220802 
Crash id: 389b5d5b-5140-429e-b216-bfd270220802
Original: _chkstk | nsTextFrame::ReflowText
New:      stackoverflow | nsTextFrame::ReflowText
```
(Ignore the `_chkstk` difference--that's because of another signature generation change in the last couple of months.)
```
app@socorro:/app$ socorro-cmd signature e0d562aa-1ee3-43ee-a266-61b5b0221019    
Crash id: …
```
> bug 1796389: add "stackoverflow" to signature

- socorro/processor/rules/general.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/unittest/processor/rules/test_general.py
This changes the cpu_microcode_version field such that the processor now tries to populate it with the value generated by the stackwalker and degrades to the CPUMicrocodeVersion crash annotation value
> bug 1791742: pull cpu_microcode_version from stackwalker output

- socorro/processor/rules/general.py
- socorro/unittest/processor/rules/test_general.py
The stackwalker outputs a u32, but the crash annotation has a hex string. This fixes the processor rule to convert the stackwalker value to a hex string if there's a stackwalker value.
> bug 1791742: fix cpu_microcode_version handling to fix values

- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/static/crashstats/css/base.less
- webapp-django/crashstats/crashstats/static/crashstats/css/base/layout.less
- webapp-django/crashstats/crashstats/static/crashstats/css/components/nav.less
- webapp-django/crashstats/crashstats/static/crashstats/css/components/tip.less
- webapp-django/crashstats/crashstats/views.py
If signature generation has changed since when a crash report was last processed, then the report view will now show a note with the new signature.
In order to do this, I needed to move some things around, so I took some time to make the top of the report view more consistent with other parts of the site and reduce some of the complexity in design.
> bug 1795762: show current signature if signature generation has changed

- bin/update_siggen.py
- socorro/signature/README.rst
- socorro/signature/cmd_signature.py
- socorro/signature/generator.py
- socorro/signature/rules.py
- socorro/signature/siglists_utils.py
- socorro/signature/tests/test_rules.py
- socorro/signature/tests/test_siglists.py
- socorro/signature/tests/test_signature_generator.py
- socorro/unittest/processor/rules/test_mozilla.py
This adjusts signature generation to allow someone to build a SignatureGenerator and specify the directory containing signature lists. This functionality is extended to the `socorro-cmd signature` subcommand via a `--signature-list-dir` argument.
> bug 1799539: support specifying signature lists

- docker/set_up_stackwalker.sh
This updates rust-minidump to v20221107.0:
```
0aec5ef update indicatif now that a working version is published
dc8deb2 Improve printing of hexadecimal values
048c10a Improvements to Windows error codes printouts
c796d07 Added macOS ARM arithmetic exceptions
2d78f05 Fixed macOS ARM breakpoint and bad access exceptions and added missing ones
6aaf36a Added perma-links to Apple's sources holding the exceptions' declarations
cb7b25c Add instruction disassembly and access to JSON output
3ee32fc Properly report non-canonical addresses on Amd64 architecture
c06fd69 Remove MemoryListCursor and associated trait machinery
d64fb49 Add info about crashing instruction to output
134675e Refactor crash information into its own structure
dfcfac5 Implement op_analysis::SparseMemoryStream for memory lists …
```
> bug 1801122: update rust-minidump to v20221107.0

- socorro/signature/siglists/prefix_signature_re.txt
```
app$ socorro-cmd signature 52df7903-2585-4bd2-8b9d-c56090221124
Crash id: 52df7903-2585-4bd2-8b9d-c56090221124
Original: OOM | large | mozalloc_abort | moz_xmalloc | new[]
New:      OOM | large | mozalloc_abort | moz_xmalloc | new[] | mozilla::SPSCRingBufferBase<T>::SPSCRingBufferBase
```
> bug 1802715: add new[] to prefix list

- docker/set_up_stackwalker.sh
- socorro/processor/rules/mozilla.py
```
2df6521 (HEAD -> main, tag: v0.15.0, official/main) chore: Release
cd2a736 Update configuration for cargo release 0.22+ and add release notes
a5196a5 Appease clippy
8d7f96e Updated the dependencies
1a456a1 Merge pull request #744 from ePirat/epirat-fix-markdown-help-instructions
f04ecf5 Merge pull request #745 from ePirat/epirat-fix-cargo-release
3e3db7f Merge pull request #742 from ePirat/epirat-fix-parsing-empty-lines-symfile
00292ab Fix cargo-release replacements
66975e6 fix documentation how to generated markdown help
f5f0696 Add empty line in symbol file test
efe2fa0 Add support for empty lines to symbol file parser
```
> bug 1803385: update to rust-minidump 0.15.0

- socorro/schemas/processed_crash.schema.yaml
- webapp-django/crashstats/documentation/jinja2/docs/datadictionary/field_doc.html
- webapp-django/crashstats/documentation/views.py
I did a pass on improving the processed crash data. Mostly it was fixing formatting to take advantage of Markdown.
I also added some examples.
I added support for the "examples" field. I decided to merge it into the description rather than have another examples thing that would make "examples from last 7 days" confusing. I added some "reasons" for when there's no values for things. I added a link to the Protected Data page.
> bug 1803558: improve processed crash data and field doc template

- webapp-django/crashstats/supersearch/models.py
This rewrites the `crashstats/supersearch/models.py` `get_api_allowlist()` so it makes more sense with the current architecture. Many years ago, we moved super search fields from being defined in the database (where they were mutable) to being defined in a Python module (where they aren't).
`get_api_allowlist()` was written when the fields were mutable. Now that they aren't, we can take a lot of the dynamicism out of it.
> bug 1808593: rewrite c/s/models.py get_api_allowlist

- webapp-django/crashstats/api/views.py
- webapp-django/crashstats/crashstats/models.py
This changes the default cache expiration from 60 minutes to 5 minutes. This affects the following APIs:
* Bugs
* SignatureByBugs
* RawCrash
* ProcessedCrash
* SuperSearch
5 minutes protects against the thundering herd, but reduces the amount of stuff sitting around in cache.
> bug 1808594: change default cache expiration to 5 minutes

- bin/process_crashes.sh
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/models.py
- webapp-django/crashstats/crashstats/tests/test_views.py
- webapp-django/crashstats/crashstats/views.py
This changes the RawCrash and ProcessedCrash models to stop caching results. This updates the report view and drops the "refresh=cache" bits, too.
All caching is doing here is reducing the number of times we fetch data from S3. For the report view, HTTP GET requests are sub-1s, don't happen often, and don't tend to repeat. If we need to cache things, we should cache the output of rendering the report view template which would save us two S3 fetches and the work to render the template. We can look into that if we encounter a need to make this faster.
> bug 1808595: stop caching RawCrash and ProcessedCrash data

- socorro/signature/siglists/irrelevant_signature_re.txt
This adds several functions present in stacks when a process is waiting on shutdown. It's Linux-specific as all those type of crashes manifest themselves in slightly different platform-dependent ways.
> Bug 1806107 - Improve Linux shutdown hang signatures

- webapp-django/crashstats/documentation/jinja2/docs/datadictionary/field_doc.html
- webapp-django/crashstats/documentation/static/documentation/css/documentation.less
This fixes word wrapping for field example data. It also tweaks the text that gets shown when example data isn't available.
> bug 1803808: fix wrapping for field examples

- docker-compose.yml
- docker/config/local_dev.env
We're using nip.io to help the webapp redirect the user's browser to the oidcprovider container. However, I was fiddling with that today and I think we don't need it because the webapp container can redirect the user's browser to localhost and that'll work fine.
I'm nixing it now. It feels weird to require nip.io service in order to do local development.
> bug 1809238: drop nip.io

- socorro/processor/processor_pipeline.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/unittest/processor/test_processor_pipeline.py
- socorro/unittest/schemas/test_socorro_data_schemas.py
- webapp-django/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp-django/crashstats/crashstats/static/crashstats/css/base.less
This changes the pipeline so that it stores the notes for the most recent processing pass in "processor_notes" and stores all previous notes in "processor_history".
This makes it easier to search for things that happened in processing without looking at all of the processing history.
> bug 1809728: implement processor_history

- socorro/signature/siglists/irrelevant_signature_re.txt
This adds more assorted implementation functions that were revealed by ignoring the enum ones, so that the resulting signatures are sensible.
> Bug 1809847 - Add rust enum methods and others to the list of irrelevant functions

- docker/set_up_ubuntu.sh
- webapp-django/package-lock.json
This updates to node 18 and also regenerates the package-lock.json file to the new lockfile version.
We have no JavaScript tests. So to verify this, I did:
1. built the app container from scratch (`--no-cache`) and checked the `npm install` output for errors
2. ran the webapp and did a light testing of the site: super search fields, super search, api docs
After this lands, we should go through the site more thoroughly using the webapp manual test. https://socorro.readthedocs.io/en/latest/tests/system_checklist.html
> bug 1810880: update to node 18

- docker/Dockerfile.oidcprovider
This runs the oidcprovider with tini which causes it to shutdown much faster which saves some dev time. Shutdown goes from 10.3s to 0.5s.
> Run oidcprovider with tini

- requirements.txt
This updates face to 22.0.0 which makes the hash mismatch issue moot. We could have added the hash for the new py3 wheel, but might as well upgrade.
> bug 1811242: update face to 22.0.0

- socorro/lib/task_manager.py
- socorro/lib/threaded_task_manager.py
- socorro/processor/processor_app.py
- socorro/tests/lib/test_task_manager.py
- socorro/tests/lib/test_threaded_task_manager.py
This removes the waiting_func argument that gets passed around the task management code because it's not used anywhere.
> bug 1529342: removing waiting_func

- bin/lint.sh
This updates black reformatting to target Python 3.9 and also include socorro-cmd.
> Fix linting

- socorro/processor/processor_app.py
The existing infrastructure configuration uses the old resource.boto.temporary_file_system_storage_path variable that we dropped (code-wise) in 1eb8a195. This adds some code to make the code backwards-compatible with the old configuration.
> bug 1529342: fix temporary path value

- socorro/signature/rules.py
We hit a case where the condition name was a float. That should never happen and we should catch that in processing in a validation/normalization rule so that signature generation doesn't have to deal with weird data.
However, in the interests of getting a fix out there now, I'm just going to stringify the condition names.
> bug 1815235: stringify cond names in SignatureShutdownTimeout rule

- socorro/processor/processor_app.py
- socorro/processor/symbol_cache_manager.py
If the symbol cache directory hasn't been created before the symbol cache manager starts up, then it fails. This fixes the race problem by making sure the processor is built before the symbol cache manager is started.
> bug 1529342: fix symbol cache manager race

- webapp/crashstats/crashstats/management/commands/verifyprocessed.py
- webapp/crashstats/crashstats/tests/test_verifyprocessed.py
We phased out raw crash paths with entropy in September, so verifyprocessed doesn't need to check those anymore.
The remaining bits of entropy stuff are in the boto crash storage code. We need to keep that there until March 7th, 2023 when all the old data has expired out.
> bug 1815535: remove raw crash path with entropy from verifyprocessed

- socorro/lib/threaded_task_manager.py
- socorro/mozilla_settings.py
- socorro/processor/cache_manager.py
- socorro/processor/rules/breakpad.py
The webapp imports mozilla_settings and when it does that, it doesn't have settings for the processor-related configuration, so those things get set to the empty string which isn't a valid int.
This accounts for that by handling the empty string case and making it a None. Then it adds some code to the relevant parts of the codebase that use those settings to handle the None value.
> bug 1529342: handle empty string not being a valid int

- socorro/processor/cache_manager.py
If a file was created and deleted rapidly, we should ignore the CREATE event.
> bug 1822648: handle race condition in CREATE event

- socorro/processor/cache_manager.py
This is a stop-gap fix. We don't want to be hitting q overflows for inotify, but I don't want to leave it hanging this weekend like this.
> bug 1822651: add handling for IN_Q_OVERFLOW

- socorro/mozilla_settings.py
This switches to the DatadogMetrics backend which supports tags.
> bug 1529342: switch to datadogmetrics backend

- bin/run_processor.sh
- bin/run_processor_cache_manager.sh
- bin/run_processor_process.sh
- docker/config/local_dev.env
- requirements.in
- requirements.txt
- socorro/lib/liblogging.py
- socorro/mozilla_settings.py
- socorro/tests/processor/test_cache_manager.py
- webapp/crashstats/settings/base.py
This updates Everett to 3.2.0 which has `parse_data_size` and `parse_time_period`.
This changes the `STACKWALKER_KILL_TIMEOUT` to use `parse_time_period` and changes the value to "2m" which is more readable than "120".
This changes the `SYMBOLS_CACHE_MAX_SIZE` to "40gb" which is more readable than "40000000000".
Honcho manages multiple processes and by default it prefixes stdout with the process name. This removes that prefix and puts the process name in the logging metadata.
> Bug 1529342: everett and honcho

- socorro/signature/siglists/irrelevant_signature_re.txt
This should improve crashes like: https://crash-stats.mozilla.org/report/index/75873ba4-f5c4-45ef-ba71-6047b0230323
> Add std::alloc::_::__rg_oom to irrelevant_signature_re.txt

- requirements.in
- requirements.txt
* Update Django to 3.2.19
* Update requirements
* awscli: 1.27.106 --> 1.27.125
* boto3: 1.26.106 --> 1.26.125
* dj-database-url: 1.3.0 --> 2.0.0
* pygments: 2.14.0 --> 2.15.1
* ruff: 0.0.263 --> 0.0.264
* sentry-sdk: 1.19.1 --> 1.21.1
* Recompile requirements.txt
* Bump attrs from 22.2.0 to 23.1.0 (from PR #6405)
* Bump sqlparse from 0.4.2 to 0.4.4 (from PR #6400)
> Updates 20230503

- docker/set_up_stackwalker.sh
- socorro/processor/rules/breakpad.py
- socorro/processor/rules/general.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/tests/processor/rules/test_breakpad.py
- socorro/tests/processor/rules/test_general.py
This updates the stackwalker from v0.15.0 to v0.16.0.
This fixes the handling for `cpu_microcode_version` since it changed from a u32 to a hexcode and the stackwalker now handles looking at the `CPUMicrocodeVersion` crash annotation if the minidump doesn't have the data.
This adds support for `crash_info.adjusted_address` and using that information to determine the final `address` in the processed crash.
> bug 1827416, 1827495: update stackwalker to v0.16.0; add support for adjusted_address

- requirements.in
- requirements.txt
* Update dependencies
* awscli: 1.27.125 -> 1.27.138
* boto3: 1.26.125 -> 1.26.138
* ruff: 0.0.264 -> 0.0.269
* sentry-sdk: 1.21.1 -> 1.24.0
* werkzeug: 2.2.3 -> 2.3.4
* Bump requests from 2.29.0 to 2.31.0 (from PR #6409)
> Updates 20230523

- webapp/crashstats/crashstats/jinja2/crashstats/bug_comment.txt
- webapp/crashstats/crashstats/templatetags/jinja_helpers.py
The JavaStackTrace annotation is a long vaguely structured string. The create-a-bug code uses that to build the bug description. If that value is too long, it exceeds the max url length and then gets clipped causing the create-a-bug links to not work.
This truncates the JavaStackTrace value.
At some point, we should look at switching to JavaException which is structured when it's available and fall back to JavaStackTrace if necessary.
> bug 1837409: fix create-a-bug links for Fenix Java crashes

- socorro/schemas/raw_crash.schema.yaml
Crash reports can contain crash annotations in a JSON blob. When this happens, some values can be null and thus have a null type. This fixes the schema to support null type for `ReleaseChannel`.
> bug 1810789: support null as a valid type for ReleaseChannel

- socorro/lib/search_common.py
- webapp/crashstats/documentation/jinja2/docs/supersearch/home.html
- webapp/crashstats/supersearch/form_fields.py
- webapp/crashstats/supersearch/forms.py
- webapp/crashstats/supersearch/tests/test_form_fields.py
This fixes `__null__` and `!__null__` for number fields. Support was partially implemented a couple of years ago in the search library code, but the Django form fields which parse and validate the request query string were never adjusted to support `__null__` and `!__null__`, so it never worked.
This adds support for `__null__` and `!__null__` and also adds appropriate validation for combinations of these values and other filters for a number field. This adds appropriate tests as well.
> bug 1837423: support __null__ for number fields in supersearch

- socorro/signature/siglists/prefix_signature_re.txt
```
app@socorro:/app$ ./socorro-cmd signature 521a8bc3-d9ff-45f3-9c29-100130230615 6ee01b21-eb71-4863-aecd-e48e90230614 ed1435c3-ed21-4ea5-be93-b6c170230614 
Crash id: 521a8bc3-d9ff-45f3-9c29-100130230615
Original: mozilla::dom::syncedcontext::Transaction<T>::Commit
New:      mozilla::dom::syncedcontext::Transaction<T>::Commit | mozilla::dom::BrowsingContext::SetOpenerPolicy
Crash id: 6ee01b21-eb71-4863-aecd-e48e90230614
Original: mozilla::dom::syncedcontext::Transaction<T>::Commit
New:      mozilla::dom::syncedcontext::Transaction<T>::Commit | mozilla::dom::BrowsingContext::SetCurrentInnerWindowId
Crash id: ed1435c3-ed21-4ea5-be93-b6c170230614
Original: mozilla::dom::syncedcontext::Transaction<T>::Commit
New: …
```
> bug 1834536: add mozilla::dom::syncedcontext::Transaction<T>::Commit to prefix list

- socorro/external/es/super_search_fields.py
- socorro/mozilla_rulesets.py
- socorro/processor/rules/mozilla.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/tests/processor/rules/test_mozilla.py
- socorro/tests/schemas/test_socorro_data_schemas.py
- webapp/crashstats/topcrashers/forms.py
- webapp/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html
- webapp/crashstats/topcrashers/tests/test_views.py
- webapp/crashstats/topcrashers/views.py
This adds a `report_type` field with values "crash" (the default) and "hang". It implements a processor rule to populate this field using heuristics we've been using for signature generation for a while. It also adjusts the Top Crasher report to allow users to filter on "report type" with values "any", "crash" (the default), and "hang".
This eases triage work by splitting the hang type crash reports from the crash type crash reports which are more actionable.
> bug 1667997: report_type field, processor rule, and adjustment to Top Crasher report

- requirements.in
- requirements.txt
* Fix requirements.txt file
* Bump django from 3.2.19 to 3.2.20 (from PR #6435)
* Bump ruff from 0.0.269 to 0.0.275 (from PR #6433)
> Updates 20230712

- webapp/crashstats/topcrashers/jinja2/topcrashers/topcrashers.html
- webapp/crashstats/topcrashers/tests/test_views.py
- webapp/crashstats/topcrashers/views.py
This changes the report_type default from "crash" which is what we eventually want to use to "any" which is less terrifying when there's no data in the search index with a report_type set.
Once we've accumulated several weeks of crash reports with report_type set, we can change the default back to "crash".
> bug 1667997: change report_type default to "any"

- docker/Dockerfile
This restricts pip to only installing requirements specified in requirements.txt.
> Add --no-deps to pip install arguments

- socorro/processor/cache_manager.py
- socorro/tests/processor/test_cache_manager.py
This adds:
* `processor.cache_manager.file_sizes.median`
* `processor.cache_manager.file_sizes.ninety_five`
metrics.
It also redoes the metrics emitting so it's in a clearer "heartbeat" section that uses less cpu to debounce.
> bug 1850750: add disk cache file size metrics

- socorro/processor/cache_manager.py
This adds:
* `processor.cache_manager.files.count`
* `processor.cache_manager.files.gt_500`
* `processor.cache_manager.file_sizes.avg`
* `processor.cache_manager.file_sizes.max`
> bug 1850750: add additional metrics for disk cache

- socorro/processor/rules/mozilla.py
- socorro/schemas/raw_crash.schema.yaml
- socorro/signature/rules.py
- socorro/signature/schema.rst
- socorro/signature/tests/test_rules.py
- socorro/signature/utils.py
When there's no `JavaStackTrace` annotation, but there is a `JavaException` annotation, this will kick in and generate a signature that matches what it would look like if it came from the `JavaStackTrace` annotation.
The code is a little over-engineered, but gets us a step closer to changing the format for Java signatures to be more like the C signatures and to allow us to iterate over more than the first frame and include/ignore them like we do with C signatures.
This also moves the schema for the signature generation crash data structure to the socorro repository.
> bug 1847429: implement signature generation for JavaException

- bin/run_mdsw.sh
We no longer use timeout when running the stackwalker. This removes it from the bin/run_mdsw.sh script we use for testing/development.
> Remove timeout from bin/run_mdsw.sh

- socorro/processor/processor_app.py
This generalizes the exception handling to catch all psutil errors. There are a lot of race conditions that can happen during the course of the loop so for now we want to keep track of processes generally, but not sweat the details when a race condition happens.
> bug 1851884: generalize to catch all psutil errors

- docker/Dockerfile
- docker/set_up_stackwalker.sh
- docker/set_up_ubuntu.sh
- bug 1853662: update stackwalker to 0.18.0 (v20230927.0)
- bug 1863662: update to python:3.9.18-slim base image
> bug 1853662: update stackwalker to 0.18.0

- docker/Dockerfile
- docker/set_up_stackwalker.sh
This downgrades the base image from bookworm to bullseye. It pulls in a
stackwalker built with bullseye so we don't have a glibc version
problem.
> bug 1853662: downgrade to python:3.9.18-slim-bullseye

- bin/run_mdsw.sh
- docker/set_up_stackwalker.sh
This updates the stackwalker to v20231013.0 which is rust-minidump v0.18.0 plus:
* the codeinfo lookup fix (this bug)
* drop ThreadIdNameMapping fix
* pub-file-lookup fix
> bug 1746940: update stackwalker to v20231013.0 with codeinfo lookup

- requirements.in
- requirements.txt
This updates Django to 3.2.23 to pick up a security fix.
https://www.djangoproject.com/weblog/2023/nov/01/security-releases/
> Update Django to 3.2.23

- bin/service-status.py
- bin/waitfor.py
- socorro/processor/rules/mozilla.py
- socorro/schemas/validate_telemetry_socorro_crash.py
- socorro/scripts/db.py
- socorro/scripts/fetch_crashids.py
- socorro/signature/utils.py
- webapp/crashstats/crashstats/decorators.py
- webapp/crashstats/crashstats/tests/test_jinja_helpers.py
- webapp/crashstats/crashstats/tests/test_models.py
- webapp/crashstats/manage/admin.py
- webapp/crashstats/sources/views.py
and from `urllib.parse.urlunparse` to `urllib.parse.SplitResult.geturl` instead of `urllib.parse.urlunsplit` so that we consistently use `geturl` instead of a mix of both
> bug-1799125: switch from urllib.parse's urlparse to urlsplit

- webapp/crashstats/crashstats/static/crashstats/js/socorro/utils.js
This fixes a bug that occurs when breaking up the querystring into key=val parameters when the value has an = in it. Instead of dropping everything after the second = from the value, this takes more care to split on the first = and ensures everything after that is part of the value.
Before this fix, something like this kicks up a JS error in the console and prevents the page from fetching search results:
http://localhost:8000/search/?date=%3E=2024-01-09&date=%3C2024-01-10#crash-reports
After this fix, the params are parsed correctly, the from date is filled in, and search results show correctly.
> bug-1873658: fix params parsing date=>=2024-01-10 bug

- socorro/external/es/super_search_fields.py
- socorro/mozilla_rulesets.py
- socorro/processor/rules/mozilla.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/tests/conftest.py
- socorro/tests/processor/rules/test_mozilla.py
- socorro/tests/schemas/test_socorro_data_schemas.py
This adds a missing_symbols field to the processed crash and the search index.
This field is a `;` delimited list of "filename/version/debugid" tuples.
This is generated from the json_dump.modules list of modules that have a "filename" and "missing_symbols=True". "missing_symbols=True" indicates that the stackwalker was unable to find a symbols file at the time it was processing the minidump.
Because I'm working with debug ids, I decided to add a debug_id_helper pytest fixture for creating valid debug ids.
To test:
1. download some crash reports and process them
2. go to supersearch and do a facet on "missing symbols"
Unless you're really lucky, there should be one or two missing symbols.
> bug-1862204: add missing_symbols field

- socorro/mozilla_rulesets.py
- socorro/processor/rules/android.py
- socorro/processor/rules/general.py
- socorro/processor/rules/java.py
- socorro/processor/rules/mozilla.py
- socorro/tests/processor/rules/test_android.py
- socorro/tests/processor/rules/test_general.py
- socorro/tests/processor/rules/test_java.py
- socorro/tests/processor/rules/test_mozilla.py
This moves some java/android related processor rule code into separate modules. It makes it a little easier to find rules.
> bug-1812771: clean up processor rules for java/android things

- socorro/mozilla_rulesets.py
- socorro/processor/rules/android.py
- socorro/processor/rules/mozilla.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/tests/processor/rules/test_android.py
- socorro/tests/processor/rules/test_mozilla.py
We want to pull the version for Android from the `Android_Version` annotation which holds the sdk version and the release name. Then we use that to build an os_pretty_version that works for C++/Rust crash reports as well as Java crash reports and is much more useful than what we've got now.
I did this implementation so that it only changes the `os_name`, `os_version`, and `os_pretty_version` for crashes on Android platforms.
What we've got now:
*Figure 1: Bunch of "Unknown" and the version is set to the Linux kernel. Unhelpful.*
What the changes in this PR do:
*Figure 2: Android crashes are marked "Android" and the version is always the sdk version.*
> bug-1812771: fix os_name, os_version, and os_pretty_version for Android

- socorro/signature/siglists/prefix_signature_re.txt
Treat frames like `<.plt ELF section in libxul.so>` as prefix signatures.
For example, this bug is not a useful aggregation: https://bugzilla.mozilla.org/show_bug.cgi?id=1870546
That includes the crash:
https://crash-stats.mozilla.org/report/index/82af7f36-4ed2-4826-bdd6-6397c0240118
whose stack begins:
```
<.plt ELF section in libxul.so>
js::wasm::Instance::callExport(JSContext*, unsigned int, JS::CallArgs, js::wasm::CoercionLevel)
```
That second frame would be a much more interesting thing to file the crash under.
> bug-1876623: Treat `<.plt ELF section...>` as prefix signature

- Makefile
This prevents docker from attaching to backing services which have a lot of output and make the console hard to follow.
To test:
1. `docker compose stop`
2. `./slick.sh`
3. `make run`
> bug-1880154: explicitly attach to primary services

- requirements.in
- requirements.txt
3.2.24 release notes: https://docs.djangoproject.com/en/5.0/releases/3.2.24/
> obs-125: update django to 3.2.24

- requirements.in
- requirements.txt
* attrs: 23.1.0 -> 23.2.0
* awscli: 1.29.77 -> 1.32.47
* boto3: 1.28.77 -> 1.34.47
* datadog: 0.47.0 -> 0.48.0
* dockerflow: 2022.8.0 -> 2024.2.0
* fillmore: 1.1.0 -> 1.2.0
* freezegun: 1.2.2 -> 1.4.0
* glom: 23.3.0 -> 23.5.0
* more-itertools: 10.1.0 -> 10.2.0
* mozilla-django-oidc: 3.0.0 -> 4.0.0
* pip-tools: 7.3.0 -> 7.4.0
* psutil: 5.9.6 -> 5.9.8
* pygments: 2.16.1 -> 2.17.2
* pytest: 7.4.3 -> 8.0.1
* pytest-django: 4.6.0 -> 4.8.0
* sentry-sdk: 1.34.0 -> 1.40.5
* typing-extensions: 4.8.0 -> 4.9.0
* botocore: 1.31.77 -> 1.34.47
* s3transfer: 0.7.0 -> 0.10.0
This updates mozilla-django-oidc, so once this lands and is deployed to stage, I'll verify that auth still works.
> Update requirements in requirements.in

- .circleci/config.yml
Previously, we specified an image that's now deprecated. This removes the version specification which will cause it to use the default which is currently docker 24. default will change over time, but we'll know if CI fails pretty quick and we're switching to GCP soon with a completely different deploy pipeline anyhow.
CI spit out this output for the "setup remote docker" step:
```
Created container accessible with:
DOCKER_HOST=unix:///var/run/docker.sock
DOCKER_MACHINE_NAME=localhost
Server Engine Details:
Version:          24.0.9
API version:      1.43 (minimum version 1.12)
Go version:       go1.20.13
Git commit:       fca702d
Built:            2024-02-01T00:48:39.000000000+00:00
OS/Arch:          linux/amd64
Experimental:     false
```
That's using Docker 24, so I think we're good.
> bug-1881630: update circleci remote docker image

- docker/set_up_stackwalker.sh
This updates the stackwalker to v0.20.0 which picks up the following changes:
```
3581196 (tag: v0.20.0) chore: Release
852af14 Updated cargo-dist configuration
0b3aff9 Updated the release notes for the next version
8e2dae5 Updated ctor to version 0.2
7da12de Updated all the dependencies, this removes a few duplications and picks up some useful fixes
e6b5c2a fix: restore the idx field on thread spans
dd377d1 Remove the dependency on dump_syms
35651c5 Make MmapMinidump static
8d69037 Avoid requiring a dependency on memmap2 to use Minidump<'_, Mmap>
7f38b36 bug-1873529: fix debug id for modules found by code-info lookup
5f31ab7 Update scroll to 0.12
362a4a0 Update memmap2 to 0.9.3
a068902 fmt
05396af fix clippy lints from 1.75.0
99e0590 Use the procfs crate in minidump for parsing linux …
```
> bug-1862730: update stackwalker to v0.20.0

- socorro/external/es/super_search_fields.py
- socorro/mozilla_rulesets.py
- socorro/processor/rules/breakpad.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/tests/processor/rules/test_breakpad.py
- webapp/crashstats/crashstats/jinja2/crashstats/report_index.html
This adds is_likely_guard_page to the stackwalker output part of the processed crash schema.
It also adds a new top-level has_guard_page_access protected field. This is true iff there's at least one memory access where is_likely_guard_page is true.
These fields are marked protected because there are security concerns with this data.
Example crash reports:
* 8dd52551-692d-45ff-82d0-9ab000240228
* a5875ef2-5cc1-4fdd-bbab-0b1400240229
* 7c66167c-de29-4b8f-85c3-1c7db0240228
* 456b3a73-1607-4487-9814-929700240228
* c52e0b31-5a34-4937-a922-b97c30240228
To test:
1. rebuild local dev environment
2. process crash reports
3. open browser in webapp (not logged in)
1. view crash report
1. verify you can't see "Has guard page access: true" in "Details" tab
2. verify you can't see …
> bug-1830954: add support for has_guard_page_access

- requirements.in
- requirements.txt
- webapp/crashstats/api/views.py
- webapp/crashstats/crashstats/monkeypatches.py
- webapp/crashstats/settings/base.py
- webapp/crashstats/topcrashers/views.py
- webapp/crashstats/urls.py
We used django-session-csrf which is a Mozilla maintained library that we wrote back in the heady Mozilla webdev days which had properties our webdev and websec folks wanted. That was a long time ago, Django's built-in csrf module has improved over time, the world has changed (no more Flash), and the library hasn't been actively maintained in some time.
This drops the django-session-csrf and some of the interesting code around it in favor of Django's built-in csrf.
To test:
1. set up a local dev environment
2. process some crash reports
3. try a POST with no csrf token: `curl -X POST http://localhost:8000` -- should return an HTTP 403
4. open the webapp in your browser
5. while not logged in
1. test quick search (top right-hand corner) with a crash id that you processed
2. test …
> bug 1883055: stop using django-session-csrf

- socorro/schemas/processed_crash.schema.yaml
Previously `CrashAnnotations.yaml` listed `ipc_system_error` as a string, but Socorro treated it as an integer. We had a note because of the discrepancy.
That's no longer true--`CrashAnnotations.yaml` has been fixed. We can remove the note.
> bug-1867814: remove irrelevant comment

- docker/set_up_stackwalker.sh
This updates the stackwalker to v0.21.1 which picks up the following changes:
```
e7ecb41 (HEAD -> main, tag: v0.21.1, origin/main, origin/HEAD) chore: Release
dff1530 Updated the release notes for the next version
b65c81a Updated all the dependencies
10eefc4 Merge pull request #968 from afranchuk/dont-require-system-info
73097b4 Only require the MinidumpSystemInfo stream when using local debug info.
2611865 (tag: v0.21.0) chore: Release
2f56803 Updated cargo-dist configuration using version 0.11.1
c154dbd Updated the release notes for the next version
52ffeda Updated all the dependencies
58a239c Allow passing the path to a symbol files in --symbols-path
7b28df6 Merge pull request #963 from rust-minidump/dependabot/cargo/framehop-0.9.0
9030821 Merge pull request #955 from …
```
> bug-1884718: update stackwalker to v0.21.1

- socorro/external/es/crashstorage.py
- socorro/external/es/super_search_fields.py
- socorro/tests/conftest.py
- socorro/tests/external/es/test_analyzers.py
- socorro/tests/external/es/test_crashstorage.py
- socorro/tests/external/es/test_query.py
- socorro/tests/external/es/test_super_search_fields.py
- socorro/tests/external/es/test_supersearch.py
- webapp/crashstats/crashstats/tests/test_updatemissing.py
- webapp/crashstats/crashstats/tests/test_verifyprocessed.py
- webapp/crashstats/signature/tests/test_views.py
- webapp/crashstats/supersearch/tests/test_views.py
- webapp/crashstats/topcrashers/tests/test_views.py
In bug 1763264, we finished all the work to stop using the raw crash when indexing crash report data. The only data we're indexing now comes from the processed crash after being normalized and validated by processor rules. This radically reduces problems with indexing from weird values.
This cleans up the remnants of those old days by removing `raw_crash` from building documents, indexing, and related documentation. This also removes a deepcopy call which will speed up indexing a little.
> bug-1885978: remove raw crash from indexing code

- webapp/crashstats/documentation/jinja2/docs/protected_data_access.html
To test, do this:
1. build socorro and then `make run`
2. go to http://localhost:8000/documentation/protected_data_access/
3. click on link to request protected data access
4. make sure the priority isn't set to `P3`--it should be `--`
> bug 1888223: remove priority from protected data access request link

- socorro/tests/external/pubsub/test_crashqueue.py
- webapp/crashstats/crashstats/tests/test_models.py
by comparing delivered crash ids as sets instead of as lists
> bug-1886018: Fix flaky tests due to pubsub duplicate delivery

- webapp/crashstats/crashstats/tests/test_jinja_helpers.py
- webapp/crashstats/libbugzilla.py
- webapp/crashstats/tests/test_libbugzilla.py
This adds support for java_exception field when generating the
description for creating new bugs.
This also creates `webapp/crashstats/tests/test_libbugzilla.py` and
moves a bunch of tests from `test_jinja_helpers.py` so that
`test_libbugzilla.py` tests all the requirements for the functions.
I also switched the comment-building tests to use dedent instead of
string delimiters, newlines, and such. It's a little easier to
manipulate and a lot easier to read and verify.
This also re-does `test_corrected_os_version_name` so it's parametrized.
> bug-1884041: support java_exception in crash_report_to_description

- .circleci/config.yml
Fixes a couple of minor issues I noticed when looking at CI failures.
- Remove `docker compose up ...` in CI step
- Update cimg/python image to 3.10.13 hoping that picked up a new docker client, but it didn't
We see this warning when running `make build`:
```
--progress is a global compose flag, better use `docker compose --progress xx build ...
```
I really thought I also saw it when we were looking at CI failures the other day, but when I fix it CI fails saying that it doesn't know about `docker --progress xx`. I think that in CI while the docker server is up to date, the docker plugins and docker client aren't. I updated the `cimg/python` image, but that didn't change anything.
Anyhow, something we'll have to look at in the future.
> circleci fixes

- bin/pubsub_cli.py
- docs/dev.rst
while working on #6577 i noticed some places where pubsub should be mentioned, and for compatibility with `bin/sqs_cli.py` I added support for reading crash ids from stdin for `socorro-cmd pubsub publish`
> bug-1886018: update dev.rst to mention pubsub

- socorro/signature/siglists_utils.py
Python 3.8 has a `importlib.resources`, but it doesn't include the `files()` function. So for Python 3.8, siggen will require `importlib_resources`.
That's great, except we needed to invert the `importlib_resources` preference so it now prefers the backport library if it's there and uses the built-in library if it's not.
This fixes https://github.com/willkg/socorro-siggen/issues/124 .
> Reverse preference for importlib_resources

- bin/test.sh
- webapp/crashstats/monitoring/tests/test_views.py
- webapp/crashstats/monitoring/views.py
This adds the `CLOUD_PROVIDER` environment variable value to `/__version__` output so we can easily determine which cloud the service is running in.
To test:
1. run the webapp
2. go to `http://localhost:8000/__version__` and verify there's a "cloud" key with the value of `CLOUD_PROVIDER` in it
Note that this is a dirty way of doing what we want and the Dockerflow "standard" doesn't necessarily allow for other things to be in the `/__version__` output, but we'll plan to clean this up post-GCP-migration so it's temporary.
> bug-1887629: add CLOUD_PROVIDER to `/__version__` output

- bin/waitfor.py
This changes the blocking timeout to 5s for waitfor--previously it used the socket default timeout of 1s.
The theory is that in CI, it's taking longer than 1s for localstack to respond sometimes which causes CI to fail.
> bug 1894925: change blocking timeout to 5

- webapp/crashstats/tokens/admin.py
- webapp/crashstats/tokens/management/__init__.py
- webapp/crashstats/tokens/management/commands/__init__.py
- webapp/crashstats/tokens/management/commands/createtoken.py
- webapp/crashstats/tokens/tests/test_createtoken.py
This fixes the token admin headers like we did with Tecken. Further, it adds a createtoken command like Tecken has allowing us to create tokens from the command line in the local dev environment.
To test:
```
cd webapp/
./manage.py createtoken jimmy@example.com c7d1f8cad79545b6a06dc4122f0eb3cd
```
> Fix token admin headers and add createtoken command

- Makefile
- bin/entrypoint.sh
- bin/run_fakecollector.sh
- bin/run_service_stage_submitter.sh
- bin/test.sh
- docker-compose.yml
- docker/config/local_dev.env
- docs/service/index.rst
- docs/service/stage_submitter.rst
- fakecollector/collector.py
- pytest.ini
- socorro/lib/liblogging.py
- socorro/mozilla_settings.py
- socorro/stage_submitter/__init__.py
- socorro/stage_submitter/submitter.py
- socorro/tests/stage_submitter/conftest.py
- socorro/tests/stage_submitter/test_submitter.py
This implements a stage submitter that pulls crash ids from QUEUE and crash data from STORAGE, packages that up into a crash report payload, and submits it to STAGE_SUBMITTER_DESTINATIONS.
This creates a `make runsubmitter` system that runs the stage submitter and a fake collector allowing you to use `bin/process_crash.sh` to set everything up and publish a crash id to the standard queue which the submitter will see and submit a crash to the fake collector. The fake collector will parse the payload and log headers, annotations, and files.
This adds stage submitter tests.
To test:
1. `make build`
2. `make setup`
3. `make runservices`
4. `make runsubmitter`
5. in another terminal, run `make shell` and then you can use `bin/process_crash.sh` to download crash data, put it in storage, and …
> bug-1889185: implement stage submitter and fake collector

- bin/load_processed_crashes_into_es.py
- socorro/tests/test_load_processed_crashes_into_es.py
Because:
* We need to migrate Elasticsearch from AWS to GCP as part of the Socorro GCP migration.
* Due to our version of Elasticsearch being very old, the best (only?) possible migration path is to [load data into the GCP Elasticsearch cluster from the original source](https://www.elastic.co/guide/en/cloud/current/ec-migrating-data.html), which is S3 in our case.
This PR:
* Adds a script that loads processed crashes from either S3 or GCS (depending on `settings.CRASH_SOURCE`) into Elasticsearch by either date (YYYY-MM-DD) or crash ID.
<details>
<summary>How to test this locally</summary>
I have painstakingly added test cases for all the major scenarios, so running the tests in `socorro/tests/test_load_processed_crashes_into_es.py` (or replicating the setup before running the script with …
> bug 1889156: script to load processed crashes into Elasticsearch

- socorro/signature/siglists/irrelevant_signature_re.txt
nsStringBuffer:: is still on the prefix list, but I don't actually see any instances of it besides AddRef and Release, so I'll leave it alone.
> Bug 1860947 - Add ReleaseData and string buffer AddRef and Release methods to the irrelevant signature list

- docker/config/gunicorn_config.py
- fakecollector/collector.py
- socorro/external/boto/crashstorage.py
- socorro/external/es/crashstorage.py
- socorro/external/gcs/crashstorage.py
- socorro/lib/liblogging.py
- socorro/libmarkus.py
- socorro/mozilla_settings.py
- socorro/processor/cache_manager.py
- socorro/processor/pipeline.py
- socorro/processor/processor_app.py
- socorro/processor/rules/base.py
- socorro/processor/rules/breakpad.py
- socorro/processor/rules/general.py
- socorro/processor/rules/mozilla.py
- socorro/stage_submitter/submitter.py
- socorro/tests/processor/test_pipeline.py
- socorro/tests/stage_submitter/test_submitter.py
- webapp/crashstats/__init__.py
- webapp/crashstats/crashstats/apps.py
- webapp/crashstats/crashstats/decorators.py
- webapp/crashstats/crashstats/management/commands/verifyprocessed.py
- webapp/crashstats/crashstats/models.py
- webapp/crashstats/crashstats/tests/test_sentry.py
- webapp/crashstats/crashstats/tests/test_views.py
- webapp/crashstats/cron/management/commands/cronrun.py
- webapp/crashstats/settings/base.py
This adds a "host" tag to emitted metrics when running in GCP. This is derived from "HOSTNAME" if it exists, otherwise it defaults to `socket.gethostname()` like our other services.
This changes Sentry and logging to use `HOSTNAME` configuration variable rather than `HOST_ID`. This brings us in line with other services as we migrate to GCP.
This also adds `"socorro."` prefix to all emitted keys, but only for the GCP environments so we don't make a major change to socorro running in AWS at this time. This brings keys in line with our other services.
In order to do this, I had to create a singleton `METRICS` in `socorro/libmarkus.py` and then rework everything to use that.
To test:
1. run the tests--they have assertions about keys and tags
2. run socorro, process crashes, make sure metrics …
> bug-1898341, bug-1898345: add "host" tag, fix metrics key prefix

- webapp/crashstats/settings/base.py
This changes Crash Stats to store the csrf token in the session rather than in the cookie.
This also adjusts the order of the middleware per Django's documented conventions.
This also sets the `CSRF_COOKIE_NAME` to "crashstatscsrftoken" to make it distinguishable in the local dev environment from other things creating a "csrftoken". It shouldn't get created anymore and now it's a lot easier to verify that.
To test:
1. check out this pr, then switch to the first commit
2. set up your local dev environment
3. run `make run`
4. go to `localhost:8000` in a fresh private window and log in
5. check firefox dev tools Storage tab Cookies
You'll see the csrf cookie from crash stats code (crashstatscsrftoken) and the one from the oidc provider (csrftoken) which we use in the local dev environment. …
> bug-1898800: fix csrf token storage

- docker/set_up_ubuntu.sh
this installs tools `psql`, `pg_dump` and `pg_restore` which are needed for the plan to migrate the postgres from aws to gcp.
> OBS-87: install postgres cli tools for db maintenance

- socorro/external/pubsub/crashqueue.py
- socorro/stage_submitter/submitter.py
- socorro/tests/stage_submitter/test_submitter.py
This fixes the submitter to only consume from the standard subscription rather than from standard, priority, and reprocessing.
It does it by stomping on the subscription_name settings for priority and reprocessing in the PubSubCrashQueue class. That means this will never run in AWS, but that's what our plan was anyhow.
> bug-1900646: fix submitter to only consume standard queue

- socorro/processor/rules/mozilla.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/tests/processor/rules/test_mozilla.py
This adds the code_id to the misisng_symbols field. Now the field will have one of two shapes:
* module/version/debugid
* module/version/debugid/codeid
This doesn't affect how we index this field in Elasticsearch. Further, we can reprocess existing crash reports to pick up the codeid information once this is deployed to production if we want to do that.
To test:
1. build socorro local dev environment
2. index some crash reports with missing symbols:
* 2cca63d3-2d4a-4981-adac-562030240605
* 6a61e999-b227-4779-8fff-475960240605
* e27ddaf3-3760-4d8b-9380-a5b570240605
```
./bin/process_crashes.sh 2cca63d3-2d4a-4981-adac-562030240605 6a61e999-b227-4779-8fff-475960240605 e27ddaf3-3760-4d8b-9380-a5b570240605
```
3. use supersearchfacet to get a facet of `missing_symbol` (make sure to include …
> bug-1900806: add code_id to missing_symbols field

- socorro/signature/generator.py
- socorro/signature/pipeline.rst
- socorro/signature/rules.py
- socorro/signature/schema.rst
- socorro/signature/tests/test_rules.py
- socorro/signature/utils.py
This removes a signature generation rule that used moz_crash_reason data to stomp on the signature in a certain situation. The assertion that triggered crash reports for this situation is no longer in the code base so this rule no longer has any effect. This removes the rule and the use of moz_crash_reason.
There isn't a good way to test this beyond running the tests. The related bug covers investigation of the situation.
> bug-1900995: remove SignatureParentIDNotEqualsChildID rule

- docker/Dockerfile.fakesentry
- requirements.in
- requirements.txt
- socorro/processor/processor_app.py
- socorro/tests/processor/rules/test_mozilla.py
- socorro/tests/processor/test_cache_manager.py
- socorro/tests/processor/test_pipeline.py
- socorro/tests/processor/test_processor_app.py
- webapp/crashstats/crashstats/apps.py
- webapp/crashstats/crashstats/tests/test_sentry.py
This updates sentry-sdk to 2.5.1, fillmore to 2.0.0, and kent to 2.0.0. This gets us over the sentry-sdk API change.
This also fixes some flakey cache manager tests that sometimes fails and I think it has to do with there not being enough time between creating the files and reading the first file such that the first file doesn't end up with a measurably recent mtime.
> Update sentry-sdk, fillmore, and kent

- socorro/signature/siglists/irrelevant_signature_re.txt
- socorro/signature/siglists/prefix_signature_re.txt
- socorro/signature/siglists/signature_sentinels.txt
- socorro/signature/tests/test_rules.py
This is for: https://bugzilla.mozilla.org/show_bug.cgi?id=1885919
The idea would be for crashes with signatures like `mozilla::ipc::FatalError | mozilla::ipc::IProtocol::HandleFatalError | IPC::MessageReader::FatalError` to produce `IPC::MessageWriter::FatalError | IPC::ParamTraitsIPC<mozilla::UniquePtr<void*, mozilla::detail::FileHandleDeleter> >::Read(IPC::MessageReader*, mozilla::UniquePtr<void*, mozilla::detail::FileHandleDeleter>*)` instead.
No idea if this works...
> Bug 1885919 - Add IPC::MessageReader::FatalError to sentinels list

- socorro/signature/siglists/prefix_signature_re.txt
See [bug 1904528](https://bugzilla.mozilla.org/show_bug.cgi?id=1904528): Add APP_DATA::FreeCachedMem, SysFreeString and VariantClear to the prefix list for better triage of [bug 1900964](https://bugzilla.mozilla.org/show_bug.cgi?id=1900964). I think this will automatically apply for VariantClearWorker as well?
> Add APP_DATA::FreeCachedMem, SysFreeString and VariantClear to the prefix list

- socorro/external/es/super_search_fields.py
- socorro/external/es/supersearch.py
- socorro/tests/external/es/test_supersearch.py
- webapp/crashstats/documentation/jinja2/docs/supersearch/home.html
- webapp/crashstats/supersearch/static/supersearch/js/lib/dynamic_form.js
In Crash Stats, if you go to Super Search and then search for `platform="Linux"`, you get back crash reports on the Linux platform. If you search for `platform="Mac OS X"`, you get back crash reports on the Mac OS X platform. However, if you want to search for `platform=["Linux", "Mac OS X"]`, you _only_ get back crash reports for Linux.
This happens for a couple of reasons:
1. the `platform` super search field is an analyzed field despite there being only 5 possible values and being treated as an enum in the search form -- it shouldn't be analyzed, but that's a problem for a different day
2. when you search on a field with a single value, the supersearch code does a "simple_query_search" query, but if you search on a field with 2 or more values, it does a "terms" query -- …
> bug-1100790: fix super search platform queries

- bin/gcs_cli.py
from python help for `Bucket.delete`:
>    If ``force=True`` and the bucket contains more than 256 objects / blobs
>    this will cowardly refuse to delete the objects (or the bucket). This
>    is to prevent accidental bucket deletion and to prevent extremely long
>    runtime of this method. Also note that ``force=True`` is not supported
>    in a ``Batch`` context.
> bug-1904645: fix gcs_cli.py deleting buckets with more than 256 objects

- webapp/crashstats/api/tests/test_views.py
- webapp/crashstats/api/views.py
because it's not in s3 anymore. this changes the api, and i'm not sure how impactful that is.
> bug-1908543: remove s3_ prefix from keys in crash verify response

- bin/permadelete_crash_data.py
- socorro/external/crashstorage_base.py
- socorro/external/es/crashstorage.py
- socorro/external/fs/crashstorage.py
- socorro/external/gcs/crashstorage.py
- socorro/tests/external/fs/test_fspermanentstorage.py
- socorro/tests/external/test_crashstorage_base.py
this adds `delete_crash` methods to the gcs and es crash storage classes, so that backend-specific code lives within the implementation.
blocks #6669
>  bug-1908543: fix permadelete for gcs

- bin/update_siggen.py
This improves the update_siggen.py to include the authors of commits at the end of the commit summary line. We should be giving credit where credit is due. This information shows up in the merge commits in siggen as well as the HISTORY file and tag annotation.
Before:
```
Dest sha:   2edf2158a00f0dfc58cc542a5beeceb03b2ce954
Source sha: bd98591d35775be47531a51faed03ff4c9839328
fd9a5192f  Bug 1907894 - Add mozilla::Atomic<T> to the irrelevant signature list.
f51eb338c  Bug 1906667 - Add mozilla::media::Interval<T> to the prefix list. (#6663)
e1d2b1a8a  Bug 1905714 - Only match JS::Call exactly in signatures. (#6652)
8cf6cf349  bug-1904528: add SafeVariantClear and VariantCopy to prefix list
```
After:
```
Dest sha:   2edf2158a00f0dfc58cc542a5beeceb03b2ce954
Source sha: …
```
> Improve update_siggen.py to include authors

- socorro/stage_submitter/submitter.py
because stage submitter threw some errors last night due to the stage collector latency spiking above the current timeout of 3 seconds for a short while.
> bug-1910376: increase stage submitter request timeout to 10 seconds

- socorro/signature/cmd_doc.py
- socorro/signature/pipeline.rst
This fixes some whitespace issues with signature generation docs.
Old output:
New output:
> Fix signature generation docs

- bin/pubsub_cli.py
We need to set the ack_deadline_seconds otherwise it defaults to 10 seconds which isn't long enough and causes crash ids to get read again. And again. And again. And again again.
This _only_ affects the local dev environment, so I'm putting it up for review for reals.
> bug-1912979: fix rerererereprocessing problem in local dev env

- socorro/external/es/super_search_fields.py
- socorro/external/es/supersearch.py
- socorro/tests/external/es/test_supersearch.py
- webapp/crashstats/documentation/jinja2/docs/supersearch/home.html
- webapp/crashstats/supersearch/static/supersearch/js/lib/dynamic_form.js
In Crash Stats, if you go to Super Search and then search for `platform="Linux"`, you get back crash reports on the Linux platform. If you search for `platform="Mac OS X"`, you get back crash reports on the Mac OS X platform. However, if you want to search for `platform=["Linux", "Mac OS X"]`, you _only_ get back crash reports for Linux.
This happens for a couple of reasons:
1. the `platform` super search field is an analyzed field despite there being only 5 possible values and being treated as an enum in the search form -- it shouldn't be analyzed, but that's a problem for a different day
2. when you search on a field with a single value, the supersearch code does a "simple_query_search" query, but if you search on a field with 2 or more values, it does a "terms" query -- …
> bug-1100790: change supersearch terms query to matches

- docs/conf.py
- docs/exts/document_metrics.py
- docs/index.rst
- docs/metrics.rst
- requirements.in
- requirements.txt
- socorro/libmarkus.py
- socorro/processor/cache_manager.py
- socorro/processor/processor_app.py
- socorro/stage_submitter/submitter.py
- socorro/statsd_metrics.yaml
- socorro/tests/conftest.py
- socorro/tests/external/es/test_crashstorage.py
- socorro/tests/processor/rules/test_breakpad.py
- socorro/tests/processor/test_cache_manager.py
- socorro/tests/processor/test_processor_app.py
- webapp/conftest.py
- webapp/crashstats/crashstats/apps.py
- webapp/crashstats/crashstats/tests/test_sentry.py
- webapp/crashstats/cron/management/commands/cronrun.py
This upgrades markus to 5.0.0. It adds a specification for all metrics emitted. It adds autodocumentation of those metrics to the docs.
While doing this, I found a handful of issues:
1. markus wasn't set up at test session start, so tests may or may not be running with the markus filters set up; now we set up markus at pytest session start
2. `sentry_scrub_error` had a key per service; now we have a single key with the service specified as a tag which makes it easier to have a single dashboard panel covering all sentry scrub errors
3. cronrun emitted separate metrics for success and failure with the timing as a gauge; now it's a timing and one key with the result as a tag
> bug-1906112: upgrade markus to 5.0.0 and fix metrics-related issues

- webapp/crashstats/libbugzilla.py
- webapp/crashstats/tests/test_libbugzilla.py
Because:
* The `moz_crash_reason` value (and similarly, the `reason` value) was not displaying properly in the Bugzilla create bug page due to some extra whitespace and missing newline characters in the value of the `comment` query parameter passed in the create bug URL.
This commit:
* Trims any whitespace on these values.
* Adds a newline character before and after the triple backticks.
Note: Shortly after bug-1919789 was fixed (which temporarily blocked this bug), I can no longer reproduce the issue in this bug locally or in prod, however, it makes sense to make these changes anyway, so that the formatting will reflect standard Markdown formatting regardless of the current Bugzilla create bug URL implementation.
Here's a screenshot of what the Preview looks like in the Bugzilla create …
> bug-1918223: fix moz_crash_reason and reason formatting in create bug Description field.

- socorro/external/es/crashstorage.py
- socorro/external/es/super_search_fields.py
- socorro/tests/external/es/test_super_search_fields.py
multi_field was removed in elasticsearch 1.0, and in 1.x is automatically translated to the new format, but starting with 5.x it throws an error
also fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1905772
> bug-1921849: fix deprecated type: multi_field from super_search_fields

- Makefile
Because:
* Several developers intermittently had issues where the shells from these commands were exiting.
* These commands originally relied on the default entrypoint of the base Docker image, i.e. `ENTRYPOINT ["/usr/bin/tini", "--", "/app/bin/entrypoint.sh"]` in `docker/Dockerfile`, and we believe Tini is interfering with this shell and causing it to exit prematurely[1].
This commit:
* Passes a different entrypoint into these commands to bypass using Tini in the default entrypoint command.
[1]: As @relud observed, and I've confirmed: `docker compose run --rm -ti --entrypoint '/usr/bin/tini' app bash` does the bad thing and `docker compose run --rm -ti --entrypoint '/bin/bash' app` works
> prevent bash from auto-exiting on keypress for `make shell` and `make testshell` commands

- docs/dev.rst
Because:
* The `./manage.py test` command uses the `test` command from `setuptools`, which uses `unittest` under the hood.
* Our webapp tests run with `pytest`, and we have test-specific overrides configured in `webapp/pytest.ini` that won't get applied when the tests are run outside of `pytest` leading to test failures.
This commit:
* Updates the docs to use the pytest command.
> replace Django `test` command with `pytest` in webapp test docs

- socorro/external/es/crashstorage.py
- socorro/external/legacy_es/crashstorage.py
- webapp/crashstats/crashstats/management/commands/updatesignatures.py
- webapp/crashstats/crashstats/tests/conftest.py
- webapp/crashstats/supersearch/forms.py
- webapp/crashstats/supersearch/libsupersearch.py
- webapp/crashstats/supersearch/models.py
- webapp/crashstats/supersearch/tests/test_forms.py
- webapp/crashstats/supersearch/tests/test_libsupersearch.py
- webapp/crashstats/supersearch/views.py
In PR #6741, we're moving the code where we convert between the processed crash schema permissions in super search fields to webapp permissions to the general Socorro code. We try really hard to not have webapp things leak into the general Socorro code, so I wanted to experiment with other ways of solving the problem of having two elasticsearch crash storage implementations in respects to super search fields.
This tests that out by adding a `get_supersearch_fields()` function to `webapp/crashstats/supersearch/libsupersearch.py` which imports the specified Elasticsearch crashstorage, gets `SUPERSEARCH_FIELDS` from it, converts the permissions and returns it.
While doing that, I fixed some clarity issues in the code. `convert_permissions` will never have a case where the field has …
> Rework how supersearch fields permissions are handled

- docker-compose.yml
socorro dev is on PostgreSQL 12 right now, which will be EoL on November 14, 2024. for additional details see https://mozilla-hub.atlassian.net/browse/OBS-367
> bug-1926948: upgrade dev to postgresql 16.4

- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
Because:
* Some module names have extra square brackets, in particular one at the end (bug-1926561).
* This causes Crash Stats report Bugzilla tab not to list related bugs.
This commit:
* Removes enclosing square bracket(s) from module names in stack frames.
I tested this locally by processing the crash mentioned in the bug. The extra closing bracket gets removed as desired:
**Before**
Bugzilla tab does not list the expected bug, Bug-1923773:
**After**
I also verified that the crash bug that wasn't originally showing up in the reports view Bugzilla tab is now showing up:
> bug-1926077: remove enclosing square bracket(s) from module name in signature generation

- bin/entrypoint.sh
- bin/run_cache_manager.sh
- bin/run_fakecollector.sh
- bin/run_processor.sh
- bin/run_service_processor.sh
- bin/run_service_stage_submitter.sh
- bin/run_service_webapp.sh
- bin/run_symbolsserver.sh
- docker-compose.yml
- docker/Dockerfile
- docker/Dockerfile.fakesentry
- docker/Dockerfile.oidcprovider
- docker/set_up_ubuntu.sh
The tini process was originally added to make Docker comtainers quite properly when receiving the TERM signal on `docker compose stop`. Some containers don't react to this signal, so terminating them will hang for ten seconds before Docker Compose sends SIGKILL.
The changes in this PR are similar to https://github.com/mozilla-services/tecken/pull/3049.
I added `exec` to run the main command to a bunch of shell scripts. This ensures the shell script doesn't linger around, and the _actual_ main process receives the signals, which is a lot more useful.
https://mozilla-hub.atlassian.net/browse/OBS-361
> OBS-361: Remove tini and set up stop signals.

- socorro/external/pubsub/crashqueue.py
- socorro/tests/external/pubsub/test_crashqueue.py
When a user uses the Reprocessing API, they send some number of crash ids to be reprocessed. If something happens when publishing the crash ids to PubSub, the crash id is added to a "failed" list and the exception is logged. Then at the end if there were any failures, a CrashIdsFailedToPublish exception is thrown with the list of failures.
That causes Django to return an HTTP 500 to the user and sentry captures the CrashIdsFailedToPublish exception, but the event isn't very helpful--we have no idea what happened.
This attempts to alleviate that in a couple of ways:
1. It uses sentry_sdk.capture_exception() to capture each problem enountered when publishing to PubSub.
We'll be able to see what's going on in Sentry events.
2. It keeps track of the errors along with the crash ids and wraps …
> bug 1909875: improve CrashIdsFailedToPublish information

- requirements.in
- requirements.txt
- socorro/processor/pipeline.py
- socorro/processor/processor_app.py
- socorro/processor/rules/mozilla.py
- socorro/stage_submitter/submitter.py
- socorro/tests/processor/rules/test_mozilla.py
- socorro/tests/processor/test_cache_manager.py
- socorro/tests/processor/test_pipeline.py
- socorro/tests/processor/test_processor_app.py
This updates sentry_sdk to 2.17.0. In order to do that, we had to do two fundamental changes:
1. Switch `sentry_sdk.push_scope()` calls to `sentry_sdk.new_scope()` which does roughly the same thing.
2. Switch from using `sentry_sdk.add_extra()` to `sentry_sdk.set_context()`. `add_extra()` was nice in that it allowed us to add additional things to the sentry event payload that gave context to the error. We used this to capture the processor rule, ruleset, crash_id, signature generation rule, etc in an additive way.
`add_extra()` is deprecated and Sentry suggests to switch to `set_context()` which is not an additive kind of thing. So now we have to set a new context section everywhere we set the context. That's a little annoying, but it'll be fine.
I updated the code and tests accordingly. …
> bug-1920739: update sentry_sdk to 2.17.0

- socorro/lib/task_manager.py
- socorro/lib/threaded_task_manager.py
- socorro/processor/processor_app.py
- socorro/statsd_metrics.yaml
- socorro/tests/processor/test_processor_app.py
This removes processor heartbeat (and the scaffolding for that heartbeat) which generated process metrics for the processor container. We don't need those anymore--the problem those were added to help us understand is long gone now.
> bug-1911367: Remove processor heartbeat and process metrics

- socorro/mozilla_rulesets.py
- socorro/processor/rules/mozilla.py
- socorro/tests/processor/rules/test_mozilla.py
This fixes these two rules to stop editing the raw crash--that's soo bad!
Now they run after we copy everything from the raw crash to the processed crash (validated and normalized), use data from the processed crash to figure out what to do, and edit data in the processed crash if necessary.
> bug-1851708: fix ESRVersionRewriteRule and FenixVersionRewriteRule

- webapp/crashstats/crashstats/jinja2/400.html
- webapp/crashstats/crashstats/jinja2/404.html
- webapp/crashstats/crashstats/jinja2/500.html
- webapp/crashstats/crashstats/jinja2/crashstats_base.html
- webapp/crashstats/crashstats/jinja2/error_base.html
- webapp/crashstats/crashstats/jinja2/footer_nav.html
- webapp/crashstats/crashstats/jinja2/header_title.html
- webapp/crashstats/signature/jinja2/signature/signature_report.html
- webapp/crashstats/supersearch/jinja2/supersearch/search.html
- webapp/crashstats/supersearch/jinja2/supersearch/search_custom.html
"crash reports" is the name of the collector, so it's always been a dissonance that the header of the Crash Stats site said Crash Reports.
While doing this, I also fixed the hierarchy of error templates and removed an unneeded header_title.html template.
Currently we have:
This fixes it to:
> bug-1863963: fix site title to Mozilla Crash Stats

- socorro/signature/generator.py
- socorro/signature/rules.py
- socorro/signature/tests/test_rules.py
The crash signature contains data from stackwalker output as well as JavaException annotations and other places, too. Because of this, it's possible for the signature to contain non-ascii and non-printable characters. This rule restricts signatures to printable ASCII characters.
> bug-1764633: remove non-printable/non-ascii characters from signature

- webapp/crashstats/sources/tests/test_views.py
- webapp/crashstats/sources/views.py
If the url provided isn't a valid url, treat it as if the document doesn't exist and return an HTTP 404.
To test:
```
> curl "http://localhost:8000/sources/highlight/?url=https://crash-stats.allizom.org\[@a.xxx.org/?"
```
Compare that with:
```
> curl "https://crash-stats.allizom.org/sources/highlight/?url=https://crash-stats.allizom.org\[@a.xxx.org/?"
```
(You need the `\[` because otherwise curl thinks the `[` means something and kicks up `curl: (3) bad range specification in URL position 78:`.)
> bug-1902001: fix source highlight with bad urls

- webapp/crashstats/topcrashers/forms.py
This fixes `_report_type` validation in the TopCrashers form so it doesn't create bad Super Search queries which kick up an HTTP 500.
Previously, the form did no useful validation (why even have a form?). Now it enforces that `_report_type` is one of "any", "hang", or "crash" which are the only three values it should have. If it gets a different value, the form will cause the view to raise an HTTP 400 with an error saying that the `_report_type` value isn't one of the available choices.
I did manual testing:
1. go to `http://localhost:8000/` and chose "TopCrashers" from the dropdown in the quick navigation bar
2. on the TopCrashers report, click through the three report types -- this should work fine
3. now manually edit the url and change `_report_type` to something like "pumpkin" -- …
> bug-1928808: fix _report_type validation

- webapp/crashstats/crashstats/models.py
- webapp/crashstats/crashstats/tests/test_models.py
Sometimes Bugzilla returns an HTTP 200 with JSON content, but it doesn't have "bugs" in it.
Rather than throw an HTTP 500 because of an unhandled `KeyError`, this changes the code to raise a `BugzillaRestHTTPUnexpectedError` with the payload it did get. This will give us a better idea of what's happening so we can figure out what to do about it if anything.
> bug-1892787: handle case where Bugzilla returns bad payload

- webapp/crashstats/documentation/jinja2/docs/supersearch/api.html
- webapp/crashstats/signature/tests/test_views.py
- webapp/crashstats/signature/views.py
In 9b425e50, I changed the name of the field the webapp permissions were stored in, but missed updating the signature report view. This fixes that and adds a test.
To test:
1. process a crash report
2. go to `localhost:8000`
3. if you're logged in, log out
4. go to the crash report then click on the signature to go to the signature report
5. go to the "Aggregations" tab and click on the "Aggregate on..." drop down -- there should be fields
6. go to the "Reports" tab -- there should be fields listed in the unlabeled columns field
7. go to the "Graphs" tab and click on "Crashes per day, by ..." drop down -- there should be fields
> bug-1928934: fix super search fields in signature report forms

- socorro/scripts/fetch_crashids.py
This adds a "thismonth" value to the value domain for the `--date" argument because it's not uncommon to be testing signature generation changes for situations that have happened in the last month, but not in the last week.
```
$ just shell
app@socorro:/app$ socorro-cmd fetch_crashids --date=thisweek --signature-contains=g_malloc
app@socorro:/app$ socorro-cmd fetch_crashids --date=thismonth --signature-contains=g_malloc
9c924bb4-cc8d-4071-afef-000140241031
72d845fc-6f33-4f44-9203-1dc490241104
e4a0a8dd-341b-430a-9f6a-2ad0c0241028
aef97233-ca73-4ba9-a6d1-c8a280241104
ede7036b-4927-41a0-834e-9e4a80241105
4ea1423a-fce6-45a9-95e2-6a05e0241110
f17cd077-17a7-46cd-a378-2dc8a0241102
8d1cc235-dcbd-4606-a99d-eaf840241104
2b89f970-0451-43fc-a237-ecf7a0241106
```
> Adding a "thismonth" option to the date argument for fetch_crashids

- socorro/processor/rules/mozilla.py
- socorro/tests/processor/rules/test_mozilla.py
This changes the `CopyFromRawCrashRule` to strip the right side of string field values. I haven't seen anything in crash reports so far where whitespace at the end of a crash annotation value is significant so I think this is safe.
If it turns out not to be safe, we can extend `CopyFromRawCrashRule` to look at a "transforms" field to glean how it should transform the value after copying it. This would be helpful for the increasing number of fields that are comma or semi-colon delimited, too.
To test:
1. process a Fenix crash report
2. view the `Android_CPU_ABI2` value in the raw crash--it has `\r\n` at the end
3. view the `android_cpu_abi2` value in the processed crash--it does not have `\r\n` at the end
> bug-1906021: strip whitespace from Android_CPU_ABI2 and other string fields

- webapp/crashstats/crashstats/jinja2/crashstats/report_index.html
- webapp/crashstats/crashstats/views.py
This removes the collector-added fields from the Crash Annotations tab. For anyone who isn't a crash ingestion system maintainer, these fields are confusing because they're not part of the crash report payload.
After these changes, the fields will be omitted from the public and protected annotations lists in the Crash Annotations tab.
This also adds "version" to the Debug tab. This value represents the schema version of the raw crash structure. It's relevant to crash ingestion internals and nothing else, so having it in the Debug tab is helpful (though at this point, everything is version 2 so it's not wildly interesting anymore).
This also removes a few lines from the report view template that said we could remove them in 2022. That day has long passed.
To test:
1. process a crash report …
> bug-1933774: omit collector-added fields from Crash Annotations tab

- requirements.in
- requirements.txt
This fixes subscription creation in the local dev environment so the ack deadline is 600 seconds which gives the processor enough time to retrieve a crash id, process the crash, and ack the crash id. Prior to this fix, subscriptions would use the default 10 seconds and that's not enough time to process crash reports.
We fixed this originally in bug-1912979, but that fix was dropped when we moved utilities to obs-common.
> Update obs-common to pick up the ack_deadline_timeout fix

- webapp/crashstats/crashstats/models.py
100 characters wasn't enough information to understand the error, so doubling it.
> bug-1935274: increase message length for BugzillaRestHTTPUnexpectedError

- webapp/crashstats/supersearch/tests/test_views.py
The index name template uses week number and when we calculate the expected index names by adding 7 days to figure out the next week number, that doesn't work at the beginning of the year when the previous year includes a partial week.
This fixes that by changing the code to figure out week numbers by incrementing by one day, generating index names, throwing those in a set, and then turning that into a sorted list.
> Fix TestCustomQuery test that fails at beginning of year

- socorro/external/es/connection_context.py
This only impacts new Elasticsearch 8 which adds HTTPS. Previously for Elasticsearch 1.4, this option did nothing, because we weren't using HTTPS.
This change is to test the new ES 8 cluster with socorro in stage (e.g. can we get the stage processor to write to both the old and new ES clusters?). We will discuss setting up a CA instead of disabling this before deploying Elasticsearch 8 in prod ([OBS-427](https://mozilla-hub.atlassian.net/browse/OBS-427)).
> bug-1925594: don't verify certs for Elasticsearch

- socorro/external/es/supersearch.py
- socorro/tests/external/es/test_supersearch.py
In ES 8+ index.max_result_window defaults to 10,000: https://www.elastic.co/guide/en/elasticsearch/reference/8.17/index-modules.html
> bug-1942406: Fix search_phase_execution_exception: Result window is too large

- socorro/external/es/connection_context.py
- socorro/external/es/crashstorage.py
- socorro/mozilla_settings.py
This only impacts https urls, which right now we only use for elastic cloud.
In stage we are currently depending on `verify_certs=False` to connect to elastic cloud, and this will allow us to instead use a `certs.pem` provided by elastic cloud to verify their https certs.
> OBS-427: Support verify_certs with self-issued certs for elastic cloud

- socorro/signature/siglists/prefix_signature_re.txt
We don't want to add this function to the irrelevant list because it conveys an important bit of information (that we're crashing because an invalid paramter has been passed to a Windows system function), but we still want to skip over it in order to be able to tell different crashes apart.
> Bug 1943919 - Add TppRaiseInvalidParameter to the prefix list

- socorro/external/es/supersearch.py
- socorro/tests/external/es/test_supersearch.py
for es8+ search results may contain an AggResponse object under the `aggregations` key, instead a missing attribute like in es1.4, so here we convert that empty object to a dict
> bug-1945553: Fix json encoding error with empty aggregations object

- .devcontainer/Dockerfile
- docker/Dockerfile
- docker/set_up_stackwalker.sh
- docker/set_up_ubuntu.sh
https://mozilla-hub.atlassian.net/browse/OBS-270
Debian bookworm contains a nodejs package with a newer version than we install from Nodesource. I had to add an apt pin to prefer the Nodesource version over the version included in Debian. I also removed the use of `apt-key`, which has been deprecated for a long time now.
> OBS-270: Use Python images based on Debian bookworm.

- socorro/external/es/crashstorage.py
- socorro/external/legacy_es/crashstorage.py
- socorro/tests/external/es/test_crashstorage.py
- socorro/tests/external/legacy_es/test_crashstorage.py
renames `fix_float` to `fix_double` because that's the actual es storage type name, and added cases to `test_indexing_bad_data` to show it's actually working this time
This also applies the fix to legacy_es, since the bug also appeared there and that was impacting manual testing on the processor with the problem crash.
> bug-1946895: Fix detecting float/double field when building es8 documents

- .devcontainer/Dockerfile
- docker/Dockerfile
- justfile
Currently when making changes to the FE build process (package.json, etc), most of the app image rebuilds unnecessarily.  These FE changes also trigger a rebuild of the “devcontainer” image.  Consequently, every change takes ~5 minutes on my machine.
With this PR build times are reduced to under 30 seconds (as tested on my machine)
> OBS-504: Optimize Socorro builds for better FE dev speed 

- justfile
This ensures these two directories are owned by the host user rather than root during image building and container running.
To test:
1. delete `webapp/static/` and `webapp/node_modules/` if they exist
2. run `just clean`
3. run `just build`
4. ensure `webapp/static/` and `webapp/node_modules/` are owned by the host user and not root (this is only a problem on Linux)
5. run `just build` to make sure it builds even if the directories exist
> obs-512: fix webapp/static and webapp/node_modules directory ownership

- webapp/package-lock.json
- webapp/package.json
The version of Moment we're using has a [vulnerability](https://github.com/mozilla-services/socorro/security/dependabot/37).  This PR updates Moment to the minimum patched version, 2.29.4.
According to the [changelog](https://github.com/moment/moment/blob/000ac1800e620f770f4eb31b5ae908f6167b0ab2/CHANGELOG.md), not too much has changed between versions other than the patch for the vulnerability, which itself looks low-risk.
I also spot-checked the Signature Report view that likely uses Moment (given its inclusion of the Moment package in the HTML).  No obvious breakage occurs with anything date-related.
To test:  
- spot check date-related aspects of the webapp, including Signature Report
> OBS-556: Update Moment to 2.29.4

- .dockerignore
- .gitignore
Upon populating crash data, the files and data appear locally and are at risk of being checked in.  Especially since the data might be sensitive, we should explicitly ignore these files.
> Ignore generated crashdata files/folders from check-in

- webapp/package-lock.json
- webapp/package.json
The version of QS we're using (6.9.4) has a [high vulnerability](https://github.com/mozilla-services/socorro/security/dependabot/42). This PR updates QS to the minimum patched version, 6.9.7.
Reviewing the [changelog](https://github.com/ljharb/qs/blob/v6.9.7/CHANGELOG.md) suggests this update is low-risk especially since it's a patch version.  This patched version is the last release before major version change.
I searched the code to find where QS is used, apparently in testdrive.js which involves the API.  I spot-checked the API view and functionality. No obvious breakage occurs with anything date-related.
To test:
- spot check API-related aspects of the webapp.
To do:
- use of the QS package appears to be minimal and likely can be rewritten with native code to remove the package …
> OBS-557: Update QS to 6.9.7

- docker/set_up_stackwalker.sh
This updates the stackwalker to v0.25.0. One thing this picks up is a new field in the stackwalker output: soft_errors.
However, the value for that field is documented as "object" and we don't know what that is so we can't put it in the schema. If they want that field to be public or if they want us to do something with it in Crash Stats, they'll have to flesh out the structure of the object.
https://github.com/rust-minidump/rust-minidump/blob/4bc0e1bb3a19f22d5b7c4057112197ac5f6ea2d9/minidump-processor/json-schema.md#L692-L693
To test:
1. build socorro
2. process some crash reports and df1ce584-5ad2-4b35-9c0f-a00ed0250321
3. verify that the stackwalker doesn't crash
4. log into `http://localhost:8000` with an account with protected data access
5. view df1ce584-5ad2-4b35-9c0f-a00ed0250321 …
> bug-1954596: update stackwalker to v0.25.0

- webapp/package-lock.json
- webapp/package.json
It's been a while since front-end dependencies were audited and updated.  This PR removes two packages that I believe are unused, [graceful-fs](https://www.npmjs.com/package/graceful-fs) and [prop-types](https://www.npmjs.com/package/prop-types).
On the surface, the two packages don't appear relevant to Socorro: `graceful-fs` is a replacement for native Node file system operations, and `prop-types` relates to React which we're not using.  I also searched the codebase for traces of the above packages with no results.
> OBS-400: Remove unused dependencies

- webapp/package-lock.json
- webapp/package.json
Our version of jquery-ui (1.13.0) has a [moderate vulnerability](https://github.com/mozilla-services/socorro/security/dependabot/38). This PR updates jquery-ui to the minimum patched version, 1.13.2.
Reviewing the [changelog](https://jqueryui.com/changelog/1.13.2/) suggests this update is low-risk especially since it's a patch version.
I searched the code to find where jquery-ui is used, apparently in supersearch. I spot-checked the supersearch UI and date picker – no obvious breakage occurs.
To test:
spot check jquery-ui aspects of the webapp: search, report, and signature report
> OBS-572: update jquery-ui

- webapp/crashstats/settings/base.py
This makes sure the OIDC callback URL is correct when behind Fastly.
https://mozilla-hub.atlassian.net/browse/CRINGE-56
> CRINGE-56: Use X-Forwarded-Host header to infer hostname for absolute URLs.

- socorro/external/es/super_search_fields.py
- socorro/schemas/processed_crash.schema.yaml
- socorro/schemas/raw_crash.schema.yaml
- socorro/tests/schemas/test_socorro_data_schemas.py
Based off of #6429 
To do:
Because:
* Firefox devs want to search processed crash reports based on the Marionette and RemoteAgent annotations.
This PR:
* Adds `Marionette` and `RemoteAgent` fields to the raw crash schema.
* Adds `marionette` and `remote_agent` fields to the processed crash schema.
* Ensures the values for each field are copied and normalized (`0` -> `false`, 1 -> `true`, field omitted in raw crash -> `false`).
* Sets the fields as public.
* Adds the fields to SuperSearch, so they will be indexed.
I have verified that this works locally[1] with the following STR for crash IDs `8b0d4f98-5851-41a7-a67a-e08690250902` (has `Marionette: 1` and `RemoteAgent: 1`) and `ab5a27b6-47c3-40ed-aa07-bce510250905` (has neither field):
1. Open both crash reports in separate tabs in prod …
> bug-1943891: support Marionette and RemoteAgent crash annotations

- product_details/Fenix.json
This product has been renamed from "Fenix" to "Firefox for Android".
> Bug 1959806 - Use Firefox for Android as the product
